### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by Nghidang14** [firebase/firebase-unity-sdk#1015]
I tried to it but not run with error DllNotFoundException: FirebaseCppApp-11_9_0

**Comment by argzdev** [comment]
Hey there, @Nghidang14. Could you file a new issue and provide details from our template? The template will provide us with information that will allow us to conduct an initial investigation of your issue. That said, I'll go ahead and close this thread. Thanks!

**Comment by Nghidang14** [comment]
> Hey there, @Nghidang14. Could you file a new issue and provide details from our template? The template will provide us with information that will allow us to conduct an initial investigation of your issue. That said, I'll go ahead and close this thread. Thanks!

![Erorr](https://github.com/firebase/firebase-unity-sdk/assets/128838947/b219d965-d6bc-4201-b156-fcaeed9aa1af)
I tried to Play bui it just loaded about 10% end freezen :(
