### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-11_6_0 in Windows 10

### ISSUE THREAD

**Issue by Nghidang14** [firebase/firebase-unity-sdk#1022]
### Description

I'm using my windows 10 laptop to clone a Unity project that uses firebase and I get the error DllNotFoundException: FirebaseCppApp-11_6_0 when I press Play. My teammates in my team all run normally when using other computers. I don't know where the problem is. Please help me if you know!
![image](https://github.com/firebase/firebase-unity-sdk/assets/128838947/d86adc8e-5ed3-4605-bbc0-71317461d89d)

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2020.3.48f1

### Installation Method

.unitypackage

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

Mono

### Release Distribution Type

Open-source from this repo

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Thanks for reaching out, @Nghidang14. Could you share a few information in order for us to investigate your issue:
1. What Firebase products are you using?
2. Have you imported the correct [Firebase product](https://developers.google.com/unity/packages#firebase) needed for your project?
3. Have you tried performing a [manual-resolution](https://github.com/googlesamples/unity-jar-resolver?tab=readme-ov-file#auto-resolution)?
Manual resolution can be performed using the following menu options:
    - `Assets > External Dependency Manager > Android Resolver > Resolve`
    - `Assets > External Dependency Manager > Android Resolver > Force Resolve`

Let me know if this helps. Thanks!

**Comment by Nghidang14** [comment]
> Thanks for reaching out, @Nghidang14. Could you share a few information in order for us to investigate your issue:
> 
> 1. What Firebase products are you using?
> 2. Have you imported the correct [Firebase product](https://developers.google.com/unity/packages#firebase) needed for your project?
> 3. Have you tried performing a [manual-resolution](https://github.com/googlesamples/unity-jar-resolver?tab=readme-ov-file#auto-resolution)?
>    Manual resolution can be performed using the following menu options:
>    
>    * `Assets > External Dependency Manager > Android Resolver > Resolve`
>    * `Assets > External Dependency Manager > Android Resolver > Force Resolve`
> 
> Let me know if this helps. Thanks!

Thank your ans. But that is not work for me. I use FirebaseAnalytics, CrashLytics, RemoteConfig. I have followed all the steps and tried all the solutions.

**Comment by argzdev** [comment]
There might've been a version mismatch. You mentioned that you're using `FirebaseCppApp-11_6_0`, but the stacktrace is looking for version `11.9.0`. Could you try that version and see if that resolves the issue?

**Comment by Nghidang14** [comment]
I also tried to change version, but without success

**Comment by argzdev** [comment]
Not sure what's the issue here. Could you provide a minimal reproducible example so we can take a look into this? Thanks!

**Comment by Nghidang14** [comment]
I solved the problem. Maybe I downloaded something missing because when I deleted the version of Unity I was using and redownloaded it, it ran normally. Great, excellent, wonderfull. Thank you for your interest and support

**Comment by argzdev** [comment]
That's interesting, and good to hear that it's finally working, @Nghidang14. Thank you for sharing your resolution on this. I'll go ahead and close this thread.
