### ISSUE TITLE
[Bug] Processing Libraries from Forced Resolution popup won't disappear 

### ISSUE THREAD

**Issue by alex-moonlitgames** [firebase/firebase-unity-sdk#1033]
### Description

Today I did a force resolution for android, like I do when making a new release candidate and this newer popup without a close button appeared.

There was a smaller popup that told me that everything is complete, with an OK button, but pressing that OK button did not remove the big one. I had to drag the corners to slightly move it away from blocking me.

Restart / Library delete did not help

![image](https://github.com/firebase/firebase-unity-sdk/assets/124737077/02c637ea-7a2b-49bd-9acb-0008dfad5e22)

### Reproducing the issue

Trigger Android Force Resolution

### Firebase Unity SDK Version

11.6.0

### Unity editor version

2022.3.29f1

### Installation Method

Local
Packages/GooglePackages/com.google.firebase.app-11.6.0.tgz

### Additional SDKs you are using

Facebook, Singular

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

Mono, IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @alex-moonlitgames, thanks for reaching out. It looks like it might be a problem specific to our [Unity Jar Resolver](https://github.com/googlesamples/unity-jar-resolver). Could you file a new issue in the said repository? Thanks!
