### ISSUE TITLE
[Bug] Firebase wants to use your confidential in keychain after add keychain-access-group.

### ISSUE THREAD

**Issue by Fatorin** [firebase/firebase-unity-sdk#1036]
### Description

Hi, I'm developing a Unity game for Steam that uses Firebase Authentication for our login system.

When I run my game, I always see that Firebase wants to use confidential information from the keychain.

After researching this issue, I found that it should be fixed in SDK version 9.6.
[https://github.com/firebase/firebase-ios-sdk/pull/10181](url)

Even after adding the keychain-access-group in my game, it still shows up.

Is this a bug, or is there something wrong with my settings?

![issue](https://github.com/firebase/firebase-unity-sdk/assets/23738444/31c2abdb-7e1c-4e52-8afb-1f57ff8a1b2e)

### Reproducing the issue

1. Use Unity to build my application with Xcode project (release)
2. Open Xcode project.
3. Choose Signing & Capabilites.
4. Add Hardend Runtime Disable Libray Validation, Disable Executeable Memory Protection for Steam.
5. Add Keychain Sharing in my project for Firebase.
6. Archive my application.
7. Distribute App and finish notarized.
8. Run my app and check result.

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2021.3.25f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Analytics, Crashlytics, Messaging, Remote Config, Storage

### Targeted Platform(s)

Apple Platforms, Desktop

### Unity editor platform

Mac, Windows

### Scripting Runtime

Mono

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hey @Fatorin, thanks for reaching out. I do see that the fix has been applied for [Firebase Installations](https://github.com/firebase/firebase-ios-sdk/blob/afcd2c7dbc6b980127b716ac159089ef06f48612/FirebaseMessaging/Sources/Token/FIRMessagingAuthKeychain.m#L69-L73). And I also noticed that this fix has been included in [Firebase Auth](https://github.com/firebase/firebase-ios-sdk/blob/560777f5720dae48efd593cbf2124146340f3d25/FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m#L238-L248), but with an #ifndef condition. I'm not sure with these changes so let me get some feedback from our engineers.

**Comment by Fatorin** [comment]
I noticed that this code works on versions 10.15 and above. I will try to adjust the xcode project and test it again.

**Comment by argzdev** [comment]
That's interesting, the Firebase Unity SDK `11.9.0` mapped to `10.24.0` of iOS SDK, are you somehow using a lower version of the iOS SDK?

**Comment by Fatorin** [comment]
After my testing, I determined that the default minimum version will be 10.13.
![image](https://github.com/firebase/firebase-unity-sdk/assets/23738444/c13b1f9f-b251-420e-8d14-81e6282514bf)
![image](https://github.com/firebase/firebase-unity-sdk/assets/23738444/142e3b46-d495-4e6c-884f-2783c300e85f)

**Comment by argzdev** [comment]
Oh I see, sorry for misunderstanding. Thanks for sharing these details. From my understanding, the issue is resolvable once the `kSecUseDataProtectionKeychain` key has been set to true. According to the docs, this [key](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain) is available in macOS versions `10.15` and above. That said, could you verify if this is working for versions `10.15` or above? If so, then I believe it is working as intended.

**Comment by Fatorin** [comment]
I set minimum version to `10.15` and all is work, thanks your help!

**Comment by argzdev** [comment]
Awesome, thank you for confirming, @Fatorin. I'm glad you were able to resolve the issue.
