### ISSUE TITLE
Firebase Storage: List files

### ISSUE THREAD

**Issue by pragmascript** [firebase/firebase-unity-sdk#104]
Hi,

the [List Files API](https://firebase.google.com/docs/storage/web/list-files) seems to be completely missing in the Unity SDK.

Without the ability to list files the storage API is not useful. When will this be added?

**Comment by owais2399** [comment]
Yup, I've been looking everywhere as well but can't find it. 😞

**Comment by ferretnt** [comment]
Doesn't appear to be implemented, which is a shame because the underlying iOS/Android SDKs do support it. Does anyone know the official channel to file a feature request?

**Comment by kaapiel** [comment]
I'm also looking forward to have this feature

**Comment by StephenHodgson** [comment]
There's a bunch of rest apis you could use but won't be as good as the grpc native versions

**Comment by chkuang-g** [comment]
For management purpose, let me use https://github.com/firebase/firebase-unity-sdk/issues/98 as the main feature request post since it is the oldest (and the age of the FR matters :))

Please upvote that post if you consider it important to your team. 

Thank you!
