### ISSUE TITLE
[Bug] Crash in firebase::auth::Env

### ISSUE THREAD

**Issue by abogarsukov-braingames** [firebase/firebase-unity-sdk#1041]
### Description

Crash trace:
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 31053 >>> com.wordfarm.scapes <<<

backtrace:
  #00  pc 0x000000000026f768  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libFirebaseCppApp-11_9_0.so (firebase::auth::Env(firebase::auth::AuthData*))
  #01  pc 0x0000000000278da3  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libFirebaseCppApp-11_9_0.so (void firebase::auth::RegisterCallback<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >(_jobject*, firebase::SafeFutureHandle<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, firebase::auth::AuthData*, firebase::auth::FutureCallbackData<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::ReadFutureResultFn)+18)
  #02  pc 0x0000000000278ca1  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libFirebaseCppApp-11_9_0.so (firebase::auth::User::GetToken(bool)+136)
  #03  pc 0x000000000026eed1  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libFirebaseCppApp-11_9_0.so (firebase::auth::User::GetTokenThreadSafe(bool)+28)
  #04  pc 0x0000000000203da5  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libFirebaseCppApp-11_9_0.so (Firebase_Auth_CSharp_FirebaseUserInternal_Token+44)
  #05  pc 0x0000000000c407b4  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #06  pc 0x000000000225768c  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #07  pc 0x000000000224a09c  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #08  pc 0x000000000224e384  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #09  pc 0x000000000171ebd4  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #10  pc 0x000000000171e98c  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #11  pc 0x000000000156c4ac  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #12  pc 0x0000000001fe7d94  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #13  pc 0x0000000001fe7c94  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #14  pc 0x0000000000511a04  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #15  pc 0x0000000000511860  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libil2cpp.so (BuildId: cb9f101fd7ca63a52d1d0a74e328055b43e26ad3)
  #16  pc 0x0000000000210d71  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #17  pc 0x000000000021b819  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #18  pc 0x0000000000294e49  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #19  pc 0x00000000001800c3  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #20  pc 0x00000000001800e5  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #21  pc 0x000000000018027b  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #22  pc 0x0000000000277111  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #23  pc 0x0000000000287bc7  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/lib/arm/libunity.so (BuildId: a53f9854668383a5813b445309df71ce7171f9ca)
  #24  pc 0x000000000014b71d  /apex/com.android.art/lib/libart.so (art_quick_generic_jni_trampoline+44)
  #25  pc 0x000000000032c9ec  /apex/com.android.art/lib/libart.so (nterp_helper+2908)
  #26  pc 0x0000000001b0302c  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/oat/arm/base.vdex (com.unity3d.player.UnityPlayer.access$500)
  #27  pc 0x000000000032bec8  /apex/com.android.art/lib/libart.so (nterp_helper+56)
  #28  pc 0x0000000001b0261c  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/oat/arm/base.vdex (com.unity3d.player.UnityPlayer$e$1.handleMessage+228)
  #29  pc 0x0000000000a2bb63  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.Handler.dispatchMessage+122)
  #30  pc 0x0000000000a2eedb  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.Looper.loopOnce+882)
  #31  pc 0x0000000000a2eadf  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.Looper.loop+1022)
  #32  pc 0x000000000032bf3c  /apex/com.android.art/lib/libart.so (nterp_helper+172)
  #33  pc 0x0000000001b029ec  /data/app/~~tQT1AB3Tn5nwwpU3wxoRbg==/com.wordfarm.scapes-jWezGSxcGdDspd61m9-QAg==/oat/arm/base.vdex (com.unity3d.player.UnityPlayer$e.run+40)
  #34  pc 0x00000000001441d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #35  pc 0x00000000001bc28b  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+466)
  #36  pc 0x0000000000235faf  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+2070)
  #37  pc 0x00000000000ad483  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
  #38  pc 0x000000000006459d  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)`

### Reproducing the issue

We observe the crash in the Google Play Console vitals.

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2021.3.37

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Analytics, Authentication, Crashlytics, Database, Messaging

### Additional SDKs you are using

Facebook, AppLovin, Singular

### Targeted Platform(s)

Android

### Unity editor platform

Mac, Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by abogarsukov-braingames** [comment]
Hey @argzdev, unfortunately we don't have steps to reproduce the issue. We observe such crashes on all our apps that use Firebase Auth in crashlytics reports. We've never caught one ourselves.

**Comment by argzdev** [comment]
I believe the issue has something to do with user data e.g. `firebase::auth::Env(firebase::auth::AuthData*)`, so I'm guessing the issue occurs only with some specific users. However, without any other information, it's difficult to pinpoint what the issue might be. We'll continue to investigate, and provide feedback if we find anything. Feel free to add additional information that you think might be helpful in investigating this further. Thanks!

**Comment by argzdev** [comment]
Hi @abogarsukov-braingames, since we're unable to move this forward without any information. I'll close this for now. Feel free to come back here once there's further information for us to conduct another investigation. Thanks!
