### ISSUE TITLE
[Bug] "Please fix your bundle id window" - annoyingly keeps appearing!

### ISSUE THREAD

**Issue by matanshukry** [firebase/firebase-unity-sdk#1044]
### Description

Not sure why, but now I keep getting this very annoying window about "Please fix your bundle id" on every build.
The bundle id it self is fine, I can work with firebase and everything is working - and even if I select the value and click Apply, the window keeps appearing.

Not sure why that happens but honestly I just want that annoying window gone.
Is there perhaps a secret way I'm missing? 🤞 

### Reproducing the issue

just building

### Firebase Unity SDK Version

11.9.0

### Unity editor version

2022.3.27f1

### Installation Method

.unitypackage

### Other Firebase Component(s) in use

Crashlytics

### Additional SDKs you are using

Google Analytics

### Targeted Platform(s)

Android, Desktop

### Unity editor platform

Windows

### Scripting Runtime

Mono

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @matanshukry, thanks for reaching out. This looks like a bug, however the window should only appear if the package name from the Player Settings does not match any package name from the `google-services.json`. I'm wondering if this is the case for you, could you check this out? Also, I'm not encountering this issue on our quickstart. It'll be a great help if you could share with us a [minimal reproducible behavior](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) so we can investigate this further. Thanks!
