### ISSUE TITLE
Auth not working in Unity editor

### ISSUE THREAD

**Issue by GoShikhar** [firebase/firebase-unity-sdk#1048]
Facing a weird auth issue in Unity editor whereby auth isn't working all of a sudden.
The sign-in and token refresh was working in this project but out of nowhere it isn't anymore in Unity editor. We haven't updated Unity editor, we have updated to the latest firebase sdk now, still no luck.
Although, it's working as expected in the built android apk.

Unity editor: 2023.2.18f1
Firebase Sdk: 12

These methods give errors which aren't much detailed.
SignInWithEmailAndPasswordAsync, user.TokenAsync()

```
Exception: An internal error has occurred.
StackTrace:   at Firebase.Auth.FirebaseAuth.SignInWithEmailAndPasswordAsync (System.String email, System.String password) [0x00038] in /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/linux_unity/auth/swig/Firebase.Auth_fixed.cs:3555 
UnityEngine.Debug:LogError (object)
FirebaseManager:<SignInEmail>b__97_0 (System.Threading.Tasks.Task`1<Firebase.Auth.AuthResult>) 
```

Can anyone please help here?

**Comment by argzdev** [comment]
Thanks for reaching out, @GoShikhar. I'm wondering if there's an issue with our Firebase Auth version `12.0.0`. Could you try and use version `11.9.0` as a mitigation? At the same time, any chance you could provide a minimal reproducible example of this issue? I'm currently trying to test this with our Unity Quickstart for Auth, however it doesn't seem like there's an issue with the email/password login.

**Comment by argzdev** [comment]
Sorry for the delayed response, @GoShikhar. I'm glad you were able to resolve your issue, thank you for sharing the solution of your problem. I'm sure it'll help other folks who encounter the same issue.
