### ISSUE TITLE
[Bug] PutFileAsync won't finish or throws errors in Windows

### ISSUE THREAD

**Issue by ChurikiTenna** [firebase/firebase-unity-sdk#1053]
### Description

I have this code to upload a file to storage which works fine on Mac.
However, it doesnt continue to the next line of the code after `var metadata = await uploadTask;`

I see the file is successfully uploaded on Storage, and log seems to indicate the same.
![image](https://github.com/firebase/firebase-unity-sdk/assets/52132649/07ad8c58-3330-4aa2-b6f5-c2f3902fe080)
It just doesn't continue to the next process (i.e. Debug.Log("Upload task completed");) after uploading.

```
public static async Task<string> UploadFileAsync(string localFilePath)
    {
        try
        {
            Debug.Log($"UploadFileAsync {localFilePath}");
            
            string uniqueFileName = $"custom_chara/{FirebaseAuthHelper.uid}_{DateTime.UtcNow.ToString("yyyyMMddHHmmss")}_{Path.GetFileName(localFilePath)}";
            Debug.Log($"UploadFileAsync.uniqueFileName {uniqueFileName}");
            
            FirebaseStorage storage = FirebaseStorage.DefaultInstance;
            var uploadTask = storage.GetReferenceFromUrl("gs://projectname.appspot.com")
                .Child(uniqueFileName)
                .PutFileAsync(localFilePath);
            Debug.Log($"Upload task created {uploadTask}");
            var metadata = await uploadTask;
            if (uploadTask.IsCompleted)
            {
                Debug.Log("Upload task completed");
            }
            else if (uploadTask.IsFaulted)
            {
                Debug.LogError("Upload task faulted");
            }
            else if (uploadTask.IsCanceled)
            {
                Debug.LogError("Upload task canceled");
            }
            Debug.Log($"Finished uploaded to... {metadata.Path}");
            return metadata.Path;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
            return null;
        }
    }
```

### Reproducing the issue

Run the code above in windows.

### Firebase Unity SDK Version

11.6.0

### Unity editor version

2022.3.17f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Storage

### Other Firebase Component(s) in use

Authentication, Firestore

### Targeted Platform(s)

Desktop

### Unity editor platform

Windows

### Scripting Runtime

Mono

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @ChurikiTenna, could you try testing with our latest version `12.1.0` to see if that makes any difference? We usually advise this to avoid issues that might've already been fixed in the most recent versions. Thanks!
