### ISSUE TITLE
[Bug] Cannot send array of Items with Firebase Analytics event

### ISSUE THREAD

**Issue by Kevin-Hamilton** [firebase/firebase-unity-sdk#1056]
### Description

This issue was called out here, 4 years ago: https://github.com/firebase/quickstart-unity/issues/713

There are several ecommerce events like "[purchase](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=18167566225038720690-NC&client_type=gtag#purchase)", "[view_cart](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=18167566225038720690-NC&client_type=gtag#view_cart)", and "[view_item_list](https://developers.google.com/analytics/devguides/collection/ga4/reference/events?sjid=18167566225038720690-NC&client_type=gtag#view_item_list)" which expect to receive an array of items.  Under the Unity SDK, sending these events does not appear to be possible.

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2019.4.16f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Thanks for bringing this up to my attention, @Kevin-Hamilton. This looks like a long running bug, let me reach out to our engineers and see if we get some feedback.

**Comment by Kevin-Hamilton** [comment]
I would say the quickstart thread was the wrong place to report this and perhaps why it did not get attention sooner, since it is an issue with the SDK. So it seems like closing that thread and keeping this one open makes more sense to me. But I will defer to your judgement, as I don't know how the developer resources are organized around these projects.  Thanks for bringing it up with the engineers.

**Comment by argzdev** [comment]
Well said, @Kevin-Hamilton. I'll close the quickstart thread instead. We'll keep you posted, once we get updates.

**Comment by ilsnk** [comment]
finally! do it please!

**Comment by a-maurice** [comment]
Alright, it is finally in with the latest release, 12.4.0, https://github.com/firebase/firebase-unity-sdk/releases/tag/v12.4.0

For an example on how to use it, you can see https://github.com/firebase/firebase-unity-sdk/blob/446d14173a224464e6df865a2bcc86e5fa69a6b7/analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandler.cs#L121
