### ISSUE TITLE
[Question] how post a purchase log event?

### ISSUE THREAD

**Issue by aminbarzegari** [firebase/firebase-unity-sdk#1062]
### What is your question?

hi.

how post a purchase log event?

### Firebase Unity SDK Version

11.8.1

### Unity editor version

2022.3.16f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

All

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by aminbarzegari** [comment]
>                 FirebaseAnalytics.LogEvent(FirebaseAnalytics.EventPurchase, productId, (double) price);


this code not work for send detail and only a purchase event without details.

**Comment by argzdev** [comment]
Hey @aminbarzegari, thanks for reporting. Upon testing with our [Firebase Unity Quickstart](https://github.com/firebase/quickstart-unity) with Firebase Analytics version `12.1.0`, I tried adding the code snippet below:

```
public void AnalyticsPurchase()
    {
      DebugLog("Logging a purchase event.");
      FirebaseAnalytics.LogEvent(
        FirebaseAnalytics.EventPurchase,
        "RandomProductId",
        14.99
      );
    }
```

So far I'm not encountering the issue you've mentioned. Using the Debug View shows that the event has been captured with the provided details.
<img width="318" alt="Screenshot 2024-07-05 at 11 49 40 PM" src="https://github.com/firebase/firebase-unity-sdk/assets/93124282/f3fb96fc-41ca-4929-a988-d7feb94377b2">

Could you try using the latest version of the SDK version `12.1.0`? You can try using the [DebugView](https://firebase.google.com/docs/analytics/debugview#android) to investigate the events being logged. If you're using Android, you're going to need to execute this command through the terminal `adb shell setprop debug.firebase.analytics.app com.google.firebase.unity.analytics.testapp`, this will track and events in the DebugView that are being logged.

Let me know if this helps. Thanks!

**Comment by aminbarzegari** [comment]
```
            Parameter[] purchaseParam =
            {
                new Parameter(FirebaseAnalytics.ParameterTransactionId, productId),
                new Parameter(FirebaseAnalytics.ParameterAffiliation, storType),
                new Parameter(FirebaseAnalytics.ParameterCurrency, "USD"),
                new Parameter(FirebaseAnalytics.ParameterValue, price),
                new Parameter(FirebaseAnalytics.ParameterPrice, price),

            };
            
            
                        FirebaseAnalytics.LogEvent(FirebaseAnalytics.EventPurchase, purchaseParam);

```

**Comment by argzdev** [comment]
Hey, @aminbarzegari, I used the code snippet you've provided, so far all these details are displayed in the DebugView.
```
public void AnalyticsPurchase()
    {
      DebugLog("Logging a purchase event.");

      Parameter[] purchaseParam =
      {
          new Parameter(FirebaseAnalytics.ParameterTransactionId, "productId"),
          new Parameter(FirebaseAnalytics.ParameterAffiliation, "storType"),
          new Parameter(FirebaseAnalytics.ParameterCurrency, "USD"),
          new Parameter(FirebaseAnalytics.ParameterValue, 14.99),
          new Parameter(FirebaseAnalytics.ParameterPrice, 14.99),
      };

      FirebaseAnalytics.LogEvent(FirebaseAnalytics.EventPurchase, purchaseParam);
}
```

<img width="649" alt="Screenshot 2024-07-06 at 1 14 51 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/93124282/0837b4be-8a15-4318-ba0a-0ccc8bbeec99">

In order for us to investigate this further, you need to provide more information on what specific detail is not showing.

**Comment by argzdev** [comment]
I'll go ahead and close this thread for now. Feel free to come back here once you have more details regarding the issue. Thanks!
