### ISSUE TITLE
[Bug] Firebase 12.1.0 Gradle Build Failure

### ISSUE THREAD

**Issue by akroshteotia** [firebase/firebase-unity-sdk#1063]
### Description

After importing firebase to empty project and tried to make build. On Platform 34 and 35. 
Its giving 

Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:: AAPT: aapt2.exe E 07-06 10:56:20 16568 23564 LoadedArsc.cpp:96] RES_TABLE_TYPE_TYPE entry offsets overlap actual entry data.
     aapt2.exe E 07-06 10:56:20 16568 23564 ApkAssets.cpp:149] Failed to load resources table in APK 'C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-35\android.jar'.
     error: failed to load include path C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-35\android.jar.

### Reproducing the issue

1. Import firebase plugin
2. Try to make build
3. Grade will fail

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2021.3.39f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

Crashlytics

### Additional SDKs you are using

None

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity, Open-source from this repo

### Relevant Log Output

```shell
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.7.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

Environment Variables:
SHIM_MCCOMPAT = 0x810000001
PROCESSOR_ARCHITECTURE = AMD64
AMPLITUDE_API_KEY_YELLOWBUCKET_DEV = 48835b4d1f5e342aefe5f016324d296a
BURST_ANDROID_MIN_API_LEVEL = 22
DriverData = C:\Windows\System32\Drivers\DriverData
USERDOMAIN = BYOD-AKROSH
CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files
COMPUTERNAME = BYOD-AKROSH
DEBUG_ENV_VAR = UnityHub
LOGONSERVER = \\BYOD-AKROSH
AMPLITUDE_TOKEN_GREENBUCKET_PROD = ZpUcbAdZXJYzNSoHsAWtL_s_JppwWid9
PUBLIC = C:\Users\Public
ProgramData = C:\ProgramData
SESSIONNAME = Console
AMPLITUDE_TOKEN_YELLOWBUCKET_PROD = UYDQtPOw83dIfVy3SrW5oMyo7ru4PRkV
NVIDIAWHITELISTED = 0x01
ALLUSERSPROFILE = C:\ProgramData
SystemRoot = C:\WINDOWS
windir = C:\WINDOWS
AMPLITUDE_API_KEY_REDBUCKET_DEV = 46b8b46515e7632fc42a504b72e05fd0
ProgramFiles(x86) = C:\Program Files (x86)
ProgramW6432 = C:\Program Files
OS = Windows_NT
ANDROID_NDK_ROOT = C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
HOMEPATH = \Users\TVDMUMAT792
FPS_BROWSER_USER_PROFILE_STRING = Default
EFC_20100 = 1
AMPLITUDE_TOKEN_REDBUCKET_DEV = U4PSN7S7PuYVRODivvdcFwbu8R6IHGqa
CHROME_CRASHPAD_PIPE_NAME = \\.\pipe\crashpad_6280_BAQSZSNGINIYVLCH
PROCESSOR_LEVEL = 6
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
CommonProgramFiles = C:\Program Files\Common Files
JAVA_HOME = C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK
USERDOMAIN_ROAMINGPROFILE = BYOD-AKROSH
TEMP = C:\Users\TVDMUM~1\AppData\Local\Temp
ProgramFiles = C:\Program Files
CommonProgramW6432 = C:\Program Files\Common Files
AMPLITUDE_TOKEN_YELLOWBUCKET_DEV = wKi8foVigDditGFvmZewRFWsEbX9Y0YO
AMPLITUDE_API_KEY_GREENBUCKET_DEV = 3ded2a762163603391a425f688f990c8
AMPLITUDE_API_KEY_REDBUCKET_PROD = ca12bb461ea96f9bdf5df4ded7d52994
HOMEDRIVE = C:
AMPLITUDE_API_KEY_STAGING = 83ee04fccc67e4fcc7dd527c4c6f1e21
USERNAME = TVDMUMAT792
OneDrive = C:\Users\TVDMUMAT792\OneDrive
AMPLITUDE_API_KEY_YELLOWBUCKET_PROD = e03a9bbe92dc38a88cdb068d24c65b46
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
AMPLITUDE_TOKEN_REDBUCKET_PROD = jTIgKs5KTZOjiqEEVdZFbgo_VRhABduL
NUMBER_OF_PROCESSORS = 8
AMPLITUDE_TOKEN_GREENBUCKET_DEV = 84H2gMm_FJzhr3mBaX1lM1JVukmCM7d9
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_DEV = client-wbjHYrmeSR87GmWOE7LDpf7sUySOIKHm
AMPLITUDE_API_KEY_GREENBUCKET_PROD = c86fea37a9e1d3f0878b96e15b111c7c
ComSpec = C:\WINDOWS\system32\cmd.exe
ORIGINAL_XDG_CURRENT_DESKTOP = undefined
PROCESSOR_REVISION = a502
AMPLITUDE_DEPLOYMENT_KEY_RED_BUCKET_PROD = client-zH8Y7OK1i331EKuG77C6UxN8ygcM6LzS
TMP = C:\Users\TVDMUM~1\AppData\Local\Temp
SystemDrive = C:
AMPLITUDE_API_KEY = 28f3cae0b33b8b3702120c9ed1a935aa
FPS_BROWSER_APP_PROFILE_STRING = Internet Explorer
SENTRY_ACCESS_TOKEN = 3df78d9e53f8456aa90fbae044ce1a6261421ab1d0014674bc2e933477289017
APPDATA = C:\Users\TVDMUMAT792\AppData\Roaming
Path = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\TVDMUMAT792\AppData\Local\Microsoft\WindowsApps;C:\Users\TVDMUMAT792\AppData\Local\Programs\Git\cmd
PSModulePath = C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
LOCALAPPDATA = C:\Users\TVDMUMAT792\AppData\Local
USERPROFILE = C:\Users\TVDMUMAT792
WOOTRIC_CLIENT_TOKEN = NPS-aa8be4c3


stderr[
ERROR:: D8: com.android.tools.r8.kotlin.H

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:: AAPT: aapt2.exe E 07-06 10:56:20 16568 23564 LoadedArsc.cpp:96] RES_TABLE_TYPE_TYPE entry offsets overlap actual entry data.
     aapt2.exe E 07-06 10:56:20 16568 23564 ApkAssets.cpp:149] Failed to load resources table in APK 'C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-35\android.jar'.
     error: failed to load include path C:\Program Files\Unity\Hub\Editor\2021.3.39f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-35\android.jar.
```

**Comment by gulliversgames** [comment]
Same here.

**Comment by argzdev** [comment]
Hi folks, according to the [Firebase Android release notes](https://firebase.google.com/support/release-notes/android#2024-05-02), Firebase Unity version `12.1.0` now includes a new version of the Firebase Android SDK (Firebase Analytics version `22.0.0`) which have breaking changes:
> - **Breaking change**: Changed the required minimum `compileSdkVersion` to be 34 or higher
> - **Breaking change**: Updated `minSdkVersion` to API level 21 or higher.

According to the [Unity forum](https://forum.unity.com/threads/warning-upgrade-gradle-version-for-api-33.1511924/#post-9698765), only Unity editor version `2023` have support for compileSdkVersion 34. 

In this case, I believe this is more of a compatibility issue which would be resolved once Unity Editor version `2023.3`+ is used. That said, I'll go ahead and close this thread.

**Comment by a-maurice** [comment]
Just to clarify, you can use older versions of Unity with the latest Firebase SDK.  You just need to update your Android tools, to have installed API level 34 or higher.  In your Unity player settings for Android, this is the "Target API level" setting, which usually defaults to highest installed, so just installing the API level at 34 or 35 would likely be enough to fix the issue.

**Comment by akroshteotia** [comment]
> Just to clarify, you can use older versions of Unity with the latest Firebase SDK. You just need to update your Android tools, to have installed API level 34 or higher. In your Unity player settings for Android, this is the "Target API level" setting, which usually defaults to highest installed, so just installing the API level at 34 or 35 would likely be enough to fix the issue.

Hi @a-maurice ,
Tried your way in Unity 2021.3 but its not working. Set minSdkVersion  to 22 and "Target API level" highest Installed, which is 35. 

I will with 2023 @argzdev .

**Comment by SanketAIT** [comment]
* Unity 2022.3.37f1
* Min API - 24
* Max API - 34
* Firebase 12.1.1 [Analytics, Auth, Remote Config, Database, Firestore, Storage]
* Admob 9.1.1
* Play Games 0.11.01
* In app review 1.8.2
* Gradle [Unity Default, 6.7.1, 6.9.4, 8.9]

Error

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2022.3.37f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2022.3.37f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

Please help.

**Comment by jsyzzxz** [comment]
> Just to clarify, you can use older versions of Unity with the latest Firebase SDK. You just need to update your Android tools, to have installed API level 34 or higher. In your Unity player settings for Android, this is the "Target API level" setting, which usually defaults to highest installed, so just installing the API level at 34 or 35 would likely be enough to fix the issue.

that right  i use unity2017 which max is support 29，but i can export google project    in andoird  studio，targetsdkversion set 34

**Comment by jsyzzxz** [comment]
agp up 8.4.2 can solve problem 
      etc：   com.android.tools.build:gradle -> 8.4.2
file:gradle-wrapper.properties : distributionUrl -> gradle-8.6-bin.zip

**Comment by akroshteotia** [comment]
Found a better solution. Add settingTemplate.gradle using this link and it works perfectly

https://discussions.unity.com/t/unity-2021-3-and-android-build-failure-when-using-android-legacy-libraries-and-target-api-34/952277
