### ISSUE TITLE
CommandInvokationFailure: Gradle build failed. 

### ISSUE THREAD

**Issue by SanketAIT** [firebase/firebase-unity-sdk#1067]
### What is your question?

* Unity 2022.3.37f1
* Min API - 24
* Max API - 34
* Firebase 12.1.1 [Analytics, Auth, Remote Config, Database, Firestore, Storage]
* Admob 9.1.1
* Play Games 0.11.01
* In app review 1.8.2
* Gradle [Unity Default, 6.7.1, 6.9.4, 8.9]

Error

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2022.3.37f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2022.3.37f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

Please help.

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.37f1

### Installation Method

.unitypackage

### Additional SDKs you are using

Admob, Play Games, In app review, OneSignal

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hi @SanketAIT, this is most likely an issue with the Android Gradle Plugin. The most recent versions of Firebase SDK for Android have [breaking changes](https://firebase.google.com/support/release-notes/android#2024-06-20):
> Breaking change: Changed the required minimum compileSdkVersion to be 34 or higher.
> Breaking change: Updated minSdkVersion to API level 21 or higher.

It might be a compatibility issue. Could you try using Unity editor version `2022.3.38f1` and up. You may check out the [Version compatibility chart](https://docs.unity3d.com/Manual/android-gradle-overview.html) in the official Unity documentations and use the specific Unity Editor version accordingly:

Unity version | Gradle version | Android Gradle Plug-in version
| ------------ | -------------- |-------------- |
2022.3 (starting from 2022.3.38f1) | 7.5.1 | 7.4.2
2022.3 (up and including 2022.3.37f1) | 7.2 | 7.1.2
2021.32020.3 (starting from 2020.3.15f1) | 6.1.1 | 4.0.1
2020.3 (up to and including 2020.3.14f1) | 5.6.4 | 4.0.1

Let me know if this works, thanks!

**Comment by SanketAIT** [comment]
@argzdev Downloaded Unity 2023.2.20f1. 

getting this error now. can you please check?

MY SETTINGS
![Screenshot 2024-07-16 224644](https://github.com/user-attachments/assets/a7478ee7-79e1-4cc1-934c-3d5e641c9b59)


ERROR
![Screenshot 2024-07-16 224521](https://github.com/user-attachments/assets/1ea3be03-05d9-4918-b06d-3ac394e270f1)

**Comment by argzdev** [comment]
Hey @SanketAIT, I'm not sure. Could you reach out to community forum in [Unity](https://forum.unity.com/), they will likely be able to assist you better in setting up your Unity editor. This issue does not indicate any problem that's related to the Firebase SDK.

**Comment by SanketAIT** [comment]
Hello @argzdev, I was previously using Firebase version 11.8.1, but after upgrading to version 12.1.0, I am encountering issues with building the .APK file. It seems that the upgrade may have introduced compatibility issues or conflicts affecting the build process. I will also be reaching out to the Unity community for further assistance with this issue. 

Thank you very much for your help. :)

**Comment by argzdev** [comment]
Yeah, that does sound like the upgrade issue is due to the breaking change. I'll go ahead and close this thread for now. Feel free to let me know if there's other underlying issues that come up after fixing the compatibility issue. We can always reopen the thread if we identify that Firebase SDK is causing the problem.
