### ISSUE TITLE
[错误]错误：D8：com.android.tools.r8.kotlin.H Unity2022.3.38 升级android api 34 build failure

### ISSUE THREAD

**Issue by shuaigedev** [firebase/firebase-unity-sdk#1071]
### Description

ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:dexBuilderRelease'.
> Could not resolve all files for configuration ':launcher:detachedConfiguration5'.
   > Failed to transform jetified-play-services-measurement-api-22.0.2-runtime.jar to match attributes {artifactType=ext-dex-dexBuilderRelease, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingExternalLibArtifactTransform: /Users/zhongzesheng/.gradle/caches/transforms-3/7f37ac3da37ecbfd37089762d121c97a/transformed/jetified-play-services-measurement-api-22.0.2-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.28

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

Analytics

### Additional SDKs you are using

无

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hi @shuaigedev, thanks for reaching out. Unfortunately, it seems that there's an issue with Firebase SDK version `12.1.0`. For context, there are [breaking changes](https://firebase.google.com/support/release-notes/android#bom_v33-0-0) in Firebase Android SDK which requires compileSdkVersion `34`.

> Breaking change: Changed the required minimum compileSdkVersion to be 34 or higher.
> Breaking change: Updated minSdkVersion to API level 21 or higher.

Now according to the [Unity forums](https://forum.unity.com/threads/cant-build-for-android-34.1486539/), Unity Editors currently do not support compileSdkVersion 34, and is currently being worked on by their engineers. There are workarounds, by the [Unity engineer](https://forum.unity.com/threads/cant-build-for-android-34.1486539/#post-9909282), however I haven't tried it myself. That said, lease continue your report in the linked Unity thread.

Thanks!

**Comment by shuaigedev** [comment]
@argzdev Hi, I am currently using compileSdkVersion 34, but it still doesn't work. I will try using 11.9.0 to see if it works
！[图片]（https://github.com/user-attachments/assets/d828b190-aaa6-41d4-8904-1aaa998296ca）
