### ISSUE TITLE
[Bug] NoClassDefFoundError at startup

### ISSUE THREAD

**Issue by marcoseverguild** [firebase/firebase-unity-sdk#1072]
### Description

Hello
We are experiencing an issue with the last Firebase Unity SDK 12.1.0.
We are building aab with multidex and split application binary enabled, Unity 2022.3.13f1

The build seems to crash at startup with this error:

07-18 18:38:35.765  7452  7452 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.checkContentProviderAuthority(FirebaseInitProvider.java:85)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:60)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7940)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7451)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7209)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8377)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
07-18 18:38:35.765  7452  7452 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

We have tried almost everything, so we are running out of ideas. Some things that we are seeing:
- After updating to the new firebase we were using the 10.4.0, where if we disable the custom main gradle we were able to build and it was working correctly.
- We have updated the Firebase SDK so we could compile with target sdk 34 (that will be required by google in one month), and just with that we weren't able to build, so we activated the custom main gradle template and use the resolver to patch it. That fixed the build, but it crashed at startup with the error mentioned
- We tried a lot of solutions, adding some configurations and implementations to the gradle, try removing and putting multidex, remove other plugins...but with no luck, we always end up with that error.

Any suggestions?

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.13f1

### Installation Method

.unitypackage

### Additional SDKs you are using

Helpshift, Appsflyer, Playfab

### Targeted Platform(s)

Android

### Unity editor platform

Mac, Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @marcoseverguild, thanks for reaching out. Could you share which Firebase products are you using? Thanks!

**Comment by marcoseverguild** [comment]
Yes, we are using Analytics, Messaging and Database

**Comment by argzdev** [comment]
Thanks for the extra details, @marcoseverguild. There's an issue with Firebase SDK version 12.1.0. For context, there are [breaking changes](https://firebase.google.com/support/release-notes/android#bom_v33-0-0) in Firebase Android SDK which requires compileSdkVersion 34.

> Breaking change: Changed the required minimum compileSdkVersion to be 34 or higher.
> Breaking change: Updated minSdkVersion to API level 21 or higher.

Now according to the [Unity forums](https://forum.unity.com/threads/cant-build-for-android-34.1486539/), Unity Editors currently do not support compileSdkVersion 34, and is currently being worked on by their engineers. There are workarounds, by the [Unity engineer](https://forum.unity.com/threads/cant-build-for-android-34.1486539/#post-9909282), however I haven't tried it myself.

Another mitigation would be to downgrade Firebase SDK version 11.9.0 while waiting for Unity to update the compileSdkVersion on their side.

That said, please continue your report in the linked Unity thread.

Thanks!

**Comment by argzdev** [comment]
Hey @marcoseverguild, could you try the solution provided by one of the developers:
> - Export the Unity project to Android Studio, change Gradle and AGP version to 8+. ([This page says Android 34 requires AGP 8.1.1+](https://developer.android.com/build/releases/gradle-plugin#api-level-support)).
> - Change min SDK from 23 to 24.

Let me know if that makes any difference. Thanks!
