### ISSUE TITLE
[Bug] Failed to transform jetified-play-services-measurement-api-21.6.2-runtime.jar to match attributes {artifactType=ext-dex-dexBuilderRelease, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

### ISSUE THREAD

**Issue by shuaigedev** [firebase/firebase-unity-sdk#1073]
### Description

Minimum API Level : Android 5.1
Target API:Level API Level 34
![image](https://github.com/user-attachments/assets/775f31d1-afeb-4fdb-a735-54127fa18d95)

ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:dexBuilderRelease'.
> Could not resolve all files for configuration ':launcher:detachedConfiguration5'.
   > Failed to transform jetified-play-services-measurement-api-21.6.2-runtime.jar to match attributes {artifactType=ext-dex-dexBuilderRelease, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingExternalLibArtifactTransform: /Users/zhongzesheng/.gradle/caches/transforms-3/e7e328a97b5334ced724062f61acc4d1/transformed/jetified-play-services-measurement-api-21.6.2-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:203)

### Reproducing the issue

最低API级别：Android 5.1最低API级别：Android 5.1目标API：级别API级别34！[图像]（https://github.com/user-attachments/assets/775f31d1-afeb-4fdb-a735-54127fa18d95）目标API：级别API级别34！[图像]（https://github.com/user-attachments/assets/775f31d1-afeb-4fdb-a735-54127fa18d95）

use this seeting build android apk

### Firebase Unity SDK Version

11.9.0 and 12.1.0

### Unity editor version

2022.3.38f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

Analytics

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by zudl** [comment]
I can confirm, the same thing happens to me, but the error is slightly different.

```1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:dexBuilderRelease'.
> Could not resolve all files for configuration ':launcher:detachedConfiguration4'.
   > Failed to transform jetified-play-services-measurement-api-22.0.2-runtime.jar to match attributes {artifactType=ext-dex-dexBuilderRelease, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingExternalLibArtifactTransform: /Users/needle/.gradle/caches/transforms-3/64b0c7447f3c6bbe741650ffe23d8c98/transformed/jetified-play-services-measurement-api-22.0.2-runtime.jar.
         > Error while dexing.
```

It is impossible to build directly from Unity. However, if you bypass this and build through the Gradle project and Android Studio, everything works without any issues.

Unity 2022.3.38f1
API Level 34
Firebase RemoteConfig + Analytics 12.1.0
Mac
IL2CPP

**Comment by AgentSamad** [comment]
Same thing happpen to me 
Unity Version : 2022.3.38f1 
target Sdk Verion 34 
 
 Working fine until i import firebase (tried both versions 12.1 & 11.9

**Comment by nghuuhieu1994** [comment]
Bump the `AndroidMinSdkVersion` from `23` to `24` to temporarily fix the issue.

**Comment by argzdev** [comment]
Hey folks, could you try the solution provided [here](https://github.com/firebase/firebase-unity-sdk/issues/1070#issuecomment-2243809612):

> Export the Unity project to Android Studio, change Gradle and AGP version to 8+. ([This page says Android 34 requires AGP 8.1.1+](https://developer.android.com/build/releases/gradle-plugin#api-level-support)).
> Change min SDK from 23 to 24.

So far when testing with our Firebase Analytics from the Unity Quickstart, it works correctly with Android 14 emulator.

**Comment by kevin-redcellgames** [comment]
We've also been able to make a build with minsdk=22 by changing the android gradle plugin versions in `baseProjectTemplate.gradle`

```
// Old
// id 'com.android.application' version '7.4.2' apply false
// id 'com.android.library' version '7.4.2' apply false

// New
id 'com.android.application' version '7.1.2' apply false
id 'com.android.library' version '7.1.2' apply false
```
Don't know what the repercussions of this change are yet, though.

**Comment by hoanganhnh2009** [comment]
> Bump the `AndroidMinSdkVersion` from `23` to `24` to temporarily fix the issue.

It work with me. tks

**Comment by argzdev** [comment]
Closing this thread as this has been resolved. For folks who would like to maintain using version `22`. We've discussed a few possible solutions [here](https://github.com/googlesamples/unity-jar-resolver/issues/703#issuecomment-2278773620). Feel free to check it out. Thanks!
