### ISSUE TITLE
[Bug] internal::IsInitialized() Error When LogEvent

### ISSUE THREAD

**Issue by ak1320** [firebase/firebase-unity-sdk#1099]
### Description

I think I installed Firebase SDK without any problems. Google-services.json is in the Asset folder. When I want to use a "LogEvent" in the game, I get this error without any details.

`Autoconnected Player "Autoconnected Player" System.ApplicationException: internal::IsInitialized()
  at Firebase.Analytics.FirebaseAnalytics.LogEvent (System.String name, Firebase.Analytics.Parameter[] parameters) [0x00000] in <00000000000000000000000000000000>:0 
  at PUS.Start () [0x00000] in <00000000000000000000000000000000>:0 `

The start function is as follows:
```
try
        {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
            {
                FirebaseApp app = FirebaseApp.DefaultInstance;

            });
            FirebaseApp.LogLevel = LogLevel.Debug;
            Parameter[] parameters = { new Parameter("Player", ZPlayerPrefs.GetString("username")) };
            FirebaseAnalytics.LogEvent("opened_mall", parameters);
        }catch(Exception e)
        {
            Debug.Log(e);
        }
```

### Firebase Unity SDK Version

12.2.0

### Unity editor version

2022.3.40f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

All

### Other Firebase Component(s) in use

Analytics

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @ak1320, thanks for reaching out. `CheckAndFixDependenciesAsync` runs asynchronously so you're likely logging events before the check completes. You should log your events only after the dependency check completes.
```
try
{
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
            {
                FirebaseApp app = FirebaseApp.DefaultInstance;
                // move your log events here
                FirebaseApp.LogLevel = LogLevel.Debug;
                Parameter[] parameters = { new Parameter("Player", ZPlayerPrefs.GetString("username")) };
                FirebaseAnalytics.LogEvent("opened_mall", parameters);
            });
} 
catch(Exception e)
{
    Debug.Log(e);
}
```

That said, I believe this resolves your issue. I'll go ahead and close this thread. Thanks!

**Comment by ak1320** [comment]
![image](https://github.com/user-attachments/assets/563578ef-d666-4dce-a87b-bdc110a03836)

Unfortunately, this code attempt did not work either.
![image](https://github.com/user-attachments/assets/45c453e9-4e48-496b-918f-fb97f1abe9a1)

**Comment by ak1320** [comment]
@argzdev issue not solved yet, please open this issue again.

**Comment by argzdev** [comment]
I've tried testing your code with our [Firebase Unity quickstart](https://github.com/firebase/quickstart-unity) and so far I'm unable to experience the same behavior. Could you provide an MCVE for us to investigate this further?
