### ISSUE TITLE
[Bug] [libFirebaseCppApp-12_2_0.so] Firebase_Analytics_CSharp_LogEvent__SWIG_5

### ISSUE THREAD

**Issue by Ls9257** [firebase/firebase-unity-sdk#1106]
### Description

My Google Play Console has a large number of firebase crashes as follows:
[libFirebaseCppApp-12_2_0.so] Firebase_Analytics_CSharp_LogEvent__SWIG_5
[libFirebaseCppApp-12_2_0.so] firebase::analytics::Parameter::operator=(firebase::analytics::Parameter const&)

Here is my initialization code

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Text;
using Firebase;
using UnityEngine;
using Firebase.Analytics;
using Firebase.Extensions;

public class AnalyticsComponent : Singleton<AnalyticsComponent>
{
    private ConcurrentDictionary<string, Parameter[]> _analyDic =
        new ConcurrentDictionary<string, Parameter[]>();

    private readonly List<Parameter> _pars = new List<Parameter>();

    private readonly StringBuilder _builder = new StringBuilder();

    private bool _isFirebase;

    protected override void Awake()
    {
        base.Awake();
        if (Application.platform == RuntimePlatform.Android)
        {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
            {
                if (task.Result != DependencyStatus.Available) return;

                _isFirebase = true;

                if (_analyDic.Count > 0)
                    foreach (var tmp in _analyDic)
                        FirebaseAnalytics.LogEvent(tmp.Key, _analyDic[tmp.Key]);

                _analyDic.Clear();
            });
        }
    }

    public void Analytics(string anName)
    {
        if (Application.platform == RuntimePlatform.Android)
        {
            if (_isFirebase)
                FirebaseAnalytics.LogEvent(anName);
            else
                _analyDic.TryAdd(anName, null);
        }

        Debug.Log(anName);
    }

    public void Analytics(string anName, string parameterName, string parameterValue)
    {
        if (Application.platform == RuntimePlatform.Android)
        {
            if (_isFirebase)
                FirebaseAnalytics.LogEvent(anName, new Parameter(parameterName, parameterValue));
            else
                _analyDic.TryAdd(anName,
                    new[] { new Parameter(parameterName, parameterValue) });
        }

        Debug.Log(anName + " " + parameterName + " " + parameterValue);
    }

    private void Analytics(string anName, params Parameter[] parameters)
    {
        if (Application.platform == RuntimePlatform.Android)
        {
            if (_isFirebase)
                FirebaseAnalytics.LogEvent(anName, parameters);
            else
                _analyDic.TryAdd(anName, parameters);
        }
    }

    public void Analytics(string anName, Dictionary<string, string> parameters)
    {
        _pars.Clear();

        _builder.Clear();

        foreach (var par in parameters)
        {
            if (Application.platform == RuntimePlatform.Android)
            {
                _pars.Add(new Parameter(par.Key, par.Value));
            }

            _builder.Append(par.Key + ":" + par.Value + " ");
        }

        Debug.Log(anName + " " + _builder.ToString());

        Analytics(anName, _pars.ToArray());
    }

    public void OnAnalytics(string anName, Dictionary<string, string> parameters) => Analytics(anName, parameters);
}
![83ba18062b7f06306440267778e007e](https://github.com/user-attachments/assets/88b918c6-0cf1-434b-91fa-f31ec75a926e)
![ccfcef82a2bb0022ad23ca4aa83111a](https://github.com/user-attachments/assets/b95df227-c537-4dcc-a6bd-a4d27672a220)
![dac1e627776d9320d2e188fc55ce7eb](https://github.com/user-attachments/assets/54126569-4000-4b0d-908c-4a2b4e34d27f)

### Firebase Unity SDK Version

12.2.0

### Unity editor version

2021.3.43f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Analytics

### Other Firebase Component(s) in use

Analytics, Crashlytics, Messaging

### Additional SDKs you are using

Admob GoogleReview

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
[libFirebaseCppApp-12_2_0.so] firebase::analytics::Parameter::operator=(firebase::analytics::Parameter const&)
[libFirebaseCppApp-12_2_0.so] Firebase_Analytics_CSharp_LogEvent__SWIG_5
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @Ls9257, I wasn't able to reproduce this behavior when using your code snippets with your setup configuration. Are you able to reproduce this issue locally? If so, any chance you could share an MCVE so I can investigate this further? Thanks!

**Comment by Ls9257** [comment]
I'm not sure if an error was generated because the event parameter was passed with a null value

**Comment by Ls9257** [comment]
The reason for this error is that I mistakenly passed a Null parameter

**Comment by argzdev** [comment]
Glad you were able to resolve the issue, @Ls9257. Thanks for letting us know.
