### ISSUE TITLE
[Bug] Null value set to PhotoUrl is not saved on Android devices

### ISSUE THREAD

**Issue by georgemarkosian** [firebase/firebase-unity-sdk#1112]
### Description

Our app has a user avatar feature that allows users to delete their avatars. It's done through setting a null value to PhotoUrl and calling UpdateUserProfileAsync method. This works well on iOS and in Unity Editor, but on Android devices the task completes fine but the change is not applied.

### Reproducing the issue

0. Use Android device
1. Call UpdateUserProfileAsync with user profile with valid Uri in PhotoUrl
2. Call UpdateUserProfileAsync with the user profile with PhotoUrl set to null
3. PhotoUrl doesn't change and remains the same as set on step 1

### Firebase Unity SDK Version

12.2.0

### Unity editor version

2022.3.46

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Analytics, Crashlytics, Firestore, In-App Messaging, Installations, Messaging, Remote Config, Storage

### Additional SDKs you are using

FacebookSDK, AppsFlyer, GoogleSignIn.

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Thanks for reaching out, @georgemarkosian. I was able to reproduce the same behavior. I'll go ahead and notify our engineering team.
