### ISSUE TITLE
[Question] Cloud Functions for Firebase support for 2nd Gen functions

### ISSUE THREAD

**Issue by aixaCode** [firebase/firebase-unity-sdk#1113]
### What is your question?

Does Unity SDK support 2nd Gen functions?

### Firebase Unity SDK Version

12.1.0

### Unity editor version

2022.3.4.47

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Functions

### Targeted Platform(s)

Apple Platforms, Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hey @aixaCode, thanks for reaching out. Yes, the Firebase Functions of Unity SDK can call 1st gen and 2nd gen functions. There's no need to change the client side code implementation for either generations. You may check out our [documentations](https://firebase.google.com/docs/functions/callable?gen=2nd#call_the_function) how to do this. Likewise, you may also check out our [Firebase Unity Quickstarts](https://github.com/firebase/quickstart-unity) to get set up a lot faster. Though our quickstarts which includes the server side code is still using 1st gen.

Here's a sample 2nd gen server side code with NodeJS:
```javascript
const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { logger } = require("firebase-functions/v2");

exports.addNumbersV2 = onCall((request) => {
    const firstNumber = request.data.firstNumber;
    const secondNumber = request.data.secondNumber;

    if (!Number.isFinite(firstNumber) || !Number.isFinite(secondNumber)) {
        throw new HttpsError("invalid-argument", "The function must be called " +
            "with two arguments \"firstNumber\" and \"secondNumber\" which " +
            "must both be numbers.");
    }

    return {
        firstNumber: firstNumber,
        secondNumber: secondNumber,
        operator: "+",
        operationResult: firstNumber + secondNumber,
    };
});
```

I believe this answers your question. That said, I'll go ahead and close this thread. Feel free to open another issue in case you have further issues. You may also file a support ticket to our [Firebase support channel](https://firebase.google.com/support) for general inquiry questions. Thanks!
