### ISSUE TITLE
[Bug] Firebase Messaging SDK requires Android Min SDK version 24 but min SDK 23 is mentioned ChangeLogs of 12.0.0

### ISSUE THREAD

**Issue by Awais6** [firebase/firebase-unity-sdk#1122]
### Description

Firebase Messaging SDK requires Android Min SDK version 24 but not defined in changelog and it should work fine with minSDK 23 as mentioned in the changelogs of Firebase SDK 12.0.0.

### Reproducing the issue

Install Firebase Messaging SDK 12.3.0 and try to build by defining 23 as minSDK in Unity Project Settings.

### Firebase Unity SDK Version

12.3.0

### Unity editor version

2021.3.42f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Messaging

### Other Firebase Component(s) in use

Analytics, Authentication, Crashlytics, Database, Firestore, Functions, Remote Config

### Additional SDKs you are using

Unity Ads

### Targeted Platform(s)

Android

### Unity editor platform

Linux

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
stderr[
/root/project/Library/Bee/Android/Prj/IL2CPP/Gradle/launcher/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 23 cannot be smaller than version 24 declared in library [:firebase-messaging-cpp:] /root/.gradle/caches/transforms-3/c45ccf72757dbf30efe6877036598e6b/transformed/jetified-firebase-messaging-cpp/AndroidManifest.xml as the library might be using APIs not available in 23
        Suggestion: use a compatible library with a minSdk of at most 23,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.google.android.gms.messaging.cpp" to force usage (may lead to runtime failures)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build completed with 2 failures.
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by Awais6** [comment]
I have build my project successfully with Firebase Unity SDK 12.2.1 and minSDK 23. 
Issue is with the current release (12.3.0) only.

**Comment by argzdev** [comment]
Hey @Awais6, thanks for bringing this up. I was able to reproduce the same behavior. Let me notify our engineers about this.

**Comment by a-maurice** [comment]
Sorry about that.  The 12.3.0 release had some problems with our dependencies updating, and one of the fixes was updating the minSdkVersion, which we then forgot to call out in the release notes.  I'll update the release notes to reflect that change, since it is a rather annoying one, and one we would like to avoid if possible.  We'll also reinvestigate if we can reduce it back to 23, though no promises of it that will be possible.  In the meantime, the best course of action if you need to set the minSdkVersion to 23 would be to use the 12.2.1 release instead.
