### ISSUE TITLE
[Bug] 'headerValue()' is unavailable in Swift: Use asyncHeaderValue()

### ISSUE THREAD

**Issue by Kharion** [firebase/firebase-unity-sdk#1130]
### Description

Xcode is unable to build our game. We did not made any changes to Firebase or any other SDK since October 9th. The builds stopped working overnight with following error:

```
build/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:112:40: error: 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
      request.setValue(heartbeatLogger.headerValue(), forHTTPHeaderField: "X-Firebase-Client")
                                       ^~~~~~~~~~~
FirebaseCoreExtension.FIRHeartbeatLoggerProtocol:12:10: note: 'headerValue()' has been explicitly marked unavailable here
    func headerValue() -> String?
```

We use EDM 1.2.183, Firebase Unity SDK 12.3.0. Not even downgrade to 12.2.1 helps. Google Mobile Ads version 9.2.0 (unity package). This is very unfortunate since we are in the release week. Please give us workaround instructions.

### Reproducing the issue

Install Firebase SDK, and try to build iOS project in the Xcode

### Firebase Unity SDK Version

12.3.0

### Unity editor version

2022.3.40f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Analytics, Crashlytics, Messaging

### Additional SDKs you are using

Facebook (17.0.1), AdMob (9.2.0), AppLovin 7.0.0, Singular, TapJoy

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
build/Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift:112:40: error: 'headerValue()' is unavailable in Swift: Use `asyncHeaderValue() async -> String?` instead.
      request.setValue(heartbeatLogger.headerValue(), forHTTPHeaderField: "X-Firebase-Client")
                                       ^~~~~~~~~~~
FirebaseCoreExtension.FIRHeartbeatLoggerProtocol:12:10: note: 'headerValue()' has been explicitly marked unavailable here
    func headerValue() -> String?
         ^

RegisterExecutionPolicyException /Users/build/Library/Developer/Xcode/DerivedData/Unity-iPhone-
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

PODS:
  - AppLovinMediationFacebookAdapter (6.15.2.1):
    - AppLovinSDK (>= 13.0.0)
    - FBAudienceNetwork (= 6.15.2)
  - AppLovinMediationGoogleAdapter (11.10.0.0):
    - AppLovinSDK (>= 13.0.0)
    - Google-Mobile-Ads-SDK (= 11.10.0)
  - AppLovinMediationIronSourceAdapter (8.4.0.0.0):
    - AppLovinSDK (>= 13.0.0)
    - IronSourceSDK (= 8.4.0.0)
  - AppLovinMediationMintegralAdapter (7.7.2.0.1):
    - AppLovinSDK (>= 13.0.0)
    - MintegralAdSDK (= 7.7.2)
    - MintegralAdSDK/BidSplashAd (= 7.7.2)
  - AppLovinMediationUnityAdsAdapter (4.12.3.0):
    - AppLovinSDK (>= 13.0.0)
    - UnityAds (= 4.12.3)
  - AppLovinMediationVungleAdapter (7.4.2.0):
    - AppLovinSDK (>= 13.0.0)
    - VungleAds (= 7.4.2)
  - AppLovinSDK (13.0.0)
  - FBAEMKit (17.0.3):
    - FBSDKCoreKit_Basics (= 17.0.3)
  - FBAudienceNetwork (6.15.2)
  - FBSDKCoreKit (17.0.3):
    - FBAEMKit (= 17.0.3)
    - FBSDKCoreKit_Basics (= 17.0.3)
  - FBSDKCoreKit_Basics (17.0.3)
  - FBSDKGamingServicesKit (17.0.3):
    - FBSDKCoreKit (= 17.0.3)
    - FBSDKCoreKit_Basics (= 17.0.3)
    - FBSDKShareKit (= 17.0.3)
  - FBSDKLoginKit (17.0.3):
    - FBSDKCoreKit (= 17.0.3)
  - FBSDKShareKit (17.0.3):
    - FBSDKCoreKit (= 17.0.3)
  - Firebase/Analytics (11.0.0):
    - Firebase/Core
  - Firebase/Auth (11.0.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 11.0.0)
  - Firebase/Core (11.0.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (~> 11.0.0)
  - Firebase/CoreOnly (11.0.0):
    - FirebaseCore (= 11.0.0)
  - Firebase/Crashlytics (11.0.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 11.0.0)
  - Firebase/Messaging (11.0.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 11.0.0)
  - FirebaseAnalytics (11.0.0):
    - FirebaseAnalytics/AdIdSupport (= 11.0.0)
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAnalytics/AdIdSupport (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleAppMeasurement (= 11.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - FirebaseAppCheckInterop (11.4.0)
  - FirebaseAuth (11.0.0):
    - FirebaseAppCheckInterop (~> 11.0)
    - FirebaseAuthInterop (~> 11.0)
    - FirebaseCore (~> 11.0)
    - FirebaseCoreExtension (~> 11.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GTMSessionFetcher/Core (~> 3.4)
    - RecaptchaInterop (~> 100.0)
  - FirebaseAuthInterop (11.4.0)
  - FirebaseCore (11.0.0):
    - FirebaseCoreInternal (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Logger (~> 8.0)
  - FirebaseCoreExtension (11.4.0):
    - FirebaseCore (~> 11.0)
  - FirebaseCoreInternal (11.4.0):
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
  - FirebaseCrashlytics (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - FirebaseRemoteConfigInterop (~> 11.0)
    - FirebaseSessions (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - FirebaseInstallations (11.4.0):
    - FirebaseCore (~> 11.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - PromisesObjC (~> 2.4)
  - FirebaseMessaging (11.0.0):
    - FirebaseCore (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/Reachability (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
  - FirebaseRemoteConfigInterop (11.4.0)
  - FirebaseSessions (11.3.0):
    - FirebaseCore (~> 11.0)
    - FirebaseCoreExtension (~> 11.0)
    - FirebaseInstallations (~> 11.0)
    - GoogleDataTransport (~> 10.0)
    - GoogleUtilities/Environment (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - nanopb (~> 3.30910.0)
    - PromisesSwift (~> 2.1)
  - Google-Mobile-Ads-SDK (11.10.0):
    - GoogleUserMessagingPlatform (>= 1.1)
  - GoogleAppMeasurement (11.0.0):
    - GoogleAppMeasurement/AdIdSupport (= 11.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleAppMeasurement/AdIdSupport (11.0.0):
    - GoogleAppMeasurement/WithoutAdIdSupport (= 11.0.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleAppMeasurement/WithoutAdIdSupport (11.0.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 8.0)
    - GoogleUtilities/MethodSwizzler (~> 8.0)
    - GoogleUtilities/Network (~> 8.0)
    - "GoogleUtilities/NSData+zlib (~> 8.0)"
    - nanopb (~> 3.30910.0)
  - GoogleDataTransport (10.1.0):
    - nanopb (~> 3.30910.0)
    - PromisesObjC (~> 2.4)
  - GoogleUserMessagingPlatform (2.6.0)
  - GoogleUtilities/AppDelegateSwizzler (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
    - GoogleUtilities/Privacy
  - GoogleUtilities/Environment (8.0.2):
    - GoogleUtilities/Privacy
  - GoogleUtilities/Logger (8.0.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Privacy
  - GoogleUtilities/MethodSwizzler (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/Network (8.0.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Privacy
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (8.0.2)":
    - GoogleUtilities/Privacy
  - GoogleUtilities/Privacy (8.0.2)
  - GoogleUtilities/Reachability (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GoogleUtilities/UserDefaults (8.0.2):
    - GoogleUtilities/Logger
    - GoogleUtilities/Privacy
  - GTMSessionFetcher/Core (3.5.0)
  - IronSourceSDK (8.4.0.0)
  - MintegralAdSDK (7.7.2):
    - MintegralAdSDK/BannerAd (= 7.7.2)
    - MintegralAdSDK/BidBannerAd (= 7.7.2)
    - MintegralAdSDK/BidInterstitialVideoAd (= 7.7.2)
    - MintegralAdSDK/BidNativeAd (= 7.7.2)
    - MintegralAdSDK/BidNewInterstitialAd (= 7.7.2)
    - MintegralAdSDK/BidRewardVideoAd (= 7.7.2)
    - MintegralAdSDK/InterstitialVideoAd (= 7.7.2)
    - MintegralAdSDK/NativeAd (= 7.7.2)
    - MintegralAdSDK/NewInterstitialAd (= 7.7.2)
    - MintegralAdSDK/RewardVideoAd (= 7.7.2)
  - MintegralAdSDK/BannerAd (7.7.2):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/BidBannerAd (7.7.2):
    - MintegralAdSDK/BannerAd
    - MintegralAdSDK/BidNativeAd
  - MintegralAdSDK/BidInterstitialVideoAd (7.7.2):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/InterstitialVideoAd
  - MintegralAdSDK/BidNativeAd (7.7.2):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/BidNewInterstitialAd (7.7.2):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/NewInterstitialAd
  - MintegralAdSDK/BidRewardVideoAd (7.7.2):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/RewardVideoAd
  - MintegralAdSDK/BidSplashAd (7.7.2):
    - MintegralAdSDK/BidNativeAd
    - MintegralAdSDK/SplashAd
  - MintegralAdSDK/InterstitialVideoAd (7.7.2):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/NativeAd (7.7.2)
  - MintegralAdSDK/NewInterstitialAd (7.7.2):
    - MintegralAdSDK/InterstitialVideoAd
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/RewardVideoAd (7.7.2):
    - MintegralAdSDK/NativeAd
  - MintegralAdSDK/SplashAd (7.7.2):
    - MintegralAdSDK/NativeAd
  - nanopb (3.30910.0):
    - nanopb/decode (= 3.30910.0)
    - nanopb/encode (= 3.30910.0)
  - nanopb/decode (3.30910.0)
  - nanopb/encode (3.30910.0)
  - PromisesObjC (2.4.0)
  - PromisesSwift (2.4.0):
    - PromisesObjC (= 2.4.0)
  - RecaptchaInterop (100.0.0)
  - TapjoySDK (13.0.1)
  - UnityAds (4.12.3)
  - VungleAds (7.4.2)

DEPENDENCIES:
  - AppLovinMediationFacebookAdapter (= 6.15.2.1)
  - AppLovinMediationGoogleAdapter (= 11.10.0.0)
  - AppLovinMediationIronSourceAdapter (= 8.4.0.0.0)
  - AppLovinMediationMintegralAdapter (= 7.7.2.0.1)
  - AppLovinMediationUnityAdsAdapter (= 4.12.3.0)
  - AppLovinMediationVungleAdapter (= 7.4.2.0)
  - AppLovinSDK (= 13.0.0)
  - FBAudienceNetwork (~> 6.15.0)
  - FBSDKCoreKit (~> 17.0.1)
  - FBSDKCoreKit_Basics (~> 17.0.1)
  - FBSDKGamingServicesKit (~> 17.0.1)
  - FBSDKLoginKit (~> 17.0.1)
  - FBSDKShareKit (~> 17.0.1)
  - Firebase/Analytics (= 11.0.0)
  - Firebase/Auth (= 11.0.0)
  - Firebase/Core (= 11.0.0)
  - Firebase/Crashlytics (= 11.0.0)
  - Firebase/Messaging (= 11.0.0)
  - Google-Mobile-Ads-SDK (~> 11.10.0)
  - GoogleUserMessagingPlatform (= 2.6.0)
  - TapjoySDK (= 13.0.1)

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - AppLovinSDK
    - FBAudienceNetwork
    - FBSDKCoreKit
    - FBSDKCoreKit_Basics
    - FBSDKShareKit
    - FirebaseCore
    - Google-Mobile-Ads-SDK
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - PromisesObjC
  trunk:
    - AppLovinMediationFacebookAdapter
    - AppLovinMediationGoogleAdapter
    - AppLovinMediationIronSourceAdapter
    - AppLovinMediationMintegralAdapter
    - AppLovinMediationUnityAdsAdapter
    - AppLovinMediationVungleAdapter
    - FBAEMKit
    - FBSDKGamingServicesKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAnalytics
    - FirebaseAppCheckInterop
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCoreExtension
    - FirebaseCoreInternal
    - FirebaseCrashlytics
    - FirebaseInstallations
    - FirebaseMessaging
    - FirebaseRemoteConfigInterop
    - FirebaseSessions
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - GTMSessionFetcher
    - IronSourceSDK
    - MintegralAdSDK
    - nanopb
    - PromisesSwift
    - RecaptchaInterop
    - TapjoySDK
    - UnityAds
    - VungleAds

SPEC CHECKSUMS:
  AppLovinMediationFacebookAdapter: a569c3015e24b5e00049a46bb344ba00894b3541
  AppLovinMediationGoogleAdapter: cfe4d8971d01cc3fc31bfb3850243e37bc02812d
  AppLovinMediationIronSourceAdapter: 780e901f72f69bade8e53a645a9c07bb220a8f01
  AppLovinMediationMintegralAdapter: 9952d52bcec54fe038b690bf9a29375d5728419a
  AppLovinMediationUnityAdsAdapter: 715fccd4edd58ed8b42708f6cd6229888db0226f
  AppLovinMediationVungleAdapter: ae90969e09a9d69dced0b56f2f0dee9e7a958b03
  AppLovinSDK: c0ecb434df24008b6ecdd7f1e5b8587bc45ff381
  FBAEMKit: 9900b2edd99a2d21629a6277e6166f14c6215799
  FBAudienceNetwork: 2457a89b45e2596241fd81b0c2fd8cb6f6053869
  FBSDKCoreKit: 0791f8f68a8630931a4c12aa23a56cc021551596
  FBSDKCoreKit_Basics: 46d6b472c0dd0a5a7e972c025033d1c567f54eb4
  FBSDKGamingServicesKit: 599a63c235776b7c6288d5dfd7c02edab9a1d3b7
  FBSDKLoginKit: b4a4eba1d62eb452544411824f41689adabd5bd2
  FBSDKShareKit: eb1169eafe3c06f881dc6deed2d7979585b16959
  Firebase: 9f574c08c2396885b5e7e100ed4293d956218af9
  FirebaseAnalytics: 27eb78b97880ea4a004839b9bac0b58880f5a92a
  FirebaseAppCheckInterop: 1b9643ae2f1ee214488caa2f8e32b7bc2f0f3735
  FirebaseAuth: d5cf28be74d7e82257f6a3f717509eff70d3cf4a
  FirebaseAuthInterop: 9ac948965ac13ec9d8a080f39490ddb2bda30520
  FirebaseCore: 3cf438f431f18c12cdf2aaf64434648b63f7e383
  FirebaseCoreExtension: 4445e4cd877e0790c4af33bedca61eaef27b7513
  FirebaseCoreInternal: 5c2b016f06a96fbf20d9b443459f80427a827d7b
  FirebaseCrashlytics: 745d8f0221fe49c62865391d1bf56f5a12eeec0b
  FirebaseInstallations: 6ef4a1c7eb2a61ee1f74727d7f6ce2e72acf1414
  FirebaseMessaging: d2d1d9c62c46dd2db49a952f7deb5b16ad2c9742
  FirebaseRemoteConfigInterop: e76f46ffa4d6a65e273d4dfebb6a79e588cec136
  FirebaseSessions: 655ff17f3cc1a635cbdc2d69b953878001f9e25b
  Google-Mobile-Ads-SDK: 13e6e98edfd78ad8d8a791edb927658cc260a56f
  GoogleAppMeasurement: 6e49ffac7d3f2c3ded9cc663f912a13b67bbd0de
  GoogleDataTransport: aae35b7ea0c09004c3797d53c8c41f66f219d6a7
  GoogleUserMessagingPlatform: 0c3a08353e53ce8c2feab7addd0b652cde522450
  GoogleUtilities: 26a3abef001b6533cf678d3eb38fd3f614b7872d
  GTMSessionFetcher: 5aea5ba6bd522a239e236100971f10cb71b96ab6
  IronSourceSDK: 557a0edad39c2a48a225af07b491c672ca5acd36
  MintegralAdSDK: 7e05f9ab5f555b7049435a9477d457d7bf9b5473
  nanopb: fad817b59e0457d11a5dfbde799381cd727c1275
  PromisesObjC: f5707f49cb48b9636751c5b2e7d227e43fba9f47
  PromisesSwift: 9d77319bbe72ebf6d872900551f7eeba9bce2851
  RecaptchaInterop: 7d1a4a01a6b2cb1610a47ef3f85f0c411434cb21
  TapjoySDK: 30df1515a5a0a16076c6610c517911657164b2c2
  UnityAds: 32596c2f76856d643b50d3da51c47a552b80d5a4
  VungleAds: d7cf66a6dfd390a583ea2b2cfb9af1043b686e58

PODFILE CHECKSUM: ba7e215eea7f89c0da8ea5779d17b06f7113f98d

COCOAPODS: 1.14.2

**Comment by yepMad** [comment]
The same happens here, even in builds that previously worked and were untouched.

**Comment by argzdev** [comment]
Hey folks, thanks for reaching out. This looks like what's also happening with React Native built apps.
- https://github.com/invertase/react-native-firebase/issues/8073

Let me bring this up to our engineers.

**Comment by yepMad** [comment]
I've found a **workaround** for this, based on the answers the React Native Firebase folks provided.

In `/Firebase/Editor` inside all the `Dependencies.xml` you have (eg. `AppDependencies.xml`, `AuthDependencies.xml`, `FirestoreDependencies.xml`) change the “version” of `<iosPod ... />` to 11.4.0. This should solve the problem for now.

**Example:**

```
<iosPods>
    <iosPod name="Firebase/Auth" version="11.4.0" minTargetSdk="13.0">
    </iosPod>
</iosPods>
```

**Comment by argzdev** [comment]
Hi folks, I tried creating a new project and adding FirebaseAuth dependency, so far the iOS built app is now pulling the correct transitive dependencies. I guess that verifies that the issue has been resolved. I'll go ahead and close this thread now. Thanks!
