### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by aas-ka** [firebase/firebase-unity-sdk#1131]
### What is your question?

'GoogleSignIn/GIDSignIn.h' file not found
<img width="531" alt="Screenshot 2024-10-24 at 6 47 33 PM" src="https://github.com/user-attachments/assets/f8569130-52c2-43e0-bfac-510f1ae43749">

I am not able to see any pods created in Xcode. Unity compilation successful but Xcode is failing

### Firebase Unity SDK Version

12.3.0

### Unity editor version

2022.3.25f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Authentication

### Other Firebase Component(s) in use

Authentication

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hey @aas-ka, thanks for reaching out. This package doesn't look like a dependency within our Firebase Unity SDK. If you're using [Google-Unity-SignIn](https://github.com/googlesamples/google-signin-unity), you can file in their repository for further help. However, I did notice that their last commit was roughly 6+ years ago, so there might not be anyone managing that repository. You'll likely find more help if you file a report in the Unity forum, I saw a [similar thread](https://discussions.unity.com/t/google-sign-in/912126/26) that could help. That said, there's not much we can do on the SDK side. I'll go ahead and close this thread. Thanks!

**Comment by aas-ka** [comment]
But how can we integrate the Google sign in then?

**Comment by argzdev** [comment]
You can integrate Google Sign in by following the [official guide](https://docs.unity.com/ugs/manual/authentication/manual/platform-signin-google) in the Unity documentation. After that, if you'd like to save user information with Firebase, you can pass the ID token generated from the Google Sign in to Firebase using this [guide](https://firebase.google.com/docs/auth/unity/google-signin#authenticate_with_firebase).
