### ISSUE TITLE
[Bug] Quickstart example of cloud functions is not working (data parameter with numbers is not passed)

### ISSUE THREAD

**Issue by gudkovtimur** [firebase/firebase-unity-sdk#1135]
### Description

Quickstart example of cloud functions is not working. Data parameter is not passed. Tested in Unity Editor and android devices, both of emulator and deployed versions. It always return "Firebase.Functions.FunctionsException: The function must be called with two arguments "firstNumber" and "secondNumber" which must both be numbers."

### Reproducing the issue

Code is copied without modifications from https://github.com/firebase/quickstart-unity/tree/master/functions/testapp/Assets/Firebase/Sample/Functions

### Firebase Unity SDK Version

12.2.1

### Unity editor version

2022.3.16f

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Functions

### Other Firebase Component(s) in use

Authentication, Database, Storage

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Open-source from this repo

### Relevant Log Output

```shell
{"verifications":{"app":"MISSING","auth":"VALID"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"DEBUG","message":"Callable request verification passed"}
```

**Comment by argzdev** [comment]
Hey @gudkovtimur, thanks for reaching out. I'm able to reproduce the issue. It seems that the server side code embedded in the quickstart hasn't been updated for quite sometime. I'll try and see if I can make a pull request to adjust this. Thanks!
