### ISSUE TITLE
[Question] DllNotFoundException Error When Building for Android with Firebase Unity SDK: Missing FirebaseCppApp-12_4_1

### ISSUE THREAD

**Issue by Denisedkidu** [firebase/firebase-unity-sdk#1152]
### What is your question?

Hello! I've encountered an issue with a missing library FirebaseCppApp-12_4_1 when trying to build a project for Android. The error message I get is as follows:

DllNotFoundException: Unable to load DLL 'FirebaseCppApp-12_4_1'. Tried to load the following dynamic libraries: Unable to load dynamic library 'FirebaseCppApp-12_4_1' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "FirebaseCppApp-12_4_1" not found
at Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil

I am using Firebase Unity SDK to integrate various Firebase features into my app, but this error occurs during the Android build process.
![ошибка3](https://github.com/user-attachments/assets/33d39ed0-ed70-485b-9918-cc9c02b86b8e)

I have installed all necessary Firebase Unity SDK components, including Auth, Firestore, and Crashlytics. However, when building the Android app in Unity, I receive a DllNotFoundException indicating that FirebaseCppApp-12_4_1 is missing.

### Firebase Unity SDK Version

12.4.1

### Unity editor version

2022.3.35f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Analytics, App Check, Authentication, Crashlytics, Firestore

### Other Firebase Component(s) in use

Analytics, App Check, Authentication, Crashlytics, Firestore

### Additional SDKs you are using

no

### Targeted Platform(s)

Android

### Unity editor platform

Windows

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by Denisedkidu** [comment]
solved

**Comment by ahmedbenf** [comment]
Hi @Denisedkidu , i struggle with this error for a week. can you tell me how do you solve it  please ??

**Comment by rotolonico** [comment]
I am having the same issue, i'm on Mac Unity 2022.3.43f1

**Comment by argzdev** [comment]
Hey folks, thanks for reaching out. Since this issue is resolved on @Denisedkidu side. I'll go ahead and close this thread.

Please open a new issue @ahmedbenf, @rotolonico, so that we can investigate your issues. Thanks!
