### ISSUE TITLE
Can com.google.firebase.app remove Google Play Service dependencies?

### ISSUE THREAD

**Issue by milkcocoa** [firebase/firebase-unity-sdk#12]
https://firebase.google.com/docs/android/android-play-services says all Android packages don't have dependencies on Google Play services.

However, I only add the `com.google.firebase.app` Unity package, it seems that `com.google.android.gms:play-services-base` Android package is resolved automatically. Can you remove the Google Play services dependencies from the `com.google.firebase.app` Unity package, and make Unity packages which really need them have the dependencies.

**Comment by samtstern** [comment]
@milkcocoa `play-services-base` contains some utility classes, your app will still be able to run on devices without Google Play services installed.

**Comment by milkcocoa** [comment]
I'm sorry for replying late, but I've just confirmed you're right, `com.google.firebase.app` doesn't have any effect on Google Play services.
