### ISSUE TITLE
Wrong arguments in stack trace

### ISSUE THREAD

**Issue by AntonPetrov83** [firebase/firebase-unity-sdk#136]
Suddenly I noticed that method arguments are broken in Crashlytics. All methods have only one argument which has a type of a class method belongs to.

What is going on? This is Android build of a Unity game.

![image](https://user-images.githubusercontent.com/1997978/146364023-46c82248-00c0-424d-b862-d1ef71c26cf9.png)

**Comment by chkuang-g** [comment]
@AntonPetrov83 

Sorry to get back to you this late. Could you provide a bit more information:

- Which Unity version did you use?
- Which Firebase version did you use?
- This maybe either a client SDK issue or a backend issue. Is your issue resolved by upgrading to the later version of SDK or it is still happening now?

Thank you,
Shawn

**Comment by AntonPetrov83** [comment]
@chkuang-g 

Looks like it is not a problem any more.
