### ISSUE TITLE
Module that require Google Play Services breaks Firebase initialization if they are missing

### ISSUE THREAD

**Issue by vdaineko** [firebase/firebase-unity-sdk#170]
Hello! As documented https://firebase.google.com/docs/android/android-play-services some Firebase Android SDKs depend on Google Play Services (GPS). We publish our game for various Android stores, and it is assumed that devices not from the Google Play store may not have GPS installed. The problem is that, for example, the presence of Dynamic Links package installed (even without explicit use) breaks Firebase initialization on Amazon device and as a result it is impossible to use other modules, such as Remote Config, which do not require GPS. Is this the intended behavior? If yes, then it turns out that we should remove Firebase packages that require GPS and resolve dependencies before build for non Google Play store?

**Comment by gromilQaaaa** [comment]
To cut it short - Firebase Remote Config breaks Amazon and UDP builds! It is important! Please reply!

It is very problematic to uninstall a package during build stage. Android allows building on multiple stores, FIrebase must not limit us, it should at least ignore initialization instead of throwing an error.

**Comment by chkuang-g** [comment]
Hi @gromilQaaaa 

I think we removed Google Play Services dependencies for Remote Config quite awhile ago. Right now only FCM and Dynamic Links requires Google Play Services
https://github.com/firebase/firebase-cpp-sdk/search?q=FIREBASE_UTIL_RETURN_FAILURE_IF_GOOGLE_PLAY_UNAVAILABLE

Could you upgrade Firebase Unity SDK and see if this resolves your issue?

Thank you
