### ISSUE TITLE
Unity 2021.2.10 - error in android build process

### ISSUE THREAD

**Issue by IvanMurzak** [firebase/firebase-unity-sdk#173]
Firebase adds files automatically to `Assets/Plugins/Android/res/values/...`, as a result, I have the error when trying to create a new android build.
`Error building Player: Exception: OBSOLETE - Providing Android resources in Assets/Plugins/Android/res was removed, please move your resources to an AAR or an Android Library. See "AAR plug-ins and Android Libraries" section of the Manual for more details.`

Unity 2021.2.10
Firebase Unity SDK 8.8.0

**Comment by IvanMurzak** [comment]
@Yaski Firebase Unity plugin contains External Dependency Resolver. Possibly that is the issue related to that nested plugin. If so, I guess need to put a new External Dependency Resolver into the Firebase Unity plugin package.

**Comment by CriticalForce** [comment]
Actually for us this was caused by having our own version on my_backup_rules.xml etc under a res folder.
FireBase used Android Library implementation which is supported on 2021.2.

I'd suggest checking the other /res/ folders

**Comment by DellaBitta** [comment]
Hi @IvanMurzak,

A few questions:

- Is this something that can be reproduced with a quickstart? 
- Have you tried the latest SDK to see if the issue persists?
- What other SDKs are you importing?

Thanks!
