### ISSUE TITLE
After upgrading to 8.8, GetCredtialAsync() creates Internal Firebase Error

### ISSUE THREAD

**Issue by cjcurrie** [firebase/firebase-unity-sdk#188]
Operating system: Windows 10 Home
Operating system version: 20H2
Version of Unity: 2021.2.8f1

What steps will reproduce the problem:
1. Create blank Unity project
2. Install Firebase.Auth plugin version 8.8 (latest)
3. Install Google Play Services for Unity version 10.14 (latest)
4. Create a script that checks firebase dependencies, then creates the app, then calls auth.SignInWithCredentialAsync()

- OR -
Download and run the blank project I created to demonstrate this problem: [Google Drive Public Link](https://drive.google.com/file/d/1yVhC-0P8Wv0mEHGVK8fEv3DmG5d6XS0F/view?usp=sharing)

What is the expected result?
That auth signin will work correctly, as it did before upgrading from 8.0 to 8.8

What happens instead of that?
Internal Firebase Error - no further details given.

Please provide any other information below, and attach a screenshot if possible.

Hello,
I have a Unity game I've been developing with Firebase for over a year. I first created the Authentication process back during I think version 6.0 of Firebase for Unity. Since then I was able to upgrade twice without issue.

However, after upgrading from 8.0 to 8.8, GetCredentialAsync() creates an internal firebase error with no debug information. I've
- Downloaded the latest version of Firebase for Unity (from https://firebase.google.com/download/unity)
- Updated Google Play Games for Unity to the latest version, 0.10.14 (from https://github.com/playgameservices/play-games-plugin-for-unity)
- Checked Unity logs which show no sign of error
- Ensured my project number, project id, and client id in google-services.json match what's in firebase console
- Tried using different email/password user accounts to log in
- Created a new blank project with only the firebase auth plugin, google play games plugin, and GetCredentialAsync() code. See [Google Drive Public Link](https://drive.google.com/file/d/1yVhC-0P8Wv0mEHGVK8fEv3DmG5d6XS0F/view?usp=sharing)

Note 1:
Even in the new project, Google Version Handler is prompting me to delete version 1.2.167 of Google.IOSResolver.dll, JarResolver.dll, PackageManagerResolver.dll, and VersionHandlerImpl.dll. Is this expected behavior?
Note 2:
Because I won't post my app secret config here, you'll need to supply your own google-services.json to Assets folder and edit AuthTest.cs:86 with your app config. Likewise, you'll need to set the email and password on line 23 to a user registered with Email Signin to your project.

--------------------
Please help me with this error. Since Firebase doesn't host old versions of the plugins (and I don't commit plugins to version control) I'm unable to downgrade and undo the change. 

- CJ

**Comment by chkuang-g** [comment]
@cjcurrie 

Sorry to get you back this late.  

About your note 1, yes, that should be normal because Firebase and Play Game Plugin includes different version of EDM4U.  Version Handler was basically trying to remove the older version of EDM4U.

Also, you should be able to get Firebase version back to `6.13.0` here. But make sure that you are using `.Net 4.x`.

https://developers.google.com/unity/archive#firebase

- Are you experiencing this issue on desktop (Windows/macOS/Linux) or mobile (iOS/Android) device?
- Are you still experiencing the same issue with later version of Firebase SDK?
