### ISSUE TITLE
[CRASHLYTICS] Android native crashes only have "???" in the title

### ISSUE THREAD

**Issue by jamier-hh** [firebase/firebase-unity-sdk#190]
I'm seeing a strange issue where native Android crashes show up in Crashlytics with "???" as the title instead of something more useful. I'm not sure if this is expected behaviour but it doesn't feel like it.

Setup:
Unity Version: 2019.4.26f1
Firebase Version: 8.8.0

STR:
* Setup up the [quickstart-unity](https://github.com/firebase/quickstart-unity) project for Crashlytics.
* Build for Android
* Trigger a native crash* and re-open the app.
* (Optional) Upload the symbol files
* Go to the Crashlytics dashboard and see the crash
** It should have a title "???"

* I used this method to trigger a native crash however it also appears in our production environment for native other native crashes:
```
    public void ThrowNativeCrash()
    {
      // https://stackoverflow.com/questions/17511070/android-force-crash-with-uncaught-exception-in-thread
      var message = new AndroidJavaObject("java.lang.String", "This is a test crash, ignore.");
      var exception = new AndroidJavaObject("java.lang.Exception", message);
	       
      var looperClass = new AndroidJavaClass("android.os.Looper");
      var mainLooper = looperClass.CallStatic<AndroidJavaObject>("getMainLooper");
      var mainThread = mainLooper.Call<AndroidJavaObject>("getThread");
      var exceptionHandler = mainThread.Call<AndroidJavaObject>("getUncaughtExceptionHandler");
      exceptionHandler.Call("uncaughtException", mainThread, exception);
    }
```

**Comment by jamier-hh** [comment]
Also, I followed the steps [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity) to upload the symbols to Crashlytics and it seemed to make no difference.

**Comment by gclaret** [comment]
Would love to hear an update about this. Having something similar happening to me

**Comment by CriticalForce** [comment]
Having similar issue where a group of different crashes are grouped.

Unity: 2020.3.33f1
Firebase: 8.9.0

**Comment by samedson** [comment]
Hey folks, this can happen if no symbols are uploaded for that crash. Are you getting readable stacktraces for other native crashes in your app?
