### ISSUE TITLE
Analytics: missing iOS events

### ISSUE THREAD

**Issue by VolodymyrBS** [firebase/firebase-unity-sdk#205]
Firebase version: 8.7.0, 8.8.0;
Unity version: 2019.4.16f1 and 2020.3.24f1
XCode version: 13.2
Device: iPhone XR
iOS version: 15.1

Hi! I have a problem with Firebase Analytics. I see no events except a few buildin.
tried to configure testapp from here https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp but it still logs no events.

this is debug view that I see after clicking all buttons in the tests app and vaiting for some time
![image](https://user-images.githubusercontent.com/20375870/158871291-2c16713c-3a37-4bab-a70b-77fb53db2161.png)

**Comment by chkuang-g** [comment]
@VolodymyrBS 

Odd, I was able to see all the events from the quickstart with no issue. I built the quickstart with Firebase `9.6.0` in Unity `2019.4.36f1`

Did you add `-FIRDebugEnabled` to command line in your Xcode project?

https://firebase.google.com/docs/analytics/debugview#ios+

Could you show us the code snipper about how you logged the event?

Shawn
