### ISSUE TITLE
Apple Silicon not supported

### ISSUE THREAD

**Issue by alex-blastproofgames** [firebase/firebase-unity-sdk#233]
Could you guys also release new versions with Apple Silicon in mind?

A lot of us work on macs and new releases are unusable.

**Comment by waleed347** [comment]
+1 
We're also getting "DllNotFoundException: FirebaseCppApp-8_2_0...." on unity 2020.3.0f1 LTS which has silicon native support on m1 devices. 
We have also tried latest firebase for unity 8.9, it didn't work either

**Comment by steffen-roemer** [comment]
still not working with 8.10.0 for me

**Comment by cynthiajoan** [comment]
We have a feature requested issue addressing this https://github.com/firebase/firebase-unity-sdk/issues/278

**Comment by happypepper** [comment]
Hello @cynthiajoan I don't think feature request is accurate for this as Unity 2021.3.1 apple silicon is already LTS version. Bug is more accurate in my opinion

**Comment by chorobochrontochor** [comment]
+1

**Comment by nodrock** [comment]
+1

**Comment by waleed347** [comment]
Any update on this?

**Comment by a-maurice** [comment]
Hi all,

We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, which adds support for Apple Silicon chips.
