### ISSUE TITLE
Firebase Unity SDK download size is 2.04 GB!!!

### ISSUE THREAD

**Issue by KAMIKAZEUA** [firebase/firebase-unity-sdk#258]
<img width="871" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/3391456/165294674-d7125b9e-6fe9-4f72-8edf-76c17824ff95.png">

https://firebase.google.com/download/unity 

<img width="222" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/3391456/165295238-6b637b57-7267-4b7d-bb79-a0ff7a8fafe7.png">

Inside this ZIP file there are useless files for **dotnet3**: 

<img width="619" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/165297263-57c5938e-4244-4b4b-8594-d4328ad5f5fb.png">

We are using **dotnet4** for sure, so why I downloaded 1Gb of wasted files? Why just not to split this before into different ZIP files for dotnet 3 and 4? 
So, I'll use dotnet4, but again it folder contains a bunch of plugins which are not needed for all our projects.

**We only need these files:** 

<img width="721" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/3391456/165297657-b778c7d0-4db9-438e-ac9d-fe357e53c8fb.png">

So, each time when I want to update FireBase SDK: 
 -  I download **2GB** zip file
 - remove unused **dotnet3** folder: **~1Gb**
 - remove unused plugins .unitypackage files in **dotnet4** folder: **~845,8 MB** 
 - use only 2 files, which are in total: **177,8 MB**

How about just to provide link to each **.unitypackage** ? So I'd just clicked only on files I really needed and quickly downloaded them?

**Comment by AtomicTroop** [comment]
There's a separate package archive with each of these packaged separately, found here:
[https://developers.google.com/unity/packages](https://developers.google.com/unity/packages)

It's a shame the instructions don't really direct the user to the archive page.

**Comment by cynthiajoan** [comment]
Thanks @AtomicTroop to point out the separate position. Also the support for dotnet3 will be deprecated in a few months.

**Comment by KAMIKAZEUA** [comment]
@cynthiajoan and why this is closed if https://firebase.google.com/docs/unity/setup?authuser=0 documentation still points to 1 big file? Even if dotnet3 will be removed, that file still will be **1GB**.

Documentation should point to list of link, so I can pick only any I need.
