### ISSUE TITLE
[Bug]  Unity.IL2CPP.HashCodeCollisionException

### ISSUE THREAD

**Issue by AminSojoudi** [firebase/firebase-unity-sdk#280]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.30_____
  * Firebase Unity SDK version: 8.10.1_____
  * Source you installed the SDK: .unitypackage_____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _Analytics or Messgeing____ (Auth, Database, etc.)
  * Other Firebase Components in use: _Analytics or Messgeing____ (Auth, Database, etc.)
  * Additional SDKs you are using: _GameAnalytics____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _Windows____ (Mac, Windows, or Linux)
  * Platform you are targeting: _Android____ (iOS, Android, and/or desktop)
  * Scripting Runtime: __IL2Cpp___ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: ___pre-build SDK__

### [REQUIRED] Please describe the issue here:

I have upgraded my firebase sdk from 8.8.0. tried to build the project and saw this error:
then reverted the firebase sdk upgrade and then the project started to building again.

`Unity.IL2CPP.HashCodeCollisionException: Hash code collision on value `019A3EBF54AA28D1614816EC1DF11DE3AC773E99` Existing Item was : `System.Object Google.MiniJSON.Json::Deserialize(System.String)` Colliding Item was : `System.Object Google.MiniJSON.Json::Deserialize(System.String)`

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
#### Steps to reproduce:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by chkuang-g** [comment]
This may be related to the missing namespace issue.  
https://github.com/firebase/firebase-unity-sdk/commit/7054ec3248797d5f46689aac2381b7df4ec1e7d6

This should be patched in `9.1.0`. Could you upgrade and see if this issue is fixed?

Shawn
