### ISSUE TITLE
[Bug][iOS][Unity] Firebase packages make Unity get stuck on import on Mac Mini M1

### ISSUE THREAD

**Issue by lacee666** [firebase/firebase-unity-sdk#288]
### [REQUIRED] Please fill in the following fields:
  * Unity editor version: 2021.3.1f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: tgz tarball (also tried as .unitypackage)
  * Problematic Firebase Component: ExternalDependencyManager
  * Other Firebase Components in use: App,Analyzer,Crashlytics
  * Additional SDKs you are using: _____ 
  * Platform you are using the Unity editor on: Mac (OS Monterey 12.3, Mac Mini M1)
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built
### [REQUIRED] Please describe the issue here:

Hey, I'm trying to build my game to iOS and I have Firebase in my project which is already setup (working on pc, getting logs on crashlytics for android).
On the Mac I'm calling Unity from command line(or from gitlab CI) for building iOS that calls my Build method, but somewhere along switching platform to iOS and importing the assets, the whole process is just hanging and remains there forever. After trying to remove packages one by one and building it again I noticed the issue disappeared whenever I removed Firebase. At first I had Firebase 8.8.0, so I upgraded it to latest 8.10.1, and after that I had some relevant logs in the build process where it got stuck (before that, it got stuck in random places). Now it always gets stuck around [API Updater] and around any Firebase dll. Some log examples:

.tgz version at Firebase.Platform.dll
```
Filename: /Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/MonoBleedingEdge/bin/mono
Arguments: "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Tools/ScriptUpdater/AssemblyUpdater.exe" update -a "/Users/mymac01/builds/c1qxczap/0/mygame/puzzle/Puzzle/Library/PackageCache/com.google.firebase.app@5180d3a6613a/Firebase/Plugins/Firebase.Platform.dll" --output "/var/folders/v4/lbj0ckgd15d0q1dlyf7jyd0m0000gn/T/tmpb007b83.tmp" --api-version 2021.3.1f1  -s "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed:+/Users/mymac01/builds/c1qxczap/0/mygame/puzzle/Puzzle/Assets:+/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed" "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed/UnityEngine.dll"
```
.unitypackage version at Google.JarResolver.dll
```
Filename: /Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/MonoBleedingEdge/bin/mono
Arguments: "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Tools/ScriptUpdater/AssemblyUpdater.exe" update -a "Assets/ExternalDependencyManager/Editor/1.2.170/Google.JarResolver.dll" --output "/var/folders/v4/lbj0ckgd15d0q1dlyf7jyd0m0000gn/T/tmp5343f755.tmp" --api-version 2021.3.1f1  -s "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed:+/Users/mymac01/builds/c1qxczap/0/mygame/puzzle/Puzzle/Assets:+/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed" "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed/UnityEngine.dll" "/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/Managed/UnityEditor.dll"
```

This happens around 80% of the time, and whenever it works it usually takes a few seconds to go through this part, other times it's just stuck here. Up until this point even the CPU is working hard, then the Unity process just drops to around 0% and stays there forever. There are no popups, no errors, it even happens in batchmode.
I have Firebase added as tarball from .tgz, also tried importing as .unitypackage but it didn't help. Tried versions from 2020.3.32 LTS up to 2021.3.2 LTS, also tried some solutions from #278 as I saw I have the exact macOS version as in that issue, but nothing seemed to work, even restarting the mac didn't.
Windows and android is working fine, even when iOS is built on that 20% of the times, crashlytics reports crashes correctly.

Since I'm getting no errors, and it doesn't always happen, it's really mysterious and I'm not sure how to go forward with this, so I thought I'd start asking here.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
- Tried with a fresh unity project importing only Firebase as tarball from tgz and the issue still happened. But even if I setup something incorrectly, it's still so weird that I get no errors, it's just stuck. As it's working on every other platform except on Mac, I might be thinking it's M1 related issue since I see other threads about it.

What's the issue repro rate? 
- 80%, usually it's not working for a long time, then it works for a little, then again it happens.

What happened? How can we make the problem occur?
- Trying a sample project on M1 Mac Mini, OS Monterey 12.3? It seems like only I have encountered this exact issue :(

**Comment by DellaBitta** [comment]
Hi @lacee666,

We officially added M1 support with Firebase Unity SDK release 9.0.0, though that affects the target more than the host.    Could you try upgrading the Firebase SDK to see if that behaves similarly.

Is there any way you can attach a debugger to the process to see where it hangs or to get more logs?

Does the build work if you launch it from inside the editor on the mac?

Thanks!

**Comment by ikoryakin** [comment]
I'm having exact same issue with Firebase updated to version 9.3.0
