### ISSUE TITLE
[Bug] Crash at startup on devices running iOS 15+

### ISSUE THREAD

**Issue by wspier16** [firebase/firebase-unity-sdk#293]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.33f1
  * Firebase Unity SDK version: 8.9.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: messaging (Auth, Database, etc.)
  * Other Firebase Components in use: crashlytics (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built from site

### [REQUIRED] Please describe the issue here:

For the latest release of my application we upgraded our firebase sdk version to 8.9.0. Since then we are seeing a large percentage of iOS users with crashes on startup. Looking in crashlytics, it appears these users are all using iOS 15 or higher (except for one outlier).   This is a fatal crash that occurs within the first few seconds of startup.  I opened a ticket on google cloud platform and they mentioned it may be an issue between my version of the sdk and the latest iOS version. Would upgrading my sdk version solve the issue?
 Here is a copy of the stack trace:
Crashed: GC Finalizer
0  libsystem_kernel.dylib         0x6bbc __pthread_kill + 8
1  libsystem_pthread.dylib        0xd854 pthread_kill + 208
2  libsystem_c.dylib              0x1f6a4 abort + 124
3  libsystem_malloc.dylib         0x1b9d8 _malloc_put + 546
4  libsystem_malloc.dylib         0x1bb88 malloc_report + 60
5  libsystem_malloc.dylib         0x1cec free + 284
6  UnityFramework                 0x61f8e0 operator delete(void*) + 48
7  UnityFramework                 0x11d0df4 firebase::messaging::Notification::~Notification() + 3820
8  UnityFramework                 0x11d0ed0 firebase::messaging::Message::~Message() + 4040
9  UnityFramework                 0x11d4ec8 Firebase_Messaging_delete_FirebaseMessage + 16
10 UnityFramework                 0x1c08b08 aece0ca012db7ae9f82cc8b3c490870a.cold.2 + 4361702152
11 UnityFramework                 0x1c089f4 aece0ca012db7ae9f82cc8b3c490870a.cold.2 + 4361701876
12 UnityFramework                 0x16d580 RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**) + 4333802880 (Il2CppInvokerTable.cpp:4333802880)
13 UnityFramework                 0x11ae46c il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 116096
14 UnityFramework                 0x1147bcc il2cpp::gc::GarbageCollector::RunFinalizer(void*, void*) + 11560
15 UnityFramework                 0x113d850 GC_invoke_finalizers + 44804
16 UnityFramework                 0x1147b10 il2cpp::gc::FinalizerThread(void*) + 11372
17 UnityFramework                 0x116cf08 il2cpp::os::Thread::RunWrapper(void*) + 8784
18 UnityFramework                 0x116f6b8 il2cpp::os::ThreadImpl::ThreadStartWrapper(void*) + 18944
19 libsystem_pthread.dylib        0x3348 _pthread_start + 116
20 libsystem_pthread.dylib        0x1948 thread_start + 8

#### Steps to reproduce:

- Run application.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

No

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Mentioned above (with strack trace)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by reaver** [comment]
We might be having the same crash, but I don't have any non iOS15 devices at the moment where I can test if it's only 15+.

I haven't been able to get any information from the crash logs past it happening in UnityFramework.

Unity editor version: 2020.3.34f1
Firebase Unity SDK version: 9.0.0
Source you installed the SDK: Unity Package Manager (self hosted)
Problematic Firebase Component: Unknown
Other Firebase Components in use: Crashlytics, Cloud Messaging, Analytics, Remote Config, Dynamic Links
Additional SDKs you are using: Facebook, IronSource with mediation, 
Platform you are using the Unity editor on: Mac
Platform you are targeting: iOS
Scripting Runtime: IL2CPP

**Comment by DellaBitta** [comment]
This has the signs of a memory corruption issue.  Can you detail more about what's occurring before the crash? Could you create a reproducible test case for us to look into?

Thanks!
