### ISSUE TITLE
[Bug] Crashing on iOS 12.5.5

### ISSUE THREAD

**Issue by pf-mkenichi** [firebase/firebase-unity-sdk#294]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.32f1
  * Firebase Unity SDK version: 8.10.0, 8.10.1
  * Source you installed the SDK: FirebaseMessaging.unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Unknown (Auth, Database, etc.)
  * Other Firebase Components in use: not identified (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: iL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here:

Unity2020.3.32f1
Xcode version 13.3 
iPhone6Plus(iOS12.5.5)

With the above configuration, import FirebaseMessaging.unitypackage and run
When using Firebase 8.10 or later version, the app crashes on startup. 
Occurs with just adding firebase to an empty project.

Firebase 8.9.0 No problem
Firebase 8.10.0 Crash
Firebase 8.10.1 crash

Not reproduced on iPhoneX (iOS 15.4)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I haven't tried it.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

xcode log
-----------
2022-05-17 13:00:41.939976+0900 firebase-sample[1231:505132] FCM: Loading UIApplication FIRFCM category
(lldb) 
-----------

xcode screenshot iPhone6Plus(iOS12.5.5)

<img width="1680" alt="xcode-screen-shot" src="https://user-images.githubusercontent.com/29224244/168727162-ebc1261d-6266-4dd7-bd7e-782eec8de24d.png">

**Comment by acgourley** [comment]
We're seeing this too. We didn't QA on this device class before release and now we have justifiable upset users 😞

**Comment by acgourley** [comment]
![Screen Shot 2022-05-17 at 2 34 53 PM](https://user-images.githubusercontent.com/7680/168913956-c04e8b48-b599-48c0-897c-8e591c8e76a6.png)
Here's more of the stack if it's helpful to the devs

**Comment by a-maurice** [comment]
Hi all,

Thanks for flagging this issue.  We will try to get a fix out at soon as possible.  Unfortunately, the only workaround seems to be rolling back to the 8.9.0 release.

**Comment by a-maurice** [comment]
We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, that includes the fix for this.  Thanks again for flagging it.
