### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Archi97** [firebase/firebase-unity-sdk#295]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.15
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: etc.
  * Other Firebase Components in use: etc.
  * Additional SDKs you are using: NatCorder, Facebook, AppleSignIn, GoogleSignIn, Admob, etc.
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android.
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:
Lately I got more crashes on my application. I did some research and found that newer version of the Firebase(mine was 8.0.0) can display crashes in correct format in the dashboard(line of my actual code instead of addresses in memory). 
Now after upgrading the all Firebase plugins, [uploading Debug Symbols](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity&authuser=1&hl=en#android) into Firebase with help of Firebase CLI I can see the reasons of the few crashes. 
**But problem is that there are to much missing Symbols.** 
![image](https://user-images.githubusercontent.com/36793459/168750827-a16f84d2-4652-4291-8362-a6582f3e1e21.png)

Depending on [this video](https://youtu.be/G1PzMgMAdg0?t=580) I guess I should upload the other plugins' Debug symbols as well. But how to do that? I can't find a way to export their Debug Symbol Files. 
I found some *.so files but they are all scattered in the project, few of them having same name as well. 

Please help me to figure out the right way of doing this. 
Thanks ;)

**Comment by samedson** [comment]
This is a good question.

Just to clarify, you've already gone through the steps [under Generating a symbols package](https://docs.unity3d.com/2020.3/Documentation/Manual/android-symbols.html) to create the symbols.zip, and uploaded the symbols in the zip.

The problem you're running into is you have other 3rd party libraries / plugins that have their own symbols, and can't find them.

- I would recommend uploading the *.so files you've found in your project. Are you uploading them and finding they aren't symbolicating correctly?
- In some cases, 3rd party plugin will have symbols stripped (this can only happen if the plugin is pre-compiled). In this case there's no way to get the symbols. You may ask the library owner if symbol stripping is on purpose, and whether they can release the library unstripped.

I have a colleague who has more knowledge on this that is back in on Monday. I will ask them as well to see if they have more information to share on this as well.

**Comment by Archi97** [comment]
Hello @samedson , Nice to e-meet you. I wondered how to find you to ask questions directly to you as you were in the video ;) 
The link you have shared I haven't seen will definitely go through that.  

About 1st point - Yes, I found some .so files which are in the plugins folder. I tried to move all of them into one folder to make one single ZIP file to upload, but most of them have the same name, so I didn't continue.  Question - Can I use the same CLI tool and upload the single *.so file?
About 2nd point - I will check on that as well. Can you let me know how can I know that the plugin is precompiled? Is it about the *.aar files?

Thanks a lot for your help, I appriciate it.

**Comment by samedson** [comment]
Yeah nice to e-meet you too!

Ok so talking to my colleague, it sounds like your dependencies are generally always going to be compiled. In some cases the AAR will have a .so file compiled in it.

You can unzip aars like a normal .zip file (eg. on mac, you'd run `unzip library.aar` and it would spit out a directory

**Comment by Archi97** [comment]
@samedson ok,  I will write some program that will export all *.so files form the project and upload them into Firebase. 
One more question. Uploading new *.zip file means replacing the previously uploaded one, or it is going as addition by replacing only repetitive ones? 
And by uploading just one single *.so file will also added to previously uploaded files?

e.g.  I have Built app version 1 and uploaded *.zip file.  then I'm building app version 2 with small changes only in one script and I'm not uploading new *.zip file. 
Will I still get the correct crash report from unchanged scripts from app version 2?

P.S. I think Firebase team must do more case specific video for this topic, as it is the biggest key of the crash fixing process.
Thanks ;)

**Comment by samedson** [comment]
Hey @Archi97 - apologies for the delay been OOO.

So uploading a new zip will replace the old one, but only if they are the same symbols if that makes sense. If you make 2 builds of your app and upload zips for both, they won't overwrite. We'll accept all new versions of the symbols.

So that's also true with a library. If you have an .so for a library, and you make 2 different builds of your app, but the library .so stays the same, you don't need to re-upload that library's .so.

That's good advice on the video. Symbols are a complicated topic so these are great questions.

**Comment by chkuang-g** [comment]
Thank you for the automation tool.

Seems like this issue is resolved.  I will close this for now.  

If not, please open a new ticket and reference this post, for visibility.

Shawn
