### ISSUE TITLE
Possible to register crashlyticsDidDetectCrashDuringPreviousExecution callback in Unity?

### ISSUE THREAD

**Issue by tzmm** [firebase/firebase-unity-sdk#309]
### Please fill in the following fields:
Unity editor version: 2018.4.12f1
Firebase Unity SDK version: firebase_unity_sdk_6.6.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook 
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows 
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
Is there a way to register the crashlyticsDidDetectCrashDuringPreviousExecution with the Crashlytics instance generated during the normal Crashlytics startup in Unity?  It's clear how to do this if we were to instantiate the Crashlytics object ourself, but not sure if this is possible with the Unity SDK.  (We're doing this manually on iOS by patching the .mm file in a post build step, which works great for us).

**Comment by a-maurice** [comment]
It seems the underlying function has since been removed from the Android and iOS SDKs.  Also, the Unity SDK is now open source (located where this bug is now located).  I'm going to close this issue.
