### ISSUE TITLE
Dynamic Links crashes with il2cpp on Android due to Proguard stripping

### ISSUE THREAD

**Issue by rahuloftheramaneffect** [firebase/firebase-unity-sdk#311]
**Platforms and SDKs**

Unity editor version: 2019.1.11 f1
Firebase Unity SDK version: 6.2.0
Firebase plugins in use (Auth, Database, etc.): Auth, DynamicLinks
Additional SDKs you are using (Facebook, AdMob, etc.): GoogleSignIn ([Github link](https://github.com/googlesamples/google-signin-unity)) Facebook, AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
________________________

**Context**:
I'm using Firebase Dynamic Links Unity SDK to create dynamic referral links in my game. The script I wrote generates a long dynamic link from a DynamicLinkComponents instance.
________________________

**Code**:
```

DynamicLinkComponents dynamicLink = new DynamicLinkComponents(
                new Uri("https://flareupdigital.com/?invitedby=" + referralID),
                "https://flareupdigital.page.link"
);

Debug.Log(dynamicLink.LongDynamicLink); // Works fine with "Mono", Throws exception with "il2cpp"
```
________________________

**Issue**:
When compiled with "il2cpp" scripting backend, dynamic link generation fails in device with the following error:

ApplicationException: internal::IsInitialized() at Firebase.DynamicLinks.FirebaseDynamicLinks.GetLongLinkInternal(Firebase.DynamicLinks.DynamicLinkComponentsInternal components)

(Full stack here - [log.txt](https://github.com/firebase/quickstart-unity/files/3416270/log.txt))
________________________

**Important Notes**:
The script WORKS FINE in our devices (Google Pixel 2 XL, OnePlus 7, etc.) if compiled with the "Mono" scripting backend in Unity.
________________________

**Additional References**:
This issue has been discussed before, but there was no solution posted or the solution does not work:

1) [Unable to generate Firebase dynamic link](https://github.com/firebase/quickstart-unity/issues/328)
- _Suggested "Force Resolve" in the PlayServiceResolver, but that did not work for me_

2) [Firebase Dynamic Links Fail To Generate On Real Device](https://github.com/firebase/quickstart-unity/issues/308)

- _No solution posted_

**Comment by chkuang-g** [comment]
Is this still happening to you guys with the latest SDK, ex. `9.2.0`?

I think we might be able to do something for this in the editor tool.  That is, adding proguard lines automatically.

I will change this to a FR since we never support this functionality before.

**Comment by paulinon** [comment]
Hey folks,

Please note that the Firebase Dynamic Links service will be shutdown on August 25, 2025. For now, only critical or security issues will be fixed in the SDK.

You may refer to https://firebase.google.com/support/dynamic-links-faq for more information.
