### ISSUE TITLE
[Bug] Android - Crash when click on notification while app is suspended.

### ISSUE THREAD

**Issue by npicouet** [firebase/firebase-unity-sdk#316]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.5f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: TGZ Local Package Manager
  * Problematic Firebase Component: Notification
  * Other Firebase Components in use: Using all firebase components
  * Additional SDKs you are using: Facebook, Apple Sign In, Google Sign In, Unity IAP
  * Platform you are using the Unity editor on: Mac M1
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Prebuilt TGZ

### [REQUIRED] Please describe the issue here:

On Android, clicking on notifications in the tray while the app is suspended crashes the app. Expected behavior is that the app resumes and triggers the payload action. If the app is killed completely, the notification works as intended and triggers the payload correctly. I have not tested iOS.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Did not try.
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by paulinon** [comment]
Hi @npicouet,

Thanks for reporting this. In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to replicate the issue?

**Comment by npicouet** [comment]
Hey there! It looks like this issue has come up before, looking at the issues history. It has to do with a permission not being added correctly. I'm not sure why its needed now, it wasn't needed in previous firebase versions.

Here is the error message I got from logcat:
`
05-31 10:45:40.835 29216 29216 E AndroidRuntime: FATAL EXCEPTION: main
05-31 10:45:40.835 29216 29216 E AndroidRuntime: Process: com.curiousmedia.doodleparty, PID: 29216
05-31 10:45:40.835 29216 29216 E AndroidRuntime: java.lang.IllegalArgumentException: Scheduled service ComponentInfo{com.curiousmedia.doodleparty/com.google.firebase.messaging.MessageForwardingService} does not require android.permission.BIND_JOB_SERVICE permission
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2429)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2334)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:348)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:56)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at androidx.core.app.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:343)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:523)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:501)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.google.firebase.messaging.MessageForwardingService.enqueueWork(MessageForwardingService.java:37)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.google.firebase.MessagingUnityPlayerActivity.onNewIntent(MessagingUnityPlayerActivity.java:75)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.Activity.performNewIntent(Activity.java:8070)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1441)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1454)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3904)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3911)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2709)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enqueue(JobSchedulerService.java:2794)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:177)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1143)
05-31 10:45:40.835 29216 29216 E AndroidRuntime: 
`

**Comment by npicouet** [comment]
The fix was in this other issue thread from last year.
https://github.com/firebase/quickstart-unity/issues/1070

**Comment by paulinon** [comment]
Glad to hear that you've fixed the issue, @npicouet. That being said, I'll be closing this for now. Let me know if an issue arises.
