### ISSUE TITLE
[Bug] App is crashing when launched

### ISSUE THREAD

**Issue by FazalConsoliads** [firebase/firebase-unity-sdk#322]
* Unity editor version: _2020.3.22f1____
  * Firebase Unity SDK version: _9.0.0____
  * Source you installed the SDK: ___.unitypackage__ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: ___Storage__ (Auth, Database, etc.)
  * Other Firebase Components in use: __Auth, Database___ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __Mac___ (Mac, Windows, or Linux)
  * Platform you are targeting: __iOS___ (iOS, Android, and/or desktop)
  * Scripting Runtime: __IL2CPP___ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

Application is working fine when debugging (running ) using Xcode. but when launch from device without xcode attached. app is keep on crashing. I managed to get the error from console application.

Error loading /var/containers/Bundle/Application/82904F4D-D348-4C96-8757-4813BDDDCCAA/CrashCheck.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/82904F4D-D348-4C96-8757-4813BDDDCCAA/CrashCheck.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): code signature in (/private/var/containers/Bundle/Application/82904F4D-D348-4C96-8757-4813BDDDCCAA/CrashCheck.app/Frameworks/UnityFramework.framework/Frameworks/libswift_Concurrency.dylib) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Create New Project Unity Editor version 2020.3.22f1
Download firebase_unity_sdk_9.0.0
Add FirebaseAuth.unitypackage from dotnet4 folder
Add FirebaseStorage.unitypackage from dotnet4 folder
Now build for iOS, run iOS project from xcode.
Now run from the mobile device directly, app keeps crashing.

**Comment by paulinon** [comment]
Hi @FazalConsoliads,

Could you confirm if the issue persists when the app is built using an updated version of the Unity editor (Unity 2020.3.35f1 is the latest LTS version)? If so, please provide the Xcode version you're using as well as the details pertaining to the device you've tested (such as its iOS version or if it's a simulator).
