### ISSUE TITLE
[Bug] Crashlytics cannot receive the log with 9.0.0, switch back 8.x, works

### ISSUE THREAD

**Issue by xinatcg** [firebase/firebase-unity-sdk#323]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.16f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Analytic (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android and iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: [_____](https://developers.google.com/unity/archive)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Crashlytics cannot receive the log with 9.0.0, switch back 8.x, works

The Analytic works and it also show crash, but when click the crash to Crashlytics, still shows waiting for data

<img width="516" alt="image" src="https://user-images.githubusercontent.com/55399567/171416365-e95e922a-dc70-47c8-b774-118c9f705adc.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/55399567/171416543-0b4917ae-5d8c-4f57-b38e-22ecb89f06cf.png">

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @xinatcg,

Thanks for reporting this. In order to identify what's causing this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps taken to reproduce the issue?
