### ISSUE TITLE
[Bug] Unity 2021.3.1f1 "Internal build system error. Backend exited with code 2"

### ISSUE THREAD

**Issue by RafaelGomes00** [firebase/firebase-unity-sdk#326]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.1f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: com.google.firebase.app (Auth, Database, etc.)
  * Other Firebase Components in use: Messaging, Crashlytics, Analytics
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

After I updated the firebase SDK from version 8.9.0 to 9.0.0, I started getting the following error messages: "Internal build system error. Backend exited with code 2." or "Backend produced unparsable log entry" and then the unity compiler crashes, and i can't edit do play mode or build.

#### Steps to reproduce:

- Create a empty project
- Install Firebase SDK version 9.0.0
- Recompile the unity folder (Create a script for example)
- Problem reproduced
- Not sure the exact repro rate

**Comment by RafaelGomes00** [comment]
Hi, I downloaded the editor version you specified, and at first sight the problem didn't occurred, I'm trying to install Android and iOS build supports to see if there is any correlations

**Comment by paulinon** [comment]
Hi @RafaelGomes00,

[Version 9.1.0](https://firebase.google.com/support/release-notes/unity#version_910_-_june_10_2022) of the SDK has been released. Could you try it out and see if the issue persists?

**Comment by RafaelGomes00** [comment]
Hi, I will not be able to continue this thread, because I switched computers with another team worker, and on the new computer the error doesn't appear.

I tried installing Version 9.1.0, but the error persisted.

**Comment by paulinon** [comment]
Thanks for the update, @RafaelGomes00. I'll be closing this for now since you wouldn't be continuing this thread. In case you encounter the issue again, you may reopen this ticket or you can create a new ticket with updated information.

**Comment by streamDragon** [comment]
Internal build system error. Backend exited with code -1073741819.

i got it after switching from 2021 to 2022
