### ISSUE TITLE
[Bug] iOS Build failed 9.0.0 with libFirebaseCppApp.a does not contain bitcode

### ISSUE THREAD

**Issue by Str4tos** [firebase/firebase-unity-sdk#336]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.36f
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: App
  * Other Firebase Components in use: Analytics, Dynamic Links
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

`Plugins/i0S/Firebase/libFirebaseCppApp.a(idl_parser.cpp.o)` does not contain bitcode.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? - Yes
What's the issue repro rate? (eg 100%, 1/5 etc) - 100%

1. Enable `ENABLE_BITCODE`.
2. Archive application to release in AppStore.3. 
3. An build error occurs:
```
ld: '/Users/mishadenver/UnityBuilds/i0S/bike_Rc1/Libraries/com.psv.firebase. base/Plugins/i0S/Firebase/
libFirebaseCppApp.a(idl_parser.cpp.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode
setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/
Users/mishadenver/UnityBuilds/i0S/bike_Rc1/Libraries/com.psv.firebase. base/Plugins/i0S/Firebase/
libFirebaseCppApp.a' for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

#### Relevant Code:

I don't have any code.

**Comment by a-maurice** [comment]
Thanks for flagging this, we will investigate it.

**Comment by Str4tos** [comment]
Thank you! 
Perhaps there is a quick solution for us, such as replacing the dll?
Or just wait for a new version of the plugin? 
Is there a deadline for the release of the new version?

**Comment by a-maurice** [comment]
We are working on getting a release out with the fix, alongside some other fixes.  While I can't say an exact release time, it should be within a week.

**Comment by a-maurice** [comment]
The Firebase for Unity SDK v9.1.0 is out, which should have the bitcode enabled correctly in the library.  It can be downloaded from here https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.1.0

Thanks again for flagging this issue.
