### ISSUE TITLE
[Bug] 9.0.0 build unable to upload to testflight with 'bundle contains disallowed file 'Frameworks' ' error.

### ISSUE THREAD

**Issue by RoboticAccolade** [firebase/firebase-unity-sdk#349]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: either Analytics, Crashlytics, or Messaging (Auth, Database, etc.)
  * Other Firebase Components in use: as above, Analytics, Crashlytics, and Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: AdMob, Facebook login (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (as well as android but this concerns iOS) (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP I believe (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built SDK from the link in Releases

### [REQUIRED] Please describe the issue here:

Upon upgrading from 8.10.1 to 9.0.0, built Archive file is refused by TestFlight with the error 'bundle contains disallowed file 'Frameworks' '.  Presumably this is Swift related.

#### Steps to reproduce:

Recently we updated our project to include 8.10.1, which we eventually got working correctly.  For the most part.  Unfortunately, users running iOS 12 and previous were unable to launch our game post-patch.  Apparently there was a bug in 8.10.1 for this that 9.0.0 addressed.

On updating to 9.0.0, however, our build began to crash on ALL devices with a termination description: DYLD, Library not loaded: @rpath/libswiftCore.dylib

Nothing else in our build had changed so naturally I was a bit confused at how to proceed from here. 

I realized I hadn't updated the Resolver alongside the Firebase modules, so I reinstalled all three (the only change being the Resolver proper since they had successfully installed previously), bringing the Resolver version from 1.2.170 to 1.2.171.  I noticed in the settings that the Enable Swift Framework Support Workaround had changed to (Recommended) and been automatically checked in 1.2.171 (in 1.2.170 and our previous builds, it was unchecked and builds functioned fine without them).  So I made some quick change and restore alterations to settings to ensure the new settings were saved (Swift Workaround enabled, Framework Version set to 5.0).

I built an Archive as normal, but this time the archive would not upload to TestFlight, with the error mentioned above.

Some light googling indicated that this was a swift related error, but I'm unsure how to resolve it.  The xcode project itself has Always Embed Swift set to 'No', and I highly suspect that disabling the Workaround in the Resolver would only lead to a non-functional build as before.  It's possible something in our project is contributing to this issue but I tested rolling back to 8.10.1 and building again and had no trouble, so there has to be something in 9.0.0 that is triggering this issue.

#### Relevant Code:

no code, but here's the error box:
<img width="521" alt="スクリーンショット 2022-06-10 16 01 00" src="https://user-images.githubusercontent.com/76253638/173010940-e9fb1649-a104-4697-8b82-fca8ff97d0cd.png">

**Comment by calinpavel787** [comment]
Hi, I have the same issue. @RoboticAccolade, do you have any workarounds until we receive something official from Firebase?

**Comment by RoboticAccolade** [comment]
We're currently internally testing a build that uses Firebase 8.9.0, as this version was the one recommended to avoid the iOS 12 issue prior to the release of v9.0.0.  I got the pre-build version of the libraries by going to the releases page and replacing the _8.10.0.zip with _8.9.0.zip as the extension.

It's still too early to say whether this workaround will be successful for us and it may not be an option if there's an issue with 8.9.0 that makes its usage non-viable for you, but it's what we're currently pursuing.

**Comment by calinpavel787** [comment]
> We're currently internally testing a build that uses Firebase 8.9.0, as this version was the one recommended to avoid the iOS 12 issue prior to the release of v9.0.0.  I got the pre-build version of the libraries by going to the releases page and replacing the _8.10.0.zip with _8.9.0.zip as the extension.
> 
> 
> 
> It's still too early to say whether this workaround will be successful for us and it may not be an option if there's an issue with 8.9.0 that makes its usage non-viable for you, but it's what we're currently pursuing.

Have you tried the latest update (9.1.0)?

**Comment by a-maurice** [comment]
Hi all,

Thanks for flagging this, we are looking into it.  As of version 9.0.0, our underlying dependencies started requiring swift, and it seems like enabling it has caused this submission problem, while not causing an issue during development.  There is a potential fix detailed in the Unity forum, https://forum.unity.com/threads/an-empty-folder-named-frameworks-in-unityframework-framework.751559/#post-6959384, though we are still checking to see if changing those settings will fix this without causing other problems.

**Comment by calinpavel787** [comment]
> Hi all,
> 
> Thanks for flagging this, we are looking into it. As of version 9.0.0, our underlying dependencies started requiring swift, and it seems like enabling it has caused this submission problem, while not causing an issue during development. There is a potential fix detailed in the Unity forum, https://forum.unity.com/threads/an-empty-folder-named-frameworks-in-unityframework-framework.751559/#post-6959384, though we are still checking to see if changing those settings will fix this without causing other problems.

I can confirm that is working. Thank you very much @a-maurice

**Comment by a-maurice** [comment]
Both a new version of EDM4U and a new version of the Firebase SDK to point to it have been released.  Thanks again for bringing this issue to our attention.
