### ISSUE TITLE
The value of Firebase.Database.ServerValue.Timestamp is different from actual value in database.

### ISSUE THREAD

**Issue by unace** [firebase/firebase-unity-sdk#360]
### Please fill in the following fields:
Unity editor version: 2019.3.0f6
Firebase Unity SDK version: 6.9.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): Nothing.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
The value of Firebase.Database.ServerValue.Timestamp is different from actual value in the database.
I can read the actual value if I reconnect. Is there any way to get the actual value without reconnection?

```
var database = Firebase.Database.FirebaseDatabase.DefaultInstance;
await database.GetReference("serverTime").SetValueAsync(Firebase.Database.ServerValue.Timestamp);
var serverTimeSnapshot = await database.GetReference("serverTime").GetValueAsync();
Debug.Log(serverTimeSnapshot.ToString());
```

log
`DataSnapshot { key = serverTime, value = 1580863620000 }`

actual value in database
![image](https://user-images.githubusercontent.com/7022750/73800943-3f2b5300-476e-11ea-8465-49f49d6888b3.png)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? I haven't tried.

What's the issue repro rate? (eg 100%, 1/5 etc) 
100%

**Comment by argzdev** [comment]
Just bumping this thread. It looks like this issue can be resolved by using our [Clock skew](https://firebase.google.com/docs/database/web/offline-capabilities#clock-skew) functionality. You can add the offset needed in your local time. You may also refer to this conversation [thread](https://github.com/FirebaseExtended/firechat/issues/1#issuecomment-22778431). And for what it's worth, I don't think there's any way for the an app to get the actual server value without reconnection. I'll go ahead and close this thread.
