### ISSUE TITLE
The same received event of Dynamic Links is called every time after maximizing app

### ISSUE THREAD

**Issue by sebastian-dudzic** [firebase/firebase-unity-sdk#364]
Unity editor version: 2018.4.5f1
Firebase Unity SDK version: 6.6.0, 6.9.0, 6.10.0 (all not working)
Firebase plugins in use (Auth, Database, etc.): Analytics, RemoteConfig, Crashlytics, DynamicLinks
Additional SDKs you are using (Facebook, AdMob, etc.): Admob mediation, Facebook provider for Admob, Facebook SDK, Appsflyer, Android Native Pro, 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono and IL2CPP
Dot.net: 4.x
Devices: Xiaomi Mi 8, Google Pixel 4, Samsung S7, Samsung Note 4
Android version: from 6.0 to 10.0 (older not tested)

It's exactly the same bug as in https://github.com/firebase/quickstart-unity/issues/502

Steps to reproduce:
1. Open App or do nothing
2. Click dynamic link
3. App is opened, link is correctly received
4. Minimize app
5. Maximize (but select app from background apps previews list, don't click on app icon, then it's working)
6. Previously clicked link is received again (though nothing was clicked)

I have also tried clicking multiple times in different dynamic links in on app run. Behaviour is always the same. After maximize it fires only LAST clicked link. Not all. But expected behavior is to do nothing then.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes. Mono, Unity 2018.4.5f1, Firebase 6.10.0.

What's the issue repro rate? 
100%

There is a video with bug using quickstarts project: https://drive.google.com/file/d/1BJF_fx9gGeEZNZMJM1c440NmBi4HP-pf/view?usp=sharing

**Comment by marcinwalus** [comment]
Hello.
I used a solution suggested by @JohannCaron to clear "extra" and it was working correctly. 
But this solution no longer works - after opening my app with link, I'm displaying form to the user and after closing keyboard "OnDynamicLinkReceived" is fired again.

I was trying to use this code to check if "extras" exist but both values are false.

```
var hasExtraDYNAMIC_LINK_DATA = intent.Call<bool>("hasExtra", "com.google.firebase.dynamiclinks.DYNAMIC_LINK_DATA");
var hasExtraREFERRAL_BUNDLE = intent.Call<bool>("hasExtra", "com.google.android.gms.appinvite.REFERRAL_BUNDLE");
```

I suspect that those extras names changed but have no idea how to list those extras.

 My setup:
- Firebase 9.4.0
- Unity 2021.3
- Android 12.0
- Samsung A53

**Comment by mgrogin** [comment]
Any update on this?

**Comment by JF47** [comment]
@paulinon How in the world is this still an active problem with no official solution!?!? This is insane, and needs to be fixed.

**Comment by Jake-NSW** [comment]
Oh well... they have deprecated Dynamic Links it looks like... 

https://firebase.google.com/support/dynamic-links-faq

 I don't think the issue will be getting fixed. 😢

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
