### ISSUE TITLE
Internal task faulted

### ISSUE THREAD

**Issue by querywilly** [firebase/firebase-unity-sdk#372]
### Please fill in the following fields:
Unity editor version: Unity 2017 4.36 
Firebase Unity SDK version: 6.10.0 framework 3.5
Firebase plugins in use (Auth, Database, etc.):Real time database
Additional SDKs you are using (Facebook, AdMob, etc.): facebook admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): MacOs
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):Mono

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
DatabaseReference leaderBoardRef = mDatabaseRef.Child("userlist/"+auth.userid+"/coin");

```
leaderBoardRef.RunTransaction(mutableData => {
			if(mutableData.Value!=null){
				long A=long.Parse(mutableData.Value.ToString());
				mutableData.Value=(A+newvalue);
			}
			return TransactionResult.Success(mutableData);

                               }).ContinueWith(task =>
			{
				if (task.IsFaulted)
				{
                                   print(task.Exception.Message);   
                   AggregateException ex = task.Exception as AggregateException;
			if (ex != null) {

			DatabaseException inner = ex.InnerExceptions[0] as DatabaseException;
                            print(inner.Message.ToString());
                                  }

```

all error message
"Exception of type 'System.AggregateException' was thrown."
"Internal task faulted"

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
i tested latest version firebase realtime database.
What's the issue repro rate? (eg 100%, 1/5 etc)
%10 rate
It's not happening everytime

**Comment by chkuang-g** [comment]
Hi all,

This has been awhile.  The problem on Android may be fixed in the later version. 

If this is still happening, please open a new issue and reference this one.
