### ISSUE TITLE
DynamicLinksComponents missing NavigationInfoParameters

### ISSUE THREAD

**Issue by simsis3d** [firebase/firebase-unity-sdk#373]
### Please fill in the following fields:
Unity editor version: **2018.4.12f1**
Firebase Unity SDK version: **6.8.1**
Firebase plugins in use (Auth, Database, etc.): **Dynamic Links and Analytics**
Additional SDKs you are using (Facebook, AdMob, etc.): **Facebook and Admob**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows**
Platform you are targeting (iOS, Android, and/or desktop): **Android and IOS**
Scripting Runtime (Mono, and/or IL2CPP): **IL2CPP**

Hey to all,
I have a few questions regarding Dynamic Links:
1. i had android and ios apps on firebase with package name/bundle Id "com.SimgeSimulation.CanliKelimeOyunu", Then i deleted these apps and added new ones with package name/bundleId "com.SimgeSimulation.WordGame". i deleted old json/plist files and impoted new ones, and updated all the codes with new bundle ids, etc. But when i create a new dynamic links with updated infos, and debug it (You can see here https://stockwordgame.com/invite/invite?d=1) it shows an error that "Android app 'com.SimgeSimulation.CanliKelimeOyunu' lacks SHA256. AppLinks is not enabled for the app." Why still shows old bundle id? Even new bundled id has SHA256
2. https://firebase.google.com/docs/dynamic-links/create-manually  this link says there is a paremeter(efr in Navigation parameters) about app preview page, but i couldnt find it in Firebase Unity SDK! There are Android parameters, IOS parameters, etc. but not Navigation parameters.

I am about to publish my game but still mess around Dynamic Link integration. Please help me.

**Comment by paulinon** [comment]
Hi @simsis3d,

Please note that the Firebase Dynamic Links service will be shutdown on August 25, 2025. For now, only critical or security issues will be fixed in the SDK.

You may refer to https://firebase.google.com/support/dynamic-links-faq for more information.
