### ISSUE TITLE
[Bug] Crashlytics - Every version 8.10.0 or newer breaks when using IL2CPP (iOS AND Android)

### ISSUE THREAD

**Issue by nitzanwilnai** [firebase/firebase-unity-sdk#383]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1 (but doesn't seem to matter. Also tested 2020.3.36f1, 2021.3.5f1, etc..)
  * Firebase Unity SDK version: 8.10.0 and newer
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS and Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:
CRASHLYTICS DOES NOT WORK WHEN USING IL2CPP

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
New Unity project
Add crashlytics
Follow the crashlytics quick start and add the exception-every-60-sec script.
Test on iOS or Android
NOTE - Make sure you switch Android to IL2CPP (Mono works)

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Exception not reported

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

NOTE - The issue does not exist in 8.9.0 or 8.7.0

**Comment by paulinon** [comment]
Hi @nitzanwilnai,

I noticed that you filed [this ticket](https://github.com/firebase/quickstart-unity/issues/1290) as well in the quickstart repo. I'll be closing this so that all our discussions can just be in that thread.
