### ISSUE TITLE
[FR] Support Signin with Facebook Gaming Graph login (which is different from regular Facebook login)

### ISSUE THREAD

**Issue by ferretnt** [firebase/firebase-unity-sdk#396]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11
  * Firebase Unity SDK version: 15.2
  * Source you installed the SDK: UPM (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: RTDB (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Editor), il2cpp (Device) (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

We have updated one of our development apps to use the gaming graph. Login to facebook (using Facebook APIs) works correctly, and returns an access token of the form "GG|{tokenString}". Attempting to pass this token to SignInWithCredentialAsync() results in: 

`(Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.`

We can confirm that that token is for the gaming graph API (by logging the Facebook AccessToken's GraphDomain) , however, when we attempt to log in to Firebase using a credential generated from that token, SignInWithCredentialAsync() throws an exception , the inner of which is:

`(Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.`

Interestingly, Credential.IsValid() returns true. 

We are as certain we've got this test right as it's possible to be when most of the opportunities for error are mostly app configuration dashboards rather than the 10 lines of fairly well tested code itself.

Relevant code: 

```
Debug.Log($"Getting credential from access token {AccessToken.CurrentAccessToken.TokenString}");
Firebase.Auth.Credential credential = Firebase.Auth.FacebookAuthProvider.GetCredential(AccessToken.CurrentAccessToken.TokenString);
Debug.Log($"Credential has provider {credential.Provider} : IsValid {credential.IsValid()}" + credential.ToString());
var authTask = auth.SignInWithCredentialAsync(credential);

Debug.Log("Android debugging with printf is fun.");

try
{
    var authUser = await authTask;
    Debug.Log($"Firebase auth sign in task completed. IsCompleted:{authTask.IsCompleted} IsCanceled:{authTask.IsCanceled}. UserID {authUser.UserId} Provider: {authUser.ProviderId}");
}
catch (System.Exception ex)
{
...
```

#### Steps to reproduce:

* Produce a simple app with Firebase and Facebook SDKs. 
* Confirm that sign in with Facebook and Firebase Auth FacebookCredentialProvider works. 
* Switch facebook app in the Facebook developer dashboard to use Gaming Graph API
* [https://www.facebook.com/fbgaminghome/developers/gaming-services/](https://www.facebook.com/fbgaminghome/developers/gaming-services/)
* Confirm that Facebook will still sign in correctly but Firebase SignInWithCredentialAsync logs exception: 

---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---

Repro 100%

**Comment by manelinho** [comment]
I'm still having the exact same issue. Any updates?

**Comment by flaengel** [comment]
Still no updates?

**Comment by manel-graca** [comment]
I ended this non-sense and ditched Firebase. It's a lot of work to implement another backend service but I just can't take this anymore. I'm back using Playfab. I don't even know why I decided to use Firebase in my current project tbh.

**Comment by Awais6** [comment]
The same happens to me!

**Comment by fmoyano** [comment]
Anyone has tried this recently? Is it yet not possible to user Facebook Login for Gaming with Firebase?

**Comment by hdemircioglu** [comment]
It is still not working. I think this feature needs to be prioritized. Nowadays, Facebook login for gaming is an important aspect of the games.

**Comment by Sitiyoh** [comment]
https://github.com/firebase/flutterfire/issues/4524#issuecomment-764610739

This worked for me by recreating Facebook Application with type of Consumer.

I have noticed that Facebook Application built for gaming doesn't have `public_profile` available in their permissions and have `gaming_profile` instead.
I haven't tried it out, but for those of you that doesn't want to recreate Facebook Application, maybe replacing `public_profile` permission requirements to `gaming_profile` may avoid this error.

**Comment by Toupoc** [comment]
@Sitiyoh does this work? Consumer profile doesnt work with the invitable_friends endpoint and connecting players with thier friends is 100% of the reason we're involving facebook. Are you implying that I may be able to change the user permission to gaming_profile  instead of public_profile and that will circumvent the issue?

**Comment by zhihaozhangim** [comment]
Hi everyone, I'm an engineer from Facebook Login for Gaming. We have landed a fix on our end last week and verified Facebook Login for Gaming now can integrate with our Firebase test App. Could you please help us confirm if the issue has also been resolved for your Apps? 

Thank you very much for your patience and help!

**Comment by Whyser** [comment]
> Hi everyone, I'm an engineer from Facebook Login for Gaming. We have landed a fix on our end last week and verified Facebook Login for Gaming now can integrate with our Firebase test App. Could you please help us confirm if the issue has also been resolved for your Apps?
> 
> Thank you very much for your patience and help!

"A fix is expected in coming weeks" - from Facebook dev a year ago. And a year later you fix this issue?

This is such disrespect to developers using Facebook. And to answer your question: because of this issue we never created an app as a gaming app ever again. Once we do, we'll let you know.

**Comment by flaengel** [comment]
> Hi everyone, I'm an engineer from Facebook Login for Gaming. We have landed a fix on our end last week and verified Facebook Login for Gaming now can integrate with our Firebase test App. Could you please help us confirm if the issue has also been resolved for your Apps?
> 
> Thank you very much for your patience and help!

Yes, thanks I can confirm is working now.

**Comment by ferretnt** [comment]
Closing as closed.
