### ISSUE TITLE
[Bug] Failed to upload android symbols

### ISSUE THREAD

**Issue by revolt3r** [firebase/firebase-unity-sdk#400]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.34f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .tgz with PackageManager
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: many other
  * Additional SDKs you are using: not relevant
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: [Google Archive](https://developers.google.com/unity/archive)

### [REQUIRED] Please describe the issue here:

Firebase is unable to see the symbols, even though they are there (it's adding c: to the path for some reason):
`java.io.IOException: Unstripped native library path does not exist: C:BUILD_PATH/p\.build\last\android-debug\Debug Android Concept 2-0.18.0-v826.symbols.zip. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.`

#### Steps to reproduce:

Here's the script I'm using with Unity Cloud Build
```
#!/bin/bash
echo "Installing Firebase Tools"
npm install -g firebase-tools
echo "Uploading Android Symbols to Firebase..."
if firebase crashlytics:symbols:upload --app=1:[REMOVED APP ID] "${UNITY_PLAYER_PATH_DEBUG_SYMBOLS}" ; then
    echo "Upload Android Symbols to Firebase with success"
else
    echo "Upload Android Symbols to Firebase failed"
fi
```

This is what the environment variable returns
![image](https://user-images.githubusercontent.com/11783754/178519315-3855be39-dd1b-4a4c-b896-69fec2caa5e9.png)

And these are the logs I get (here I tried to add a slash before the path to check if would fix the issue)
![image](https://user-images.githubusercontent.com/11783754/178519443-b517f25a-ea89-491a-adaa-eee301593a24.png)

The symbols are generated, I can download them separately and they are also uploaded to the Unity Dashboard
![image](https://user-images.githubusercontent.com/11783754/178519771-a4a82fdc-7af4-43f1-8656-47bb5fa77019.png)

**Comment by paulinon** [comment]
Hi @revolt3r,

In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps performed to replicate this behavior?

**Comment by revolt3r** [comment]
@paulinon I don't think the project is relevant here. It can be any project (the FIrebase example one should work).

- To reproduce it you would need to build a debug build with UCB (it would generate the symbols automatically)
- Set this script as a Post-Build Script in the UCB config
```
#!/bin/bash
echo "Installing Firebase Tools"
npm install -g firebase-tools
echo "Uploading Android Symbols to Firebase..."
if firebase crashlytics:symbols:upload --app=1:[REMOVED APP ID] "${UNITY_PLAYER_PATH_DEBUG_SYMBOLS}" ; then
    echo "Upload Android Symbols to Firebase with success"
else
    echo "Upload Android Symbols to Firebase failed"
fi
```

**Comment by revolt3r** [comment]
Updated to 9.2.0, same issue.

Let me know if you would like me to add anything to the bash script for additional info.

`40700: Installing Firebase Tools
40701: npm WARN deprecated har-validator@5.1.3: this library is no longer supported
40702: npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
40703: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
40704: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
40705: added 696 packages, and audited 698 packages in 2m
40706: 27 vulnerabilities (21 moderate, 6 high)
40707: To address issues that do not require attention, run:
40708:   npm audit fix
40709: To address all issues (including breaking changes), run:
40710:   npm audit fix --force
40711: Run `npm audit` for details.
40712: Uploading Android Symbols to Firebase...
40713: i  Downloading buildtools.jar to C:\Users\buildbot\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-2.8.0.jar
40714: i  For open source licenses used by this command, look in the META-INF directory in the buildtools.jar file
40715: i  Generating symbols for BUILD_PATH/p/.build/last/android-debug/Debug Android Concept 2-0.19.0-v856.symbols.zip
40716: !  [CRASHLYTICS LOG DEBUG] Invoked Crashlytics Buildtools with arguments: 
40717: 	-generateNativeSymbols true
40718: 	-verbose true
40719: 	-symbolFileCacheDir C:\Windows\temp\crashlytics-fd734470-001f-4171-b44c-b8355b0b14d9\nativeSymbols\1-197338315222-android-ad411b1138969402568c77\breakpad
40720: 	-unstrippedLibrary BUILD_PATH/p/.build/last/android-debug/Debug Android Concept 2-0.19.0-v856.symbols.zip
40721: 	-symbolGenerator breakpad
40722: [CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
40723: [CRASHLYTICS LOG DEBUG] Extracting dump_syms from dump_syms/windows/dump_syms.bin to BUILD_PATH/p\.crashlytics\dump_syms.exe
40724: [CRASHLYTICS LOG DEBUG] Extracting mingw DLLs to .crashlytics
40725: [CRASHLYTICS LOG DEBUG] Breakpad symbol generator initialized: BUILD_PATH/p\.crashlytics\dump_syms.exe
40726: java.io.IOException: Unstripped native library path does not exist: C:BUILD_PATH/p\.build\last\android-debug\Debug Android Concept 2-0.19.0-v856.symbols.zip. Either specify the correct unstrippedNativeLibsDir or disable Crashlytics symbol uploading.
40727: Error: Failed to upload symbols
40728: Upload Android Symbols to Firebase failed`

**Comment by samedson** [comment]
Based on the output, it looks like the variable BUILD_PATH isn't being expanded - am I correct in assuming it should be a bash variable instead of a folder name?

**Comment by revolt3r** [comment]
From what I understand "/BUILD_PATH/" is a valid path for Unity Cloud Build. Unfortunately there's not much documentation, but you can see a few examples of paths that UCB returns from its environmental variables: https://forum.unity.com/threads/ucb-environment-variables-list.992231/

And a few more logs from the build where Unity uses the same path
![image](https://user-images.githubusercontent.com/11783754/179553970-3df95536-12a3-4b9c-84cb-046fc69448ed.png)

**Comment by mrichards** [comment]
Hi @revolt3r,

I agree it appears that `BUILD_PATH` appears to be a literal path and not an environment variable. So I think the issue is that the Firebase CLI is not correctly inferring absolute vs relative path in this situation. This is likely due to one or both of: 1) the shell (cygwin?) &  Java are having a weird interaction on UCB; or 2) the Firebase windows path resolution implementation has a bug that is only apparent on non-standard Windows volumes.

I am working on getting access to UCB so I can reproduce this myself. In the meantime, can you try modifying your script to `cd` into the parent directory of `${UNITY_PLAYER_PATH_DEBUG_SYMBOLS}`, and then run the upload command simply with the base filename (without the directory) as your zipped symbol file path? 

(If `dirname` and `basename` commands are available in your shell, that is probably the easiest way, i.e., ```cd `dirname $UNITY_PLAYER_PATH_DEBUG_SYMBOLS` ```, etc.)

**Comment by revolt3r** [comment]
@mrichards thanks for the reply.
I don't think I have enough bash knowledge to do that. I assume I would need to parse the filename from ${UNITY_PLAYER_PATH_DEBUG_SYMBOLS} besides changing the directory, and I'm not sure how to do that.

**Comment by luan-lucas** [comment]
I managed  to get the upload to complete in UCB by separating the path and file name:

```
FILE_NAME=$(basename "$UNITY_PLAYER_PATH_DEBUG_SYMBOLS")
PATH_NAME=$(dirname "$UNITY_PLAYER_PATH_DEBUG_SYMBOLS")
cd $PATH_NAME
if firebase crashlytics:symbols:upload --app=$APP_ID "${FILE_NAME}" ; then
    		echo "Upload Android Symbols to Firebase with success."
	else
    		echo "Upload Android Symbols to Firebase failed."
fi
```

**Comment by mrichards** [comment]
@luan-lucas Thank you!  That seems like an effective short-term workaround, and gives me some hints on how to modify the Firebase CLI to work, even without access to a UCB instance.

**Comment by revolt3r** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/11783754/185560144-63aae241-12ef-49ec-8b92-899c09271a6d.png)

**Comment by mrichards** [comment]
After looking into this deeper, there's no obvious bug in the code. So, without being able to reproduce it on UCB, I don't expect a proper fix to be released in the short term. I'm going to close this GitHub issue for now because of the workaround, though we're still tracking it internally. (internal tracking ref: b/238782396)
