### ISSUE TITLE
[Question] Firestore + Play Integrity API

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-unity-sdk#406]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.29f1
  * Firebase Unity SDK version: 9.2.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Auth, Crashlytics, Remote Config
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

How do we use Firebase (for example Firestore) together with the Play Integrity API? The package was recently released for Unity, but I can't find any documentation besides the Android one.
There, it seems all we need to do is to install the app check at runtime, and everything else happens in the background.

How is this done in Unity?

**Comment by paulinon** [comment]
Hi @Nyankoo,

It appears that enabling App Check with Play Integrity on Unity hasn't been implemented yet, but this seems like a good feature to have for a Unity app. I'll be relaying this to the team, and you may refer to this ticket for any updates.

**Comment by a-maurice** [comment]
Hi all,

Firebase App Check with Unity has just launched as part of the [11.0.0 release](https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.0.0), which includes support for the Play Integrity provider with Firestore.
