### ISSUE TITLE
[Bug] Undefined FIRApp on iOS

### ISSUE THREAD

**Issue by cathrynmataga** [firebase/firebase-unity-sdk#418]
* Unity editor version: 2019.4.13f1
  * Firebase Unity SDK version: 9.2.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: App (Auth, Database, etc.)
  * Other Firebase Components in use: Crashyltics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, leanplum (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac(Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: il2cpp (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: prebuilllt

I've followed the instructions for installing Crashlytics, but on iOS I'm getting undefined linker errors for _OBJC_CLASS_$_FIRApp and other undefined symbols.

CMATAOAKOSXL3:Firebase cathryn.mataga$ pwd
/Users/cathryn.mataga/slotsburg-client-android/SlotsBurg_Unity/Assets/Plugins/iOS/Firebase
CMATAOAKOSXL3:Firebase cathryn.mataga$ ls -al
total 100816
drwxr-xr-x  10 cathryn.mataga  BIGFISH\Domain Users       320 Jul 22 10:49 .
drwxr-xr-x  18 cathryn.mataga  BIGFISH\Domain Users       576 Jul 21 16:55 ..
-rwxrwxr-x@  1 cathryn.mataga  BIGFISH\Domain Users   1976000 Dec  4  2016 libFirebaseCppAnalytics.a
-rw-r--r--@  1 cathryn.mataga  BIGFISH\Domain Users      1363 Dec  4  2016 libFirebaseCppAnalytics.a.meta
-rwxrwxr-x@  1 cathryn.mataga  BIGFISH\Domain Users  46316144 Dec  4  2016 libFirebaseCppApp.a
-rw-r--r--@  1 cathryn.mataga  BIGFISH\Domain Users      1357 Dec  4  2016 libFirebaseCppApp.a.meta
-rwxrwxr-x@  1 cathryn.mataga  BIGFISH\Domain Users   1293896 Dec  4  2016 libFirebaseCppCrashlytics.a
-rw-r--r--@  1 cathryn.mataga  BIGFISH\Domain Users      1365 Dec  4  2016 libFirebaseCppCrashlytics.a.meta
-rw-r--r--   1 cathryn.mataga  BIGFISH\Domain Users   2010056 Jul 21 16:54 libFirebaseCppMessaging.a
-rw-r--r--   1 cathryn.mataga  BIGFISH\Domain Users      1363 Jul 21 16:54 libFirebaseCppMessaging.a.meta

iOS resolver settings are set to defaults.
<img width="849" alt="Screen Shot 2022-07-22 at 12 50 28 PM" src="https://user-images.githubusercontent.com/61515454/180517146-a8a79044-b31b-46af-a918-8cd65fb66427.png">

In the build results, I don't see anything in the Pods directory? Is that correct?
CMATAOAKOSXL3:Pods cathryn.mataga$ pwd
/Users/cathryn.mataga/slotsburg-client-android/SlotsBurg_Unity/Builds/r8811_IOS_Development_Stage_Tech/SlotsBurg_1.0_r8811_Stage_Tech/Pods
CMATAOAKOSXL3:Pods cathryn.mataga$ ls -al *
Headers:
total 0
drwxr-xr-x  2 cathryn.mataga  BIGFISH\Domain Users   64 Jul 22 12:20 .
drwxr-xr-x  5 cathryn.mataga  BIGFISH\Domain Users  160 Jul 22 12:20 ..

Local Podspecs:
total 0
drwxr-xr-x  2 cathryn.mataga  BIGFISH\Domain Users   64 Jul 22 12:20 .
drwxr-xr-x  5 cathryn.mataga  BIGFISH\Domain Users  160 Jul 22 12:20 ..

Target Support Files:
total 0
drwxr-xr-x  2 cathryn.mataga  BIGFISH\Domain Users   64 Jul 22 12:20 .
drwxr-xr-x  5 cathryn.mataga  BIGFISH\Domain Users  160 Jul 22 12:20 ..

My Podfile looks like the following.

CMATAOAKOSXL3:SlotsBurg_1.0_r8811_Stage_Tech cathryn.mataga$ cat Podfile
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '9.2.0'
  pod 'Firebase/Core', '9.2.0'
  pod 'Firebase/Crashlytics', '9.2.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'GoogleSignIn', '>= 4.0.2'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

This is my pod version
CMATAOAKOSXL3:SlotsBurg_1.0_r8811_Stage_Tech cathryn.mataga$ pod --version
1.11.2

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

Going to try this.  See if I can compare the sample to our game.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in libFirebaseCppMessaging.a(messaging_231c52c311096cfce13e67fa91eb9ac5.o)
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in libFirebaseCppApp.a(app_ios.mm.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in libFirebaseCppApp.a(app_ios.mm.o)
  "_OBJC_CLASS_$_FIRCrashlytics", referenced from:
      objc-class-ref in libFirebaseCppCrashlytics.a(CrashlyticsiOSWrapper.m.o)
  "_OBJC_CLASS_$_FIRExceptionModel", referenced from:
      objc-class-ref in libFirebaseCppCrashlytics.a(CrashlyticsiOSWrapper.m.o)
  "_OBJC_CLASS_$_FIRConfiguration", referenced from:
      objc-class-ref in libFirebaseCppApp.a(app_ios.mm.o)
  "_OBJC_CLASS_$_FIRStackFrame", referenced from:
      objc-class-ref in libFirebaseCppCrashlytics.a(CrashlyticsiOSWrapper.m.o)
  "_FIRCLSUserLoggingRecordInternalKeyValue", referenced from:
      _CLUSetInternalKeyValue in libFirebaseCppCrashlytics.a(CrashlyticsiOSWrapper.m.o)
#### Relevant Code:

Thanks, and sorry for the noise. I think maybe something stupid, but I'm not figuring this out myself right now.

**Comment by cathrynmataga** [comment]
I think something is broken with my cocoapods maybe? I'm not familiar with how pods gets from 'Firebase/Analytics' to the actual code.

MATAOAKOSXL3:SlotsBurg_1.0_r8811_Stage_Tech cathryn.mataga$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (= 9.2.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (= 9.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
CMATAOAKOSXL3:SlotsBurg_1.0_r8811_Stage_Tech cathryn.mataga$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (= 9.2.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (= 9.2.0)`.

You have either:
 * mistyped the name or version.

**Comment by paulinon** [comment]
Hi @cathrynmataga,

Thanks for reporting this issue. From the looks of your `Podfile`, it appears that the Messaging SDK hasn't been updated compared to the other Firebase SDKs. Could you try if fixing the version mismatch resolves the issue?

**Comment by cathrynmataga** [comment]
Thanks, changing that 7.0.0 to 9.2.0 makes cocoapods act more coherent.

Though building I'm still getting this.
ld: framework not found AppAuth

Odd that it shows AppAuth getting installed. (Looking at this now...)


CMATAOAKOSXL3:SlotsBurg_1.0_r8811_Stage_Tech cathryn.mataga$ pod install
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.5.0)
Installing Firebase (9.2.0)
Installing FirebaseAnalytics (9.2.0)
Installing FirebaseCore (9.2.0)
Installing FirebaseCoreDiagnostics (9.3.0)
Installing FirebaseCoreInternal (9.3.0)
Installing FirebaseCrashlytics (9.2.0)
Installing FirebaseInstallations (9.3.0)
Installing FirebaseMessaging (9.2.0)
Installing GTMAppAuth (1.3.0)
Installing GTMSessionFetcher (1.7.2)
Installing GoogleAppMeasurement (9.2.0)
Installing GoogleDataTransport (9.2.0)
Installing GoogleSignIn (6.2.2)
Installing GoogleUtilities (7.7.0)
Installing PromisesObjC (2.1.1)
Installing nanopb (2.30909.0)
Generating Pods project
Integrating client project

**Comment by paulinon** [comment]
Hi @cathrynmataga,

Has there been an error or warning message after the build was finished? Could you provide your updated `Podfile` and `Podfile.lock` file so we could identify the cause of the issue?

**Comment by cathrynmataga** [comment]
looks like it's working now. Instead of monkeyinig with the PodFile, I just installed   Messaging 9.2.0 and that fixed this.
