### ISSUE TITLE
Wrong version order in Unity packages archive

### ISSUE THREAD

**Issue by stopiccot** [firebase/firebase-unity-sdk#419]
https://developers.google.com/unity/archive#firebase_app_core

It took me a while to find 9.2.0 because for some reason it's located at the very bottom
<img width="927" alt="Screenshot 2022-07-25 at 14 52 05" src="https://user-images.githubusercontent.com/24836/180771829-b8714d0b-ba4a-496f-b70b-233167eeaec3.png">

**Comment by paulinon** [comment]
Hi @stopiccot,

Thanks for bringing this up. The latest SDK version seems to be out of order in the documentation. I'll be relaying this to the team, and you may refer to this ticket for updates.

**Comment by AlmostMatt** [comment]
As of the 9.3 release, the order of SDK versions should be correct again.
