### ISSUE TITLE
Critical issue warning in google play developer console in firebase unity sdk when making build with firebase messaging

### ISSUE THREAD

**Issue by dpkporwal** [firebase/firebase-unity-sdk#426]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.36
  * Firebase Unity SDK version: 9.3
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Analytics, Crashlytics, DynamicLinks, 
  * Additional SDKs you are using: Facebook, AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: __https://firebase.google.com/download/unity___

### [REQUIRED] Please describe the issue here:

Your latest production release (5.2) contains SDK issues "Project NAme"
Jul 18, 2022 16:07
Critical issues have been reported with the following SDK versions:

com.google.android.gms:play-services-tasks:18.0.0

What the SDK developer told us:
play-services-tasks v18.0.0 has known issues that can lead to runtime NPEs (NullPointerException) when handling Task<Void> results in Kotlin code. We strongly recommend that you avoid using this version. This also impacts the SDKs listed in the December 9, 2021 release, because they all depend on play-services-tasks. A fix for this issue is included in play-services-tasks v18.0.1. See https://developers.google.com/android/guides/releases#december_16_2021

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? not verified
What's the issue repro rate?  100%

What happened? How can we make the problem occur?
 yes We have two projects , In one project we are not using Firebase messaging and in another we are using firebase messaging
 the project in which we are using firebase mesasging when we make build and upload on google play developer console it will giving me this warning . when i removed firebase messaging messaging then i have tried the warning is gone.
 But we need to use firebase messaging. I have tried fire base version 8.10 , 9.0, 9.1 , 9.2, 9.3

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment]
Hi @dpkporwal, 

Thanks for reporting this. Could you provide the `AppDependencies.xml` file of your implementation? There may be a dependency issue that's causing this.

**Comment by paulinon** [comment]
Hi @dpkporwal,

Could you share the `MessagingDependencies.xml` file as well? It's possible that this points to an older version of the Messaging Android SDK

**Comment by dpkporwal** [comment]
> Hi @dpkporwal,
> 
> Could you share the `MessagingDependencies.xml` file as well? It's possible that this points to an older version of the Messaging Android SDK

I  am attaching the file content of MessagingDependencies.xml also
[MessagingDependencies.txt](https://github.com/firebase/firebase-unity-sdk/files/9240913/MessagingDependencies.txt)
![Screenshot 2022-08-02 150310](https://user-images.githubusercontent.com/14894500/182342797-31a6638c-44b3-409c-926d-3195ba582f26.png)

**Comment by paulinon** [comment]
Hi @dpkporwal,

The Android dependencies appear to be in order. Are there any other differences you've observed between the build without the Firebase SDK and the build with the Firebase SDK? Does the error message appear with just the Firebase SDK in your implementation?

Additionally, please provide your `mainTemplate.gradle` file so we could determine the effect the Facebook or Admob SDKs may have in your project.

**Comment by dpkporwal** [comment]
> Hi @dpkporwal,
> 
> The Android dependencies appear to be in order. Are there any other differences you've observed between the build without the Firebase SDK and the build with the Firebase SDK? Does the error message appear with just the Firebase SDK in your implementation?
> 
> Additionally, please provide your `mainTemplate.gradle` file so we could determine the effect the Facebook or Admob SDKs may have in your project.

Yes there are differences in build,
When i have made the build with firebase messaging then this warning is coming other wise this warning is not coming when i made the build without firebase messaging( used  firbase analytics, firebase crashlytics and firebase remoteconfig in both the cases)

I am attaching the main template file here also as you want, please have a look

[mainTemplate.txt](https://github.com/firebase/firebase-unity-sdk/files/9248222/mainTemplate.txt)

**Comment by paulinon** [comment]
Hi @dpkporwal,

Is the error message the only difference you noticed between the builds? Could you confirm if your project containing **only** the Firebase SDK results in a similar error message?

Also, could you confirm if adding this line of code in your `mainTemplate.gradle` file makes any difference?
```
// Android Resolver Dependencies Start
implementation 'com.google.android.gms:play-services-tasks:18.0.2'
```

**Comment by dpkporwal** [comment]
> Hi @dpkporwal,
> 
> Is the error message the only difference you noticed between the builds? Could you confirm if your project containing **only** the Firebase SDK results in a similar error message?
> 
> Also, could you confirm if adding this line of code in your `mainTemplate.gradle` file makes any difference?
> 
> ```
> // Android Resolver Dependencies Start
> implementation 'com.google.android.gms:play-services-tasks:18.0.2'
> ```

Yes this error message is the only difference between the builds. When i used firebase messaging and vice versa.

I have tried uploading build after making with this line in maintemplate.
It didnt make any difference. same warning again. 
Just want to clarify this is a warning in playstore not an error from the start. but i want to resolve this warning too.

**Comment by dpkporwal** [comment]
Hello , i am waiting for the solution

**Comment by a-maurice** [comment]
Hi @dpkporwal 

We haven't been able to reproduce this problem on our side yet, it keeps pulling play-services-tasks:18.0.2 correctly.  If you could, in your Unity project can you check in the taskbar Assets > External Dependency Manager > Android Resolver > Display Libraries.  That should open up window that lists out what libraries it is trying to include, what versions, and where it gets it from.  This might help indicate where it is pulling the wrong version of tasks from.

Another option is in the Android Resolver, under Settings, turning on Verbose Logging, and then running Force Resolve.  There might be something indicated in the logs that might be helpful.

**Comment by chkuang-g** [comment]
@dpkporwal 

I just tried FIrebase SDK `9.6.0` and I think the default `com.google.android.gms.play-services-tasks` version EDM4U downloaded is `18.0.2`. Please try to upgrade the Firebase SDK.

If you still get `18.0.0`, I suspect some of the other third_party plugin you added to the project tried to pin the version to `18.0.0`.

In that case, please try to pin the version in `mainTemplate.gradle` this way:

```
implementation 'com.google.android.gms:play-services-tasks:[18.0.2]'
// Android Resolver Dependencies Start
```

Note the use of `[18.0.2]` and make this above `// Android Resolver Dependencies Start` so that this line won't be overridden by EDM4U during build time.

Also take a look of `Temp/gradleOut/launcher/build/outputs/logs/manifest-merger-release-report.txt` and see if Gradle from the Unity actually picked `18.0.2`

**Comment by dpkporwal** [comment]
I have updated the firebase to 9.6.0 but still same issue, maybe because of some third party plugin.
I have also added this in main maintemplate as you said
implementation 'com.google.android.gms:play-services-tasks:[18.0.2]'
// Android Resolver Dependencies Start

when i am checking Temp/gradleOut/launcher/build/outputs/logs/manifest-merger-release-report.txt this file it showing me 18.0.2 not 18.0.0
but when i am uploading to google play store then showing same warning.

**Comment by DellaBitta** [comment]
Hi @dpkporwal,

Since we can't reproduce this here could you please post a copy of your verbose AndroidResolver log so we can look through it?

Under the Android Resolver`Settings` turn on `Verbose Logging`, and then running `Force Resolve`.

Thanks!
