### ISSUE TITLE
[Bug] Google API for Unity Archive page did not update for non-en languages

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-unity-sdk#430]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

I'm not 100% sure if the people who are working here are able to help with this, but the TGZ files under "https://developers.google.com/unity/archive#cloud_firestore_for_firebase" are not updated since version 9.1.

It would be great when this could be passed on internally and that in the future, this is updated in a timely manner.

As a workaround, copying the 9.1 link and replace 9.1.0 with 9.3.0 (or the latest version) in the URL works, so the files are there, just the website was not updated in a while.

**Comment by Nyankoo** [comment]
Update: it seems that the English version of the page has the latest version, but eg. the German one stops at 9.1.

**Comment by paulinon** [comment]
Thanks for bringing this to our attention, @Nyankoo. I've observed that the documentation you provided isn't consistent with all languages. I'll be relaying this to the team, and you may refer to this ticket for updates.

**Comment by argzdev** [comment]
It looks like this issue has been fixed for some time now. I'll go ahead and close this thread. Thanks!
