### ISSUE TITLE
[Question] Billing when using SetAsync with a FirestoreData object

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-unity-sdk#433]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

The billing documentation is quite clear regarding what actions get billed, but I just want to make sure I understand the specific instance of writing a whole object to Firestore correctly.

When I have an object of a class that is marked with "FirestoreData" with a few "FirestoreProperty" properties and I then call "SetAsync(thatObject)", how is billing handled?

- Does it count as one write (assumption: "Set" is only called once) or
- Does it count as X writes, were X is the amount of "FirestoreProperty" properties the object has (assumption: "Set" is called multiple times internally)
- Something entirely different

**Comment by paulinon** [comment]
Hi @Nyankoo,

Regardless of the number of fields being written in one operation, it still counts as one write. You may also refer to this [video](https://www.youtube.com/watch?v=6NegFl9p_sE) talking about Cloud Firestore's pricing for more information.

I'll be closing this for now. Feel free to reopen if you have any other questions.
