### ISSUE TITLE
[Bug] Unity metadata is not available for iOS crashes

### ISSUE THREAD

**Issue by AntonPetrov83** [firebase/firebase-unity-sdk#434]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.32f1
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: AdMob, AppLovin, Singular
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Reproducible 100% for iOS

All events for out iOS application have empty Unity metadata page.
Android version of the app has this data filled.

**Comment by paulinon** [comment]
Hi @AntonPetrov83,

Could you verify if this persists using the latest version (9.3.0) of the SDK? If so, please provide the sample code you used along with the steps to replicate the issue so that we could analyze what's causing this behavior.
