### ISSUE TITLE
[Bug] Unsymbolicated split_config callstack with 9.2.0

### ISSUE THREAD

**Issue by cathrynmataga** [firebase/firebase-unity-sdk#435]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.29
  * Firebase Unity SDK version: 9.2.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics(Auth, Database, etc.)
  * Other Firebase Components in use: Messaging, Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Leanplum (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac(Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: il2cpp (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: prebuilt

### [REQUIRED] Please describe the issue here:
I have a crash "Fatal Exception: java.lang.Error" on Android with callstacks with split_config that have no symbols. I

I'm trying to understand where split_config comes from and is it possible to get symbols for split_config

![Screen Shot 2022-08-03 at 1 34 42 PM](https://user-images.githubusercontent.com/61515454/182706536-b1e52e9c-c383-4172-b778-c81db42c118c.png)

This bug seems to happen before Unity is actually initialized at all, how it looks.  That I see no Unity Metadata for this bug only, but other issues have correct Unity Metadata.

![Screen Shot 2022-08-03 at 12 45 01 PM](https://user-images.githubusercontent.com/61515454/182702215-84d9cd2a-e702-441d-b910-d95cd623f323.png)
![Screen Shot 2022-08-03 at 12 45 12 PM](https://user-images.githubusercontent.com/61515454/182702228-3f1249c6-0c42-4818-a4a5-b147ceadf4fe.png)

I do see other native call stacks on Android, and I'm on 9.2.0 and my symbols.zip upload went fine. This is an  So I think Crashlytics is generally working for native symbols otherwise. 

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
This is a issue from the wild, and we don't have a repro this locally. This issue is Android 11 and Android 12 only. 

What happened? How can we make the problem occur?
Issue happens at launch of the game.

**Comment by cathrynmataga** [comment]
What's weird, is I don't think split_config is our code or Unity's either.

**Comment by cathrynmataga** [comment]
Oh dear. This is not encouraging.    I have exactly this issue here.

https://issuetracker.google.com/issues/236621930

**Comment by paulinon** [comment]
Hi @cathrynmataga,

Could you confirm if the issue persists using the latest SDK version (9.3.0)? If it does, I'd like you to try enabling `Custom Main Manifest` in your Android Publishing settings, and adding this line in the generated manifest file:
```
<application>
    android:extractNativeLibs="true"
    ...
</application>
```
I look forward to your results.

**Comment by cathrynmataga** [comment]
Thanks for the reply.  Yeah, I think our data bundles are quite a bit bigger than our code bundles anyway, so if extractNativeLibs="true" only affects code, we could take  this.

**Comment by paulinon** [comment]
Glad to hear this, @cathrynmataga. I'll be closing this issue for now. Let me know if an issue arises

**Comment by rkfteam** [comment]
@cathrynmataga Did setting extractNativeLibs = true help you? No more crashes?
