### ISSUE TITLE
[Bug] Crash stacktrace truncated in Crashlytics dashboard

### ISSUE THREAD

**Issue by VolodymyrBS** [firebase/firebase-unity-sdk#440]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.6f1
  * Firebase Unity SDK version: 9.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Linux
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built

### [REQUIRED] Please describe the issue here:

I'm testing crashlytics integration in my android game. I'm trying a different exception. one normal C# exception and one fatal exception that stops the game.
General C# exception looks good, but the fatal exception missing lot frames from stack traces.
This is a log that I see in logcat:
![image](https://user-images.githubusercontent.com/20375870/183941046-64a0489c-2b42-4238-9c7b-e7bcfa4db7fd.png)

and this is what I see in dashboard:
![image](https://user-images.githubusercontent.com/20375870/183941132-5bd1badc-f695-41dc-b673-6e635307e947.png)
![image](https://user-images.githubusercontent.com/20375870/183941205-c3be9212-4415-41cb-8bdb-b05ac1b3f9f5.png)

I'm not sure if it is something that I need to configure or if it's Crashlitics limitation

**Comment by paulinon** [comment]
Hi @VolodymyrBS,

[Version 9.4.0](https://firebase.google.com/support/release-notes/unity#version_940_-_august_10_2022) of the SDK has been released recently. Could you confirm if this version makes a difference in terms of your issue? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to replicate the issue so that we can identify what's causing this behavior.

**Comment by VolodymyrBS** [comment]
Hi @paulinon,
I have created a minimal reproducible example with the latest SDK
Here is the repo: [TestCrashlytics](https://github.com/VolodymyrBS/TestCrashlytics)

Steps to reproduce:
 1. Clone the repo;
 2. Import project into Unity for the Android platform;
 3. Import Firebase Crashlytics SDK into the project;
 4. Add package id;
 5. Add google-services.json into the project;
 6. Build the game with IL2CPP scripting backend and public symbols.zip;
 7. Upload symbold.zip to Firebase Crashlytics;
 8. Run the app on the device;
 9. Click the button with "Hard" text;
 10. Observe build was closed
 11. Check logcat for crash with SIGSEGV;
 12. Open crashlytics dashboard and open crash in libunity.so in method `Mesh.CreateMesh()`;
 13. Observe that crash has only a few stack frames (2 in my case)

**Comment by VolodymyrBS** [comment]
also, I just noticed that `#00` and `#01` pc-s differ between stack trace from logcat and displayed in Crashlytics.
logcat shows `#01 pc` as `99e710`, and dashboard shows `99bde8`
![image](https://user-images.githubusercontent.com/20375870/184357854-c33d19f9-2988-41ca-b43f-3c1948843da9.png)
![image](https://user-images.githubusercontent.com/20375870/184357908-6cf14843-4d9c-4c1f-a849-db6bd4f9ba0d.png)

**Comment by paulinon** [comment]
Thanks for providing the needed information, @VolodymyrBS. I was able to encounter the behavior you're facing where ` libunity.so ` appeared in the crashed thread. I also noticed missing frames corresponding to system libraries such as `libart.so`, `libc.so`, `boot.oat`, `boot-framework.oat`, and others. We currently cannot symbolicate these system libraries as we don't have visibility into the symbols associated with them. Our team is working on making this better, but we don't have any information or specific timeline to share other than that.

I'll be closing this for now. Should you have any related questions, you may get in touch with [Firebase Support](https://firebase.google.com/support).

**Comment by VolodymyrBS** [comment]
okay, I got it.
is there any way to manually download raw crash information to process it by hand?

**Comment by paulinon** [comment]
Hi @VolodymyrBS,

To do this, you may [export Crashlytics data to BigQuery](https://firebase.google.com/docs/crashlytics/bigquery-export) so that your data can be analyzed further.

**Comment by VolodymyrBS** [comment]
@paulinon 
thanks a lot!
