### ISSUE TITLE
[Bug] DllNotFoundException in editor on Windows

### ISSUE THREAD

**Issue by VolodymyrBS** [firebase/firebase-unity-sdk#443]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.6f1
  * Firebase Unity SDK version: 9.4.0, 9.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: 
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows 10 Pro 21H2 CPU:  AMD Ryzen 7 5700G
  * Platform you are targeting: Android and desktop
  * Scripting Runtime: Mono (Editor)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

One of the developers in my team got this exception as soon as the first access to firebase happens
```
DllNotFoundException: FirebaseCppApp-9_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Firebase.LogUtil..ctor () (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Firebase.LogUtil..cctor () (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at <e453f444a42d4ceeaaeeea32bbd6030c>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
CrashTest.Awake () (at Assets/CrashTest.cs:11)
```
This happens only on one machine. on other computers, everything works fine, without any problems. We have also tried version 9.3.0, but got the same error. previously we had version 8.8.0 and had no exceptions.

#### Steps to reproduce:

Here minimal repro of this problem: [TestCrashlytics](https://github.com/VolodymyrBS/TestCrashlytics)
it has nothing special but it reproduces the error on that machine
Steps used to reproduce the issue:
 1. Clone the repo;
 2. Import project into Unity for the Android platform;
 3. Import Firebase Crashlytics SDK into the project;
 4. Add package id;
 5. Add google-services.json into the project;
 6. Open SampleScene;
 7. Hit `Play`

**Comment by paulinon** [comment]
Hi @VolodymyrBS,

It's rather odd that this issue occurs on just one machine. Could you try if force resolving makes a difference? 
`Assets > External Dependency Manager > Android Resolver > Force Resolve`

Could you also confirm if using one of our [quickstart samples](https://github.com/firebase/quickstart-unity) results in a similar error message?

**Comment by VolodymyrBS** [comment]
Hi @paulinon,

`Force Resolve` does not make any effect.

Also, we have tried the quickstart sample and it still has the same issue.
Here is the stacktrace from quickstart sample:
```
DllNotFoundException: FirebaseCppApp-9_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Firebase.LogUtil..ctor () (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Firebase.LogUtil..cctor () (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at <dbf74e6f5d904800a52278fadc1d17c2>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Crashlytics.UIHandler.Start () (at Assets/Firebase/Sample/Crashlytics/UIHandler.cs:39)
```

**Comment by paulinon** [comment]
Hi @VolodymyrBS,

Could you try if installing the SDK using the [Unity Package Manager](https://firebase.google.com/docs/unity/setup-alternative#alternative_unity_package_manager) makes any difference? Do the other machines that don't experience the issue make use of the same operating system and CPU?

**Comment by VolodymyrBS** [comment]
We have tried UPM version but the result is the same
```
DllNotFoundException: FirebaseCppApp-9_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/android_unity/armeabi-v7a/app/swig/Firebase.App_fixed.cs:3909)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/android_unity/armeabi-v7a/app/swig/Firebase.App_fixed.cs:3929)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/android_unity/armeabi-v7a/app/swig/Firebase.App_fixed.cs:4636)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/android_unity/armeabi-v7a/app/swig/Firebase.App_fixed.cs:1897)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Crashlytics.UIHandler.Start () (at Assets/Firebase/Sample/Crashlytics/UIHandler.cs:39)
```

Regarding OS version and CPU, they differ from machine to machine. Most are on windows 10 21H2, some are on Windows 11  21H2. CPUs differ too: Ryzen 5800x3d,  Intel Core I5-9400f, Ryzen 7 5800HS, Intel Core i7-9750H

**Comment by paulinon** [comment]
Hi @VolodymyrBS,

Does the machine have a C++ Redistributable? The Firebase Unity SDK uses a C++ layer across all platforms, so not having the C++ redistributable would cause the call into the library to fail.

**Comment by VolodymyrBS** [comment]
HI @paulinon 

We found the issue. On that single machine was installed C++ Redistributable 2005, 2010, 2012, 2013, 2017 but not newer.
Installing C++ Redistributable 2015-2022 fixed the issue.

So I'm closing this issue. Thanks for your help!
