### ISSUE TITLE
[Bug] FirebaseCppApp-9_4_0.dll is dynamic linked against vcruntime140_1.dll (and friends).

### ISSUE THREAD

**Issue by bithoarder** [firebase/firebase-unity-sdk#446]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2021.3.4f1
  * Firebase Unity SDK version: 9.4
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: App/Core
  * Other Firebase Components in use: Crashlytics, Analytics
  * Additional SDKs you are using: na
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: na
  * Scripting Runtime: na
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

When starting a Unity project in the Windows Editor, FirebaseCppApp-8_9_0.dll will fail to load if the VC2015 redist have not been installed by some unrelated application.

#### Steps to reproduce:

* Clean window install (ie. no other application that has installed the required VC runtime dlls must be installed).
* Create a new project
* add Firebase App (Core) v9.4
* add call to FirebaseApp.CheckAndFixDependenciesAsync()
* hit play
* notice exception in Unitys log:
DllNotFoundException: FirebaseCppApp-9_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)

#### Relevant Code:

```
using System.Collections;
using System.Collections.Generic;
using Firebase;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log("Before");
        FirebaseApp.CheckAndFixDependenciesAsync();
        Debug.Log("After");
    }
}
```

**Comment by paulinon** [comment]
Hi @bithoarder,

- Have you imported the External Dependency Manager? It's imperative that this be imported first before Firebase App (Core).
- Could you share the full error message so we can identify what's causing the behavior?
- When you mentioned "friends", do you mean are there any other related `.dll` files that have to be present?

**Comment by dginovker** [comment]
Without the full error it's hard to say but this looks like a dupe of #443
