### ISSUE TITLE
Remote Config version 21.1.1+ in Unity SDK

### ISSUE THREAD

**Issue by TellmewowBilbao** [firebase/firebase-unity-sdk#450]
* Unity editor version: 2020.3.33f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Analytics, Crashlitics
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows 10 Pro
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

When uploading new version to Google Play Console this issue is reported:

_Critical issues have been reported with the following SDK versions:
com.google.firebase:firebase-config:21.1.0
What the SDK developer told us:
Bug affecting some locales causing HTTP errors Please downgrade to 21.0.2 or, if available, update to the next version which will contain a fix. For more info please see: https://github.com/firebase/firebase-android-sdk/issues/3757_

I didn't find in your changelog which Firebase Unity SDK version includes Remote Config version 21.1.1 that fixes the problem as described [here](https://firebase.google.com/support/release-notes/android#remote-config_v21-1-1)
Will latest version fix this or we need to wait for future versions?

**Comment by paulinon** [comment]
Hi @TellmewowBilbao,

The latest Unity releases typically point to the latest version of the build SDK at the time of release. Version 9.4.0 is currently pointing to Remote Config version 21.1.1, so an SDK update should solve the issue.

That being said, I'll be closing this ticket. Let me know if an issue arises.
