### ISSUE TITLE
[Question] Why C++ Redistributable is required starting from Firebase 9.x and it wasn't in older versions?

### ISSUE THREAD

**Issue by pabloleban** [firebase/firebase-unity-sdk#454]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.38f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase Core App
  * Other Firebase Components in use: Auth, Storage, Crashlytics
  * Additional SDKs you are using: Yodo1 MAS
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android, and Windows
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: https://firebase.google.com/download/unity

### [REQUIRED] Please describe the question here:

C++ wasn't required before on Windows. After I've updated Firebase version, I had to enable the C++ Redistributable to be installed right after installing the game on Steam. However there are still a few users that are having the `DllNotFoundException: Unable to load DLL 'FirebaseCppApp-9_1_0': The specified module could not be found.` error, despite they have installed C++ Redistributable. Any ideas?

**Comment by paulinon** [comment]
Hi @pabloleban,

The Firebase Unity SDK makes use of a C++ layer across all platforms, so if a Windows device does not have the C++ redistributable, then calls into the library would fail. For the case of your users, installing a newer C++ Redistributable would resolve the issue.

I'm going to close this issue for now, but we will see about improving our documentation to make this dependency more apparent. Let me know if your users are still facing any issues after installing a newer C++ Redistributable so this ticket could be reopened

**Comment by pabloleban** [comment]
Users with Windows 7 and an updated C++ Redistributable are still getting this issue.

**Comment by chkuang-g** [comment]
@pabloleban 

Interesting. In the first post, you mentioned that you use `9.1.0` but the error message is about `9.4.0`.

Is there a chance that you mix-match different of Firebase SDK? This error message commonly occur when you mix-match Firebase SDK versions, for instance, Auth for `9.1.0` and Crashlytics for `9.4.0`.

If that is the case, I would recommend you to fully remove Firebase from your project and re-import everything back again. Make sure you are using the same version this time.

If you are using `.unitypackage`, you can follow [the instruction here](https://firebase.google.com/docs/unity/setup-alternative#alternative_migrate_to_upm) for removal.  If you are using UPM...you can just import different `.tgz`

Let me know
