### ISSUE TITLE
[Bug] Unity3d iOS il2cpp does not generate .xcodeworkspace project

### ISSUE THREAD

**Issue by mayur-r-d** [firebase/firebase-unity-sdk#463]
Following error found in build logs

Begin MonoManager ReloadAssembly
Assembly 'Assets/Firebase/Editor/Firebase.Crashlytics.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'Google.VersionHandlerImpl'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Google.JarResolver'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Assembly 'Assets/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'Google.JarResolver'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Google.VersionHandlerImpl'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Google.IOSResolver'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

Firebase Core : v9.3.0
Firebase Analytics : v9.3.0
Firebase Crashlytics : v9.3.0

External dependency Manager = v1.2.172

Xcode : v14.0(14A309) 
Pod : v1.11.3
Unity3d : v2020.3.22f1

**Comment by mayur-r-d** [comment]
Had some progress after changing Firebase and External Dependency Manager version I was able to generate .xcodeworkspace project but stuck with following error :

/build/intermediates/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises(FBLPromise.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 

/build/intermediates/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64[0m

Firebase Core : v8.9.0
Firebase Analytics : v8.9.0
Firebase Crashlytics : v8.9.0

External dependency Manager = v1.2.170

Xcode : v14.0(14A309)
Pod : v1.11.3
Unity3d : v2020.3.22f1

**Comment by paulinon** [comment]
Hi @mayur-r-d,

Bitcode has been deprecated in Xcode 14 as seen in the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes). Turning off bitcode in your Xcode project should remove the warning you're facing.

I'll be closing this for now. Let me know if an issue arises.

**Comment by mayur-r-d** [comment]
Hi @paulinon ,
Tried disabling the bitcode but, still the problem is not resolved.
