### ISSUE TITLE
[Bug] Revenue data not getting updated for iOS purchases on Google Analytics

### ISSUE THREAD

**Issue by ap4996** [firebase/firebase-unity-sdk#464]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.4f
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Crashlytics, Dynamic Links, Cloud Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Adjust, Unity Ads (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac and Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android and iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

The revenue generated from IAPs in our iOS game isn't getting recorded on Google Analytics. It has been almost a year since it stopped recording properly. We have tried manually triggering the in_app_purchase event also for iOS, but no change in the data.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
This is happening with all the iOS IAPs.

What happened? How can we make the problem occur?
Purchases are working on iOS for our app but there is no revenue data being recorded for the same.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

We have tried to trigger a separate event for this as well and mark it as a conversion. The event gets triggered but there is no revenue data for the same.

This code that we wrote to manually trigger the event:

```
#if UNITY_IOS
		AppHelper.SendFirebaseTracker("in_app_purchase", new Firebase.Analytics.Parameter[] { 
			new Firebase.Analytics.Parameter("product_id", product.definition.id),
			new Firebase.Analytics.Parameter("value", Convert.ToInt64(product.metadata.localizedPrice)),
			new Firebase.Analytics.Parameter("quantity", 1),
			new Firebase.Analytics.Parameter("price", Convert.ToInt64(product.metadata.localizedPrice)),
			new Firebase.Analytics.Parameter("currency", product.metadata.isoCurrencyCode)
		});
		AppHelper.SendFirebaseTracker("in_app_ios", new Firebase.Analytics.Parameter[] { 
			new Firebase.Analytics.Parameter("product_id", product.definition.id),
			new Firebase.Analytics.Parameter("value", Convert.ToInt64(product.metadata.localizedPrice)),
			new Firebase.Analytics.Parameter("quantity", 1),
			new Firebase.Analytics.Parameter("price", Convert.ToInt64(product.metadata.localizedPrice)),
			new Firebase.Analytics.Parameter("currency", product.metadata.isoCurrencyCode)
		});
#endif
```

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @ap4996,

Could you verify if version 9.5.0 produces the same issue? If so, kindly provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with the logs returned after the events have been triggered so that we can analyze what's causing this behavior.

**Comment by ap4996** [comment]
Hey @paulinon , sorry for the delay. Our team is still trying to get the update out with version 9.5.0. I will update as soon as that is done. Thank you.

**Comment by ap4996** [comment]
So, we updated the Firebase version to 9.5.0 but still no revenue data for iOS. I will provide you with as much information from our side as possible in a couple of days.
