### ISSUE TITLE
[Question] DIINotFoundException: Unable to load DLL "FirebaseCppApp-9_4_0'. Tried the load the following dynamic libraries: Unable to load dynamic library 'FirebaseCppApp-9_4_0' because of 'Failed to open the requested dynamic library (OX06000000) dlerror() = dlopen failed: library "FirebaseCppApp-9_4_0" not found

### ISSUE THREAD

**Issue by DakshPoshiya** [firebase/firebase-unity-sdk#471]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version:2021.3.6
  * Firebase Unity SDK version: 9.4.0
  * Source you installed the SDK:  .UnityPackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Databse
  * Other Firebase Components in use: N/A
  * Additional SDKs you are using:Admob
  * Platform you are using the Unity editor on: Android
  * Platform you are targeting: Android
  * Scripting Runtime: Both (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
When i try to get data from firebase database in unity Editor it's works perfect But when I Build it for android then i can't not get Data from Databse.

**Comment by a-maurice** [comment]
This typically indicates that the Android libraries did not get resolved correctly.  In your project, under Plugins/Android you should have a bunch of aar files, importantly `com.google.firebase.firebase-app-unity-9.4.0.aar`  If those files aren't there, or just to validate, from the taskbar you can go Assets > External Dependency Manager > Android Resolver > Force Resolve.
