### ISSUE TITLE
[Question] Question about authentication token data stored on device in plain text 

### ISSUE THREAD

**Issue by andygruening** [firebase/firebase-unity-sdk#473]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: Dynamic Links (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the question here:

Hey there!
We are using Firebase Analytics for our mobile App and we recently ran a penetration test for security measurements.
The Pen Test identified, that authentication token data is stored on the device in plain text, which is accessible if the device is rooted.
We are not asking for a fix, but we have to evaluate whether or not this can be a potential security issue for our app.

The data has the following json structure:
`{"Fid":string, "Status": number, "AuthToken": string, "RefreshToken": string, "TokenCreationEpochInSecs": timestamp, "ExpiresInSecs": number}`

This data was found in the following directory on device:
`/data/data/<bundle-id>/files`

Was that topic already discussed at some point? And if so, what was the outcome of that? 
What can be done with that token?

Thanks a lot in advance!

**Comment by paulinon** [comment]
Hi @andygruening,

Thanks for raising this. It appears that the `AuthToken` you're retrieving is an [installation auth token](https://firebase.google.com/docs/projects/manage-installations#retrieve-fis-token) from a [PersistedInstallation](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java) file. This token is a short-lived bearer token in JWT format containing information related to your Firebase project and app, and it is used for several Firebase services like FCM or Remote Config. You may learn more about Firebase Installations in our documentation [here](https://firebase.google.com/docs/projects/manage-installations#retrieve-fis-token).

That said, I'll be closing this for now. Let me know if you have any other questions.

**Comment by andygruening** [comment]
Hey @paulinon 
thanks for giving me more details on this. It definitely cleared my questions on what the token is used for.
But I have another question that I cannot find an answer for in the documentations that you mentioned.

Can you tell more about what exactly can be done, if a user has access to this token? For example, when we are currently using Firebase Analytics, is the user theoretically authorized to send custom events to Firebase?

**Comment by paulinon** [comment]
Hi @andygruening,

A leaked auth token can be abused to impersonate a Firebase installation communicating with Firebase services or access remote configurations of specific Firebase installations. Take note that remote configurations are app configurations that are assigned to audiences of an app, not to individual installations. Leaked auth tokens can't be abused to receive/send FCM notifications or view Firebase Analytics events, so it seems that your example isn't possible.
