### ISSUE TITLE
[Question] None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (= 9.6.0)`.

### ISSUE THREAD

**Issue by xinatcg** [firebase/firebase-unity-sdk#482]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3
  * Firebase Unity SDK version: 9.6.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: core (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the question here:

iOS build error,   checked .cocopod folder, seem like the spec has the firebase version

```
OS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    Firebase/Analytics (= 9.6.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (= 9.6.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by xinatcg** [comment]
the pod should exist and downloaded

https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/9.6.0/Firebase.podspec.json

**Comment by xinatcg** [comment]
9.4.0 work, strange

**Comment by paulinon** [comment]
Hi @xinatcg,

Thanks for reporting this issue. Is there a `Podfile` generated after attempting to build the project? If so, could you share it with me? I'm guessing that this issue is caused by a version mismatch. 

Could you also provide the complete steps you performed before facing the issue? You may provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation as this could be used as a baseline for troubleshooting.

**Comment by xinatcg** [comment]
> Hi @xinatcg,
> 
> Thanks for reporting this issue. Is there a `Podfile` generated after attempting to build the project? If so, could you share it with me? I'm guessing that this issue is caused by a version mismatch.
> 
> Could you also provide the complete steps you performed before facing the issue? You may provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation as this could be used as a baseline for troubleshooting.

thanks for your reply, I find the issue, for some reason, one of package files did not upgrade to latest (Function) which is till 8.9.0, but pod fild update to 9.6.0. very strange, not sure why it happen. i upgrade the Function to same 9.6.0, then works.  

When I tested 9.4.0 upgrade all packages again, that's the reason why it works.
