### ISSUE TITLE
[Question] How to turn off Firebase, GPGS, and ADmob logs?

### ISSUE THREAD

**Issue by ant5033** [firebase/firebase-unity-sdk#490]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____ 9.6.0
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

<img width="803" alt="111" src="https://user-images.githubusercontent.com/80405495/196098934-237325aa-802e-4f20-a11d-79ac19a3efc7.png">

These logs have occurred since Unity Google Packages were imported

Can you tell me how to turn off these logs?

Clicking log does not link to IDE

**Comment by paulinon** [comment]
Hi @ant5033,

I can relay this to the engineers so that we can gather input related to your question. For now, let's see if this is reproducible. Are there any additional steps you've taken after importing the packages? Also, it would be great if you provide the other details indicated in the issue template so that we can analyze what's causing this behavior.

**Comment by ant5033** [comment]
Unity editor version: 2021.3.1f1
Firebase Unity SDK version:  9.6.0
Source you installed the SDK : unity package
Problematic Firebase Component: FireBase All
Other Firebase Components in use: _____ (Auth, Database, etc.)
Additional SDKs you are using: google SDK(GPGS + AdMob + ExternalDependencyManager + review + assetdelivery )
Platform you are using the Unity editor on: Windows
Platform you are targeting:Android
Scripting Runtime:  IL2CPP
Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

##

No additional work was done after the package was imported .
This may be a Unity-related setting, but I ask for your help!
