### ISSUE TITLE
[Bug] Firebase Crashlytics v9.6.0 Not Working on iOS

### ISSUE THREAD

**Issue by CodeMasterYi** [firebase/firebase-unity-sdk#493]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2018.4.36f1
  * Firebase Unity SDK version: 9.6.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook,AdMob,Adjust,AppLovin Max (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac, Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS,Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

we upgrade Firebase SDK from v9.4.0 to v9.6.0. old version's files are deleted via EDM4U.
we are sure we upgrade it in a right way.
but we find no crash or non-fatal issues on the firebase console even we explicitly throw an exception.
We are sure that it works well on v9.4.0.
BTW, 9.6.0 works well on Android.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @CodeMasterYi,

Based on the information you provided, I'm getting that crashes or non-fatal issues aren't being reported since upgrading to version 9.6.0 of the SDK, and this occurs on iOS builds. [Version 10.0.0](https://firebase.google.com/support/release-notes/unity#version_1000_-_october_17_2022) has been released recently. Could you confirm if this version makes a difference? This is to make sure that you have the latest bug fixes and updates, but take note that the minimum supported editor version for this is now Unity 2019.

**Comment by CodeMasterYi** [comment]
What we find in log!
```
09:35:25.879395+0800	destiny	[Firebase/Crashlytics] Version 9.6.0
09:35:27.891112+0800	destiny	9.6.0 - [FirebaseCrashlytics][I-CLS000000] Warning: NSUncaughtExceptionHandler is 'unknown' in '/private/var/containers/Bundle/Application/552D786E-3ED2-4A81-95D1-F752780A57C5/destiny.app/destiny'
09:35:59.507600+0800	destiny	[Firebase/Crashlytics] Version 9.6.0
09:36:01.507874+0800	destiny	9.6.0 - [FirebaseCrashlytics][I-CLS000000] Warning: NSUncaughtExceptionHandler is 'FBSDKExceptionHandler' in '/private/var/containers/Bundle/Application/552D786E-3ED2-4A81-95D1-F752780A57C5/destiny.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics'
```
Sometimes NSUncaughtExceptionHandler is 'unknown' and sometimes it is `FBSDKExceptionHandler`.
I wonder if the firebase exception handler registration has a timeline issue in v9.6.0?

**Comment by CodeMasterYi** [comment]
Sorry, I cannot provide an example for you.
What if I open another View(For example debug integration view in ApplovinMax SDK) during initialization?

**Comment by CodeMasterYi** [comment]
My iPhone OS version is 14.6
