### ISSUE TITLE
[Bug] Regardless of whether the Explode AARs is checked or not, it will export aar

### ISSUE THREAD

**Issue by xxhong** [firebase/firebase-unity-sdk#501]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: __2021.3.2f1__
  * Firebase Unity SDK version: _9.1.0、9.6.0、10.0.0____
  * Source you installed the SDK: __unitypackage___ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: __All___ (Auth, Database, etc.)
  * Other Firebase Components in use: __All___ (Auth, Database, etc.)
  * Additional SDKs you are using: __Facebook___ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __Mac___ (Mac, Windows, or Linux)
  * Platform you are targeting: __Android___ (iOS, Android, and/or desktop)
  * Scripting Runtime: __Mono and IL2CPP___ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: __https://github.com/firebase/firebase-unity-sdk/releases/tag/___

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
Regardless of whether the Explode AARs is checked or not, it will export aar. 
this is configs 
![image](https://user-images.githubusercontent.com/2645876/197505454-67b0994c-fe2b-4617-b6c6-7fc4aa38393b.png)

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
**100%**

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
1.open the setting,![image](https://user-images.githubusercontent.com/2645876/197505828-1ceda5ae-e3f8-4e82-837d-d07380a9025e.png)
2.Use the above configuration
3.save
4.resolve
![image](https://user-images.githubusercontent.com/2645876/197505982-9318063d-7758-4c31-8a85-2d250c03c203.png)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @xxhong,

Could you give the expected and actual output of the steps you listed? This may be in a form of debug logs, screenshots of generated files, etc.
