### ISSUE TITLE
DllNotFoundException: FirebaseCppApp-10_0_1 assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by smumair06** [firebase/firebase-unity-sdk#510]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.11 or 2021.3.2
  * Firebase Unity SDK version: 10.0.1
  * Source you installed the SDK: FirebaseDatabase.unitypackage
  * Problematic Firebase Component: Auth, Database
  * Other Firebase Components in use: None
  * Additional SDKs you are using: PlayFab and DOTween (No other native plugin)
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android/iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the: Website

### [REQUIRED] Please describe the issue here:

I have imported the database package and allowed Open Anyway from Mac's Preferences > Security. But, it still throws exception of DllNotFound as soon as I try to play inside UnityEditor.
This exception is thrown when I try to access the code inside the sdk, even only if I try to get the Reference of the database.

**My System Specs: Macbook Pro (13-inch), OS: 10.15.6**

I have tested the same codebase with **same Unity version on Macbook Pro (15-inch 2018), OS: Montery** as well as on **Unity version 2021.3.4f1 on iMac (Retina 5K, 27-inch, 2020), OS: 12.6** both intel processors and it **worked successfully** on those systems.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
var db = FirebaseDatabase.DefaultInstance
```

Screenshot is attached of my System Preferences as well:
![Screenshot 2022-10-31 at 2 39 38 PM](https://user-images.githubusercontent.com/17721181/198978121-bd45bb2b-17d3-410b-bc69-cd8627dc5694.png)

**Comment by a-maurice** [comment]
Hi @smumair06 

Just for clarification, you have been able to get it working on some machines (both are intel processors), but having trouble with a third machine.  Is the third machine silicon?  For the Unity version installed, is it the intel or silicon version?

The DllNotFound exception can be caused a bunch of different issues, which can make it a bit annoying.  Assuming it isn't the security issue, the other usual suspect is the CPU.  In the Unity editor, if you look under Firebase/Plugins/x86_64, there should be a file FirebaseCppApp-10_0_1.bundle.  Is it correctly being included for the editor, and using 'Any CPU'?

**Comment by smumair06** [comment]
yes, the third machine is also with intel processor.
Yes, I have FirebaseCppApp-10_0_1.bundle in x86_64 folder.

![Screenshot 2022-11-01 at 11 29 04 AM](https://user-images.githubusercontent.com/17721181/199172730-3da980aa-431b-4f62-9e3b-8d3c4455d535.png)

**Comment by smumair06** [comment]
I have tried with unity version 2021.3.4, the same version as on other macs, and it failed here too.
It seems that this version of firebase doesn't work on this OS.
But, I had tried some 9.x version of firebase as well. But, same result.
PS. Don't remember exact version of 9, but I guess it was latest from 9.x series.

**Comment by smumair06** [comment]
Any News?

**Comment by Awais6** [comment]
Same error here on windows 11

**Comment by DellaBitta** [comment]
Hi @smumair06,

There seem to be redundant versions of files in your Plugins/x86_64 directory. For instance, there are three versions of `FirebaseCppApp`, `FirebaseCppAuth` and `FirebaseCppDatabase`. Could you try deleting the duplicates, and/or deleting your plugins directory and reimporting the Firebase SDK?

Does this only happen in your project or using an quickstart project on that machine, too?
Does the problem occur if you build for a mobile target?

Thanks!

**Comment by DellaBitta** [comment]
Hi @Awais6,

Could you describe more about your project setup and which version of Unity and the Firebase SDK you're using?

Thanks.

**Comment by Awais6** [comment]
Hi @DellaBitta 

I have resolved the issue by installing VC-Redistributable 2015-2022 from Microsoft.
Moreover, I am using firebase SDK 10.0.1, Unity 2021.1.28f1

Thanks,

**Comment by DellaBitta** [comment]
@Awais6,

Great news! Thanks for the update.

**Comment by smumair06** [comment]
These all 3 files are present in your plugin files. Actually, they differ in extensions. One is .bundle, 2nd is .dll and I don't remember 3rd one. Will confirm you as soon as I'll access my system.

Also, I have tried deleting the plugins folder as well as complete package and reimporting it multiple times but result remains the same.

**Comment by mgrogin** [comment]
I have the same issue 
macOS BigSur version 11.7.1
Unity 2020.3.41f1
DllNotFoundException: FirebaseCppApp-10_0_1
Firebase installed with tgz files
In Mac "Security & Privacy Unity" => Privacy => "Files and Folders" :

- Unity has access to Downloads Folder
- Unity Hub has access to Removable Volumes, Network Volumes, Download Folder, Documents Folder, Desktop Folder

Im wondering if it's similar to the problem that was mentioned about "Unity Hub is missing some metadata in its authoring for automation to work properly on macOS Big Sur." here https://developercommunity.visualstudio.com/t/can-not-open-cs-files-from-inside-unity-202112f1/1395078 

<img width="185" alt="image" src="https://user-images.githubusercontent.com/7486227/201894613-e5cbab62-13f6-4630-a851-47fc80166796.png">
<img width="224" alt="image" src="https://user-images.githubusercontent.com/7486227/201894690-cec3e945-1682-40aa-b3b5-a856460e4dbe.png">

**Comment by smumair06** [comment]
> Hi @smumair06,
> 
> There seem to be redundant versions of files in your Plugins/x86_64 directory. For instance, there are three versions of `FirebaseCppApp`, `FirebaseCppAuth` and `FirebaseCppDatabase`. Could you try deleting the duplicates, and/or deleting your plugins directory and reimporting the Firebase SDK?
> 
> Does this only happen in your project or using an quickstart project on that machine, too? Does the problem occur if you build for a mobile target?
> 
> Thanks!

Ok, I have tested on android build and it runs successfully on the device.
This issue occurs only on editor and regarding duplicate files, actually all these files come with your package. So, if there is any file, I need to delete, can you guide me which one is that?

**Comment by megavoid** [comment]
This issue could be caused by macOS still having the bundle in quarantine. You can try to delete the quarantine flag manually.
Example in macOS Terminal with Unity project root as working directory:

`xattr -d com.apple.quarantine Assets/Firebase/Plugins/x86_64/FirebaseCppApp-10_1_0.bundle`

**Comment by smumair06** [comment]
> 

ok, have executed this command and then opening and playing the app, but it gave me exactly same results.

**Comment by mgrogin** [comment]
> xattr -d com.apple.quarantine Assets/Firebase/Plugins/x86_64/FirebaseCppApp-10_0_1.bundle

For me it said : No such xattr: com.apple.quarantine

**Comment by GabrielRosenberg** [comment]
I have the same problem. Also tried executing the command but got the same result as the answer above.

**Comment by javi-mesa** [comment]
I was having this same issue. I upgraded from macOS Big Sur to macOS Monterey and the error went away completely. Hope that helps.

**Comment by mgrogin** [comment]
> I was having this same issue. I upgraded from macOS Big Sur to macOS Monterey and the error went away completely. Hope that helps.

I'm not able to upgrade to Monterey

**Comment by DellaBitta** [comment]
Hi @mgrogin,

We haven't had any reports that our metafiles aren't being honored by Unity, other than maybe your report. It seems that the link you posted is for a different Unity version, though.

Since this seems to be solved by most users working around the macOS quarantine I'd still like to explore that route with you.Can you confirm what happens on a fresh project with the latest version of the Firebase Unity SDK release?

**Comment by mgrogin** [comment]
> Hi @mgrogin,
> 
> We haven't had any reports that our metafiles aren't being honored by Unity, other than maybe your report. It seems that the link you posted is for a different Unity version, though.
> 
> Since this seems to be solved by most users working around the macOS quarantine I'd still like to explore that route with you.
> 
> Can you try running the quarantine flag delete operation as sudo?
> 
> ```
> sudo xattr -d com.apple.quarantine Assets/Firebase/Plugins/x86_64/FirebaseCppApp-10_0_1.bundle
> ```
> 
> If that doesn't work, could you confirm what happens on a fresh project with the latest version of the Firebase Unity SDK release? Updating the Firebase SDK version will cause macOS to identify it as a different file and go through the quarantine process anew. Do you see the quarantine pop up on the new version of the Firebase SDK?

Hi @DellaBitta ,
No quarantine pop up.
Here's the flow of what I did:
I ran the project and got this exception:
```
DllNotFoundException: FirebaseCppApp-10_1_1
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3916)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3936)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4646)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:1897)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Messaging.FirebaseMessaging+Listener..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/messaging/swig/Firebase.Messaging_fixed.cs:1097)
Firebase.Messaging.FirebaseMessaging+Listener.Create () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/messaging/swig/Firebase.Messaging_fixed.cs:1106)
Firebase.Messaging.FirebaseMessaging..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/messaging/swig/Firebase.Messaging_fixed.cs:1208)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.Messaging.FirebaseMessaging' threw an exception.
```

Then I ran this command:
`sudo xattr -d com.apple.quarantine Library/PackageCache/com.google.firebase.app@f8e53ebc48aa/Firebase/Plugins/x86_64/FirebaseCppApp-10_1_1.bundle`
and got this result:
```
xattr: Library/PackageCache/com.google.firebase.app@f8e53ebc48aa/Firebase/Plugins/x86_64/FirebaseCppApp-10_1_1.bundle: No such xattr: com.apple.quarantine
```

I updated my manifest json from this:
  "com.google.external-dependency-manager": "file:../GooglePackages/com.google.external-dependency-manager-1.2.174.tgz",
```
    "com.google.firebase.analytics": "file:../GooglePackages/com.google.firebase.analytics-10.1.1.tgz",
    "com.google.firebase.app": "file:../GooglePackages/com.google.firebase.app-10.1.1.tgz",
    "com.google.firebase.auth": "file:../GooglePackages/com.google.firebase.auth-10.1.1.tgz",
    "com.google.firebase.crashlytics": "file:../GooglePackages/com.google.firebase.crashlytics-10.1.1.tgz",
    "com.google.firebase.database": "file:../GooglePackages/com.google.firebase.database-10.1.1.tgz",
    "com.google.firebase.dynamic-links": "file:../GooglePackages/com.google.firebase.dynamic-links-10.1.1.tgz",
    "com.google.firebase.messaging": "file:../GooglePackages/com.google.firebase.messaging-10.1.1.tgz",
    "com.google.firebase.remote-config": "file:../GooglePackages/com.google.firebase.remote-config-10.1.1.tgz",
```
to this:

```
    "com.google.external-dependency-manager": "file:../GooglePackages/com.google.external-dependency-manager-1.2.175.tgz",
    "com.google.firebase.analytics": "file:../GooglePackages/com.google.firebase.analytics-10.3.0.tgz",
    "com.google.firebase.app": "file:../GooglePackages/com.google.firebase.app-10.3.0.tgz",
    "com.google.firebase.auth": "file:../GooglePackages/com.google.firebase.auth-10.3.0.tgz",
    "com.google.firebase.crashlytics": "file:../GooglePackages/com.google.firebase.crashlytics-10.3.0.tgz",
    "com.google.firebase.database": "file:../GooglePackages/com.google.firebase.database-10.3.0.tgz",
    "com.google.firebase.dynamic-links": "file:../GooglePackages/com.google.firebase.dynamic-links-10.3.0.tgz",
    "com.google.firebase.messaging": "file:../GooglePackages/com.google.firebase.messaging-10.3.0.tgz",
    "com.google.firebase.remote-config": "file:../GooglePackages/com.google.firebase.remote-config-10.3.0.tgz",
```
![image](https://user-images.githubusercontent.com/7486227/210720340-27ed3d86-ae26-49a0-8f8c-08bf1bea8fb1.png)

Got this exception:

```
DllNotFoundException: FirebaseCppApp-10_3_0
Firebase.Analytics.FirebaseAnalyticsPINVOKE+SWIGExceptionHelper..cctor () (at <add95d672d894b769d5e63df11e2a0ee>:0)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.Analytics.FirebaseAnalyticsPINVOKE..cctor () (at <add95d672d894b769d5e63df11e2a0ee>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.Analytics.FirebaseAnalyticsPINVOKE' threw an exception.
Firebase.Analytics.Parameter..ctor (System.String parameterName, System.Int64 parameterValue) (at <add95d672d894b769d5e63df11e2a0ee>:0)

```

<img width="683" alt="image" src="https://user-images.githubusercontent.com/7486227/210721281-1678a896-bfaf-4c05-828b-f3713ba92be6.png">

about mac:
![image](https://user-images.githubusercontent.com/7486227/210721494-9cc09c8f-c010-4efc-896b-22f88e2a6d4f.png)

Unity 2020.3.41f1

**Comment by DellaBitta** [comment]
Hi @mgrogin,

Interesting. Unfortunately I'm running out of things to try. Some suggestions, though.

You can list (-l) the xattr properties of a file by executing `xattr -l <filename>`. You can check the bundle file and ... the meta data file of the bundle (?) to see if there are any `com.apple.quarantine` on either / any of them. Or check the other bundle files in that directory in case there's some sort of cascading dependency.

You can remove quarantine by all files in a directory with the `-d` command by using the * wildcard at the end of the directory name. For instance, `xattr -d Library/PackageCache/com.google.firebase.app@f8e53ebc48aa/Firebase/Plugins/x86_64/*`Maybe one of the other bundles is still quarantined and is interfering with the resolution process.

Finally, if the behavior still persists, then it might be worth actually adding the files to the quarantine. If we know that they're quarantined and you don't see a pop up then either a) Unity isn't actually loading the files it should be loading, or b) there's something amiss with the quarantine system on your mac (?). Just a shot in the dark.

You can [follow the instructions here](https://apple.stackexchange.com/questions/256625/how-to-set-restore-the-com-apple-quarantine-attribute) on how to add the quarantine flag back onto a file. There are also steps to check if a file is effectively in the quarantine database.

**Comment by PrisedRabbit** [comment]
> > I was having this same issue. I upgraded from macOS Big Sur to macOS Monterey and the error went away completely. Hope that helps.
> 
> I'm not able to upgrade to Monterey

Try OpenCore Legacy
