### ISSUE TITLE
[FR] Add AppCheck

### ISSUE THREAD

**Issue by awiebe** [firebase/firebase-unity-sdk#511]
### Feature proposal

* Firebase Component: AppCheck

Right now there is no attestation services built-in to the Unity firebase, so my backend server cannot verify the origin of a request made to it.  Please add the Appcheck portion of firebase to the Unity packages.

**Comment by a-maurice** [comment]
Hi @awiebe 

Thanks for your interest in Firebase App Check.  We are currently working on adding it to the C++ SDK, and then the Unity SDK will follow afterwards.

**Comment by umutakmak** [comment]
Hi, do you know when App Check is going to be added? How is progress going? Big thank you for all your hard work by the way.

**Comment by steffen-roemer** [comment]
is there any update on this?

**Comment by FlynnMacfarlane92** [comment]
any update?

**Comment by a-maurice** [comment]
Hi all,

We are still working on it.  You can see the work done so far in https://github.com/firebase/firebase-cpp-sdk/tree/main/app_check.  Essentially we have to get it working in C++, and the Unity SDK will call into that when it is ready.  Unfortunately we can't commit to any specific time for when it will be done, but it is being worked on.

**Comment by a-maurice** [comment]
Hi all,

Firebase App Check with Unity has just launched as part of the [11.0.0 release](https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.0.0).  Thanks again for showing so much interest in it over the past year!
