### ISSUE TITLE
[Bug] App freze and crash, if LogEvent called before Firebase init

### ISSUE THREAD

**Issue by khrm355** [firebase/firebase-unity-sdk#513]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.12f1
  * Firebase Unity SDK version: 10.0.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Crashlytics
  * Additional SDKs you are using: Ironsource mediation with all network sdks. Google Play Services Billing, Inapp review. Onesignal
  * Platform you are using the Unity editor on: Mac Arm 64 (Rosetta)
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:
On app startup, I send App version and OS version with FirebaseAnalytics.LogEvent(), but it instantly freeze my app in editor or build.

I initilize Firebase with this code;

```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);

        var dependencyStatus = task.Result;
        if (dependencyStatus == Firebase.DependencyStatus.Available)
        {
            // Create and hold a reference to your FirebaseApp,
            // where app is a Firebase.FirebaseApp property of your application class.
            // Crashlytics will use the DefaultInstance, as well;
            // this ensures that Crashlytics is initialized.
            Firebase.FirebaseApp app = Firebase.FirebaseApp.DefaultInstance;
            
            // Set a flag here for indicating that your project is ready to use Firebase.
            IsInitialized = true;
        }
        else
        {
            UnityEngine.Debug.LogError(System.String.Format(
                "Could not resolve all Firebase dependencies: {0}",dependencyStatus));
            // Firebase Unity SDK is not safe to use here.
        }
    });
```

#### Steps to reproduce:

- Initialize firebase on awake
- Also call, log event on awake without waiting to initialize

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
- Most likely

What's the issue repro rate? (eg 100%, 1/5 etc)
- %100, until I remove the log event line.

What happened? How can we make the problem occur?

- Unity freezes on the line Log event function, has to force quit. It also happens on IOS build, app freezes and crash after some time.

**Comment by stanislavsmagin** [comment]
I have the same problem with 10.0.1 and Unity 2021.3.11f1

**Comment by a-maurice** [comment]
I haven't had any luck reproducing this on my end.  Can I ask why you need to LogEvent before the initialization, and can't wait until afterwards?  It is definitely recommended you initialize before doing any of the other calls, but it shouldn't freeze things.

Something you can try is adding:
```
Firebase.App.LogLevel = Firebase.LogLevel.Debug;
```
before any of the other calls, which will make it log more what is happening, which might give some insight as to the problem.

**Comment by khrm355** [comment]
@a-maurice I fixed my issue with creating a callback under ContinueWith(task =>. 
Well let me explain my usage, I call initialize firebase at the beginning. After the initialize function, I also call log.event to send if the app or os is updated. 
I wonder if it's normal behavior to freeze and crash the whole game if Firebase isn't initialized somehow. Isn't that should be queue that log? event until firebase initializes? 

I had to downgrade my firebase SDKs to 9.6.0 as the 10.0.1 package is not compatible with Ironsource adapters, I will reproduce this in a new project and share it here.

**Comment by a-maurice** [comment]
It definitely shouldn't be freezing or anything, which is the odd part.  Especially in editor, where Analytics doesn't reach out to the backend at all.  If you do have anything you can share that reproduces this, or any logs from the freeze, that'd be great.  Especially if it is in the editor, the Unity editor logs might have some hints as to what the problem is.
