### ISSUE TITLE
[Bug] isEmailVerified is always `false` on new app session even after email was verified

### ISSUE THREAD

**Issue by novavision** [firebase/firebase-unity-sdk#530]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.11f1
  * Firebase Unity SDK version: 10.0.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Database
  * Additional SDKs you are using: -----
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source fr
om this repo: _____

### [REQUIRED] Please describe the issue here:

Cashed FirebaseUser isEmailVerified property is not correct on app start. Seems like that value is not updated properly after email verified and always reset to `false` on new app session.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
I have a email authentication in the app with email verification. Everything is simple:
1. User signed up
2. I request to verify the email
3. User is able to click "I've verified" button withing same session OR he will be requested to input email credentials in the next session
4. Using `ReauthenticateAsync(credential)` I receive "updated" FirebaseUser data where I see that email is verified.
5. However on new session just after dependencies check FirebaseUser.isEmailVerifdied is `false` again.  Running `FirebaseManager.AuthInstance.CurrentUser.ReloadAsync()` updates that property to actual `true`

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Actually the code I used all taken from GetStarted Untiy web page. Nothing added. Seems that is just an internal firebase sdk issue

**Comment by paulinon** [comment]
Hi @novavision,

Thanks for reporting this. I notice that you've used the `ReloadAsync()` function which refreshes the data of the current user including email verification. It's recommended that you keep this in your implementation.

That said, I'll be closing this for now. Let me know if an issue arises.
