### ISSUE TITLE
[Bug] Could not find a working python interpreter on Mac OS Ventura. 

### ISSUE THREAD

**Issue by dev-deg** [firebase/firebase-unity-sdk#534]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021 / 2022
  * Firebase Unity SDK version: 10
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: All (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Any (iOS, Android, and/or desktop)
  * Scripting Runtime: C# (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

This error re-surfaced and is making Firebase unusable for development:

**Could not find a working python interpreter. Please make sure one of the following is in your PATH: python3 python3.8 python3.7 python2.7 python2 python**

Following this, and **stdin error** will appear in the console, preventing Unity Play mode from running.

Unable to use Firebase SDK in any Unity version on Mac Silicon 13.0.1.

#### Steps to reproduce:

1. Create Unity Project

2. Include google-services

3. Import a Firebase SDK unity package.

<img width="914" alt="Screenshot 2022-11-16 at 18 15 08" src="https://user-images.githubusercontent.com/90032186/202248377-92967398-8bba-416c-b4dd-4595911095ff.png">

**Comment by a-maurice** [comment]
Hi @dev-deg 

It seems like some versions of Mac OS, like Ventura, may not start with python installed.  Based on some documentation though, it should be when you set up Xcode command line tools, which you should be able to do by running `xcode-select --install` from the command line.

After python is set up, you can run `which python3` or `which python`, which should give you the path to it.

**Comment by dev-deg** [comment]
Hi @a-maurice thank you for your kind reply.

The issue was when I updated to Mac OS Ventura, XCode CLI tools where somehow uninstalled. Running xcode-select --install fixed the issue.

I had python 3 installed and it was done so using homebrew as you can see from the output below:

which python3
/opt/homebrew/bin/python3

which python
python not found

Thank you very much for your help and support.

Kind regards,
Dave
