### ISSUE TITLE
[Bug] iOS Build failed 10.1.1 & 10.1.0 with FirebaseAnalytics(FIRAEvent.o) does not contain bitcode 

### ISSUE THREAD

**Issue by GAGOSIAN84** [firebase/firebase-unity-sdk#547]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.14f1 Apple silicon
  * Firebase Unity SDK version: 10.1.1
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: analytics (Auth, Database, etc.)
  * Other Firebase Components in use: none (Auth, Database, etc.)
  * Additional SDKs you are using: none, blank project only with analytics (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: M1 Mac 12.3 (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-build
  * Xcode 13.4.1
  * 

### [REQUIRED] Please describe the issue here:

After building from Unity then running on Xcode produces an error. 

Showing All Messages
'/Users/gagosian/Library/Developer/Xcode/DerivedData/Unity-iPhone-habdkfhyiotdaegrspsjdrimagxw/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAEvent.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/gagosian/Library/Developer/Xcode/DerivedData/Unity-iPhone-habdkfhyiotdaegrspsjdrimagxw/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics' for architecture arm64

#### Steps to reproduce:

Create 3D empty project.
Import analytics prebuilt unitypackage 10.1.1 (latest).
Import json, plist file
In the sample scene add FirebaseInit.cs script
Build iOS project.
Open Xcode with xcworkspace
Run with test device.
Build fails with messages.
FirebaseAnalytics(FIRAEvent.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

Running on Xcode works with 9.6.0, 10.0.0, 10.0.1 but fails with 10.1.1 and 10.1.0

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
FirebaseInit.cs
using Firebase;
using Firebase.Analytics;
using UnityEngine;

public class FirebaseInit : MonoBehaviour
{
    void Start()
    {
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
        });
    }
}
```

**Comment by paulinon** [comment]
Hi @GAGOSIAN84,

Thanks for reporting this. Startiing version 10.1.0, bitcode inclusion is the SDK is discontinued as seen [here](https://github.com/firebase/firebase-ios-sdk/issues/10372). For you to use later versions of the SDK, it's recommended that you make use of Xcode 14 or higher.

That being said, I'll be closing this for now. Let me know if an issue arises.
