### ISSUE TITLE
[Bug] Crash during Run or Stop Unity editor

### ISSUE THREAD

**Issue by Maskusa** [firebase/firebase-unity-sdk#561]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.12f1
  * Firebase Unity SDK version: 10.1.1 or 10.2.0 
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: FirebaseAnalytics, FirebaseCrashlytics, FirebaseDatabase
  * Additional SDKs you are using: AdMob, YandexMobile
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono, and IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: This repo

### [REQUIRED] Please describe the issue here:

While working in the Uniny editor, Unity crashes randomly when starting or stopping a project.
Events happen very often.

**firebase_unity_sdk_10.1.1**
**Log and Dump:** https://drive.google.com/drive/folders/1Ucz_9nZPJzF-BRdTjwauyEV_nxInDZ-u?usp=sharing 
```
========== OUTPUTTING STACK TRACE ==================

0x00007FFCC34D1219 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34D257B (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34CE401 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34CEFD0 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34CFC39 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34CFF29 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34CC763 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC34BF221 (FirebaseCppApp-10_1_1) uWS::HttpSocket<0>::upgrade
0x00007FFCC331D414 (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC33073C7 (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC32EB7FF (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC32EBF8B (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC32E4B89 (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC32DA781 (FirebaseCppApp-10_1_1) uS::Node::getLoop
0x00007FFCC3292964 (FirebaseCppApp-10_1_1) uS::Socket::freeMessage
0x00007FFCC329BEFF (FirebaseCppApp-10_1_1) uS::Socket::freeMessage
0x00007FFD635A0E72 (ucrtbase) beginthreadex
0x00007FFD65847BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFD65A8CED1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

**or**

**firebase_unity_sdk_10.2.0**
**Log and Dump:** https://drive.google.com/drive/folders/1qMX0iR3IXKz0_Ftu4eknTNBUtGcm7y7l?usp=sharing
```
========== OUTPUTTING STACK TRACE ==================

0x00007FFFB8291209 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB829256B (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828E3F1 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828EFC0 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828FC29 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828FF19 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828C753 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB827F211 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB80DD414 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80C73C7 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80AB7FF (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80ABF8B (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80A4B89 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB809A781 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB8052964 (FirebaseCppApp-10_2_0) uS::Socket::freeMessage
0x00007FFFB805BEFF (FirebaseCppApp-10_2_0) uS::Socket::freeMessage
0x00007FF82A0B0E72 (ucrtbase) beginthreadex
0x00007FF82B167BD4 (KERNEL32) BaseThreadInitThunk
0x00007FF82C34CED1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========


```

#### Steps to reproduce:
Click Run in Unity or click Stop

**Comment by Maskusa** [comment]
I haven't checked yet if it's the Firebase SDK that's causing the crash, but I got a response from Unity support.
I sent them many reports of these failures. I was told that the problem is in the Firebase SDK and I should contact Firebase support and provide these details that are listed above:

```
========== OUTPUTTING STACK TRACE ==================

0x00007FFFB8291209 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB829256B (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828E3F1 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828EFC0 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828FC29 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828FF19 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB828C753 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB827F211 (FirebaseCppApp-10_2_0) uWS::HttpSocket<0>::upgrade
0x00007FFFB80DD414 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80C73C7 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80AB7FF (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80ABF8B (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB80A4B89 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB809A781 (FirebaseCppApp-10_2_0) uS::Node::getLoop
0x00007FFFB8052964 (FirebaseCppApp-10_2_0) uS::Socket::freeMessage
0x00007FFFB805BEFF (FirebaseCppApp-10_2_0) uS::Socket::freeMessage
0x00007FF82A0B0E72 (ucrtbase) beginthreadex
0x00007FF82B167BD4 (KERNEL32) BaseThreadInitThunk
0x00007FF82C34CED1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

I have one guess that I made based on the errors I get when I run some AAA games on PC. Some games won't launch for me due to error **"c000001d"** with description **"Invalid application path: "**

My PC username is set to **"______"**. I changed it wherever possible to **"Mask"**, but the username folder itself didn't change. I don't change it as it could break my whole system.
Here is my path to the Crashes folder: **C:/Users/______/AppData/Local/Temp/Unity/Editor/Crashes**

**Comment by paulinon** [comment]
Thanks for the additional input, @Maskusa. Could you verify if the issue persists with just the Firebase SDK in your implementation? If so, it would be great if you could provide the complete steps to replicate this behavior. Additionally, does disabling the VPN result in a different outcome other than crashes in the editor?

**Comment by Maskusa** [comment]
``At the moment I can't take the time to do further tests to discover more details.

I can say that I managed to solve the problem of the Fall of the Unity editor. I think that this solution is a crutch for me, but for your product it is a problem that needs to be solved.

I use the code to get data from FirebaseDatabase only when the user himself opens the desired section with statistics. Before that, I used the data update method:

 ```
void Start() 
{
UpdateCounters();
}
```

Now the version that works looks like this:
```    
void Show_WindowStat()
{     
        Crashlytics.Log("Show_WindowStat()");        
#if UNITY_ANDROID && !UNITY_EDITOR
        FirebaseDatabase.DefaultInstance.GoOnline();
        UpdateCounters();
#endif
}
 
void Close_WindowStat()
{     
        Crashlytics.Log("Close_WindowStat()");        
#if UNITY_ANDROID && !UNITY_EDITOR
        FirebaseDatabase.DefaultInstance.GoOffline();
#endif
}

DatabaseReference dB_reference;

void UpdateCounters()
{
    dB_reference = FirebaseDatabase.DefaultInstance.RootReference;

    dB_reference.Child("text_1").GetValueAsync().ContinueWithOnMainThread(task =>
    {
    if (task.IsFaulted)
    {
        // Debug.Log("Handle the error...");
    }
    else if (task.IsCompleted)
    {
        DataSnapshot snapshot = task.Result;
        Debug.Log("text_1: " + snapshot.Value);            
        }           
    });

    dB_reference.Child("text_2").GetValueAsync().ContinueWithOnMainThread(task =>
    {
    if (task.IsFaulted)
    {
        // Debug.Log("Handle the error...");
    }
    else if (task.IsCompleted)
    {
        DataSnapshot snapshot = task.Result;
        Debug.Log("text_2: " + snapshot.Value);            
        }           
    });
}
```

**Comment by paulinon** [comment]
Hi @Maskusa,

Could you provide the code you originally used that was crashing the editor? This way, we can identify whether this is an intended behavior or not. You may opt to upload a reproducible project (with personally identifiable information scrubbed) to a GitHub repository and add me as a collaborator.
