### ISSUE TITLE
[Bug] There are cases where storage cannot be canceled normally.

### ISSUE THREAD

**Issue by henry-dreamo** [firebase/firebase-unity-sdk#576]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.14f1
  * Firebase Unity SDK version: 10.1.1
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Storage (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Analytics, FireStore, Installation, CloudFunction (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac, Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android, iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

We are using Admob plugin together.
Rarely, there was a case where a crash occurred while exposing Admob ads while transferring to Firebase storage. (I think the crash shouldn't happen)
Anyway, to solve this problem, I canceled the upload task right before displaying AdMob ads using CancellationToken.

But the following error occurs.
![image](https://user-images.githubusercontent.com/88139855/207793637-2c21edee-d341-4939-bf1f-ca4671180bbf.png)

I suspect that there is no controller, but I am not sure, so I ask a question.
![image](https://user-images.githubusercontent.com/88139855/207792247-e3c1f7ac-6986-4b4d-ad26-b3c92139d954.png)

When I canceled, I also found the following log.
```
[Firebase]InnerException:System.AggregateException: One or more errors occurred. ("_p_firebase__storage__MonitorController" has been disposed)
```

It's on the Firestore side, but I wonder if it's not related to [pull request](https://github.com/firebase/firebase-android-sdk/pull/4257)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No

What's the issue repro rate? Rarely reproduced.
It happens when canceling while transferring to storage, and it seems to happen when canceling a little late.

#### Relevant Code:
```
        storageCts_ = new CancellationTokenSource();
        CancellationToken cToken = storageCts_.Token;
        
        var uploadRef = reference.Child(remotePath_);
        uploadRef.PutFileAsync(localPath_, metaData, progressMonitor, cToken).ContinueWithOnMainThread(HandleTask);
```

It is called as below just before viewing the ad.
```
        if (storageCts_ == null || storageCts_.IsCancellationRequested)
        {
            return;
        }

        storageCts_.Cancel();
```

**Comment by paulinon** [comment]
Hi @henry-dreamo,

Thanks for reporting this. I'd like to clarify a few things:

- [Version 10.3.0](https://firebase.google.com/support/release-notes/unity#version_1030_-_december_14_2022) of the SDK has been released recently. Could you try it out and see if the issue persists? 
- Could you also share the list of devices that also experience this behavior?
- Does the crash persist when you remove Admob from your implementation?

**Comment by henry-dreamo** [comment]
Hi @paulinon 

1. First of all, we will apply Firebase 10.3.0 in the next update.
2. It has not yet been released with that error popping up, so only the test device Galaxy S10e exists.
3. Admob removal requires a lot of resources, so it's hard to test right now.

**Comment by paulinon** [comment]
Thanks for the update, @henry-dreamo. While waiting for the results of your update, would it be possible for you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that we can identify what's causing this behavior?

**Comment by henry-dreamo** [comment]
I will make a reproducible sample project when I have time.
First of all, please note that I will attach the stack where this crash appears.

![image](https://user-images.githubusercontent.com/88139855/208352810-d7d56eb2-9edc-4a75-b05a-f519bfa6b214.png)

![image](https://user-images.githubusercontent.com/88139855/208352864-dc7d4086-adaf-48d5-a195-e8da8d287ec8.png)

![image](https://user-images.githubusercontent.com/88139855/208352913-760d69d9-7f50-4fd5-a8d0-e52ea8eb5a19.png)

**Comment by paulinon** [comment]
Thanks for sharing this information, @henry-dreamo. I look forward to the results of your update.

**Comment by henry-dreamo** [comment]
Yes. It will be updated to a new version tomorrow.
I'll check again after the update.
I'm leaving a comment so this issue doesn't close.

**Comment by henry-dreamo** [comment]
@paulinon 
We updated the app version by updating the Firebase version.
Exception handling was also performed to check if UploadTask was terminated.
The issue has been resolved.
