### ISSUE TITLE
Unity Firebase plugin Fails as (Error loading Python DLL: error code 14001)

### ISSUE THREAD

**Issue by seanlcnr** [firebase/firebase-unity-sdk#581]
* Unity editor version: 2021.3.13f1 (The problem exits ALL versions. Not related Unity editor)
  * Firebase Unity SDK version: 10.2.0 (The problem exists ALL versions after 6.7.0 
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: Remote Config, CM (Auth, Database, etc.)
  * Additional SDKs you are using:  (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows 7 (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

Hi,

I have explained the situation with details on Stackoverflow months ago. After many other updates and new versions of Firebase, I have already tried each of them to check if the problem is fixed. However, it is same even for the latest version.
Please check this link that I explain with details:

https://stackoverflow.com/questions/59357832/unity-firebase-plugin-fails-as-error-loading-python-dll-error-code-14001

**Comment by paulinon** [comment]
Hi @seanlcnr,

Just to check if you're up to date with the latest fixes and updates, could you try version 10.3.0 of the SDK and see if it makes a difference? Also, have any of the solutions in the thread you provided helped with your issue?

**Comment by seanlcnr** [comment]
Hi,

Firebase Unity 10.3.0 plugin (December 14, 2022)  has solved the problem
after 3 years. Even the Firebase Unity 10.2.0 plugin had the same problem.

Now we can run our games with the latest Firebase version.

Regards


paulinon ***@***.***>, 21 Ara 2022 Çar, 20:44 tarihinde şunu
yazdı:

**Comment by seanlcnr** [comment]
Hi,

Firebase Unity 10.3.0 plugin (December 14, 2022)  has solved the problem after 3 years. Even the Firebase Unity 10.2.0 plugin had the same problem.

Now we can run our games with the latest Firebase version.

Regards

**Comment by paulinon** [comment]
Glad to hear that the issue has been solved, @seanlcnr. That said, I'll be closing this for now. Let me know if an issue arises with this SDK version.
