### ISSUE TITLE
Dynamic Links Crash

### ISSUE THREAD

**Issue by toseefhaiderkhansugguu** [firebase/firebase-unity-sdk#585]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity version 2020.3.42f1
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: _____ .unity package)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ using fcebook and admob mediation plugins
  * Platform you are using the Unity editor on: _____Mac
  * Platform you are targeting: _____ Android
  * Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

i am facing dynamic link related crashes in production. 

#### Steps to reproduce:

and i am not able to reproduce it myself only seeing in play store android vitals

#### Relevant Code:
Here are the crashes title:
1-[libFirebaseCppApp-9_6_0.so] firebase::dynamic_links::GetLongLink(firebase::dynamic_links::DynamicLinkComponents const&)
2-[libFirebaseCppApp-9_6_0.so] firebase::dynamic_links::SetBuilderString(_JNIEnv*, _jobject*, char const*, _jmethodID*)

log can be shared via email

**Comment by toseefhaiderkhansugguu** [comment]
Here is the log files can you please have a look into them
[logs.zip](https://github.com/firebase/firebase-unity-sdk/files/10496499/logs.zip)

**Comment by DellaBitta** [comment]
Hi @toseefhaiderkhansugguu,

Unfortunately these logs tell us the methods that the crashes occur in but there's little else in the way of information about what happened leading up to the crash. I'd recommend opening up a [Firebase Support](https://firebase.google.com/support/troubleshooter/contact) ticket and an engineer can help collect more relevant information from your account.

Thanks!
