### ISSUE TITLE
[Bug] GoogleUtilities/GULURLSessionDataResponse.h' file not found Xcode 14.2

### ISSUE THREAD

**Issue by gputhread** [firebase/firebase-unity-sdk#587]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.16
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: UPM 
  * Problematic Firebase Component: Core 
  * Other Firebase Components in use: Auth, DB, Message, Crashlytics, Analytics 
  * Additional SDKs you are using: Facebook, Admob, Google Play Plugins, Google Play Games, Google Sign In
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS 16.2
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre Build UPM Tarball from Website.

#### Steps to reproduce:

What happened? How can we make the problem occur?
Build iOS from Windows with firebase 10.3.0, open it in mac os xcode and build.

**Comment by paulinon** [comment]
Hi @gputhread,

Does the issue persist when building directly from a macOS machine? Also, could you provide the generated `Podfile` after building?

**Comment by gputhread** [comment]
This happens with firebase unity sdk 10-10.3, 
it doesn't happen and build works with 9.6. 
I will share pod file in 10hrs.

**Comment by gputhread** [comment]
> Hi @gputhread,
> 
> Does the issue persist when building directly from a macOS machine? Also, could you provide the generated `Podfile` after building?

This happens with firebase unity sdk 10-10.3,
it doesn't happen and build works with 9.6.
I will share pod file in 10hrs.
