### ISSUE TITLE
Failed to fetch the following dependencies:

### ISSUE THREAD

**Issue by FunrikaTolga** [firebase/firebase-unity-sdk#588]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.16
  * Firebase Unity SDK version: 10.0.3 (LAST)
  * Source you installed the SDK: custom import (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: All Firebase Pack Imported (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook Applovin (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Failed to fetch the following dependencies:
com.google.firebase:firebase-analytics-unity:+
com.google.firebase:firebase-config-unity:+
com.google.firebase:firebase-database-unity:+
com.google.firebase:firebase-messaging-unity:+

1.2.175 Resolver (Last)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? - Github
What's the issue repro rate? (eg 100%, 1/5 etc) : %100

We imported the latest Firebase package into Unity.
We are getting this error during Resolve.
Displayed Libraries this way.
What is the solution to the problem?

This could be a description, log/console output, etc.

Resolution Failed.

Resolution failed

Failed to fetch the following dependencies:
com.google.firebase:firebase-analytics-unity:+
com.google.firebase:firebase-app-unity:+
com.google.firebase:firebase-auth-unity:+
com.google.firebase:firebase-config-unity:+
com.google.firebase:firebase-database-unity:+
com.google.firebase:firebase-messaging-unity:+

0x00007ff66dab69cd (Unity) StackWalker::GetCurrentCallstack
0x00007ff66dabd589 (Unity) StackWalker::ShowCallstack
0x00007ff66ea40943 (Unity) GetStacktrace
0x00007ff66f0e091d (Unity) DebugStringToFile
0x00007ff66cb7c262 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000026a41578303 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000026a4157802b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000026a41577db0 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x00000267ceda1345 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x000002697078cf93 (Mono JIT Code) Google.Logger:Log (string,Google.LogLevel)
0x0000026ad1126804 (Mono JIT Code) GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel)
0x00000267ceda348b (Mono JIT Code) GooglePlayServices.PlayServicesResolver/<ResolveUnsafe>c__AnonStorey9:<>m__0 (bool,string)
0x00000267ceda32b8 (Mono JIT Code) GooglePlayServices.PlayServicesResolver/<ResolveUnsafe>c__AnonStorey9:<>m__4 ()
0x000002697078951a (Mono JIT Code) Google.RunOnMainThread:ExecuteNext ()
0x0000026970789283 (Mono JIT Code) Google.RunOnMainThread:<ExecuteAllUnnested>m__1 ()
0x0000026970789176 (Mono JIT Code) Google.RunOnMainThread:RunAction (System.Action)
0x00000269707890eb (Mono JIT Code) Google.RunOnMainThread:ExecuteAllUnnested (bool)
0x0000026a12a19bbb (Mono JIT Code) Google.RunOnMainThread:PollOnUpdateUntilComplete (System.Func`1<bool>,bool)
0x0000026aff2bcdbb (Mono JIT Code) GooglePlayServices.PlayServicesResolver:LabelAssets (System.Collections.Generic.IEnumerable`1<string>,System.Action`1<System.Collections.Generic.HashSet`1<string>>,bool,System.Action`2<single, string>,bool,bool)
0x0000026aff2ca9ab (Mono JIT Code) GooglePlayServices.GradleResolver:ProcessAar (string)
0x0000026aff2c9213 (Mono JIT Code) GooglePlayServices.GradleResolver/<ProcessAars>c__AnonStoreyB:<>m__0 ()
0x000002697078a69d (Mono JIT Code) Google.RunOnMainThread:ExecutePollingJobs ()
0x000002697078929b (Mono JIT Code) Google.RunOnMainThread:<ExecuteAllUnnested>m__1 ()
0x0000026970789176 (Mono JIT Code) Google.RunOnMainThread:RunAction (System.Action)
0x00000269707890eb (Mono JIT Code) Google.RunOnMainThread:ExecuteAllUnnested (bool)........

=======================
Displayed Android Libraries

([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://repo.maven.apache.org/maven2" // Assets/Editor/AmplitudeDependencies.xml:5
        }
        maven {
            url "https://maven.google.com" // Assets/Editor/AmplitudeDependencies.xml:11, Assets/Editor/AmplitudeDependencies.xml:17
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/AuthDependencies.xml:20, Assets/Firebase/Editor/DatabaseDependencies.xml:22, Assets/Firebase/Editor/MessagingDependencies.xml:22, Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
        }
        maven {
            url (unityProjectPath + "/Assets/GooglePlayGames/Editor/m2repository") // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
        }
        maven {
            url "https://artifact.bytedance.com/repository/pangle" // Assets/MaxSdk/Mediation/ByteDance/Editor/Dependencies.xml:8
        }
        maven {
            url "https://android-sdk.is.com/" // Assets/MaxSdk/Mediation/IronSource/Editor/Dependencies.xml:8
        }
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" // Assets/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:8
        }
        maven {
            url "https://sdk.tapjoy.com/" // Assets/MaxSdk/Mediation/Tapjoy/Editor/Dependencies.xml:8
        }
        mavenLocal()
        mavenCentral()
    }
}

**Comment by DellaBitta** [comment]
Hi @FunrikaTolga,

The output like `com.google.firebase:firebase-analytics-unity:+` suggests that the Facebook and Applovin dependencies that you're bringing in might rely on different versions of the Analytics SDK. Moreover, it's odd that the `Displayed Android Libraries` output doesn't actually have any libraries in it.  Is this the complete log?

One thing to try is to enable Custom Gradle Main Template and Custom Gradle Properties and see if that clears things up, or produces different results at least.

Open `Player Settings` in the Build window. Under `Publish Settings` enable the check mark next to `Custom Main Gradle Template` and `Custom Gradle Properties Template`. Note the path because we might need to look into those files.

Close the `Project Settings` window.

Under `Assets` -> `External Dependency Manager` -> `Android Resolver` select `Force Resolve`.

If you're still having issues could you post your `mainTemplate.gradle` and `gradleTemplate.properties` files?

Thanks!

**Comment by FunrikaTolga** [comment]
Hello, this problem is solved.

The reason for the problem was that we did not do a clean import.
We deleted all EDM and Firebase related files from within the project.

And we re-imported.
This was enough to solve our problem.

Thanks

**Comment by paulinon** [comment]
Glad to hear the issue has been resolved, @FunrikaTolga. That said, I'll be closing this ticket. Let me know if an issue arises.
