### ISSUE TITLE
[Bug] APP Crash

### ISSUE THREAD

**Issue by xq48799220** [firebase/firebase-unity-sdk#594]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.38.f1c1
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: FirebaseAnalytics，FirebaseMessaging
  * Other Firebase Components in use: none
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

1.Crashes after executing  **“Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith“**
 ```
public void initFireBase()
        {
            NLogger.Logger.Log("initFireBase");
            CheckFirebase();
        }
public void CheckFirebase()
        {
#if !UNITY_EDITOR
            Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
                var dependencyStatus = task.Result;
                if (dependencyStatus == Firebase.DependencyStatus.Available)
                {
                    NLogger.Logger.Log("Firebase.Messaging.TokenReceivedEventArgs Firebase.DependencyStatus.Available");
                    NLogger.Logger.LogAndroid("Firebase.Messaging.TokenReceivedEventArgs Firebase.DependencyStatus.Available");
                    // Create and hold a reference to your FirebaseApp,
                    // where app is a Firebase.FirebaseApp property of your application class.
                    //   app = Firebase.FirebaseApp.DefaultInstance;

                    // Set a flag here to indicate whether Firebase is ready to use by your app.

                    Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
                    Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
                }
                else
                {
                    UnityEngine.Debug.LogError(System.String.Format(
                      "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                    // Firebase Unity SDK is not safe to use here.
                }
            });
#endif
        }
```

Crash Stack : 
2023-01-11 14:12:40.296 16018-22335/? E/AndroidRuntime: FATAL EXCEPTION: Thread-25
    Process: com.XXXXXXXXXXXX, PID: 16018
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.unity3d.player.ReflectionHelper$a.<init>(Unknown Source:17)
        at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:2)

2.
**Delete CheckFirebase(),
APP runs normally**

3.Android device operating system version ： Android 12

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Click on the APP Icon,
Wait for firebase to finish executing,
And then the APP crashes.
Probability of occurrence (6/10)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @xq48799220,

Could you provide the full sample code that's used so I could try to replicate this? It looks like the code you provided lacks the `OnTokenReceived` and `OnMessageReceived` events. A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be helpful as this could be used as a baseline for troubleshooting.

Additionally, could you confirm if the issue persists with just the Firebase SDK in your implementation? The crash stack you provided doesn't seem to have anything related to Firebase.

**Comment by xq48799220** [comment]
@paulinon 

I appended a screenshot of the error stack.
It crashed immediately after printing the log **Firebase.Messaging.TokenReceivedEventArgs Firebase.DependencyStatus.Available**.

![image](https://user-images.githubusercontent.com/13251180/212293035-81a83fbc-5186-4358-85ca-b2ff28f049ea.png)



According to the information I provided above, the APP works fine after I mask the initialization method(**CheckFirebase()**).

**Comment by paulinon** [comment]
Hi @xq48799220,

I understand that the cause of this issue leads to your `CheckFirebase()` function, but I still need more context from you in order to confirm this. That said, it would be great if you provide the information I asked for previously. If that's not possible, is there any way that this could be replicated in a blank project?
