### ISSUE TITLE
Click download 10.3.0 version, but get 10.2.0 instead.

### ISSUE THREAD

**Issue by haims-hblab** [firebase/firebase-unity-sdk#595]
In the page to download 10.3.0 version. 
https://github.com/firebase/firebase-unity-sdk/releases/tag/v10.3.0

At the text:
> Prebuilt versions of the libraries are available for download [here](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_10.2.0.zip).

You uploaded the wrong file at the **here** text.
I expected 10.3.0, but the **here** gives me 10.2.0.
https://github.com/firebase/firebase-unity-sdk/releases/tag/v10.3.0

**Comment by paulinon** [comment]
Hi @haims-hblab,

Thanks for bringing this to our attention. I am also seeing this behavior in the releases page. I'll be relaying this to the team so that this could be fixed. In the meantime, I'm leaving this as a bug.

**Comment by a-maurice** [comment]
Sorry about that, should be fixed now. Thanks for bringing it to our attention.
