### ISSUE TITLE
App Crash on iOS Device[Bug]  FirebaseDatabase -[_FSRRunLoopThread main] 

### ISSUE THREAD

**Issue by iremguner** [firebase/firebase-unity-sdk#596]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.2f1
  * Firebase Unity SDK version: 10.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Realtime Database
  * Other Firebase Components in use: Analytics, Auth, Crashlytics, Remote Config, Cloud Services, RTDB
  * Additional SDKs you are using: Facebook, Applovin , Adjust
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

Crashlytics reported a crash on iOS ( Version iOS 16) device. I couldn't see the exact code line producing this issue but  It seems to related with realtime database according to crash logs.  I guess it's related with writing data to the RTDB. 

Crash Stack: 

com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0xb48 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13008 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13248 mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x108c mach_msg + 24
4  CoreFoundation                 0x7ae00 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7c044 __CFRunLoopRun + 1232
6  CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
7  Foundation                     0x41818 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  **FirebaseDatabase               0x48b30 -[_FSRRunLoopThread main] + 216**
9  Foundation                     0x5ace8 __NSThread__start__ + 716
10 libsystem_pthread.dylib        0x16cc _pthread_start + 148
11 libsystem_pthread.dylib        0xba4 thread_start + 8

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 
I couldn't able to reproduce this issue again. The app is on testflight on closed beta ios and tested by many users. This crash is logged only once so far. 

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @iremguner,

In order to identify what's causing this, could you provide the full stack trace corresponding to the crash along with the code that utilizes Realtime Database in your implementation?

**Comment by iremguner** [comment]
Yes, of course! This code is my implementation of writing some player data to the db. "FirebaseManager.PersistDBreference " is the default database instance and persistency is enabled at the beginning of the application in the successful callback task of firebase initialization. 

`public void WriteLeaderBoardEntry(int level, UserInfo userInfo)
        {
            
            LeaderboardEntry entry = new LeaderboardEntry(userInfo, level);
            string jsonEntry = JsonUtility.ToJson(entry);

            if (userInfo != null && !string.IsNullOrEmpty(userInfo.UserID))
            {
                var entryDict = entry.ToDictionary();
                FirebaseManager.PersistDBreference.Child(AllScoreDataPath).Child(userInfo.UserID).SetValueAsync(entryDict).ContinueWithOnMainThread(task =>
                {
                    if (task.IsCompletedSuccessfully)
                    {
                        Debug.Log("Leaderboard is updated.");
                        AnalyticsManager.LeaderboardUpdated(level);
                    }
                    else if (task.Exception != null)
                    {
                        Debug.Log("Exception adding score: " + task.Exception);
                    }
                    else
                    {
                        Debug.LogWarning("Leaderboard update is failed.");
                    }
                });
}`
[com.Connectinno-Games.Collect-3D_issue_c5f8405b453e91734552d3713da19fb9_crash_session_5ca23e15646f45f6b7e19492c261eaa7_DNE_0_v2_stacktrace.txt](https://github.com/firebase/firebase-unity-sdk/files/10418695/com.Connectinno-Games.Collect-3D_issue_c5f8405b453e91734552d3713da19fb9_crash_session_5ca23e15646f45f6b7e19492c261eaa7_DNE_0_v2_stacktrace.txt)

**Comment by AlmostMatt** [comment]
Your sample code looks ok to me.

My understanding of the full stack trace is that it shows the status of all threads. One of the threads is running firebase database code, which makes sense since some operations can occur asynchronously, but it doesn't necessarily mean that this thread is causing the crash.

Since you only have one report of the crash and have not been able to reproduce it, I am going to treat this as a random failure and not a consistent issue.

Feel free to reopen this issue If this crash starts occurring more frequently or if you figure out how to reproduce the crash.
