### ISSUE TITLE
[Bug] Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by Okluckej** [firebase/firebase-unity-sdk#606]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.38f1
  * Firebase Unity SDK version: 10.1.0
  * Source you installed the SDK: FirebaseAnalytics.unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: none (Auth, Database, etc.)
  * Other Firebase Components in use: none (Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the issue here:

Current result: Submission to Apple triggers APNs warning ITMS-90078 even if FirebaseAppDelegateProxyEnabled NO in Info.plist

Expected result: Apple submission won't return warning ITMS-90078 when FirebaseAppDelegateProxyEnabled NO in Info.plist

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

It seems that the issue may be caused by libFirebaseCppAnalytics.a but can't tell for sure without source code.

#### Steps to reproduce:

Reproducing the issue

I have create small repro project just integrating FirebaseAnalytics.unitypackage. After submission to Apple I get ITMS-90078 warning
https://drive.google.com/file/d/1mROaeifJkH7--BNuxTcbzJByx-NeUEFu/view?usp=sharing

Firebase SDK Version
10.1.0

Xcode Version
14.1

Installation Method
CocoaPods

#### Relevant Code:

[Podfile.lock.txt](https://github.com/firebase/firebase-unity-sdk/files/10478420/Podfile.lock.txt)
[Log.txt](https://github.com/firebase/firebase-unity-sdk/files/10478438/Log.txt)

**Comment by paulinon** [comment]
Hi @Okluckej,

Thanks for reporting this issue. It appears that the behavior you're describing is similar to #375 which is still open. I recommend that you try updating your SDK to its latest version (10.3.0 as of writing) so that it contains the latest updates and fixes. You may report your findings to the aforementioned ticket.

That being said, I'll be closing this for now.
