### ISSUE TITLE
[Question] TokenAsync occur error

### ISSUE THREAD

**Issue by t4world** [firebase/firebase-unity-sdk#613]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2021.3.11.f1____
  * Firebase Unity SDK version: ___9.5.0__
  * Source you installed the SDK: __Unity Package Manager___ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: __Auth___ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: __Facebook___ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __Mac___ (Mac, Windows, or Linux)
  * Platform you are targeting: ___Android__ (iOS, Android, and/or desktop)
  * Scripting Runtime: _IL2CPP____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _website____

### [REQUIRED] Please describe the question here:
log content1:
System.AggregateException: One or more errors occurred. (An internal error has occurred. [ Failed to connect to securetoken.googleapis.com/142.250.191.74:443 ]) ---> Firebase.FirebaseException: An internal error has occurred. [ Failed to connect to securetoken.googleapis.com/142.250.191.74:443 ] --- End of inner exception stack trace --- ---> (Inner Exception #0) Firebase.FirebaseException: An internal error has occurred. [ Failed to connect to securetoken.googleapis.com/142.250.191.74:443 ]<---

log content2:
System.AggregateException: One or more errors occurred. (An internal error has occurred. [ unexpected end of stream on com.android.okhttp.Address@41dd675 ]) ---> Firebase.FirebaseException: An internal error has occurred. [ unexpected end of stream on com.android.okhttp.Address@41dd675 ] --- End of inner exception stack trace --- ---> (Inner Exception #0) Firebase.FirebaseException: An internal error has occurred. [ unexpected end of stream on com.android.okhttp.Address@41dd675 ]<---

error stack:
![image](https://user-images.githubusercontent.com/11564932/215378783-250d0c1e-89f5-4e8f-bccf-9525ffbd682e.png)

source code:
![image](https://user-images.githubusercontent.com/11564932/215378902-32879fc2-520f-45f7-a0ff-70cca8fcac93.png)

**Comment by paulinon** [comment]
Hi @t4world,

Thanks for reporting this. Could you verify if using the latest SDK version ([10.4.0](https://firebase.google.com/support/release-notes/unity#version_1040_-_january_26_2023) as of writing) makes any difference? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps to replicate the issue so that we can identify what's causing this behavior.

**Comment by jonsimantov** [comment]
Also, it would be helpful to know if this happens every time, or if you only see it happening occasionally. Based on the exceptions, it could be related to the device having connectivity issues.

**Comment by chkuang-g** [comment]
Hi @t4world 

Could you confirm if this is still an issue with later version of Firebase SDK?
