### ISSUE TITLE
[Bug] NewGlobalRef(void*) and other errors on Android

### ISSUE THREAD

**Issue by Awais6** [firebase/firebase-unity-sdk#614]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.16f1 LTS
  * Firebase Unity SDK version: 10.0.1
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ don't know (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Firestore, Crashylytics, Sentry (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Admob, Photon (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Prebuilt

### [REQUIRED] Please describe the issue here:

Please see the crashylytics stack traces

![image](https://user-images.githubusercontent.com/46025225/215444805-cedede57-9cc6-49c0-b42f-aea8e78829ff.png)

com.unity3d.player.ReflectionHelper$a.<init>
![image](https://user-images.githubusercontent.com/46025225/215444735-2854d255-25b8-4536-a934-61b85f8f98a1.png)

AndroidJNIBindingsHelpers::NewGlobalRef(void*)
![image](https://user-images.githubusercontent.com/46025225/215444573-b245c4c2-3058-41a5-b9c6-87ea58ac1a91.png)

libc.so error
![image](https://user-images.githubusercontent.com/46025225/215444345-7356ecea-68ad-42ac-89ff-1c75ea9809d8.png)

#### Relevant Code:

**Comment by dconeybe** [comment]
Thank you for reporting this issue. It is actually a known issue (https://github.com/firebase/firebase-unity-sdk/issues/569) and we are in the final stages of releasing a fix (https://github.com/firebase/firebase-cpp-sdk/pull/1176). There really is no solid workaround either (https://github.com/firebase/firebase-unity-sdk/issues/586#issuecomment-1371101988).

I'm going to close this issue as a duplicate. Please follow https://github.com/firebase/firebase-unity-sdk/issues/569 for updates.

**Comment by Awais6** [comment]
Thank you so much for your quick response, Is there any previous firebase SDK version in which this issue doesn't happen? so we can temporarily downgrade.

**Comment by dconeybe** [comment]
No. Unfortunately, this bug has _always_ been there but was only discovered/reported recently. There is no known workaround.

**Comment by Awais6** [comment]
Ok Thanks, waiting for the fix

**Comment by argzdev** [comment]
Hey folks, since this issue has already been fixed. I'll go ahead and close this as a duplicate. Thanks!

**Comment by dconeybe** [comment]
For posterity, here is the fix: https://github.com/firebase/firebase-cpp-sdk/pull/1364
