### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by MimoLopes** [firebase/firebase-unity-sdk#616]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.37f1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth.
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo:

### [REQUIRED] Please describe the question here:

I had the same problem that happened in this issue request (https://github.com/firebase/firebase-unity-sdk/issues/530) after following what was instructed, the problem persisted only on the Android device, but it was resolved in the Unity editor.

In my case i am updating the firebaseUser when the game is paused using the ReloadAsync method and after that i am updating the values in the database using the SetValueAsync method but value verifiedEmail on firebaseUser  is never changed.

**Comment by paulinon** [comment]
Hi @MimoLopes,

Thanks for reporting this issue. Could you verify if using the latest SDK version ([10.4.0](https://firebase.google.com/support/release-notes/unity#version_1040_-_january_26_2023) as of writing) makes any difference? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps to replicate the issue so that we can identify what's causing this behavior. Also, does the issue persist in other Android devices as well?

**Comment by DellaBitta** [comment]
Hi @MimoLopes,

The issue you linked refers to a the cached user in between sessions of the app. Is this what you're enountering, too?

Could you be more specific about the flow that you're using? Does the Emailed Verified boolean value every appear to be true? If so, when and when not.

Thanks!

**Comment by MimoLopes** [comment]
Sorry for being late, I'm trying to update the SDK version.

**Comment by MimoLopes** [comment]
The problem persists even with the SDK in version 10.4.0.

Steps to reproduce:

1 - Crate a account with Email to receve the verification Link.
2 - Change the screen to your email apk or brouser with the email site and click on the link to verify the account.
3 - Go back to the application screen.
3.1 - At this point the application execute the method for update the FirbeaseUser by unpausing the application (`OnApplicationPause(bool pauseStatus)
{
if(!pauseStatus)
{
ReloadFirebaseUser();
}
}`).
3.2 - The Debug Log shows dat the value of email verification is false

**Comment by MimoLopes** [comment]
Miss click.

**Comment by cynthiajoan** [comment]
Hi @MimoLopes, could you help providing the following info:

Can you share the code snippet that how you are using database
Can you verify the issue also exist only with auth.

**Comment by MimoLopes** [comment]
Here's the scenario from the start:

1 - The player register an account;
2 - He changes the screen to check the account confirmation email and confirm the account;
3 - He returns to the game window to receive the verification bonus;

At this point, everything works just as it should in the editor, but in an Android device, the email confirmation flag in firebaseUser is false.

At the code perspective, when the player returns to the game screen (OnApplicationPause), we reload the Firebase User (following the orientation in issue #530), and them call an event so another class can check in the firebase User if the email was confirmed. If so, it updates the database with the correct value for the verification flag. This is the point that works in the editor but doesn't work in Android. Afterwards, we have things happening by listening the emailVerification flag in database.

The code below was slightly changed to keep it safe, but the structure is the same as in the project.

```
//Firebase authenticator reloads the firebase user when the player change the screen back to the game

async void OnApplicationPause(bool pauseStatus)
{
	if (!pauseStatus && !UserPersistentDataBroadcaster.Instance.UserPersistentData.emailVerificationFlag)
	{
		await ReloadUser();
	}
}

private async Task ReloadUser()
{
	await firebaseUser.ReloadAsync();

	firebaseUser = firebaseAuth.CurrentUser;

	// Invokes an event informing that the user was reloaded
}


//This other class listens to the event that informs about the user being reloaded and start checking if the email was verified.
//If so, it updates the database verified email flag.

public void OnVerifyAuthMethods()
{
	if (AuthenticationManager.Instance.firebaseUser != null)
	{
		foreach (Firebase.Auth.IUserInfo item in AuthenticationManager.Instance.firebaseUser.ProviderData)
		{
			if (state == "password")
				if (AuthenticationManager.Instance.firebaseUser.IsEmailVerified && !emailVerificationFlag /* Check if the flag in the database is different from the flag in Authentication */)
				{
					// saves the verified flag as true into the database
				}
		}
	}
}


//Beforehand, another class is listening for changes in the verified email flag in the database.

public void CheckVerificationFlag()
{
	if (!_UserPersistentData.emailVerificationFlag)
	{
		StartListenValueChangedEvent(_idListeningValueChangedField, valueDataName, CheckFlagValueChanged);
	}

}

public string StartListenValueChangedEvent(string userId, string valueDataName, EventHandler<ValueChangedEventArgs> ValueChangedListener)
{
	userId = FirebaseAuth.DefaultInstance.CurrentUser.UserId;

	if (!userId.IsNullOrWhitespace())
	{
		databaseReference.Child("users").Child(userId).Child(valueDataName).ValueChanged += ValueChangedListener;
	}

	return userId;
}

private void CheckFlagValueChanged(object sender, ValueChangedEventArgs args)
{
	if (args.DatabaseError != null)
	{
		Debug.LogError(args.DatabaseError.Message);
		return;
	}

	bool emailVerificationFlag = Convert.ToBoolean(args.Snapshot.Value);

	if (emailVerificationFlag)
	{
		// StopListenValueChangedEvent;
	}
}
```

**Comment by MimoLopes** [comment]
Changing to `firebaseAuth.CurrentUser` fixed the issue, thanks for the help.

**Comment by DellaBitta** [comment]
Great to hear!
