### ISSUE TITLE
[Bug] Assembly 'Assets/ExternalDependencyManager/Editor/1.2.175/Google.IOSResolver.dll' will not be loaded due to errors

### ISSUE THREAD

**Issue by mgarbade** [firebase/firebase-unity-sdk#623]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.3f1
  * Firebase Unity SDK version: 10.4.0
  * Source you installed the SDK: unitypackage 
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: none
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Windows 10 Pro
  * Platform you are targeting: Android
  * Scripting Runtime: Mono
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) 

### [REQUIRED] Please describe the issue here:

I get error messages right after importing the SDK. Without even starting to use it. 

#### Steps to reproduce:

Import the Firebase Unity SDK into my Unity project. Then run the game in editor mode.

issue repro rate: 100%

This is the output in the Unity Console (without even using the Firebase storage)

> Assembly 'Assets/ExternalDependencyManager/Editor/1.2.175/Google.IOSResolver.dll' will not be loaded due to errors:
> Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
> Reference validation can be disabled in the Plugin Inspector.
> 
> Assembly 'Assets/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
> Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?
> Reference validation can be disabled in the Plugin Inspector.

**Comment by mgarbade** [comment]
Already [found](https://answers.unity.com/questions/1767241/unable-to-resolve-unityeditoriosextensionsxcode.html) the problem: I had to install iOS build support although I wasn't using iOS and working on Windows:

UnityHub -> Select Unity Editor -> right click -> Add Modules --> iOS build support

**Comment by paulinon** [comment]
Glad to know that you resolved the issue, @mgarbade. I'll be closing this ticket for now. Let me know if an issue arises so that this ticket can be reopened.

**Comment by theLunarTick** [comment]
Same issue. I will give a try.
