### ISSUE TITLE
[Question] Unity macos xcode with app sandbox problem

### ISSUE THREAD

**Issue by UgurEmre06** [firebase/firebase-unity-sdk#624]
### [REQUIRED] Please fill in the following fields:

  * **Unity editor version:** _2021.3.17f1 and 2021.3.15f1_
  * **Firebase Unity SDK version:** _10.4.0_
  * **Source you installed the SDK:** _.unitypackage_ 
  * **Problematic Firebase Component:** _Auth_ 
  * **Other Firebase Components in use:** _Firestore_ 
  * **Additional SDKs you are using:** -
  * **Platform you are using the Unity editor on:** _Mac (for mac build) and Windows (for win build)_
  * **Platform you are targeting:** _Macos and Windows (iOS, Android, and/or desktop)_
  * **Scripting Runtime:** _Mono (Mono, and/or IL2CPP)_
  * **Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo:** _website_

### [REQUIRED] **Please describe the question here:**

I built my Unity project with Firebase for both MacOS and Windows platforms. Both sides are working without any problems, but I want to sign my project on MacOS, so I need to add an app sandbox. After adding the app sandbox, my project crashes at the following line:

<img width="575" alt="Ekran_Resmi_2023-02-08_11 08 57" src="https://user-images.githubusercontent.com/80154841/217618719-480ee4eb-7498-496f-abc6-ad5259e5f297.png">

source file of this crash is "google-services-desktop.json and google-services.json" if i remove this file by xcode it doesn't crash but firebase is not working. 

<img width="309" alt="Ekran_Resmi_2023-02-08_11 10 24" src="https://user-images.githubusercontent.com/80154841/217618453-2eab335b-5612-4452-8607-00f2dade6b8c.png">
<img width="808" alt="Ekran_Resmi_2023-02-08_11 11 09" src="https://user-images.githubusercontent.com/80154841/217618437-ae664ff3-e7d9-4453-9256-0ecec8518de0.png">

<img width="992" alt="Ekran_Resmi_2023-02-08_11 09 25" src="https://user-images.githubusercontent.com/80154841/217618445-42f9d451-29ff-4f82-90ef-2b68cd8b2553.png">

**Comment by paulinon** [comment]
Hi @UgurEmre06,

Thanks for reporting this. Please note that Firebase Unity SDK desktop support is a beta feature, so this may be an ongoing issue or limitaion. 

That said, could you provide the complete steps you've taken before encountering this issue? I ended up with a different project heirarchy in my Xcode build compared to yours during my first attempt in reproducing this behavior. Have you also tried if a `GoogleService-Info.plist` rather than a `google-services.json` file in your implementation makes a difference?

**Comment by UgurEmre06** [comment]
I didn't intend to upload it to the App Store, which made the app sandbox optional for me. I found that the application can be signed without the app sandbox by using the DeveloperID. I solved the problem by turning off the app sandbox. Thank you for your answer.
