### ISSUE TITLE
Unity Editor on apple silicon with Firebaseplugin

### ISSUE THREAD

**Issue by Barokoli** [firebase/firebase-unity-sdk#63]
The Unity Editor is currently running on Rosetta. 
Unity has released some preview beta versions of the Unity Editor running natively.
I've tested these native versions but the Firebase Plugin does not work since it's referencing the DLLs not build for arm.
I am guessing the native libs for iOS should work?

Currently we can just continue working with the standard Unity version and Firebase Plugin. 
This is more a feature request and a heads-up if you haven't already got this on your roadmap until the official unity editor m1 versions are released.

**Comment by aroman** [comment]
+100, this is a huge deal as Unity’s apple silicon editor is quite stable and usable day to day, but is unusable without this landing. Unity does run under rosetta, but performance is severely limited. 

Now that Apple’s laptop line has dropped x86, offering Apple Silicon support is tablestakes. 

There’s a long thread of folks asking for this here:

 https://github.com/firebase/quickstart-unity/issues/1100

**Comment by Barokoli** [comment]
As a temporary solution it's possible to use the Bundles build and mentioned in here: 
https://github.com/firebase/firebase-unity-sdk/issues/63

**Comment by a-maurice** [comment]
Sorry for not responding to this when the fix was made available.  Starting with the 9.0.0 release (roughly a year ago), the Firebase Unity SDKs have included support for Apple silicon chips.
