### ISSUE TITLE
When to fetch the TokenAsync for resource server auth

### ISSUE THREAD

**Issue by igloo12** [firebase/firebase-unity-sdk#634]
* Unity editor version: 2021.3.18f1
  * Firebase Unity SDK version: 10.5.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)

I use the Identity Token from `TokenAsync` to authenticate with my resource server. I was refreshing this token on the `IdTokenChanged` callback on `FirebaseAuth` but got locked out for API usage, and I noticed `IdTokenChanged` is called every time I sync an object with `Firestore`. I am trying to understand the best practices for calling `TokenAsync`. Do I only need to do this once on start-up? Or do I have to call before every HTTP request I make? Or am I not listening to `IdTokenChanged` correctly?

**Comment by paulinon** [comment]
Hi @igloo12,

Thank you for your question. `TokenAsync()` is essentially used whenever authenticating with the backend. That said, could you provide a sample code that describes your implementation? It's possible that syncing an object with Firestore is causing you to get locked out.

**Comment by igloo12** [comment]
I was saving the firestore token on login and IdTokenChanged like 
` IdToken = await user.TokenAsync(true);`

then passing the IdToken in the headers to my backend. Are you saying I should wrap all my backend calls with 
` var IdToken = await user.TokenAsync(true);
// make api request? 
`

**Comment by paulinon** [comment]
Thanks for the clarification, @igloo12. Ideally you can call this once in your startup as the token can be re-used for validation in your backend. You may refer to this [documentation](https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients) for more information.

I'll be closing this for now. Let me know if an issue arises or if things still seem unclear.

**Comment by igloo12** [comment]
Thanks, @paulinon I have one follow-up question. I am responsible for tracking token expiration or is there an event I can listen to?

**Comment by paulinon** [comment]
Hi @igloo12,

Aside from your ID token, a refresh token is also returned after a user signs in. You can make use of this to retrieve new ID tokens. For more information, you can check out our [documentation](https://firebase.google.com/docs/auth/admin/manage-sessions).
