### ISSUE TITLE
Unity Crashes When I User Firestore[Bug] 

### ISSUE THREAD

**Issue by Bieses** [firebase/firebase-unity-sdk#637]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.16f1
  * Firebase Unity SDK version: 10.5.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

I am trying to make a login, register system for my Android app. When I try to save my user datas to Firestore, my Unity crashes without any error. Also I can use Firebase auth.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

-> Start the project.
-> Write your email, password and etc.
-> Click on Signup button and Unity Crashes.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @Bieses,

Thanks for reporting this issue. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation? This could be used as a baseline for troubleshooting. Additionally, when you mentioned that Unity crashes, are you observing this from the Unity editor or the app build?

**Comment by tom-andersen** [comment]
@Bieses, are you able to share some logs to potentially debug what part of system is involved in crash?
