### ISSUE TITLE
[Question] Remote Config doesn't build on M1

### ISSUE THREAD

**Issue by EAdemov** [firebase/firebase-unity-sdk#638]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.45f1
  * Firebase Unity SDK version: 10.5.0
  * Source you installed the SDK: .unitypackage(.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Remote Config (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics and Cloud Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: FacebookSDK, Appsflyer, IronSource (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac M1 (Mac, Windows, or Linux)
  * Platform you are targeting: Android and iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: from official website

### [REQUIRED] Please describe the question here:

Hey. I'm trying to implement Firebase into my project. Seems like it works all fine on both Android and iOS. It builds on my MacOS(intel) but when I try to build it on cloud machine which is MacOS M1 it fails. Errors from the log:

```
▸ Linking UnityFramework

❌  Undefined symbols for architecture arm64
> Symbol: _Firebase_RemoteConfig_CSharp_FirebaseRemoteConfigInternal_App_get
> Referenced from: _FirebaseRemoteConfigInternal_get_App_m6BAB3BFD1C6EBF076C15281D4EA70FE699C2EBA7 in Firebase.RemoteConfig.o
❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **
The following build commands failed:
Exit status: 65

```

Any ideas what could be the problem?

**Comment by paulinon** [comment]
Hi @EAdemov,

Thanks for bringing this to our attention. Could you confirm if the issue persists with just the Firebase SDK in your implementation? You may try out our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/remote_config/testapp) so that we can isolate whether the SDK is causing this behavior.

**Comment by EAdemov** [comment]
Hey. I tried to build with Analytics and it seems it worked fine on M1. But when imported Remote Config it pretty but started this issue.

**Comment by paulinon** [comment]
Thanks for the additional input, @EAdemov. I've utilized the quickstart, but I was able to build with no issue. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates your issue so we can identify what's causing this behavior? Additionally, could you try if updating your Unity editor makes any difference? 2021.3.19f1 is the latest LTS version of the editor.

**Comment by EAdemov** [comment]
I will try to update the Unity editor. I'm pretty outdated.

**Comment by EAdemov** [comment]
Okay sorry for the late reply it was something really stupid by my side. Apparently I forgot to add some of the files in the Plugins folder to .gitignore. It works fine right now.
