### ISSUE TITLE
[Bug] Force resolve can't resolve dependencies, because can't find 10.5.0 directory

### ISSUE THREAD

**Issue by IgorNebosenko** [firebase/firebase-unity-sdk#642]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.1.23f1
  * Firebase Unity SDK version: 10.5.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics(but at Crashlytics it bug not reproduce, but other trouble)
  * Other Firebase Components in use: only Analytics and Crashlytics
  * Additional SDKs you are using: IronSource LevelPlay Mediation
  * Platform you are using the Unity editor on: Windows 10
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP(but it's editor bug)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: this repo

### [REQUIRED] Please describe the issue here:

When I make : "Force resolve" from Android dependency  manager v. 1.2.175 - I have error of resolve, and have this log at console:

Unable to copy Assets\Firebase\m2repository\com\google\firebase\firebase-app-unity\10.5.0\firebase-app-unity-10.5.0.srcaar to Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\10.5.0\firebase-app-unity-10.5.0.aar.

This is because at Assets\GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity generates folder with name 10, 10 1, 10 2 etc, but not a 10.5.0. If I create manually this folder - Force resolve completes, and build works correctly, but when I make new Force resolve - directory 10.5.0 - destroys and replaces with variant of simple 10, so I need to every Force resolve - create this directory.

This bug also with directory firebase-analytics-unity, at crashlytics - I dob't need to create 10.5.0 directory for every Force Resolve, but this directory... Empty. So I don't have info about crashes

I see this [issue](https://github.com/firebase/quickstart-unity/issues/1272#issuecomment-1204285167), but I have this bug after every Force resolve.

I think, this is simple to solve bug, because create at Generated Local Repo - directories have name 10, but for correct work - required 10.5.0

#### Steps to reproduce:

Reproduce:
1) Install my Version Unity Editor
2) Add Android dependency manager
3) Import Analytics & crashlytics from repo
4) Try to make Force resolve(maybe, need to make it twice).

I have this issue at 100 % of attempts to force resolve dependencies.

**Comment by DellaBitta** [comment]
I believe this is an issue in the Unity Editor's implementation to create directories. See the [Issue reported here](https://issuetracker.unity3d.com/issues/folder-name-is-truncated-when-dot-is-used-in-the-name).

This was reported fixed in Unity version 2022.2.4f1, though some are still reporting the problem. Is it possible for you to upgrade to that version and give a try?

**Comment by IgorNebosenko** [comment]
> Hi @IgorNebosenko,
> 
> Thanks for reporting this issue. I haven't been successful in replicating your issue so far. I have some questions about your implementation:
> 
> 1. Could you try if reimporting the Crashlytics and Analytics SDKs makes any difference?
> 2. Does the issue persist using any other Unity version? Please indicate the Unity version you used to confirm this.
> 3. As you performed your steps, have you encountered any instance saying the resolution was successful?

1. - At this moment I not might to check Crashlytic, because some SDK produce native crash and I disable all possible plugins and SDK for localize issue
2. I try make it on empty project without any other plugins, and I have next result: at 2022.1.23f1 - always in local repo generates directory with naming 10, 10 1, 10 2 etc. But at 2020.3.45f1 - all generates correctly. I'm not change android resolver version between different versions of Editor. So, I think, it may be Editor error, but downgrade Editor to 2020 - I can't.
And else one: equal issue with naming also at Google play game services
3. At 2022 Editor - it issue in every attempt to make force resolve, at 2020 - this issue I can't reproduce

**Comment by DellaBitta** [comment]
@IgorNebosenko,

We posted in quick succession. I just wanted to be sure that you saw my post above. Thanks!

**Comment by IgorNebosenko** [comment]
> @IgorNebosenko,
> 
> We posted in quick succession. I just wanted to be sure that you saw my post above. Thanks!

Yes, I see about 2022.2.4f1 version, so now I install it

**Comment by IgorNebosenko** [comment]
> @IgorNebosenko,
> 
> We posted in quick succession. I just wanted to be sure that you saw my post above. Thanks!

2022.2.4f1 not solve issue. Now it correctly force resolve, but project - don't builds. Gradle build failure.

**Comment by DellaBitta** [comment]
Could you post information about the build failure?

**Comment by IgorNebosenko** [comment]
First - I have trouble with string android.enableR8=false
* What went wrong:
A problem occurred evaluating project ':launcher'.
> Failed to apply plugin 'com.android.internal.application'.
   > The option 'android.enableR8' is deprecated.
     It was removed in version 7.0 of the Android Gradle plugin.
     Please remove it from `gradle.properties`. 
     
I remove this from properties template file. After this at build - 2 errors in console [First](https://pastebin.com/KRV4Kgup), [Second](https://pastebin.com/u8hMv82G)

**Comment by IgorNebosenko** [comment]
I can make build by disable Main Gradle Template & Gradle properties template. So now - need check all other part of project. If all will be good - I'm close this issue.
P.S. I install newer version of Editor - 2022.2.8f1
