### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-10_3_0 in Mac

### ISSUE THREAD

**Issue by fenixero** [firebase/firebase-unity-sdk#643]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.26 & 2021.3.12
  * Firebase Unity SDK version: 10.2.0, 10.3.0, 10.4.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: App (Core)
  * Other Firebase Components in use: Auth, Database, Messaging, Remote Config
  * Additional SDKs you are using: Facebook, Ironsource, Taptoy
  * Platform you are using the Unity editor on: Mac (Big Sur, Monterrey, Ventura)
  * Platform you are targeting: iOS & Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from this repo: [https://bitbucket.org/hyperbeard/firebase-pakage](https://bitbucket.org/hyperbeard/firebase-pakage)

### [REQUIRED] Please describe the issue here:
When playing the project and executing any firebase method, a message appears indicating that the library FirebaseCppApp-10_3_0.bundle has not been found.

LOG:
```
DilNotFoundException: FirebaseCppApp-10_3_0
Firebase.AppUtiIPINVOKE + SWIGExceptionHelper..cctor { (at
[Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3916)
Rethrow as TypelnitializationException: The type initializer for 'SWIGEXceptionHelper' threw an exception
Firebase.AppUtiIPINVOKE..cctor () (at
[Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:3936)
Rethrow as TypelnitializationException: The type initializer for 'Firebase.AppUtiIPINVOKE' threw an exception
Firebase.AppUtil SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at
[Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4646)
Firebase.LogUtil.ctor { (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil.cctor { (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow s TypelnitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor { (at
[Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_nity/x86_64/app/swig/Firebase.App_fixed.cs:1897)
Rethrow as TypelnitializationException: The type Initializer for Firebase.FirebaseApp' threw an exception
HyperBeard.CentriizedManager FirebaseManager.nitFirebase { (at
‘Assets/HyperFramework/HyperFirebase/Firebase/FirebaseManager.cs:239)
HyperBeard.CentrlizedManager FirebaseManager.Awake ( (at Assets/HyperFramework/HyperFirebase/Firebase/FirebaseManager cs113)
```

#### Steps to reproduce:

1. Add to a unity project the packages of the indicated repository (https://bitbucket.org/hyperbeard/firebase-pakage) 

Add this to the UPM manifest.json in any Unity project (/Packages/manifest.json):

```
{
  "dependencies": {
    "com.coffee.upm-git-extension": "https://github.com/fenixero/UpmGitExtension.git",
    "com.google.external-dependency-manager": "https://bitbucket.org/hyperbeard/playservicesresolvermodule.git#package",
    "com.google.firebase.analytics": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-analytics/#v10.3.0",
    "com.google.firebase.app": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-app/#v10.3.0",
    "com.google.firebase.auth": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-auth/#v10.3.0",
    "com.google.firebase.database": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-database/#v10.3.0",
    "com.google.firebase.installations": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-installations/#v10.3.0",
    "com.google.firebase.messaging": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-messaging/#v10.3.0",
    "com.google.firebase.remote-config": "https://bitbucket.org/hyperbeard/firebase-pakage.git?path=Packages/firebase-remote-config/#v10.3.0",
...
}
```

2. When adding it and clicking play on the project, the error appears on computers where Firebase has not been downloaded before from a browser.

This error will not happen to whoever committed the firebase version that causes the problem, only to whoever downloads it.

(I have also been able to replicate this using submodules, as the submodule used *.unitypackage files.)

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, the repository link that I indicated includes the Firebase Unity quickstarts as examples
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
I have tried using various file attributes (deleting and adding) on different computers of my users, but none have fixed the problem:

- com.apple.provenance
- com.apple.quarantine
- com.apple.macl
When running the command in terminal:
`spctl -a -t exec -vvv FirebaseCppApp-10_3_0.bundle`
I receive as an answer
```
.../Library/PackageCache/com.google.firebase.app@9b27dc4861/Firebase/Plugins/x86_64/FirebaseCppApp-10_3_0.bundle: rejected
source=no usable signature
```

The only way I've found to run the library is to manually download the TGZs and replace the files in /Library/PackageCache/com.google.firebase.app@XXXXXXXXXX/Firebase/Plugins/x86_64/

Another way is by updating the operating system, but when you get to Ventura and update to a new version of Firebase the problem occurs again.

**Comment by paulinon** [comment]
Hi @fenixero,

We recommend that you make use of the official [Firebase SDK](https://firebase.google.com/download/unity) from our documentation as we don't support third party libraries such as what you provided. You can also make use of `.tgz` files of the SDK from the [Google APIs for Unity archive](https://developers.google.com/unity/archive) if you intend to [import Firebase using the Unity Package Manager](https://firebase.google.com/docs/unity/setup-alternative#alternative_unity_package_manager).
