### ISSUE TITLE
[Bug] Database value update issue

### ISSUE THREAD

**Issue by MimoLopes** [firebase/firebase-unity-sdk#654]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.37f1
  * Firebase Unity SDK version: 10.2.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: 
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono and IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

The application only updates with the data from the database when i run the game twice (on the second time it updates) and testing it also i noticed that if i change a value (e.g. [day = 1]) directly in the database and running the game will not update, if i change the same value again in the database again (e.g. [day=3]) and running the game, it will update the modified value with the previous change (e.g. the value that will be get from the database is [day = 1]) and not with the value i just put in the database (e.g. [day = 3]).

Is there any way I can force the application to get the data directly from the database and not from local data or there is a resolution from my issue?

**Comment by MimoLopes** [comment]
Previously I was using 'GetValueAsync()` and the same issue was happening, so currently I'm using 'GetValueAsync()` to get a boolean value in user data to check if user exists and using event listener to get all user data.

The code below was slightly changed to keep it safe, but the structure is the same as in the project.

```
//Firebase authenticator Initialize on Start(), checking and fixing dependencies Asynchronously, then starts SignIn()

public class Example
{
    DatabaseReference userDataRef;

    void SignIn()
    {
        StartCoroutine(LoadUserData(StartListeningToUserBranch));
    }

    IEnumerator LoadUserData(Action loadSuccessfullCallback)
    {
        var userId = Firebase.CurrentUser.UserId;
        var userProperty = //Get a especifiqui bool item on user branch

        var DBTask = DBReference.Child("users").Child(userId).Child(userProperty).GetValueAsync();

        yield return new WaitUntil(predicate: () => DBTask.IsCompleted);

        if (DBTask.Exception != null)
        {
            //Debug's the DBTask Exception
        }
        else if (DBTask.Result.Value == null)
        {
            //Does what neds if user doesn't exist
        }
        else
        {
            loadSuccessfullCallback();
        }
    }

    private void StartListeningToUserBranch()
    {
        if (FirebaseAuthenticator.Instance.IsAuthenticated)
        {
            string userId = Firebase.CurrentUser.UserId;

            if (!userId.IsNullOrWhitespace())
            {
                userDataRef = DBReference.Child("users").Child(userId);

                userDataRef.ValueChanged += UserBranchChagedEventHandler;
            }
        }
    }

    private void UserBranchChagedEventHandler(object sender, ValueChangedEventArgs args)
    {
        if (args.DatabaseError != null)
        {
            //Debug's the DatabaseError message on args
            return;
        }

        DataSnapshot userData = args.Snapshot;

        //Does what neds to do with the user data

        StopListeningToUserBranch();
    }

    private void StopListeningToUserBranch()
    {
        if (FirebaseAuthenticator.Instance.IsAuthenticated)
        {
            if (userDataRef != null)
            {
                userDataRef.ValueChanged -= UserBranchChagedEventHandler;
            }
        }
    }
}
```

**Comment by paulinon** [comment]
Thanks for the update, @MimoLopes. I haven't successfully run the code you provided so far. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can have a better understanding on what's causing this to happen? You may upload this to a repository and add me as a collaborator. Make sure that all private information is scrubbed.

**Comment by paulinon** [comment]
Thanks for this, @MimoLopes. I've been unsuccessful in reproducing the issue using the files you provided. It would be helpful if you upload a runnable project in your repository in order to avoid any issues that prevents the scene from running.

**Comment by MimoLopes** [comment]
Sorry for the delay in answering, I had another priority on the project, I will make an executable project available in my repository as soon as possible.
