### ISSUE TITLE
RegistrationIntentService is still not changed to JobIntentService and causing ANR in unity SDK

### ISSUE THREAD

**Issue by SamiSdd** [firebase/firebase-unity-sdk#66]
https://github.com/firebase/firebase-unity-sdk/blob/93990f72433fb724f7f99d073c2ce3ba3d5300aa/messaging/AndroidManifest.xml#L25-L26

RegistrationIntentService is still not changed to JobIntentService despite open issues, discussions, and pr in cpp sdk

@alexames You have closed the original issue created at https://github.com/firebase/quickstart-unity/issues/939
@chkuang-g Did mention a fix which is fixed in cpp sdk - https://github.com/firebase/firebase-cpp-sdk/pull/436

**Comment by SamiSdd** [comment]
@alexames I can confirm this is not fixed in Firebase Unity SDK 8.3.0 specifically in com.google.firebase.firebase-messaging-unity-8.3.0.aar

![image](https://user-images.githubusercontent.com/1784844/136622984-338f6468-43ac-465d-925c-af04687d0109.png)
![image](https://user-images.githubusercontent.com/1784844/136623228-088e7655-10ca-4527-b65c-6002691951d1.png)

I have created a project using 8.3.0, Here is the [link](https://drive.google.com/file/d/1gyCD6kzZ4sd7R5Hr0RdG9KeUumaI_Dru/view?usp=sharing)

**Comment by alexames** [comment]
The manifest should be referring to the `RegistrationIntentService`. The `JobIntentService` is the base class of the `RegistrationIntentService`. [It was previously using `IntentService` as the base class](https://github.com/firebase/firebase-cpp-sdk/commit/2b2f2c24e20a661721b2d5ebe408899523f4334b), which is what needed to get updated. Unfortunately, this seems like it wasn't a complete fix. Once the root issue can be identified hopefully a better fix can be implemented.
