### ISSUE TITLE
[Bug] firebase won't work on ios build

### ISSUE THREAD

**Issue by yogev2255** [firebase/firebase-unity-sdk#666]
[REQUIRED] Please fill in the following fields:
Unity editor version: 2021.3.15f1
Firebase Unity SDK version: 10.6.0
Source you installed the SDK: ___.unitypackage __ (.unitypackage or Unity Package Manager)
Problematic Firebase Component: database___ (Auth, Database, etc.)
Other Firebase Components in use: non_ (Auth, Database, etc.)
Additional SDKs you are using: GooglePlay , facebook , apple_ (Facebook, AdMob, etc.)
Platform you are using the Unity editor on: mac  (Mac, Windows, or Linux)
Platform you are targeting: _android  and ios (iOS, Android, and/or desktop)
Scripting Runtime: IL2CPP_ (Mono, and/or IL2CPP)
Pre-built SDK from the [website]() or open-source from this repo

Hey, I am using firebase for my android game and it's working fine
now when I am trying to make a build for ios firebase won't work 

I am getting those errors :
10.6.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
 ERROR: App ID, API key, and Project ID must be specified in App options.  
ERROR: Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly.

---
I have GoogleService-Info.plist inside the project and I am using the CheckAndFixDependenciesAsync code from the docs
what should I do?

**Comment by paulinon** [comment]
Hi @yogev2255,

Thanks for bringing this to our attention. I'd like you to clarify a few items: 
- Could you provide the Firebase initialization code in your implementation so we can identify what's causing this? 
- Since you mentioned that you're using the `CheckAndFixDependenciesAsync()` method, have you called any function that makes use of Realtime Database? 
- Could you also confirm if the bundle IDs in your iOS build settings and your `GoogleService-Info.plist` file match?

**Comment by yogev2255** [comment]
1. my initialization code is this 

`    private void CheckFireBaseDependencies()
    {
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            var dependencyStatus = task.Result;
            if (dependencyStatus != Firebase.DependencyStatus.Available)
            {
                Debug.Log("FireBase is not working");

                Destroy(this.gameObject);// Check if its good to destroy
                return;
            }
            db = FirebaseDatabase.DefaultInstance.RootReference;
            db.Child("Servers").KeepSynced(true);

        });
    }
`
2. yes, I am calling SetRawJsonValueAsync but it does nothing
3. I checked and both of them are the same

**Comment by yogev2255** [comment]
I reinstalled the GoogleService-Info.plist file and its working now !!
thank you
