### ISSUE TITLE
How to add Firestore emulator support?

### ISSUE THREAD

**Issue by dex3r** [firebase/firebase-unity-sdk#67]
Right now when trying to connect to locally hosted Firestore emulator from Unity a mysterious exception is thrown:

```
Firebase.Firestore.FirestoreException : 
false for 'get' @ L6
---
at Firebase.Firestore.Internal.Util.FlattenAndThrowException (System.Threading.Tasks.Task completedTask) [0x00016] in Z:\tmp\tmp.DnKB31Zq3X\firebase\firestore\client\unity\proxy\Util.cs:94 
  at Firebase.Firestore.Internal.Util+<MapResult>c__AnonStorey0`2[T,U].<>m__0 (System.Threading.Tasks.Task`1[TResult] completedTask) [0x00000] in Z:\tmp\tmp.DnKB31Zq3X\firebase\firestore\client\unity\proxy\Util.cs:59 
```

After debugging SDK C# code I found out that error code of 7 (PermissionDenied) is also present.

I use these settings:
```
Settings.Host = "localhost:8080";
Settings.SslEnabled = false;
Settings.PersistenceEnabled = false;
```

I desperately need to support Firestore emulator in Unity. I will try to build SDK from source and implement emulator support myself.

How hard will it be? Does CPP SDK support emulator? Is it known where the problem lies?

I looked inside Android/Java Firebase SDK and it does not seem to be doing anything special besides setting port, host, ssl and persistence.

**Comment by dex3r** [comment]
Test code (empty scene with only this object):

```
using System.Collections.Generic;
using System.Threading.Tasks;
using Firebase;
using Firebase.Firestore;
using UnityEngine;

public class FirestoreEmulatorTest : MonoBehaviour
{
    async void Start()
    {
        Debug.Log("TEST START");
        
        FirebaseFirestore.DefaultInstance.Settings.Host = "localhost:8080";
        FirebaseFirestore.DefaultInstance.Settings.SslEnabled = false;
        FirebaseFirestore.DefaultInstance.Settings.PersistenceEnabled = false;

        FirebaseFirestore.LogLevel = LogLevel.Debug;
        
        await WriteToEmulator();
    }
    
    async Task WriteToEmulator()
    {
        var docRef = FirebaseFirestore.DefaultInstance.Document("testL/test");
        var documentData = new Dictionary<string, object>();

        await docRef.SetAsync(documentData);
        Debug.Log("Write done");
    }
}
```

2. 8.3.0
3. Windows 10
4. Editor
5. `firebase emulators:start`
![image](https://user-images.githubusercontent.com/3155725/136586708-35f26a60-1431-45fb-8904-c0c992a9b181.png)
6. Yes
7. https://pastebin.com/P42AGzjb
8. See above

**Comment by dex3r** [comment]
I've turned off the windows firewall but the problem persists. Removing the cache also did not help.

**Comment by dconeybe** [comment]
A quick Google search brought me to this post: https://stackoverflow.com/a/62171642/12975006

Could you ensure that your security rules in the emulator are sufficiently permissive to allow the writes?

**Comment by dconeybe** [comment]
I've logged b/202835732 (for Googlers) to see what we can do to improve the error message produced when a Firestore operation is rejected by security rules.
