### ISSUE TITLE
[Question] Is there a way of avoiding the usage of the local repository for Android?

### ISSUE THREAD

**Issue by jesus-mgtc** [firebase/firebase-unity-sdk#675]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.21f1
  * Firebase Unity SDK version: 10.7.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the question here:

Greetings!

I'm integrating Firebase Analytics in my Unity project. I've notice you're packing and using a local repository with the needed dependencies. Is there some place out there where these dependencies could be fetched online? Like in Maven or any third party or somewhere else? If not, is there a reason for this to be this way? Or are there any plans to upload the libraries to a remote repository so we can avoid using the local one?

Thank you in advance!

**Comment by a-maurice** [comment]
Hi @jesus-mgtc 

You are right that the Unity specific Android libraries are just included directly in the package, though those still depend on the underlying Firebase Android SDK, which is fetched from a Maven repo.  We currently don't have plans to upload those elsewhere, though I guess it is always a possibility.  We just haven't heard much demand for it, it would make the release process a bit more complex, and the Unity SDK would still need to exist with all of the other libraries to support all the other platforms (and the C# parts which would be needed for Android).  Can I ask why you were looking for that as an option?

**Comment by jesus-mgtc** [comment]
In our company we have 2 different games at the moment that shares a common, in-house framework of utilities such as ads, tracking, resource management etc. that can be used in both games indistinctly.  This common code lives in a Unity project with nothing in the Assets folder. It just define local packages with their own .asmdefs and code. We'd like one of this packages would be anything related to Firebase, let's call it `external.firebase`. This codebase lives as a submodule of the other two games. We never add code to the Assets folder as there's no way of sharing it with other projects.

The two games just add a reference to these local packages in their respective `manifest.json`. Generally, all needed code for a specific feature can live self-contained inside one of these packages, so the game imports the package and can start using it right away. Whenever we need to have something in the `Assets` folder though, this workflow is broken, as each specific game needs to add whatever is needed to `Assets` and the package stops being self-contained. 

This results in code, libraries or configurations duplicated across projects. In the case of Firebase it duplicates all the plugins, the local repository and the generated local repository, but what they contains are exactly the same. It'd be amazing to be able to:

1.  If libraries could be fetched from Maven and avoid the local repo logic entirely, we'd need nothing from Firebase to be in the Assets folder and everything could live self-contained in a package (Looks like the local repo logic only works fine if it's in the `Assets` folder. `External Dependency Manager` seems to work that way)

2. Make all work outside the `Assets` folder. It looks like there are some assumptions this code will always live in the `Assets` folder, and that might not be the case. If all what happens in the `Assets` folder could be self-contained in a package, or a different root folder (instead of `Assets/` be `Packages/external.firebase/`, for example) that'd be reeally helpful already.

Sorry for the looong response and I hope everything is more or less clear. In the end is a matter of easy reusability across different projects.

Thanks for your time!

**Comment by a-maurice** [comment]
Interesting, that definitely makes more sense then.  One option, if the `Assets` thing is annoying you, is we do offer the Firebase SDKs in a way that will get the in the `Packages` directory, as you mention, available here: https://developers.google.com/unity/archive

There are instructions that it links to, but essentially you download the tgz you want, import it in the Packages directory, and everything should be that directory instead.  When building for Android, it will still generate/download aars into the Assets/Plugins/Android directory, not much can be done about that unfortunately.

**Comment by a-maurice** [comment]
I'm going to close this issue for now, I think using the Packages and tgz is the best way to deal with this problem.
