### ISSUE TITLE
[Bug] Remote Config does not store/parse correctly default values for float/double

### ISSUE THREAD

**Issue by vg-swift** [firebase/firebase-unity-sdk#711]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.20f1
  * Firebase Unity SDK version: 10.7.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: many other
  * Additional SDKs you are using: irrelevant
  * Platform you are using the Unity editor on: Mac & Windows
  * Platform you are targeting: iOS and Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website] https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here:

When setting default value in languages like German, French or Russian that  use ',' instead of '.'  for comma separation, it is stored with comma, but when it tries to get the value, it uses InvariantCulture, so it instead of 0,25 you get 25. (Firebase.RemoteConfig.ConfigValue.DoubleValue =>)

I think the issue is in RemoteConfigUtil.cs in the ConvertDictionaryToMap method. It should use invariant culture when converting numbers to string.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Set 0.25 default value in RemoteConfig with regional settings set to German.
When retrieving the value, it will get 25.

**Comment by vg-swift** [comment]
It says it was fixed in 2021, but the issue still happens in 10.7.0
https://github.com/firebase/quickstart-unity/issues/899

**Comment by revolt3r** [comment]
![image](https://github.com/firebase/firebase-unity-sdk/assets/11783754/567ef68e-49b7-47c9-842a-80684b13c5e3)
1) On windows you first need to go to Time & Language -> Language & Region
2) Add german language
3) Set your regional format to German (Germany)

**Comment by revolt3r** [comment]
On Android you can go to Settings -> System -> Language & input
Add German Language and move it to the top of the list
After that restart the app

**Comment by vg-swift** [comment]
![image](https://github.com/firebase/firebase-unity-sdk/assets/113506557/f6baebf0-674b-4142-8701-658f5ead61d6)
On windows you first need to go to Time & Language -> Language & Region
Add german language
Set your regional format to German (Germany)
Make sure to restart Unity to take the changes into effect

**Comment by vg-swift** [comment]
On Android you can go to Settings -> System -> Language & input
Add German Language and move it to the top of the list
After that restart the app

**Comment by paulinon** [comment]
Thanks for the update, @vg-swift. I was able to reproduce the behavior where 0.25 returns 25 after tapping `Display Current Data`, although I should mention that I'm getting 0,25 when fetching remote data.

That said, I'll be relaying my observations to the team. Let me mark this as a bug for now.

**Comment by jonsimantov** [comment]
This should be fixed in #736, which will be included in the next release (11.2.0) of the Unity SDK. Feel free to reopen this if it still occurs in that release.
