### ISSUE TITLE
[Bug] Android app still writing to old database when updating google-services.json

### ISSUE THREAD

**Issue by ReallyRad** [firebase/firebase-unity-sdk#731]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.26
  * Firebase Unity SDK version: 8.7
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database or Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Database, Auth, Crashlytics, Remote Config
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

Hello, I am having issues updating the database to which my app should write to. I previously published an app that wrote to Realtime Database. Now I want to create a very similar app from the same Unity project, so I created a new app on Firebase and downloaded the new google-services.json.

Within the Unity Editor, the data gets written to the newly referenced database. When building to Android, it gets written to the previously referenced database. When exporting to an Android Studio project there is no reference to the previous bucket, Bundle ID, firebase URL... anywhere. Everything is updated properly.

I can share my project privately upon request. I doubt the issue will be reproducible from the SDK samples.

Thanks for your attention

**Comment by paulinon** [comment]
Hi @ReallyRad,

Based on the provided information, the cause of this behavior could lie within your project configuration. Since the issue has something to do with your `google-services.json` files, I recommend that you raise this issue to our [Firebase Support](https://firebase.google.com/support) channel where one of our agents can help you out with such matters involving personally identifiable information.

**Comment by ReallyRad** [comment]
It looks like a bug with the Firebase Unity SDK to me. I can give you access to my repo for duplication. But I'm reaching out to Firebase support as well anyways.
