### ISSUE TITLE
SMS is not Received From unity  2021.3.25f1

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/firebase-unity-sdk#732]
Unity editor version: Unity  2021.3.25f1

Firebase Unity SDK version: firebase_unity_sdk_11.0.0

Problematic Firebase Component: Auth

Other Firebase Components in use: None(only auth)

Additional SDKs you are using:None(only auth)

Platform you are using the Unity editor on: Windows

Platform you are targeting: Android

Scripting Runtime:Mono

Pre-built SDK from the website : firebase_unity_sdk_11.0.0

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 1

What happened? How can we make the problem occur?
Hi All

I have installed 2021.3.25f1 and downloaded quik start unity master and Installed Firebase firebase_unity_sdk_11.0.0..I have downloaded googleservices.json. and put it in Assets folder and also i created streaming assets folder and put googleservices.json . I have enabled sha1 and sha256 in firebase console. and enabled keystore in publish settings. There is No Error in Build. Build created successfully. When i build and enter phone number.SMS is not receiving in my mobile..
Just it says Setting Up Firebase Auth Only.

I have enabled assets/AssetResovle/Force Resolve...

kindly help me to solve this error. SMS is not receiving ...

kindly check from your side also..

**Comment by CLOUDFIRE91** [comment]
Hi Paulinon 

https://github.com/firebase/firebase-unity-sdk/issues/717#issuecomment-1561974771

Your Firebase member accepted that there is a bug in Firebase.. Kindly check from your side. Whether it is working or not. 


Unity editor version: Unity 2021.3.25f1

Firebase Unity SDK version: firebase_unity_sdk_11.0.0

Touch is not working. I have enabled event systems also. Nothing works... 

Kindly check from your side.

**Comment by CLOUDFIRE91** [comment]
Mr Paulion 

Thanks for you Reply. I  am going to contact the backend firebase team. before that i have one question. 

1)Did  you receive sms from  your side. 

2)Did Quick Start master +firebase 11.00 successfully sending Sms to you. 

Kindly confirm my questions.  because i have a doubt that  it is working or not. 

After your confirmation. i will contact firebase back end support team.

**Comment by paulinon** [comment]
Hi @CLOUDFIRE91,

Just tested two phone numbers using version 11.0.0 of the SDK, and I was able to receive both their respective OTPs. 

I hope the support agent provides the help you need.

**Comment by CLOUDFIRE91** [comment]
@paulinon  Which unity Version you tested.

**Comment by CLOUDFIRE91** [comment]
@paulinon 

I have contacted google firebase team backend. They said  my issue has been forward to engineers. they ask me to wait for some time. 

paulion, could you please forward your tested apk for receiving sms to me. i can check you apk whether it is working in my region. I am in india.. 

this is my link for my apk .  could you please test my apk  and forward ur feedback to me .you can give feedback whats my error for not receiving sms.

(https://www.dropbox.com/s/2zhvo9o3jno9i9w/Fooya7-6-23-10-30am.apk?dl=1)

**Comment by CLOUDFIRE91** [comment]
@paulinon     can you share your  auth apk..  i can test  whether it is working or not in my region .. ... did you test my apk .. ...whats ur feedback... i have contacted google firebase back end team. they said it is forward to engineer and ask me to wait....
