### ISSUE TITLE
[Bug] Android build fails after update to 11.0 from 10.7

### ISSUE THREAD

**Issue by kocburak** [firebase/firebase-unity-sdk#741]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.20
  * Firebase Unity SDK version: 11.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Analytics, RemoteConfig, Installations, Crashlytics 
  * Additional SDKs you are using: Facebook, Applovin, Adjust
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
    * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built

### [REQUIRED] Please describe the issue here:

After the Firebase 11.0.0 update from 10.7.0 build fails with the error below.
`java.util.NoSuchElementException: Key C:\Users\pc\.gradle\caches\transforms-2\files-2.1\e871f0fb74b6898cebd1fc83b7d3ec2c\jetified-mintegral-adapter-16.4.41.1-runtime.jar is missing in the map.`

 Error seams to be related with Applovin Mintegral SDK. But Since I dont know the relation between them, I am asking for guidence on how to resolve this. When I remove Mintegral from project the errror becomes this:

`java.util.NoSuchElementException: Key C:\Users\pc\.gradle\caches\transforms-2\files-2.1\0e5409d1401a9210cb0b898c26451ad6\jetified-instantapps-1.1.0-runtime.jar is missing in the map.`

So I don't think it is about other sdks. I removed the gradle caches but the error persists.

**Comment by paulinon** [comment]
Hi @kocburak,

Thanks for bringing this to our attention. Could you verify if the issue persists upon removing the Firebase SDK? Could you try our [quickstart](https://github.com/firebase/quickstart-unity) and see if it produces a similar issue?

**Comment by kocburak** [comment]
Hi,
When Firebase SDKs are removed error does not persist. Also on Firebase SDK 10.7 error does not persist. 
Sample apps are using Unity 2017. Which is a very old version. I upgraded them to 2021.3.20 and install Firebase SDK 11.0 but problem did not occur. Than I remembered. I cleared the .gradle cache but didn't clean build. Now I tried clean build it. Build is successfull now :)

**Comment by paulinon** [comment]
Glad to hear that you've successfully built your app, @kocburak. That said, I'll be closing this ticket. Let me know if an issue arises.
