### ISSUE TITLE
[Bug] Assembly name 'Google.VersionHandlerImpl' does not match file name 'Google.VersionHandlerImpl_v1.2.89.0'

### ISSUE THREAD

**Issue by ChurikiTenna** [firebase/firebase-unity-sdk#742]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.2.0b11, 2022.3.0f1 or 2023.3.0f1
  * Firebase Unity SDK version: latest
  * Source you installed the SDK: . unitypackage
  * Problematic Firebase Component: All
  * Other Firebase Components in use: All
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: Mono
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

```
Assembly 'Assets/PlayServicesResolver/Editor/Google.JarResolver_v1.2.89.0.dll' will not be loaded due to errors:
Assembly name 'Google.JarResolver' does not match file name 'Google.JarResolver_v1.2.89.0'

Assembly 'Assets/PlayServicesResolver/Editor/Google.VersionHandlerImpl_v1.2.89.0.dll' will not be loaded due to errors:
Assembly name 'Google.VersionHandlerImpl' does not match file name 'Google.VersionHandlerImpl_v1.2.89.0'

Assembly 'Assets/PlayServicesResolver/Editor/Google.IOSResolver_v1.2.89.0.dll' will not be loaded due to errors:
Assembly name 'Google.IOSResolver' does not match file name 'Google.IOSResolver_v1.2.89.0'

```

#### Steps to reproduce:

1. Import sdk with .unitypackage (https://firebase.google.com/docs/unity/setup-alternative?hl=ja)2. 
2. See errors on console

#### Relevant Code:

None

**Comment by paulinon** [comment]
Hi @ChurikiTenna,

Thanks for bringing this to our attention. Does the issue persist when you're using a more updated Unity editor (such as version 2022.2.9f1)? Could you also try if adding your `GoogleService-Info.plist` file made any difference?

**Comment by ChurikiTenna** [comment]
Hi @paulinon !

The issue persist when using 2023.3.0f1 too.
GoogleService-Info.plist is under Assets folder. I also tried moving the file into Firebase/Plugins and Plugins/iOS/Firebase.

**Comment by ChurikiTenna** [comment]
Additional information:
The project was created in Linux, and I am trying to run in M1 Mac.

**Comment by paulinon** [comment]
Hi @ChurikiTenna,

I haven't been able to reproduce the issue using the provided information so far. Are there other steps in your implementation that have to be considered? Could you confirm if a similar behavior persists using our [quickstart](https://github.com/firebase/quickstart-unity)?

**Comment by chkuang-g** [comment]
@ChurikiTenna 

You got an ancient version of EDM4U, even before it is renamed to EDM4U! How did you get that into your project? Did you get that from Firebase SDK?

Try to remove everything under `Assets/PlayServicesResolver` and `Assets/ExternalDepenencyManager`.
Also, remove EDM4U from Unity Package Manager as well, for a fresh start.

After that, you can reinstall EDM4U from tgz or `.unitypackage`, whichever you prefer.

Let us know if this helps
