### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ynj97** [firebase/firebase-unity-sdk#743]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: __20213.25f1___
  * Firebase Unity SDK version: __11.0.0___
  * Source you installed the SDK: _.unitypackage____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: ___Auth__ (Auth, Database, etc.)
  * Other Firebase Components in use: __Database, Analytics___ (Auth, Database, etc.)
  * Additional SDKs you are using: __None___ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: ___Mac__ (Mac, Windows, or Linux)
  * Platform you are targeting: __Android___ (iOS, Android, and/or desktop)
  * Scripting Runtime: ____ IL2CPP_ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Game crashes when trying to access UserId. 

#0  0x00000320c43cb8 in Firebase_Auth_CSharp_FirebaseUser_UserId_get
#1  0x0000031ef3b6d4 in  (wrapper managed-to-native) Firebase.Auth.AuthUtilPINVOKE:FirebaseUser_UserId_get (System.Runtime.InteropServices.HandleRef) [{0x11dad10e0} + 0xcc]  (0x31ef3b608 0x31ef3b78c) [0x13d942a80 - Unity Child Domain]
#2  0x0000031ef3b4ec in  Firebase.Auth.FirebaseUser:get_UserId () [{0x11dad0df8} + 0x94] [/Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/auth/swig/Firebase.Auth_fixed.cs :: 3891u] (0x31ef3b458 0x31ef3b588) [0x13d942a80 - Unity Child Domain]
#3  0x0000031f169dac in  Player:RewardPlayerClientRpc (int,int) [{0x13940b8b8} + 0x5c4] [/Users/ynj/Documents/GitHub/IdleGameCopy/Assets/Scripts/Networking/Player.cs :: 159u] (0x31f1697e8 0x31f16a020) [0x13d942a80 - Unity Child Domain]
#4  0x0000031f169708 in  Player:__rpc_handler_4107551755 (Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams) [{0x313f74810} + 0x158]  (0x31f1695b0 0x31f169744) [0x13d942a80 - Unity Child Domain]
#5  0x0000031f147604 in  (wrapper delegate-invoke) <Module>:invoke_void_NetworkBehaviour_FastBufferReader___RpcParams (Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams) [{0x2f9a99930} + 0x284]  (0x31f147380 0x31f147770) [0x13d942a80 - Unity Child Domain]
#6  0x0000031f146984 in  Unity.Netcode.RpcMessageHelpers:Handle (Unity.Netcode.NetworkContext&,Unity.Netcode.RpcMetadata&,Unity.Netcode.FastBufferReader&,Unity.Netcode.__RpcParams&) [{0x11e50dd80} + 0x2d4] [/Users/ynj/Documents/GitHub/IdleGameCopy/Library/PackageCache/com.unity.netcode.gameobjects@1.4.0/Runtime/Messaging/Messages/RpcMessages.cs :: 70u] (0x31f1466b0 0x31f146a90) [0x13d942a80 - Unity Child Domain]
#7  0x0000031f1465b4 in  Unity.Netcode.ClientRpcMessage:Handle (Unity.Netcode.NetworkContext&) [{0x11dad7af0} + 0x224] [/Users/ynj/Documents/GitHub/IdleGameCopy/Library/PackageCache/com.unity.netcode.gameobjects@1.4.0/Runtime/Messaging/Messages/RpcMessages.cs :: 151u] (0x31f146390 0x31f1465ec) [0x13d942a80 - Unity Child Domain]

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
No issue
What happened? How can we make the problem occur?
I have no idea why this occurs

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
            Debug.Log(firebaseManager == null);
            Debug.Log(firebaseManager.user == null);
            Debug.Log(firebaseManager.user.UserId == null);
            
            The result is False, False and the 3rd line crashs it so dont know what the result of that is.
            
            I am wondering in what cases can this happen? So I can figure out if any of those are the issue.
            
            Some background, the game is also using Unity.Netcode <-Not sure if this is a issue here (This is first time developing a multiplayer and also first time facing this issue with Firebase and Unity)

**Comment by AdriaandeJongh** [comment]
I'm seeing the same issue, and I'm not using Unity.Netcode so that has nothing to do with it. Quick fix for me was to simply cache the user id (as that's all I need).

**Comment by ynj97** [comment]
Ya that is what I am doing too, but want to understand if it is something im doing wrong.

**Comment by paulinon** [comment]
Hi @ynj97,

Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can identify what's causing this? So far, I haven't faced a crash using the third line of code you provided.

**Comment by MartinZazpe** [comment]
I think I am having the same issue...

Upon saving to database: 
Obtained 66 stack frames.
```
#0  0x000002d32fc430 in Firebase_Auth_CSharp_FirebaseUser_UserId_get
#1  0x000002cbc849ec in  (wrapper managed-to-native) Firebase.Auth.AuthUtilPINVOKE:FirebaseUser_UserId_get (System.Runtime.InteropServices.HandleRef) [{0x2c0e0b3a8} + 0x7c]  (0x2cbc84970 0x2cbc84a78) [0x127f42a80 - Unity Child Domain]
#2  0x000002cbc848c0 in  Firebase.Auth.FirebaseUser:get_UserId () [{0x2c0e0b2c0} + 0x30]  (0x2cbc84890 0x2cbc848f0) [0x127f42a80 - Unity Child Domain]
#3  0x000002cbc840c4 in  FirebaseManager/<UpdateDeaths>d__34:MoveNext () [{0x2a7917508} + 0xac] [/Users/Myname/Documents/UnityProjects/SpaceMission3D/Assets/GAME/Scripts/FirebaseManager.cs :: 369u] (0x2cbc84018 0x2cbc842f4) [0x127f42a80 - Unity Child Domain]
```
