### ISSUE TITLE
[Bug] Build is successful but hangs or crashes when run after updating to 11.0.0

### ISSUE THREAD

**Issue by Hanalei-Luke** [firebase/firebase-unity-sdk#744]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.31f1
  * Firebase Unity SDK version: 11.0.0
  * Source you installed the SDK: tarball 
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: core, analytics, crashlytics, installations, messaging
  * Additional SDKs you are using: AppLovin Max, Singular, Game Analytics
  * Platform you are using the Unity editor on: MacOS Ventura 13.0
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the issue here:

Android builds are successful but either crash on startup or hang shortly after. Logcat reveals this issue:
```
ApplicationException: Unable to find Method com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.remove (signature '()V', instance).  Please verify the AAR which contains the com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration class is included in your app.
```

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
* I have not been able to reproduce the issue using the quickstart project. 

What's the issue repro rate? (eg 100%, 1/5 etc) 
* It happens every time we run the build.

What happened? How can we make the problem occur? 
This could be a description, log/console output, etc. 
* See attached log file.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
Part of script responsible:

#if USE_FIREBASE_REMOTE_SETTINGS
  static bool GetConfigValue(string key, out ConfigValue v) 
  {
    var key_ = SpungeString.Replace(key, '-', '_');
    
    v = FirebaseRemoteConfig.DefaultInstance.GetValue(key_);

    if(v.Source==ValueSource.StaticValue)
    {
      return false;
    }
    return true;
  }
#endif

```

#### Extra info:

Hi there! We recently updated to 11.0.0 and have run into an issue with it. I haven't been able to reproduce it and we can't seem to figure out what's wrong. Hoping to get some more eyes on it and see if anyone else is having trouble with it as well!
Cheers!
[Logcat Output.log](https://github.com/firebase/firebase-unity-sdk/files/11596380/Logcat.Output.log)

**Comment by jonsimantov** [comment]
This is probably related to your project still having a previous version of the Remote Config Android dependency. To make sure this isn't the case, you should delete the entire Firebase plugin from your project, then re-add it. You should be able to tell in the Gradle log what version of the Remote Config Android library is being linked in, and ensure it's using com.google.firebase:firebase-config:21.3.0 or higher.

**Comment by Hanalei-Luke** [comment]
Thanks mate! I'll give that a try and report back!

**Comment by Hanalei-Luke** [comment]
Due to personal reasons I'm no long
