### ISSUE TITLE
Unable to load DLL 'FirebaseCppApp-11_1_0'. Tried the load the following dynamic libraries: Unable to load dynamic library '/FirebaseCppApp-11_1_0' because of 'Failed to open the requested dynamic library

### ISSUE THREAD

**Issue by Khusr017** [firebase/firebase-unity-sdk#760]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

  * Unity editor version: 2022.1.21f1
  * Firebase Unity SDK version: 11_1_0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: App (Core)
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I have tried multiple versions of firebase unity package. When i import the package, it works fine in the unity editor and in android devices. When i make a build for iOS device and run it in xcode with an iPhone attached, during initialization of the firebase, it throws the above issue.

I have tried other versions as well and for each version, it showing the same error, just the version number changes i.e i tried v10.3.0 and it was showing the same error i.e unable to load  dll FirebaseCppApp-10_3_0

I removed the Library,  Assets/Firebase, Assets/Plugins/iOS/Firebase, Assets/ExternalDependencyManager, Assets/Editor Default Resources but it throwing the same issue.

I have added GoogleService-Info.plist.

It seems to be failing while executing the below code:

<img width="1018" alt="Screenshot 2023-06-12 at 5 17 31 PM" src="https://github.com/firebase/quickstart-unity/assets/46478926/5d4d40e9-abf7-41ad-b4cb-b6c15598f723">

#### Steps to reproduce:

What happened? How can we make the problem occur?
<img width="903" alt="Screenshot 2023-06-12 at 5 19 02 PM" src="https://github.com/firebase/quickstart-unity/assets/46478926/b7190fb0-5a1d-447b-b7d4-e994aa0ecd4d">

#### Relevant Code:
Below is the code i am using for firebase initialization on my login screen.

FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
      {
          var dependencyStatus = task.Result;
          if (dependencyStatus == DependencyStatus.Available)
          {
              FirebaseApp app = FirebaseApp.DefaultInstance;
          }
          else
          {
              UnityEngine.Debug.LogError(System.String.Format(
              "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
          }
      });

**Comment by a-maurice** [comment]
Hi @Khusr017 

So generally that error means it is failing to load the FirebaseCppApp library.  What is odd is that I don't think on iOS that file is versioned like that, but it is on the other platforms.

My initial guess is that one of the other platform files has accidentally become enabled for iOS, and when it is loading that, it looks for the CppApp library with a version number, and fails.  So, if you could check the various dll files in your project's Assets/Firebase/Plugins folder, the only files that should be enabled for iOS are Firebase.Platform.dll, Firebase.TaskExtension.dll, Google.MiniJson.dll, and then all the libraries within the iOS folder.

Another thing to try would just be to start off with one of the quickstarts, and trying out one of those, to see if you can get a new project working with it.

**Comment by Khusr017** [comment]
Hi @a-maurice 

Thank you for the detailed response. I am not sure what be the problem. Whenever i import the package, it creates firebase folder inside Assets. Please review the below 2 screenshots which is the Assets/Firebase/Plugin folder content. 

<img width="904" alt="Screenshot 2023-06-14 at 11 25 39 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/46478926/ca973252-0333-4593-9ca0-a7bfb1a07c4e">

<img width="912" alt="Screenshot 2023-06-14 at 11 27 43 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/46478926/e00a416a-e098-4ce9-b1a1-9b052b7708a7">

Thanks again.

**Comment by paulinon** [comment]
Hi @Khusr017,

Could you confirm if going to Assets > External Dependency Manager > Android Resolver > Force Resolve makes any difference? Also, are you facing a similar issue using our [quickstart](https://github.com/firebase/quickstart-unity) project?

**Comment by a-maurice** [comment]
Nothing with what you posted stands out as wrong, unfortunately.  If you try setting up a fresh project, like the quickstart, do you see a similar error?

**Comment by tejad** [comment]
I too am having the same issue. Getting the below error. I'm on MacOS Catalina `10.15.7` and Unity version `2021.3.25f1`.  I am using the latest Firebase sdk. 

`DllNotFoundException: FirebaseCppApp-11_1_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at <f304a7e60d35404c921f5e369de9d825>:0)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at <f304a7e60d35404c921f5e369de9d825>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <f304a7e60d35404c921f5e369de9d825>:0)
Firebase.LogUtil..ctor () (at <f304a7e60d35404c921f5e369de9d825>:0)
Firebase.LogUtil..cctor () (at <f304a7e60d35404c921f5e369de9d825>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at <f304a7e60d35404c921f5e369de9d825>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Firestore.FirebaseFirestore.get_DefaultInstance () (at <702d644776aa4d60893dce52123d0173>:0)
FirestoreManager.Awake () (at Assets/Scripts/FirestoreManager.cs:21)`

**Comment by FlynnMacfarlane92** [comment]
Not sure if mentioned, have you tried going to Build Phases for Unity Framework > Linked Binaries and double check they are added in there?

**Comment by tejad** [comment]
I solved my issue by updating my MacOS from Catalina to Monterey.
