### ISSUE TITLE
[Bug] 11.2 fails Xcode Build

### ISSUE THREAD

**Issue by kocburak** [firebase/firebase-unity-sdk#773]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.20
  * Firebase Unity SDK version: 11.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Unknown
  * Other Firebase Components in use: Remote Config, Analytics, Crashlytics
  * Additional SDKs you are using: Facebook, Applovin, GameAnalytics
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

I am trying to Mac an iOS build. We updated from 11.0 to 11.2 and now the builds fails with this error on Xcode:

`
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in libFirebaseCppMessaging.a(messaging.mm.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

#### Steps to reproduce:
Just try to build.

**Comment by kocburak** [comment]
Downgraded to 11.1 . Error does not occur.

**Comment by paulinon** [comment]
Hi @kocburak,

Thanks for letting us know about this. The error message you provided mentioned Messaging. Are you using Cloud Messaging in your project as well? Does the issue persist with just the Firebase SDK in your implementation?

**Comment by kocburak** [comment]
> Hi @kocburak,
> 
> Thanks for letting us know about this. The error message you provided mentioned Messaging. Are you using Cloud Messaging in your project as well? Does the issue persist with just the Firebase SDK in your implementation?

Thats the neat part. Our game does not use Firebase messaging. It only sends local notification. Firbase Messaging has never imported in the game. And what do you mean by just the Firbase SDK? We imported only Analytics, Remote Config and Crshlytics.

**Comment by a-maurice** [comment]
I did a check, and can't seem to reproduce it when importing Analytics, Remote Config, and Crashlytics together.  Based on the error message, it seems you have libFirebaseCppMessaging.a being included, which presumably would only happen by importing Firebase Messaging.  In your Unity project it would likely be in Assets/Plugins/iOS/Firebase.  Can you see if you have that file in there, and if so any ideas on how it would have gotten there?

The reason for the failure is that it is including the CppMessaging library, which depends on the iOS Messaging library, but the iOS Messaging library is not being included in the set of Cocoapods to use, and thus missing.

**Comment by kocburak** [comment]
Yeap you are right.  I checked through git history. There is a file named "libFirebaseCppMessaging.a" in Assets/Plugins/iOS/Firebase and Assets/Plugins/tvOS/Firebase. But there is no Messaging inside Assets\Firebase . Probably this is the reason as you said. Eroor did not occur when downgrading to 11.1 because it was wiped clean for anything related to firebase before 11.1 imported. I will try it. Thank you.
