### ISSUE TITLE
[Bug] Fetching RemoteConfig in Unity editor shows windows error

### ISSUE THREAD

**Issue by MichalDolezalAG** [firebase/firebase-unity-sdk#780]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.27f1
  * Firebase Unity SDK version: 11.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: Auth, CloudMessaging, Crashlytics, RealtimeDatabase
  * Additional SDKs you are using: Ironsource (Meta, AdMob, AdColony, AppLovin)
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: [website](https://developers.google.com/unity/archive#firebase_app_core)

### [REQUIRED] Please describe the issue here:

After updating Firebase from 11.1.0 to 11.2.0, editor started to show windows error when entering play mode. It's caused by fetching remote config. All our computers have Czech language (Česko). The error says:

> Microsoft Visual C++ Runtime Library
> Runtime Error!
> 
> Program:
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

When the error is showing, play mode still run normaly. No error is shown in unity or in the log files.
When you press OK, Unity shuts down.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
Set system language to Czech

**Comment by plotlessplot** [comment]
Can confirm that this issue also happens 100% of the time on Unity 2021.3.22f1 running on a Windows 11 PC set to Português (Portuguese).

**Comment by paulinon** [comment]
Hi folks,

It appears that the issue you're reporting is similar to what's described in this [ticket](https://github.com/firebase/firebase-cpp-sdk/issues/1367) in the C++ repository, and a [fix](https://github.com/firebase/firebase-cpp-sdk/pull/1375) for this is currently in progress. That said, I'll be closing this for now, and you may check the aforementioned threads for updates.
