### ISSUE TITLE
[Bug] Unable to load Firebase app options ([C:/Users/eren/OneDrive/Masaüstü/Unity/Below Hell/Assets/StreamingAssets\google-services-desktop.json, C:/Users/eren/OneDrive/Masaüstü/Unity/Below Hell/Assets/StreamingAssets\google-services.json] are missing or malformed) UnityEngine.Debug:LogError (object) Firebase.Platform.FirebaseLogger:LogMessage (Firebase.Platform.PlatformLogLevel,string) Firebase.LogUtil:LogMessage (Firebase.LogLevel,string) Firebase.LogUtil:LogMessageFromCallback (Firebase.LogLevel,string) Firebase.AppUtil:PollCallbacks () Firebase.Platform.FirebaseAppUtils:PollCallbacks () Firebase.Platform.FirebaseHandler:Update () Firebase.Platform.FirebaseMonoBehaviour:Update ()

### ISSUE THREAD

**Issue by johntitor08** [firebase/firebase-unity-sdk#790]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @johntitor08,

Thanks for bringing this to our attention. It appears that the issue you're filing is similar to what's described in #405. A workaround for this would be to use a path for your Unity project the doesn't contain non-ASCII characters. That said, I'll be closing this for now, and you may refer to the aforementioned thread for updates.
