### ISSUE TITLE
upload-symbols high memory usage, brings system to a halt

### ISSUE THREAD

**Issue by kjyv** [firebase/firebase-unity-sdk#81]
Operating system: macOS
Operating system version: 11.6
Firebase version: 8.4.0

What steps will reproduce the problem:

1. Build project (Unity) to Xcode, finish build in Xcode

What is the expected result?

upload-symbols to finish after some time with a resonable amount of memory usage

What happens instead of that?

upload-symbols process stays open, uses more or less 100% cpu (1 core) all the time and brings my system almost to a standstill with more than 4gb used by upload-symbols. I have to kill it manually. Upload-symbols is a child process of the xcode build. It does not happen on every build. The same did not happen in 8.2.0.

Please provide any other information below, and attach a screenshot if possible.

I can see it in the ps output like this:
/bin/sh /Users/.../build/iOS/Pods/FirebaseCrashlytics/run -gsp /Users/.../build/iOS/GoogleS
ervice-Info.plist
/Users/.../build/iOS/Pods/FirebaseCrashlytics/upload-symbols -gsp /Users/.../build/iOS/GoogleService-Info.plist --build-phase

I realize that this is not much information to work with, so let me know if I can provide any stack traces from the running process or log entries that would help (and ideally info on how to retrieve it).

**Comment by samedson** [comment]
Hey @kjyv - I'm going to close this and talk on the ios-sdk Issue
