### ISSUE TITLE
How to make login page use firebase for windows in unity

### ISSUE THREAD

**Issue by Ahmedalmohr1212** [firebase/firebase-unity-sdk#821]
How to make login page use firebase for windows in unity

**Comment by paulinon** [comment]
Hi @Ahmedalmohr1212,

I see that you would like to create a login page that makes use of Firebase for a Windows build. To do this, you will need to utilize [Firebase Authentication](https://firebase.google.com/docs/auth/unity/start) as it provides backend services to authenticate users to your app whether via passwords, phone numbers, or identity providers such as Google, Facebook and Twitter.

You may check out the documentation I provided for more information. To see a working implementation, you can use our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) project as reference.
