### ISSUE TITLE
[Question] Unity3D build StackTraceType effect on Crashlytics?

### ISSUE THREAD

**Issue by dhiru1602** [firebase/firebase-unity-sdk#822]
* Unity editor version: 2021.3.14f1
  * Firebase Unity SDK version: 10.4.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Crashlytics, Messaging
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Android
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Prebuilt

When building a Unity3D project with StackTraceType set to None, the Crashlytics Dashboard doesn't show proper stacktraces even when debugging symbols are uploaded using the Firebase CLI.

Is it required to have the StackTraceType in the Unity project build settings set to ScriptOnly or Full for the Crashlytics to work?

![image](https://github.com/firebase/firebase-unity-sdk/assets/1326273/ad74ad37-906b-41b4-a5d7-b380a4225cce)

**Comment by paulinon** [comment]
Hi @dhiru1602,

If the Stack Trace Type is set to none, no stack trace will be shown in the output to log. It's best that you set its type to either ScriptOnly where managed stack trace will be shown or Full to show the native and managed stack traces.
