### ISSUE TITLE
[Bug] Code working on Mac M1, but not in a Windows Computer (Same Project)

### ISSUE THREAD

**Issue by Totoped157** [firebase/firebase-unity-sdk#832]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.15f1
  * Firebase Unity SDK version: 11.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database (Firestore)
  * Other Firebase Components in use: Auth (Storage is called but not used)
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the issue here:

I have a code to create a prefab foreach Document I find in a Database. Problem: When I run the code on Windows, it doesn't work, but when I try the same project in apple (mac m1) it works fine. The project was created on Windows.

#### Steps to reproduce:

Copy my code and try it on Windows and Mac¿

#### Relevant Code:

Document Path: "/mailsUsuarios/VzQx7anQNSU0gjywF93FoS7ptiD2/inbox/Uh4CfvRfb3qxcLR5ZcqJ"

![image](https://github.com/firebase/firebase-unity-sdk/assets/67470263/6c934e80-b1de-4f51-8e8b-fe08902793ef)
![image](https://github.com/firebase/firebase-unity-sdk/assets/67470263/28a807e9-b8d2-493c-94a7-ac928d0ef47e)

```storage = FirebaseStorage.DefaultInstance;
db = FirebaseFirestore.DefaultInstance;
auth = FirebaseAuth.DefaultInstance;
string currentUserID = auth.CurrentUser.UserId;
Query mailsRef = db.Collection($"/mailsUsuarios").Document($"/{currentUserID}").Collection("/inbox");
await mailsRef.GetSnapshotAsync().ContinueWithOnMainThread(task => 
{
       QuerySnapshot snapshot = task.Result;
       Debug.Log(snapshot);
       Debug.Log("PREFOREACH");
       foreach (DocumentSnapshot documentSnapshot in snapshot.Documents)
       {
             Debug.Log(documentSnapshot.Id);
        }
        Debug.Log("POSTFOREACH");
        });
        Debug.Log("No more Documents");
}

**Comment by cherylEnkidu** [comment]
@Totoped157 
Hi, could you explain more on "did not work"? Is it when you are trying to get the same document under the same path, Mac project can have the documents while Windows one cannot?

**Comment by Totoped157** [comment]
Correct, I ran the same code on Mac (trying to acces the same document using the foreach) and got the document data, but when I tried on Windows the same code/project, it runs the foreach but it detects that there are no Documents in snapshot.Documents so it doesn't run any code inside the foreach (but in the screenshot you can see that there is a document). Thanks!

> @Totoped157 Hi, could you explain more on "did not work"? Is it when you are trying to get the same document under the same path, Mac project can have the documents while Windows one cannot?

**Comment by dconeybe** [comment]
@Totoped157 Could you try removing the leading forward slashes in the arguments to the invocations of `Collection()` and `Document()`? Namely, change

```
Query mailsRef = db.Collection($"/mailsUsuarios").Document($"/{currentUserID}").Collection("/inbox");
```

to

```
Query mailsRef = db.Collection($"mailsUsuarios").Document($"{currentUserID}").Collection("inbox");
```

**Comment by Totoped157** [comment]
Still not working, here is the full code (The another one was adapted so it was shorter but neither of them work)

```public async void BandejaDeEntrada(){
            storage = FirebaseStorage.DefaultInstance;
            db = FirebaseFirestore.DefaultInstance;
            auth = FirebaseAuth.DefaultInstance;
            string currentUserID = auth.CurrentUser.UserId;
            Query mailsRef = db.Collection("mailsUsuarios").Document($"{currentUserID}").Collection("inbox");
            await mailsRef.GetSnapshotAsync().ContinueWithOnMainThread(task =>
           {
               if (task.IsCanceled || task.IsFaulted)
               {
                   Debug.Log(task.Result);
               }
               if (task.IsCompletedSuccessfully)
               {
                   Debug.Log("started");
                   Debug.Log(task.Result.Documents); // Result always: [ ]
                   Debug.Log(task.Result.Count); // Result always: 0
                   foreach (DocumentSnapshot documentSnapshot in task.Result.Documents)
                   {
                       Debug.Log("Test 1");
                       Dictionary<string, object> mail = documentSnapshot.ToDictionary();
                       GameObject newMail = Instantiate(mailPrefab, mailContainer.transform, false);
                       TMP_Text newMailText = newMail.transform.Find("Texto").GetComponent<TMP_Text>();
                       RectTransform newMailTextRect = newMail.transform.Find("Texto").GetComponent<RectTransform>();
                       bool mailLeido = !(bool)mail["leido"];
                       Debug.Log("Test 2");
                       int index = mail["senderMail"].ToString().IndexOf("@colegiodelsalvador.com");
                       string senderName = mail["senderMail"].ToString().Remove(index, "@colegiodelsalvador.com".Length);
                       Timestamp f = (Timestamp)mail["fecha"];
                       Debug.Log("Test 3");
                       DateTime fecha = f.ToDateTime().ToUniversalTime();
                       string fechaString = "Sin Reconocer";
                       switch (fecha.Month.ToString())
                       {
                           //not important :)
                       }
                       GetPFP(mail["senderID"].ToString(), newMail.transform.Find("TopInfo").Find("MiniPFP MASK").Find("PFP").GetComponent<Image>());
                       newMail.transform.Find("ReadOrNot").gameObject.SetActive(mailLeido);
                       Debug.Log("Test 4");
                       newMail.transform.Find("TopInfo").Find("Name").GetComponent<Text>().text = senderName + " | Alumno"; 
                       newMail.transform.Find("Asunto").GetComponent<Text>().text = mail["asunto"].ToString();
                       newMail.transform.Find("More Info").GetComponent<Button>().onClick.AddListener(()=> ChangeTextSize(newMailTextRect, newMailText, newMail.transform.Find("More Info").GetComponent<RectTransform>()));
                       newMail.transform.Find("Fecha").GetComponent<Text>().text = $"{fecha.Day} de {fechaString} del {fecha.Year} | {fecha.Hour}:{fecha.Minute}";
                       newMailText.text = mail["body"].ToString();
                       Debug.Log("Mail generado perfectamente");
                   }
               }
           });
        }

**Comment by dconeybe** [comment]
@Totoped157 Could you enable debug logging and attach the logs from both mac and Windows, so we can diff them?

To enable debug logging, set `FirebaseFirestore.LogLevel = LogLevel.Debug`

https://firebase.google.com/docs/reference/unity/class/firebase/firestore/firebase-firestore#loglevel

**Comment by Totoped157** [comment]
I don't understand why but when changing the LogLevel to .Debug it started working perfectly fine. Anyways Thanks and tell me if you need any extra Information! 

PD: Is normal that firestore takes to much time to load? Because when calling the function it takes some seconds to load.

**Comment by dconeybe** [comment]
Yikes that sounds like a race condition. If you see the issue again with debug logging enabled please send your logs.
