### ISSUE TITLE
[Bug] SendPushNotification FirebaseMessagingError: Auth error from APNS or Web Push Service

### ISSUE THREAD

**Issue by surajsk1812** [firebase/firebase-unity-sdk#840]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.8f1
  * Firebase Unity SDK version: 10.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Apple SignIn, AppsFlyer, CleverTap, Google SignIn.
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: https://firebase.google.com/download/unity

### [REQUIRED] Please describe the issue here: 
In android we are getting push notifications but not in iOS. I have added the logs below please check it. 

SendPushNotification FirebaseMessagingError: Auth error from APNS or Web Push Service

    at Function.fromServerError (/var/www/LUDO-BRAWL-LIVE/API/node_modules/firebase-admin/lib/utils/error.js:254:16)

    at createFirebaseError (/var/www/LUDO-BRAWL-LIVE/API/node_modules/firebase-admin/lib/messaging/messaging-errors-internal.js:35:47)

    at /var/www/LUDO-BRAWL-LIVE/API/node_modules/firebase-admin/lib/messaging/messaging-api-request-internal.js:79:75

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async /var/www/LUDO-BRAWL-LIVE/API/src/library/utilityLib/pushNotification.js:38:17

    at async Promise.all (index 0)

    at async /var/www/LUDO-BRAWL-LIVE/API/src/library/utilityLib/pushNotification.js:16:5

    at async Timeout._onTimeout (/var/www/LUDO-BRAWL-LIVE/API/notificationHandler.js:69:9) {

  errorInfo: {

    code: 'messaging/third-party-auth-error',

    message: 'Auth error from APNS or Web Push Service'

  },

  codePrefix: 'messaging'

}

**Comment by paulinon** [comment]
Hi @surajsk1812,

Could you confirm if both your app and APNs authentication key are properly configured in the Firebase console? It's possible that an incorrect App Store ID, Bundle ID, or Team ID is causing this to happen.

Otherwise, you may raise this ticket to [Firebase Support](https://firebase.google.com/support) as the cause of this issue may lie within your console's configuration rather than the SDK.
