### ISSUE TITLE
[Bug] On the crashlytics page in dashboard, the title and content are displayed differently

### ISSUE THREAD

**Issue by ShockRabbit** [firebase/firebase-unity-sdk#843]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.26f1, 2021.3.16f1
  * Firebase Unity SDK version: 9.3.0, 10.7.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, RemoteConfig, Storage (Auth, Database, etc.)
  * Additional SDKs you are using: facebook, appsflyer, max mediation etc (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: android, ios (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: -

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.) 
<br/>
<br/>
This is an issue with dashboard (console.firebase.google.com/). 

On the crashlytics page in dashboard, the title and content are displayed differently. 

For example 

```
# title
java.lang.Exception
java.lang.Exception - Exception : [ASSERT]_Status_==_ItemStatus.Locked EndlessTreasure.Custom.<UnlockAsync>d__38:MoveNext() EndlessTreasure.Custom.EndlessTreasureItemView:UnlockAsyn... 

# contents
Non-fatal Exception: java.lang.Exception
Exception : [ASSERT]_AdManager.IsPossibleToShowInterstitial_InterstitialInst_is_null AdManager:IsPossibleToShowInterstitial(String, Boolean) AdManager:ShowInterstitial(String, Boolean, Action`1) System.Action:Invoke() <yieldThenAction>d__0:MoveNext() UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Have you had any issues like this? 

Or is there a possibility that I'm doing something wrong that could be causing this?

Previously, multiple assertions were sometimes grouped into a single item, but never with different titles and content.

#### Steps to reproduce:
-

#### Relevant Code:
-

**Comment by paulinon** [comment]
Hi @ShockRabbit,

I understand that you may have found an issue with the crashes as seen in your dashboard. You may raise this to [Firebase Support](https://firebase.google.com/support) as they are better suited in handling these kinds of issues. Make sure you include any information related to your project so that your agent would be able to identify the cause of your behavior quicker.
