### ISSUE TITLE
Unity: DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_3_0'. Tried the load the following dynamic libraries: Unable to load dynamic library 'FirebaseCppApp-11_3_0' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "FirebaseCppApp-11_3_0" not found

### ISSUE THREAD

**Issue by wanglelewang** [firebase/firebase-unity-sdk#845]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2022.3.0f1c1____
  * Firebase Unity SDK version: _11.3.0____
  * Source you installed the SDK: __UPM___ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: __FCM Crash Analytics___ (Auth, Database, etc.)
  * Other Firebase Components in use: __FCM Crash Analytics___ (Auth, Database, etc.)
  * Additional SDKs you are using: __No___ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __Mac___ (Mac, Windows, or Linux)
  * Platform you are targeting: __Android___ (iOS, Android, and/or desktop)
  * Scripting Runtime: __IL2CPP___ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _https://developers.google.cn/unity/archive?hl=zh-cn____

### [REQUIRED] Please describe the issue here:
 
In My project , I use UPM import Firebase SDKs, then, build for android,  but error

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                m_app = Firebase.FirebaseApp.DefaultInstance;

                Debug.Log("FCMManager Firebase Init Suceess");
                // Set a flag here to indicate whether Firebase is ready to use by your app.
            }
            else
            {
                Debug.LogError(System.String.Format(
                  "FCMManager Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });

**Comment by paulinon** [comment]
Hi @wanglelewang,

Thanks for bringing this to our attention. Could you confirm if going to Assets > External Dependency Manager > Android Resolver > Force Resolve makes any difference? Also, [version 11.4.0](https://firebase.google.com/support/release-notes/unity#version_1140_-_august_17_2023) of the SDK has been released recently. Could you try this version and see if the issue persists?

**Comment by wanglelewang** [comment]
close it , because External Dependency Manager Download error
