### ISSUE TITLE
[Bug] DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_4_0'

### ISSUE THREAD

**Issue by johntitor08** [firebase/firebase-unity-sdk#856]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

Error:
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_4_0'. Tried the load the following dynamic libraries:  Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE.SWIGExceptionHelper' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.

**Comment by a-maurice** [comment]
This is a common issue with project configuration.  What platform are you running on that is getting this error?  Are all the Firebase SDKs that you are using the version at 11.4.0?

**Comment by kosars** [comment]
Have same error even on firebase database test project (https://github.com/firebase/quickstart-unity/tree/master/database/testapp)

@Antonio-Gorisek not worked for me

Unity editor version: 2022.3.8f1
Firebase Unity SDK version: 11.4.0
Source you installed the SDK: FirebaseDatabase.unitypackage
Problematic Firebase Component: Database
Other Firebase Components in use: none
Additional SDKs you are using: none
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android
Scripting Runtime: tried both Mono and IL2CPP

Error:
DllNotFoundException: FirebaseCppApp-11_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4087)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4107)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4817)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:2014)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Database.UIHandler.Start () (at Assets/Firebase/Sample/Database/UIHandler.cs:53)

**Comment by johntitor08** [comment]
> This is a common issue with project configuration. What platform are you running on that is getting this error? Are all the Firebase SDKs that you are using the version at 11.4.0?

webgl

**Comment by Andrii-Perevoznyi** [comment]
Absolutely same here! Tried all found solutions. Reinstall SDK, Force Resolve, reinstall C++ redist nothing helps. This happens for me in editor with first request on any Firebase library from code in runtime.

Unity editor version: 2022.3.8f1
Firebase Unity SDK version: 11.4.0
Source you installed the SDK: FirebaseAnalytics.unitypackage, FirebaseCrashlytics.unitypackage, FirebaseRemoteConfig.unitypackage, FirebaseMessaging.unitypackage
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android


DllNotFoundException: FirebaseCppApp-11_4_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4087)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4107)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4817)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Crashlytics.Crashlytics+PlatformAccessor..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/crashlytics/src/Crashlytics.cs:143)
Rethrow as TypeInitializationException: The type initializer for 'PlatformAccessor' threw an exception.
Firebase.Crashlytics.Crashlytics.set_IsCrashlyticsCollectionEnabled (System.Boolean value) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/crashlytics/src/Crashlytics.cs:52)
Enixan.Engine.Adapters.FirebaseCrashlyticsAdapter..ctor (Zenject.SignalBus signalBus, Enixan.Engine.Configs.IMainConfig mainConfig, Enixan.Engine.Adapters.FirebaseConnector firebaseConnector) (at Assets/EnixanEngineSubmodule/Scripts/Runtime/Adapters/Firebase/FirebaseCrashlyticsAdapter.cs:25)

**Comment by Andrii-Perevoznyi** [comment]
Unfortunately no success with my experiments. Only one option i have now that my Windows version after update becames to be incompatible with some of .Net things =(

**Comment by Andrii-Perevoznyi** [comment]
No need to make webgl build. Just wanted to make it alive in editor with
Android target platform

**Comment by Andrii-Perevoznyi** [comment]
Tried on my laptop. Works perfectly. Only differences are 
Windows 10 Hone 22H2
Processor Intel Core i7-4710HQ, 2,5GHz
x64

**Comment by Andrii-Perevoznyi** [comment]
more updates

Everything goes well with unity 2021.3.30f1 on Windows 10 Enterprise x64 + i5-6500 x64
Start failing with this exception with Unity 2022.3.8

**Comment by Nghidang14** [comment]
> Tried on my laptop. Works perfectly. Only differences are Windows 10 Home 22H2 Processor Intel Core i7-4710HQ, 2,5GHz x64

Me too, my laptop met same error. But my team don't.
I use Windows 10 core i3-4005U, 1696MHz, x64

**Comment by ogix-mimura** [comment]
@Nghidang14 
Try this.
https://github.com/firebase/firebase-unity-sdk/issues/443#issuecomment-1231976123

In my case. it solved by installation of 'c++ redistributable 2022'.

**Comment by argzdev** [comment]
Hey folks, it looks like everybody might have similar problems with different resolutions. Please file a new issue with your concern so that we can cater to each developer's specific issue. That said, it does look like the issue has been resolved with the proposed fixes, so I'll go ahead and close this thread.
