### ISSUE TITLE
[Bug] java.lang.SecurityException: "Writable dex file is not allowed. " error on Android 14 emulator.

### ISSUE THREAD

**Issue by thorikawa** [firebase/firebase-unity-sdk#865]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.1
  * Firebase Unity SDK version: 11.4.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Messaging, Crashlytics
  * Additional SDKs you are using: Adjust SDK
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-build SDK

### [REQUIRED] Please describe the issue here:

When launching an app that runs Firebase Analytics on an Android 14 emulator, it consistently crashes. The logs indicate an exception with the message: 
```
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691] Pending exception java.lang.SecurityException: Writable dex file '/data/user/0/com.google.firebase.unity.analytics.testapp/cache/app_resources_lib.jar' is not allowed.
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at java.lang.Object dalvik.system.DexFile.openDexFileNative(java.lang.String, java.lang.String, int, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:-2)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at java.lang.Object dalvik.system.DexFile.openDexFile(java.lang.String, java.lang.String, int, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:406)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.DexFile.<init>(java.lang.String, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:128)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.DexFile.<init>(java.io.File, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:101)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at dalvik.system.DexFile dalvik.system.DexPathList.loadDexFile(java.io.File, java.io.File, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexPathList.java:438)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at dalvik.system.DexPathList$Element[] dalvik.system.DexPathList.makeDexElements(java.util.List, java.io.File, java.util.List, java.lang.ClassLoader, boolean) (DexPathList.java:397)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.DexPathList.<init>(java.lang.ClassLoader, java.lang.String, java.lang.String, java.io.File, boolean) (DexPathList.java:166)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.BaseDexClassLoader.<init>(java.lang.String, java.lang.String, java.lang.ClassLoader, java.lang.ClassLoader[], java.lang.ClassLoader[], boolean) (BaseDexClassLoader.java:160)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.BaseDexClassLoader.<init>(java.lang.String, java.io.File, java.lang.String, java.lang.ClassLoader) (BaseDexClassLoader.java:105)
2023/09/18 23:50:58.236 4896 4986 Fatal alytics.testapp runtime.cc:691]   at void dalvik.system.DexClassLoader.<init>(java.lang.String, java.lang.String, java.lang.String, java.lang.ClassLoader) (DexClassLoader.java:55)
```
(Full logcat attached)
[android14_analytics_log.txt](https://github.com/firebase/firebase-unity-sdk/files/12649519/android14_analytics_log.txt)

#### Steps to reproduce:

It reproduces on Android 14 emulator 100% of the time, but not sure it happens on the actual Android 14 too. ( I don't have Android 14 device, sorry)

1. Launch Android Studio and open Device Manager.
2. Create a new device with the following specifications: Device model - Pixel 6 Pro, API Level 34, and all other settings set to default.
3. Boot up the device created in the previous step.
4. Build a sample project for Android that only runs Firebase Analytics, and execute it on the emulator booted up in the previous step.
5. Confirm that the app has crashed.

I am attaching the minimal Unity project where this bug occurs. It is the analytics sample project from the original repository."
https://drive.google.com/file/d/17B08SQZ1W-cOmba9u236Ci0In2YwG3ct/view?usp=sharing

**Comment by paulinon** [comment]
Hi @thorikawa,

Thanks for reporting this issue. I was able to reproduce the issue you described using the sample project you provided along with the steps you listed. That said, I'll relay my observations to the team so that they can take a look at what's causing this. I'll be marking this as a bug for now.

**Comment by a-maurice** [comment]
This should be fixed with the latest release, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.5.0.  Thanks for bringing this to our attention.
