### ISSUE TITLE
[Question] DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_4_0'.

### ISSUE THREAD

**Issue by johntitor08** [firebase/firebase-unity-sdk#867]
<html>
<body>

  | _JS_Log_Dump | @ | WebGL Builds.framework.js.gz:10
-- | -- | -- | --
  | $func1132 | @ | WebGL Builds.wasm.gz:0xe3923
  | $func102318 | @ | WebGL Builds.wasm.gz:0x21f10ef
  | $func102314 | @ | WebGL Builds.wasm.gz:0x21f0ee7
  | $func102312 | @ | WebGL Builds.wasm.gz:0x21f0575
  | $func98380 | @ | WebGL Builds.wasm.gz:0x21354b6
  | $func98381 | @ | WebGL Builds.wasm.gz:0x2135649
  | $func98401 | @ | WebGL Builds.wasm.gz:0x2136681
  | $func82989 | @ | WebGL Builds.wasm.gz:0x17de4db
  | $func82990 | @ | WebGL Builds.wasm.gz:0x17de4f0
  | $func98287 | @ | WebGL Builds.wasm.gz:0x212fbbe
  | $func97901 | @ | WebGL Builds.wasm.gz:0x2104ed3
  | $func97840 | @ | WebGL Builds.wasm.gz:0x20fb5df
  | $func97840 | @ | WebGL Builds.wasm.gz:0x20fb652
  | $func102432 | @ | WebGL Builds.wasm.gz:0x21fdc82
  | $dynCall_v | @ | WebGL Builds.wasm.gz:0x221d697
  | browserIterationFunc | @ | WebGL Builds.framework.js.gz:10
  | callUserCallback | @ | WebGL Builds.framework.js.gz:10
  | runIter | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_scheduler_rAF | @ | WebGL Builds.framework.js.gz:10
  | Browser_mainLoop_runner | @ | WebGL Builds.framework.js.gz:10

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by paulinon** [comment]
Hi @johntitor08,

It seems that these logs don't reference Firebase, and I noticed that this ticket has a similar title with #856 which you filed. If you have any relevant updates, you may add them in the aforementioned ticket so that the discussion can be contained in one thread.
