### ISSUE TITLE
[Bug] SIGSEGV FirebaseMessagingPINVOKE.delete_FirebaseMessage from Crashlytics report.

### ISSUE THREAD

**Issue by Gong-Tien** [firebase/firebase-unity-sdk#871]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.0f1
  * Firebase Unity SDK version: 10.6.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase Messaging
  * Other Firebase Components in use: Auth, Analytics
  * Platform you are using the Unity editor on: Mac & Windows
  * Platform you are targeting: Android,
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity)

### [REQUIRED] Please describe the issue here:

We seeing some crash via crashlytics from our users 

#### Steps to reproduce:

Not able to reproduce locally, but we keep seeing this crash logs from our users in crashlytics.

#### Relevant Code:

Nothing special, just following guideline as usual. Here is some example crash logs.

```
Crashed: Thread: SIGSEGV  0x0000007fa613b63c
#00 pc 0x4f9ec libc.so (BuildId: 1bcad8bca80d38bceb9089f70d394e33)
#01 pc 0x4f578 libc.so (BuildId: 1bcad8bca80d38bceb9089f70d394e33)
#02 pc 0x6e6dc49100
#03 pc 0x6e6dc49750
#04 pc 0x6e6dc49700
#05 pc 0x1d3e040 libil2cpp.so (FirebaseMessagingPINVOKE.delete_FirebaseMessage) (BuildId: 0a3f0042d1e81ab7de308c50e9bdf3955fc0a4ea)
#06 pc 0x10fc424 libil2cpp.so (il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**)) (BuildId: 0a3f0042d1e81ab7de308c50e9bdf3955fc0a4ea)
#07 pc 0x8ebdc libc.so (BuildId: 1bcad8bca80d38bceb9089f70d394e33)
```

**Comment by paulinon** [comment]
Hi @Gong-Tien,

[Version 11.5.0](https://firebase.google.com/support/release-notes/unity#version_1150_-_september_21_2023) of the SDK has been released  recently. Could you try it out and see if the issue still persists?

**Comment by Gong-Tien** [comment]
@paulinon Thank you for getting back to me. I will discuss with the team about this suggestions and keep you posted.
