### ISSUE TITLE
[Bug] FirebaseCppApp-11_5_0.bundle cannot be opened because developer cannot be verified

### ISSUE THREAD

**Issue by navarone77** [firebase/firebase-unity-sdk#872]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.3
  * Firebase Unity SDK version: 11.5.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: realtime database (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac  (Mac, Windows, or Linux)
  * Platform you are targeting: Desktop (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the issue here:

Downloaded the package , followed video on that page for unity, writing to database and hitting playmode i got this error 
<img width="327" alt="Screen Shot 2023-09-26 at 4 34 50 PM" src="https://github.com/firebase/firebase-unity-sdk/assets/97413201/21ef0091-e638-4b4b-85cd-b1b4ed3d15a9">

<img width="697" alt="Screen Shot 2023-09-26 at 4 45 35 PM" src="https://github.com/firebase/firebase-unity-sdk/assets/97413201/ad4616ef-4967-4fc0-af80-a36ff979d3e1">

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
DllNotFoundException: FirebaseCppApp-11_5_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4114)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4134)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4844)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:2041)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Database.FirebaseDatabase.get_DefaultInstance () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/database/src/FirebaseDatabase.cs:87)
PlayerSaveManager.Awake () (at Assets/DB/PlayerSaveManager.cs:16)

```

**Comment by paulinon** [comment]
Hi @navarone77,

When this error message appears, you need to go to your Mac's Privacy and Security Settings and allow downloading from `FirebaseCppApp-11_5_0.bundle` before you enter Play Mode. You may refer to this [page](https://firebase.google.com/docs/unity/build-debug-guide#ensure_that_you_approve_firebase_bundles_in_security_privacy_on_mac_os) for more information.

That said, I'll be closing this ticket. Let me know if an issue arises we can reopen this for discussion.

**Comment by navarone77** [comment]
> Hi @navarone77,
> 
> When this error message appears, you need to go to your Mac's Privacy and Security Settings and allow downloading from `FirebaseCppApp-11_5_0.bundle` before you enter Play Mode. You may refer to this [page](https://firebase.google.com/docs/unity/build-debug-guide#ensure_that_you_approve_firebase_bundles_in_security_privacy_on_mac_os) for more information.
> 
> That said, I'll be closing this ticket. Let me know if an issue arises we can reopen this for discussion.

Thanks, I've tried doing this but it did not work.
The first prompt did not give me any Allow/Open Option(screenshot1), so I hit Cancel then got another notification (screenshot2), I clicked Allow then Open as instructed and still get DLLNotFoundException.



<img width="871" alt="Screen Shot 2023-10-02 at 5 12 07 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/97413201/94d3db22-5a40-459c-8b64-742f294e05c6">

<img width="845" alt="Screen Shot 2023-10-02 at 5 12 26 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/97413201/2b8604eb-4df2-4e59-92b5-74ea006f0462">


<img width="793" alt="Screen Shot 2023-10-02 at 5 12 59 AM" src="https://github.com/firebase/firebase-unity-sdk/assets/97413201/64f6cc26-fe34-4b77-a9fb-1684552e2a2c">


Stacktrace:
`DllNotFoundException: FirebaseCppApp-11_5_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4114)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4134)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4844)
Firebase.LogUtil..ctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:2041)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Database.FirebaseDatabase.get_DefaultInstance () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/database/src/FirebaseDatabase.cs:87)
FireBd.Start () (at Assets/FireBd.cs:12)
`

**Comment by paulinon** [comment]
Hi @navarone77,

Does the issue persist when you press Play again? If so, could you confirm if [manually removing](https://firebase.google.com/docs/unity/setup-alternative#manual-removal) and reimporting the Firebase SDK then performing the troubleshooting steps I mentioned makes any difference?

If none of these worked, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that we can identify what's causing this to happen.

**Comment by navarone77** [comment]
> Hi @navarone77,
> 
> Does the issue persist when you press Play again? If so, could you confirm if [manually removing](https://firebase.google.com/docs/unity/setup-alternative#manual-removal) and reimporting the Firebase SDK then performing the troubleshooting steps I mentioned makes any difference?
> 
> If none of these worked, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that we can identify what's causing this to happen.

Hi @paulinon thanks response, unfortunately the issue still persisted, tried closing and opening project multiple times.

 I have also gone through and deleted all the files in assets then tried Importing SDK again, got some prompts with no success.. The project is a brand new one so nothing special going on there, nothing else in it besides this script I used to test:
 
https://gist.github.com/navarone77/773d7341f6b9aa2981993bf409a42d9a

**Video of whole process:**
https://youtu.be/D98aEcevB-Q
 <a href="http://www.youtube.com/watch?feature=player_embedded&v=D98aEcevB-Q" target="_blank">
 <img src="http://img.youtube.com/vi/D98aEcevB-Q/mqdefault.jpg" alt="Watch the video" width="240" height="180" border="10" />
</a>

I could not get Git to upload the whole project because of the .bundle files being over 100MB but LFS wasn't working for some reason but you want the full project is here: 

Using Unity 2022.3.3f
https://drive.google.com/drive/folders/1Ltjro_IR3Qqunr4CEbIqXZcGZoDnqVqR?usp=sharing

**Comment by paulinon** [comment]
Hi @navarone77,

Thanks for the update. I was able to get rid of the error message on my end, but I believe our macOS operating systems may be different. Could you provide the operating system you're using? Could you also try if either updating your operating system or using an older version of the Firebase SDK works for your use case so we can confirm if this is causing the issue in your implementation?
