### ISSUE TITLE
[Bug] Duplicate class com.google.firebase.ktx.Firebase found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime

### ISSUE THREAD

**Issue by MaxWhite87** [firebase/firebase-unity-sdk#874]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.48f
  * Firebase Unity SDK version: 11.5.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, Auth, Crashlytics, DynamicLinks, Messaging, RemoteCOnfig
  * Additional SDKs you are using: ApplovinMax, AppsFlyer
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android, desktop
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: repo

### [REQUIRED] Please describe the issue here:

Can't build android. Have following error:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.firebase.ktx.Firebase found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseCommonKtxRegistrar found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseCommonKtxRegistrar$getComponents$$inlined$coroutineDispatcher$1 found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseCommonKtxRegistrar$getComponents$$inlined$coroutineDispatcher$2 found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseCommonKtxRegistrar$getComponents$$inlined$coroutineDispatcher$3 found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseCommonKtxRegistrar$getComponents$$inlined$coroutineDispatcher$4 found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseKt found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)
     Duplicate class com.google.firebase.ktx.FirebaseKt$coroutineDispatcher$1 found in modules jetified-com.google.firebase.firebase-common-20.4.0-runtime (:com.google.firebase.firebase-common-20.4.0:) and jetified-com.google.firebase.firebase-common-ktx-20.3.3-runtime (:com.google.firebase.firebase-common-ktx-20.3.3:)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by MaxWhite87** [comment]
Have similar issue opened at unity forum, but no solution neither progress there yet
https://discussions.unity.com/t/gradle-fail-duplicate-class-com-google-firebase-ktx-firebase/297523

**Comment by MaxWhite87** [comment]
Problem started at Sunday 10/1/2023. All projects containing firebase can't build since then (have few projects, all have same issue)
Was at firebase 11.2.0, so I tried update to latest 11.5.0, didn't help. Seems it's not about sdk version

**Comment by omgnt199** [comment]
i have same issues this week and still can't fix this

**Comment by LSDemian** [comment]
Same issue. Got this on Firebase 10.3. Tried to update Firebase to the latest version and still have a build error.

**Comment by LSDemian** [comment]
Thank you for your reply @paulinon 
Yes, tried to run Force Resolve. Resolving dependencies takes about 5 minutes (which is much longer than usual), but build still fails. 
I'll try to reproduce this on the example project in a few hours

**Comment by Usslessvoid** [comment]
Кажется я нашёл решение. В файле Firebase/Editor/AppDependencies.xml зафиксировал версию firebase-common:[20.3.3], далее Force resolve и билд. Версия firebase 11.1.0

**Comment by TrieuIceTea** [comment]
> Resolved for me by the steps below:
> 
> 1. Run Force Resolve
> 2. In the `ProjectSettings/AndroidResolverDependencies.xml` find and delete a line that contains `com.google.firebase.firebase-common-ktx-20.3.3.aar`
> 3. Find and delete a file named `com.google.firebase.firebase-common-ktx-20.3.3.aar`
> 4. Turn off the "Enable Auto-Resolution" checkbox in the Android Resolver Settings

Right answer !
Or simply uncheck Android under its Include Platforms whenever building

**Comment by LSDemian** [comment]
Ok, I think I found a workaround for now. I just disabled `com.google.firebase.firebase-common-ktx-20.3.3.aar` library for the Android platform after resolving dependencies and turned off auto resolve and resolve during build.

In my case, the Facebook ad network adapter for Applovin is causing this error. Still don't know why this happened, same setup was working a few days ago.

**Comment by LSDemian** [comment]
Okay, another workaround that helped me is to edit the config file `Firebase/Editor/Appdependencies.xml` and remove these lines:
```
<androidPackage spec="com.google.firebase:firebase-common:20.3.3">
    </androidPackage>
```
As a result, after running force resolve I got 2 firebase libraries with the same version: `com.google.firebase.firebase-common-20.3.3` and `com.google.firebase.firebase-common-ktx-20.3.3`, and the build succeeded. @sulimannxx  might help in your case

**Comment by WuYangMBB** [comment]
> Resolved for me by the steps below:
> 
> 1. Run Force Resolve
> 2. In the `ProjectSettings/AndroidResolverDependencies.xml` find and delete a line that contains `com.google.firebase.firebase-common-ktx-20.3.3.aar`
> 3. Find and delete a file named `com.google.firebase.firebase-common-ktx-20.3.3.aar`
> 4. Turn off the "Enable Auto-Resolution" checkbox in the Android Resolver Settings

After trying these steps, I can build successfully, but the App stays in black after splash screen.

**Comment by liuzhuoyang** [comment]
a workaround, seems there's a version conflict between com.google.firebase.firebase-common-20.4.0 and firebase-common-ktx-20.3.3. To resolve this, I reverted to firebase.firebase-common-20.3.3, removed 20.4.0, and successfully built.

**Comment by spark9800** [comment]
It seems the bug in download_artifacts.gradle. I have a project and among transitive dependencies for different libraries there are versions: firebase-common:20.1.0, 20.2.0, 20.3.3 in project. and download_artifacts.gradle finally resolves them all as "firebase-common:+ " and it means it got last 20.4.0 version, that has conflict with  firebase-common-ktx-20.3.3.

if I change resolution strategy to patching mainTemplate.gradle  then all works fine and gradle resolves different dependencies (20.1.0, 20.2.0, 20.3.3) as 20.3.3 as expected, because it's highest version for this package through all libraries.

**Comment by ertugrulerdogan** [comment]
We have the same issue. firebase-common-20.4.2 and firebase-common-ktx-20.3.3 cause duplicate class error

**Comment by paulinon** [comment]
Thanks for the additional input, folks. I was able to reproduce this behavior using @LSDemian's sample project, and enabling both Custom Main Gradle Template and Custom Gradle Properties Template resolved the issue on my end. Resolution using the custom script in the External Dependency Manager in the Firebase SDK can be problematic at times. 

That said, does enabling both Custom Main Gradle Template and Custom Gradle Properties Template work with your use case?
