### ISSUE TITLE
[Bug] Version 11.16.0 wasn't actually updated to Firebase Cocoapods version 10.16.0

### ISSUE THREAD

**Issue by rubenwe** [firebase/firebase-unity-sdk#886]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: irrelevant
  * Firebase Unity SDK version: 11.16.0
  * Source you installed the SDK: tgz via package manager
  * Problematic Firebase Component: all of them
  * Other Firebase Components in use: most of them
  * Additional SDKs you are using: irrelevant for the issue
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android and iOS
  * Scripting Runtime: irrelevant
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) 

### [REQUIRED] Please describe the issue here:

Version 11.16.0 of the Unity SDK wasn't actually updated to Firebase Cocoapods version 10.16.0 as stated in the release notes

#### Steps to reproduce:

- Download the .tgz packages for the Unity release
- Inspect the Dependency.xml files
- Be astonished that the release notes are wrong
- Check the commit history here and realize the version was not adjusted for iOS ;)

**Comment by a-maurice** [comment]
Thanks for bringing this up.  This was an oversight on our parts, usually the releases include a version update, but it was skipped for this release to work out some issues that came up.  I will update the release notes accordingly.
