### ISSUE TITLE
Unity 2021 Editor crash on startup with 8.5.0 Firebase SDK

### ISSUE THREAD

**Issue by samskivert** [firebase/firebase-unity-sdk#89]
A skeleton project set up with Firebase App and Firebase Auth crashes Unity 2021.2 immediately on startup. The relevant error from the Editor.log is thus:

```
* Assertion at loader.c:345, condition `is_ok (error)' not met, function:mono_field_from_token, Could not resolve field token 0x0400001c, due to: Could not load type of field 'Firebase.Editor.GenerateXmlFromGoogleServicesJson:<>f__mg$cache0' (17) due to: Could not load file or assembly 'Google.JarResolver, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/Users/mdb/projects/bugs/unity-2021-firebase-files/Library/PackageCache/com.google.firebase.app@25e0485ee6cf-1636337084685/Firebase/Editor/Firebase.Editor.dll type:GenerateXmlFromGoogleServicesJson member:(null)
```

You can clone this repo: https://github.com/samskivert/unity-2021-firebase-crash and then put the requisite .tgz files from https://developers.google.com/unity/archive into GooglePackages in the top-level directory to repro the crash:

```
GooglePackages/com.google.external-dependency-manager-1.2.167.tgz
GooglePackages/com.google.firebase.app-8.5.0.tgz
GooglePackages/com.google.firebase.auth-8.5.0.tgz
```

Notably it _does not_ happen if the Unity SDK is added via the .unitypackage files, so something about installing the SDK via the package manager is tickling the bug.

I have not been able to devise a workaround, so it prevents us from upgrading from Unity 2020 (where it works) to Unity 2021 (where it crashes on startup).

**Comment by samskivert** [comment]
FWIW if you're just making a cursory examination of the error message `Google.JarResolver.dll` does exist, at the right location and it is the right version. So I think the _or one of its dependencies_ is the pertinent information here, but Mono helpfully does not tell us what downstream dependency is sticking a fort in things.

**Comment by ewnu** [comment]
still suffers from this issue in 8.6.2

**Comment by ryokomy** [comment]
I found this happens in the following versions as well
- 8.4.0
- 7.2.0

**Comment by softshadedev** [comment]
Hello comrades!
Installed Unity version 2021.2.6
Updated external-dependency-manager to version 1.2.168
Added package firebase-app-8.6.2

The editor didn't crash!

**Comment by samskivert** [comment]
Oh great day! Christmas has come early.

It's all working for us as well. Such a tiny diff to end our woe and suffering: https://github.com/googlesamples/unity-jar-resolver/commit/23a3eb72c53e62b8807a0e5f0535331f8af0178e

We still have to do some small hackery to keep things working on the new Apple Silicon Macs, but that's not too painful. For anyone that turns up here later chasing down that particular rabbit, see here: https://github.com/aroman/firebase-unity-applesilicon

I'm going to help out the Firebase team and call this closed. Upgrading EDM to 1.2.168 is the key fix.

**Comment by samskivert** [comment]
A few more details on the Apple Silicon workaround: using the .tgz files in conjunction with ASi just means installing the Firebase packages as normal via the package manager and then creating a directory in your `Assets` somewhere (like `Assets/Plugins/Firebase` but it can be called whatever you like) that has the `arm64` directory from the github project above. Unity will then complain that there are two copies of the Firebase libraries installed, but it will still correctly use the arm64 versions when running on Apple Silicon Macs.

Hopefully Google will eventually ship arm64 libraries as well for Firebase and all the hackery can end.
