### ISSUE TITLE
[Bug] Xcode 15 IL2CPP Threadpool worker (46): EXC_BAD_ACCESS (code=1, address=0x100000cfeedfac0)

### ISSUE THREAD

**Issue by WikyWu** [firebase/firebase-unity-sdk#890]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.16f1c1
  * Firebase Unity SDK version: 11.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Cloud Messaging 
  * Other Firebase Components in use: Crashlytics
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

I created a new empty Unity project, imported Firebase's Messaging, Crashlytics and other unity packages, and added the corresponding plist configuration file. Build the iOS project. When I run the project with xcode 15.0, the project terminates due to a bug. However, when I run the project with xcode 14.3, it can run normally.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
100%

What happened? How can we make the problem occur?
![crashInfo](https://github.com/firebase/firebase-unity-sdk/assets/92432345/7a737082-2ac6-42db-bcdd-e221c0670964)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

private void Awake()
    {
        FirebaseApp.LogLevel = LogLevel.Verbose;
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            var dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                FirebaseApp app = FirebaseApp.DefaultInstance;
                Debug.Log("this ensures that Firebase is initialized");
                // Set a flag here for indicating that your project is ready to use Firebase.
            }
            else
            {
                Debug.LogError(String.Format("Could not resolve all Firebase dependencies: {0}",dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
    }

**Comment by paulinon** [comment]
Hi @WikyWu,

Could you provide the macOS version you're using? I tried to replicate the issue with my macOS Sonoma device using the steps you provided, but there was no issue encountered on my end. However, I should point out that I'm using Xcode 15.0.1 and Firebase SDK version 11.5.0. 

Could you also confirm if updating both Xcode and the Firebase SDK then building a new Xcode project makes any difference?

**Comment by WikyWu** [comment]
Hi@paulinon 
my macOS is Sonoma 14.0, i tried to update the Firebase SDK version to 11.5.0, but the issue was encountered again, i will provide my unity demo for you,  could you run on your macOS Sonoma device and building a new Xcode project , test it works well or not, thanks!

**Comment by WikyWu** [comment]
Hi @paulinon.
my macOS is Sonoma 14.0, and i update the Firebase SDK version to 11.5.0, but the same issue was occurred. Could you provide some steps i should noticed ,maybe is usefully for me, thanks!

**Comment by paulinon** [comment]
Hi @WikyWu,

After importing the Firebase Cloud Messaging and Crashlytics SDKs, I attached a script containing the code you provided to a Main Camera object then built the app as normal. Could you provide the other Unity SDKs did you import into your project?

Also, I built the app using Unity 2022.3.11f1. Could you also try if updating the Unity editor did anything to your implementation?

**Comment by WikyWu** [comment]
@paulinon 
I tested and found that when the Unity Demo imported into Unity Firebase SDK 11.1.0 exports an iOS project, when the Xcode version is 14.3, no matter what the version of iOS Minnum DeployMents is, the iOS project runs OK; if the Xcode version >= 15.0, export iOS When Minnum DeployMents of the project is <14.0, the above bug will appear in the exported iOS project. If >=14.0, the iOS project runs OK. I wonder if the 11.1.0 version does not support Minnum DeployMents <14.0,The iOS project where the above bug occurred, I used Minnum DeployMents 12.0. I hope I can The test will work for you.

**Comment by WikyWu** [comment]
Hi @paulinon 
I tested and found that when the Unity Demo imported into Unity Firebase SDK 11.1.0 exports an iOS project, when the Xcode version is 14.3, no matter what the version of iOS Minnum DeployMents is, the iOS project runs OK; if the Xcode version >= 15.0, export iOS When Minnum DeployMents of the project is <14.0, the above bug will appear in the exported iOS project. If >=14.0, the iOS project runs OK. I wonder if version 11.1.0 does not support Minnum DeployMents <14.0 in Xcode15.0 or above. , hope my test is useful to you. The iOS project where the above bug occurred, I used Minnum DeployMents 12.0

**Comment by paulinon** [comment]
Thanks for the clarification, @WikyWu. Each Xcode version has a specific set of minimum requirements for deployment and supported SDKs. You can check out this [page](https://developer.apple.com/support/xcode/) for more information.

That said, I'll be closing this for now. Let me know if an issue arises.

**Comment by WikyWu** [comment]
Hi @paulinon,
Xcode 15.0 or 15.0.1 support the minimum deployment is 12.0, Maybe you should check Unity Firebase SDK 11.1.0 should set the minimum deployment 14.0, Thanks.

**Comment by WikyWu** [comment]
Hi@google-oss-bot @paulinon,
Xcode 15.0 or 15.0.1 support the minimum deployment is 12.0, Maybe you should check Unity Firebase SDK 11.1.0 should set the minimum deployment 14.0, Thanks.
