### ISSUE TITLE
What is the need for the huge .bundle files?

### ISSUE THREAD

**Issue by andypoly** [firebase/firebase-unity-sdk#894]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Any
  * Firebase Unity SDK version: latest 11.6.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: All - .bundle (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: na (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Win/Mac (Mac, Windows, or Linux)
  * Platform you are targeting: all except Linux (iOS, Android, and/or desktop)
  * Scripting Runtime: both (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: prebuilt

### [REQUIRED] Please describe the question here:

Please explain the need for the .bundle files which make this plugin unusable on some source-control systems without LFS/custom-changes because of the enormous size (FirebaseCppApp-11_6_0.bundle is over 100mb)
GitLab for instance has 100mb max commit size by default and on free tier.

You must remove the need for such big files for a code-only plugin.
What are the .bundle files needed for?

**Comment by chanon** [comment]
I am running into the same issue.
Is this 160MB file really needed?

**Comment by a-maurice** [comment]
There are a couple reasons for this, none of which are great.  The bundle file has support for both Mac architectures combined in the single file, which basically doubles the size.  I believe Unity does let you specify which architecture the bundle should be for, so it is possible to split them, we need to update our packaging logic to handle that case, across all the Unity versions we support.

The other problem is some of our dependencies are just big.  We've tried reducing them in size, and will continue to attempt so in the future.

For a workaround, you could edit the files yourself, using the lipo tool to split the architectures, and setting up your project with the one you want.

**Comment by Danejw** [comment]
Use Git LFS, open the folder with the .bundle file in it from a command line then enter **git lfs track “*.bundle”**

**Comment by argzdev** [comment]
Hey folks, I believe this question has been answered, with suggestions of possible alternatives. I'll go ahead and close this thread for now.
