### ISSUE TITLE
[Question] System.AggregateException: One or more errors occurred. (An internal error has occurred.) on CreateUserWithEmailAndPasswordAsync

### ISSUE THREAD

**Issue by ChurikiTenna** [firebase/firebase-unity-sdk#897]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.2.0b11
  * Firebase Unity SDK version: Latest
  * Source you installed the SDK: . unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

`auth.CreateUserWithEmailAndPasswordAsync` returns `An internal error has occurred.` error.
It doesn't specify exactly what is the problem. What should I check to resolve this error?

<img width="1013" alt="スクリーンショット 2023-11-10 9 21 07" src="https://github.com/firebase/firebase-unity-sdk/assets/52132649/33c73812-4ce1-44d6-8117-9c7b30779c09">

Code

```
auth.CreateUserWithEmailAndPasswordAsync(email, password).ContinueWith(task => {
            Debug.Log("CreateUserWithEmailAndPasswordAsync.done");
            if (task.IsCanceled) {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted) {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync.error " + task.Exception);
                errorText = task.Exception.Message;
            } else {
                Firebase.Auth.AuthResult result = task.Result;
                Debug.LogFormat("User signed in successfully: {0} ({1})", result.User.DisplayName, result.User.UserId);
                PopScreen();
            }
        });

```

**Comment by paulinon** [comment]
Hi @ChurikiTenna,

Have you enabled Email/Password sign-in for your Firebase project from the console? If so could you provide a full sample code so we could identify what's causing this to happen? It seems that both creating a user and signing in results in the internal error you're facing.

**Comment by ChurikiTenna** [comment]
Hi @paulinon !
Sorry for the late reply.

Yes. Email/Password is enabled.
<img width="1206" alt="スクリーンショット 2023-11-20 11 03 18" src="https://github.com/firebase/firebase-unity-sdk/assets/52132649/6c94e47f-d47e-43e2-a63f-79a8b2d290e1">


Full code:
```

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using Firebase.Firestore;
using Firebase.Auth;

public class FirebaseAuthHelper
{
    public FirebaseAuth auth;
    public FirebaseUser user;

    public FirebaseAuthHelper() 
    {
      Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
      InitializeFirebase();
    }
    public static FirebaseAuthHelper Create()
    {
        return new FirebaseAuthHelper();
    }

    void InitializeFirebase() {
      Debug.Log("Setting Up Firebase Auth");
      auth = FirebaseAuth.DefaultInstance;
      auth.StateChanged += AuthStateChanged;
      AuthStateChanged(this, null);
    }

    // Track state changes of the auth object.
    void AuthStateChanged(object sender, System.EventArgs eventArgs) {
        if (auth.CurrentUser != user) {
            bool signedIn = user != auth.CurrentUser && auth.CurrentUser != null;
            if (!signedIn && user != null) {
              Debug.Log("Signed out " + user.UserId);
            }
            user = auth.CurrentUser;
            if (signedIn) {
              Debug.Log("Signed in " + user.UserId);
            }
        }
    }

    void OnDestroy() {
      auth.StateChanged -= AuthStateChanged;
      auth = null;
    }
}

```

```
public void OnRegister() {

        var helper = new FirebaseAuthHelper();
        helper.auth.CreateUserWithEmailAndPasswordAsync(email, password).ContinueWith(task => {
            Debug.Log("CreateUserWithEmailAndPasswordAsync.done");
            if (task.IsCanceled) {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted) {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync.error " + task.Exception);
                errorText = task.Exception.Message;
            } else {
                Firebase.Auth.AuthResult result = task.Result;
                Debug.LogFormat("User signed in successfully: {0} ({1})", result.User.DisplayName, result.User.UserId);
                PopScreen();
            }
        });
    }
```

**Comment by paulinon** [comment]
Thanks for the update, @ChurikiTenna. Looking at the code you provided and the error message, the backend could be a possible cause of this behavior. You may raise this to [Firebase Support](https://firebase.google.com/support) as they are better suited in handling these kinds of issues. Make sure you include any information related to your project so that your agent would be able to identify the cause of your behavior quicker.
