### ISSUE TITLE
[Bug] In iOS 17.0 or above, an SSL error occurs in network requests and a secure connection to the server cannot be established.

### ISSUE THREAD

**Issue by WikyWu** [firebase/firebase-unity-sdk#899]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.10f1
  * Firebase Unity SDK version: 11.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component:  all package
  * Other Firebase Components in use: all
  * Additional SDKs you are using: no
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

In iOS 17.0 or above, an SSL error occurs in network requests and a secure connection to the server cannot be established. I searched for information and found that on iOS 17, Apple has strengthened its security policy and prohibited the use of this option. On iOS 17, if you try to set "Allow Arbitrary Loads in Web Content" to "YES", you will receive a wrong information. I removed the configuration Allow Arbitrary Loads in Web Content, and network requests were normal.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @WikyWu,

Does the issue persist even without the Firebase SDK in your implementation? If not, could you provide a sample code along with the complete steps in reproducing this behavior so we can identify what's causing this to happen?

**Comment by WikyWu** [comment]
Hi @paulinon ,
My above description is missing one condition, that is, my network request is initiated using AFNetworking. Maybe the "Allow Arbitrary Loads in Web Content" setting will affect the AFNetworking network request? Can you try this over there? Also, iOS17 prohibits the use of the "Allow Arbitrary Loads in Web Content" configuration. Does the Firebase SDK also need to adapt to iOS17?

**Comment by WikyWu** [comment]
Hi @paulinon ,
Has there been any progress on this issue

**Comment by argzdev** [comment]
Hi @WikyWu, thanks for reaching out. I'm not sure if I understand correctly, but this issue doesn't seem related to Firebase. Isn't this a restriction made by iOS to disable unsecured HTTP traffic? I believe our SDK is already making network calls via HTTPS, and it shouldn't be affected by this. However, if you are encountering this issue, could you provide a [minimal reproducible example](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) so that we can investigate this further? Thanks.
