### ISSUE TITLE
[Bug] Crash on Android 14 after adding Authentication with Firebase Authentication

### ISSUE THREAD

**Issue by Harsh-Khambhadiya** [firebase/firebase-unity-sdk#900]
* Unity editor version: 2021.3.21f1
  * Firebase Unity SDK version: 11.6.0
  * Source you installed the SDK: FirebaseAuth.unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: none
  * Additional SDKs you are using: GoogleSignIn (google-signin-plugin-1.0.4.unitypackage)
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android 9 and Higher
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) 

I want to use google sign in with the Firebase so that I add the GooglSigIn and Firebase.Auth Package in my UnityAndroid Project, After add I build an apk and test it on the mobile devices, it works perfact so that for beta testing I try to make an aab and upload onto the Google Play Store in Closed Testing but after making an aab and uploading it, application works perfactly on the android version 9 to 13 devices but when i tried to download it on the Android 14 device (Google Pixel 6 and 7 series) it crashes immedeatly after clicking on the app icon.

**Comment by paulinon** [comment]
Hi @Harsh-Xsquads,

While I try to reproduce this, could you provide the latest stack trace resulting from your app crashing so we can analyze what's causing this to happen? Are your stack traces similar to what's described in #863 or #865?

**Comment by murilobast** [comment]
Did it start to happen out of nowhere? I'm having reports from some users that they can't login but the issue resolves itself after some time, then i comes back again

**Comment by Harsh-Khambhadiya** [comment]
Thank you for response @paulinon @murilobast , I already tried by changing the firebase version to the 11.5.0 but issue not solved and yes @murilobast it was start out of nowhere and partial stack traces are, also I attached full stack trace file with this
(Currently this stack traces are with Firebase version 11.6.0)
[Full-logcat.txt](https://github.com/firebase/firebase-unity-sdk/files/13387822/Full-logcat.txt)


`Error AndroidRuntime FATAL EXCEPTION: main
Error AndroidRuntime Process: xsquads.scarfall.battleroyalegame, PID: 21577
Error AndroidRuntime java.lang.RuntimeException: Unable to start activity ComponentInfo{xsquads.scarfall.battleroyalegame/com.unity3d.player.UnityPlayerActivity}: java.lang.SecurityException: xsquads.scarfall.battleroyalegame: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
Error AndroidRuntime 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
Error AndroidRuntime 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:106)
Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:205)
Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:294)
Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8177)
Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Error AndroidRuntime Caused by: java.lang.SecurityException: xsquads.scarfall.battleroyalegame: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
Error AndroidRuntime 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
Error AndroidRuntime 	at android.os.Parcel.createException(Parcel.java:3041)
Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:3024)
Error AndroidRuntime 	at android.os.Parcel.readException(Parcel.java:2966)
Error AndroidRuntime 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
Error AndroidRuntime 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
Error AndroidRuntime 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
Error AndroidRuntime 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
Error AndroidRuntime 	at com.unity3d.player.UnityPlayer.<init>(Unknown Source:343)
Error AndroidRuntime 	at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:40)
Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8595)
Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8573)
Error AndroidRuntime 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
Error AndroidRuntime 	... 12 more
Error AndroidRuntime Caused by: android.os.RemoteException: Remote stack trace:
Error AndroidRuntime 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
Error AndroidRuntime 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
Error AndroidRuntime 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
Error AndroidRuntime 	at android.os.Binder.execTransactInternal(Binder.java:1339)
Error AndroidRuntime 	at android.os.Binder.execTransact(Binder.java:1275)
Error AndroidRuntime 
Info DropBoxManagerService add tag=data_app_crash isTagEnabled=true flags=0x2
Warn ActivityTaskManager   Force finishing activity xsquads.scarfall.battleroyalegame/com.unity3d.player.UnityPlayerActivity
Verbose WindowManagerShell Transition requested: android.os.BinderProxy@1fb659c TransitionRequestInfo { type = CLOSE, triggerTask = null, remoteTransition = null, displayChange = null }
Info Process Sending signal. PID: 21577 SIG: 9
Info ActivityManager Process xsquads.scarfall.battleroyalegame (pid 21577) has died: fg  TOP 
Info libprocessgroup Successfully killed process cgroup uid 10617 pid 21577 in 0ms
Info Zygote Process 21577 exited due to signal 9 (Killed)
Debug WindowManagerShell onFixedRotationFinished: TaskInfo{userId=0 taskId=1136 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.sonyliv/.ui.splash.SplashActivity } baseActivity=ComponentInfo{com.sonyliv/com.sonyliv.ui.home.HomeActivity} topActivity=ComponentInfo{com.sonyliv/com.sonyliv.ui.home.HomeActivity} origActivity=null realActivity=ComponentInfo{com.sonyliv/com.sonyliv.ui.splash.SplashActivity} numActivities=1 lastActiveTime=351241218 supportsMultiWindow=true resizeMode=0 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@651c525} topActivityType=1 pictureInPictureParams=PictureInPictureParams( aspectRatio=16/9 expandedAspectRatio=null sourceRectHint=Rect(0, 145 - 1440, 957) hasSetActions=true hasSetCloseAction=false isAutoPipEnabled=true isSeamlessResizeEnabled=false title=null subtitle=null isLaunchIntoPip=false) shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{a8066fa com.sonyliv.ui.home.HomeActivity} launchCookies=[android.os.BinderProxy@932334] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false topActivityLetterboxed= false isFromDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, state=PipTransitionState(mState=undefined, mInSwipePipToHomeTransition=false)
Debug DisplayManagerService Drop pending events for gone uid 10617
Info dzkq onResume
Error OneSearchSuggestProvider Failed to fetch suggestions from AppSearch, fallback to AGA
Error OneSearchSuggestProvider java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
Error OneSearchSuggestProvider 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:308)
Error OneSearchSuggestProvider 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:323)
Error OneSearchSuggestProvider 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:684)
Error OneSearchSuggestProvider 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:486)
Error OneSearchSuggestProvider 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2138)
Error OneSearchSuggestProvider 	at com.google.android.apps.nexuslauncher.allapps.H0.onResult(Unknown Source:59)
Error OneSearchSuggestProvider 	at android.app.appsearch.SearchSessionUtil$1.lambda$onResult$0(SearchSessionUtil.java:129)
Error OneSearchSuggestProvider 	at android.app.appsearch.SearchSessionUtil$1.$r8$lambda$_nlk9WiPjSfaAsqKYmp0aPvSRC0(SearchSessionUtil.java:1)
Error OneSearchSuggestProvider 	at android.app.appsearch.SearchSessionUtil$1$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:13)
Error OneSearchSuggestProvider 	at android.os.Handler.handleCallback(Handler.java:958)
Error OneSearchSuggestProvider 	at android.os.Handler.dispatchMessage(Handler.java:99)
Error OneSearchSuggestProvider 	at android.os.Looper.loopOnce(Looper.java:205)
Error OneSearchSuggestProvider 	at android.os.Looper.loop(Looper.java:294)
Error OneSearchSuggestProvider 	at android.os.HandlerThread.run(HandlerThread.java:67)
Error OneSearchSuggestProvider Caused by: java.util.NoSuchElementException: No value present
Error OneSearchSuggestProvider 	at java.util.Optional.get(Optional.java:144)
Error OneSearchSuggestProvider 	at com.google.android.apps.nexuslauncher.allapps.H0.onResult(Unknown Source:16)
Error OneSearchSuggestProvider 	... 8 more
`

**Comment by paulinon** [comment]
Hi @Harsh-Khambhadiya,

Based on the logs, it seems that registering receivers with intention using the RECEIVER_EXPORTED / RECEIVER_NOT_EXPORTED flag is a requirement for Android 14 onwards. A [fix](https://issuetracker.unity3d.com/issues/android-targetapi-34-crash-on-launch) has been introduced for certain Unity editor versions, so I recommend you build your app using a Unity edtor where the fix is applied. Let me know if an issue arises.
