### ISSUE TITLE
[Question] Could we get a new release with iOS-SDK 10.17+ included?

### ISSUE THREAD

**Issue by rubenwe** [firebase/firebase-unity-sdk#902]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: not relevant
  * Firebase Unity SDK version: not relevant
  * Source you installed the SDK: not relevant(.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: not relevant(Auth, Database, etc.)
  * Other Firebase Components in use: not relevant(Auth, Database, etc.)
  * Additional SDKs you are using: not relevant (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: not relevant(Mac, Windows, or Linux)
  * Platform you are targeting: not relevant (iOS, Android, and/or desktop)
  * Scripting Runtime: not relevant (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: not relevant

### [REQUIRED] Please describe the question here:

Hello!

We are experiencing massive issues with App Check on iOS. Users who change devices via Apple migration tooling are stuck in an unattested mode. This is affecting thousands of users of our app, given that a new iPhone came out not long ago and many folks migrated. The release notes for the iOS 10.17 SDK look promising and the person who made these changes even confirmed on X/Twitter that this might solve these issues. So the question is simple:

Could we please get a new release of the Unity SDK including these changes?

Thanks and have a great day!

**Comment by argzdev** [comment]
Just bumping this thread, I believe this version has been out sometime ago. That said, I'll go ahead and close this thread.
