### ISSUE TITLE
[Question] When can we expect the next release?

### ISSUE THREAD

**Issue by denzil-renderheads** [firebase/firebase-unity-sdk#905]
Sorry for skipping the template but I don't think its helpful for my simple question. Could you please let me know approximately when the next SDK will be released?

Some context: There is a crash affecting iOS 12 users which has already been fixed with the IOS version upgrade in this commit: https://github.com/firebase/firebase-unity-sdk/commit/24ee9fc41e67b7c10a4e8dce33303e8755fb033a

This was the equivalent crash in the iOS SDK https://github.com/firebase/firebase-ios-sdk/issues/1150

The issue will thus be resolved in the next release.

**Comment by rubenwe** [comment]
Given that I'm also waiting for a new release for iOS in #902 (without a reaction so far, which is still fine, it's only been a few days), I'd also love to know what the general release cycle for the Unity SDK is. Just so we can get a better feel for what we should expect as a time scale for critical fixes.

**Comment by paulinon** [comment]
Hi folks,

A new version of the Unity SDK is generally released monthly, so you can expect a new version in a few days. For now, you may tune in to our [release notes page](https://firebase.google.com/support/release-notes/unity) for updates.

**Comment by rubenwe** [comment]
@paulinon is there any news on a release? 

I think the period one could interpret as "a few days" has passed. I really dislike having to follow up on this, but again, this release is crucial for us. We have thousands of users affected by app check bugs.

Is there anything we can do to speed this up? Open support tickets somewhere else? Throw money at somebody in particular? It's not like we aren't paying millions in store fees and a good chunk for Firebase and Google Cloud products - but I'm happy to dedicate some funds if that buys us a certain level of support.

We've had previous bad experiences with support for Firebase features (in that case A/B testing numbers being wrong and forcing us to build our own system to evaluate results). We're currently scaling a new game. That game will also need backend services soon. If there is no way for us to get decent support we'll take our business elsewhere for that.
