### ISSUE TITLE
[Question] Issue resolving Firebase Crashlytics SDK 

### ISSUE THREAD

**Issue by bilalahadtech** [firebase/firebase-unity-sdk#906]
![Capture](https://github.com/firebase/firebase-unity-sdk/assets/151743241/90901ad2-2f17-4a29-96b1-0225683f7fbf)

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.30f1
  * Firebase Unity SDK version: 11.3.0 to 11.5.6.0
  * Source you installed the SDK: unity pack (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use:Analytics(Auth, Database, etc.)
  * Additional SDKs you are using: admobe  8.5.2 (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: android (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime:IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:
i am facing issue to resolving the firebase Crashlytics, when ever i import the analytics it will be resolved smoothly no matter which firebase version i use, but on importing Crashlytics the final resolving windows didn't close automatically, if i close it and makes build it will crash on start.

Stuck there. pic added for clarification

**Comment by paulinon** [comment]
Hi @bilalahadtech,

Enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings should be able to help you with this case. The generated files can handle the resolution better than the custom script in the resolver. Could you try this out and see if the issue persists?

**Comment by bilalahadtech** [comment]
> Hi @bilalahadtech,
> 
> Enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings should be able to help you with this case. The generated files can handle the resolution better than the custom script in the resolver. Could you try this out and see if the issue persists?

it doesnt show any resolving window and after making build, apk crashes on launch

**Comment by paulinon** [comment]
Hi @bilalahadtech,

Could you provide the complete steps you've performed before facing this behavior along with the [logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) that appear when the app crashes? Also, does the issue occur with just the Firebase SDK in your implementation?

**Comment by bilalahadtech** [comment]
> Hi @bilalahadtech,
> 
> Could you provide the complete steps you've performed before facing this behavior along with the [logs](https://docs.unity3d.com/Manual/android-debugging-on-an-android-device.html) that appear when the app crashes? Also, does the issue occur with just the Firebase SDK in your implementation?

the crash occurs due to not space issue in ads ids, that was fixed but Firebase crashlyics resolving still there, resolved with Version 11.0.0
