### ISSUE TITLE
[Bug] SIGSEGV FirebaseMessagingPINVOKE.delete_FirebaseMessage from Crashlytics report.

### ISSUE THREAD

**Issue by Gong-Tien** [firebase/firebase-unity-sdk#909]
[REQUIRED] Please fill in the following fields:

Unity editor version: 2021.3.0f1
Firebase Unity SDK version: 11.5.0
Source you installed the SDK: Unity Package Manager
Problematic Firebase Component: Firebase Messaging
Other Firebase Components in use: Auth, Analytics
Platform you are using the Unity editor on: Mac & Windows
Platform you are targeting: Android,
Scripting Runtime: IL2CPP
Pre-built SDK from the [website](https://firebase.google.com/download/unity)
[REQUIRED] Please describe the issue here:

We seeing some crash via crashlytics from our users

I also made a [bug report here.](https://github.com/firebase/firebase-unity-sdk/issues/871) . Which got suggested to update firebase version. However, the crash still appeared.

Steps to reproduce:

Not able to reproduce locally, but we keep seeing this crash logs from our users in crashlytics.

Relevant Code:

Nothing special, just following guideline as usual. Here is some example crash logs.

```
Crashed: Thread: SIGSEGV  0x00000087a1383e3c
#00 pc 0x4f9ec libc.so (BuildId: 55a7515345951d438fd16e74b171760b)
#01 pc 0x4ffac libc.so (BuildId: 55a7515345951d438fd16e74b171760b)
#02 pc 0x75de896d2c
#03 pc 0x75de896c8c
#04 pc 0x1e53318 libil2cpp.so (FirebaseMessagingPINVOKE.delete_FirebaseMessage) (BuildId: 747974a5237fb6e9262ae0808a93201c2696139a)
#05 pc 0x11585a8 libil2cpp.so (il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**)) (BuildId: 747974a5237fb6e9262ae0808a93201c2696139a)
#06 pc 0x8ebdc libc.so (BuildId: 55a7515345951d438fd16e74b171760b)```

**Comment by Gong-Tien** [comment]
Sure, here is some part that I can provided.

- We have this code, inside one of MonoBehaviour class.
```
        public async Task Initialize()
        {
            DependencyStatus result = await FirebaseApp.CheckAndFixDependenciesAsync();
            if (result == DependencyStatus.Available)
            {
                FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);

                FirebaseAnalytics.LogEvent(FirebaseAnalytics.EventAppOpen);
            }
        }
```

And the above function was called from another Monobehaviour under this function


```
        public void InitilizationFirebase(Action onInit)
        {
            Initialize().ContinueWithOnMainThread(_ =>
                {
			onInit?.Invoke();
            });
        }
```

Hope this help

**Comment by argzdev** [comment]
Hey @Gong-Tien, it doesn't look like anything out of the ordinary. But looking at the stacktrace you've provided, SIGSEGV usually means we're trying to read/write a memory we don't have access to. That said, the report mentions `delete_FirebaseMessage`. Are you calling any code related to Firebase Messaging? If so, could you provide some code snippets for us to further investigate this issue? Thanks!
