### ISSUE TITLE
[Question] Gradle failed to fetch dependencies.

### ISSUE THREAD

**Issue by bilalahadtech** [firebase/firebase-unity-sdk#914]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.30f1
  * Firebase Unity SDK version:Nill
  * Source you installed the SDK:IronSource (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: Nill (Auth, Database, etc.)
  * Additional SDKs you are using: Unity ads(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Android  (Mac, Windows, or Linux)
  * Platform you are targeting:Andriod (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:
i'm using iron Source with unity ads, 
already created the project on IronSource dash board and setup well...

Main issue is unable to resolve dependences, getting win32  error mesage and solves by making file "gradlew.bat" and psting lines as recommended from all...ScreenShort of error 
![image_2023_12_07T10_18_36_726Z](https://github.com/firebase/firebase-unity-sdk/assets/151743241/e89051eb-7c6c-4390-b55f-78f01f4102fd)

Gradle failed to fetch dependencies.

Failed to run 'C:\Users\Administrator\Desktop\IronSourceTest\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "C:\Users\Administrator\Desktop\IronSourceTest\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=D:/Unity/2021.3.31f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=C:\Users\Administrator\Desktop\IronSourceTest\Assets\Plugins\Android" "-PMAVEN_REPOS=https://android-sdk.is.com/;https://maven.google.com/" "-PPACKAGES_TO_COPY=com.ironsource.sdk:mediationsdk:7.6.0;com.google.android.gms:play-services-ads-identifier:18.0.1;com.google.android.gms:play-services-basement:18.1.0;com.ironsource.adapters:unityadsadapter:4.3.34;com.unity3d.ads:unity-ads:4.9.2" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=4.0.1"'
stdout:

> Configure project :
ANDROID_HOME: D:/Unity/2021.3.31f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK
MAVEN_REPOS: name=Google url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven2 url=https://maven.google.com/
MAVEN_REPOS: name=maven3 url=https://android-sdk.is.com/
MAVEN_REPOS: name=MavenLocal url=file:/C:/Users/Administrator/.m2/repository
MAVEN_REPOS: name=BintrayJCenter url=https://jcenter.bintray.com/
MAVEN_REPOS: name=MavenRepo url=https://repo.maven.apache.org/maven2/
PACKAGES_TO_COPY: com.ironsource.sdk:mediationsdk:7.6.0
PACKAGES_TO_COPY: com.google.android.gms:play-services-ads-identifier:18.0.1
PACKAGES_TO_COPY: com.google.android.gms:play-services-basement:18.1.0
PACKAGES_TO_COPY: com.ironsource.adapters:unityadsadapter:4.3.34
PACKAGES_TO_COPY: com.unity3d.ads:unity-ads:4.9.2
TARGET_DIR: C:\Users\Administrator\Desktop\IronSourceTest\Assets\Plugins\Android
Resolution attempt 1: packages [com.google.android.gms:play-services-ads-identifier:18.0.1, com.google.android.gms:play-services-basement:18.1.0, com.unity3d.ads:unity-ads:4.9.2, com.ironsource.adapters:unityadsadapter:4.3.34, com.ironsource.sdk:mediationsdk:7.6.0]
androidx.asynclayoutinflater:asynclayoutinflater conflicting due to package(s):
- com.google.android.gms:play-services-ads-identifier:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.google.android.gms:play-services-basement:18.1.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/com.google.android.gms:play-services-tasks:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-tasks:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
androidx.coordinatorlayout:coordinatorlayout conflicting due to package(s):
- com.google.android.gms:play-services-ads-identifier:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.google.android.gms:play-services-basement:18.1.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-base:18.0.1/com.google.android.gms:play-services-tasks:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
- com.unity3d.ads:unity-ads:4.9.2/com.google.android.gms:play-services-cronet:18.0.1/com.google.android.gms:play-services-tasks:18.0.1/com.google.android.gms:play-services-basement:18.0.0/androidx.fragment:fragment:1.0.0/androidx.legacy:legacy-support-core-ui:1.0.0/androidx.coordinatorlayout:coordinatorlayout:1.0.0
androidx.core:core conflicting due to package(s):
-

**Comment by paulinon** [comment]
Hi @bilalahadtech,

Given the information you provided, the issue you reported doesn't seem to be related to the Firebase SDK. If you have the External Dependency Manager for Unity in your implementation, enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings could be worth a try as the generated files from these steps can handle the resolution better than the custom script in the resolver. Otherwise, you may get in touch with [IronSource](https://ironsrc.formtitan.com/knowledge-center?fld48=#/) so that a support agent can identify what's causing this to happen.
