### ISSUE TITLE
[Bug] Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity

### ISSUE THREAD

**Issue by lewisSM** [firebase/firebase-unity-sdk#921]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.11f1
  * Firebase Unity SDK version: 10.7.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Auth, Remote Config, Crashlytics, Dynamic Links
  * Additional SDKs you are using: Ironsource, Google Play Games, Google Mobile Ads, OneSignal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS and Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: pre-built

### [REQUIRED] Please describe the issue here:

A crash event is being logged through Crashlytics. I removed Firebase Messaging a while ago as we transitioned to using OneSignal for notifications. However the stack trace has references to "Firebase-Messaging-Init" although I cannot find any files from the Messaging SDK in the project. I've attached the full stack trace that's on Crashlytics. 

[com.invinciblesstudioltd.soccermanager2024_issue_ca8f7f21e3ec633d0d1dca453409435b_crash_session_659BB37900E600010D96AFF0A34E4FD2_DNE_0_v2_stacktrace.txt](https://github.com/firebase/firebase-unity-sdk/files/13860995/com.invinciblesstudioltd.soccermanager2024_issue_ca8f7f21e3ec633d0d1dca453409435b_crash_session_659BB37900E600010D96AFF0A34E4FD2_DNE_0_v2_stacktrace.txt)

#### Steps to reproduce:

Unfortunately I've not been able to reproduce the crash. It's only occurring on Android.

**Comment by paulinon** [comment]
Hi @lewisSM,

In order to ensure that your implementation has the latest fixes and updates, could you confirm if the latest SDK version (11.6.0 as of writing) makes any difference? If so, please provide the latest stack trace encountered.
