### ISSUE TITLE
[Question] /Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:37:9 'GoogleUtilities/GULURLSessionDataResponse.h' file not found

### ISSUE THREAD

**Issue by jayantjha23** [firebase/firebase-unity-sdk#929]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2021.3.28f
  * Firebase Unity SDK version: _____11.6.0
  * Source you installed the SDK: ___.unitypackage__ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: ___Mac__ (Mac, Windows, or Linux)
  * Platform you are targeting: ___Android,iOS__ (iOS, Android, and/or desktop)
  * Scripting Runtime: ____iL2CPP_ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:
while making Archieve  getting /Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:37:9 'GoogleUtilities/GULURLSessionDataResponse.h' file not found.

**Comment by paulinon** [comment]
Hi @jayantjha23,

In order to identify what's causing this to happen, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with your `Podfile.lock` file?
