### ISSUE TITLE
Error Uploading Unity Symbols to Firebase Crashlytics: 'An unknown error occurred'

### ISSUE THREAD

**Issue by JayMehta97** [firebase/firebase-unity-sdk#932]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.17f1
  * Firebase Unity SDK version: 11.4.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Facebook and AdMob
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: website

### [REQUIRED] Please describe the issue here:

I am encountering an issue while trying to upload Unity symbols to Firebase Crashlytics. This functionality used to work correctly before, but now it's resulting in an error. Below are the details of the command used and the error message received.

**Command Used:**

firebase crashlytics:symbols:upload --app=APP_ID PATH_TO_SYMBOLS/app-name-1.1-v29.symbols.zip

**Error Message:**
- Generating symbols for APP_ID PATH_TO_SYMBOLS/app-name-1.1-v29.symbols.zip
- ⚠ An unknown error occurred
- Error: java command failed with args: -jar,/Users/username/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/var/folders/x5/v43f4j0d5ps51nf485t9c5640000gn/T/crashlytics-56bcd74f-ab91-4772-ae45-5b2f376804bc/nativeSymbols/1-246904291161-android-b99e08fbb9cc26108bd648/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,APP_ID PATH_TO_SYMBOLS/app-name-1.1-v29.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools

#### Steps to reproduce:
1. Generated an AAB build with symbols from Unity 2020.3.17f1
2. Upload those symbols to firebase using terminal

While uploading you should get the above error.
I have tried these steps in 3 different machines (2 mac, 1 ubuntu) but for all of them the same issue occurs.

This error is preventing me from uploading the necessary symbols for my Unity application. I have not made any changes to the command or the process that I used successfully in the past. It would be great to get some insights into what might be causing this issue and how to resolve it.

Any assistance or guidance you can provide would be greatly appreciated.

**Comment by paulinon** [comment]
Hi @JayMehta97,

It seems that Firebase wasn't able to find the `java` command in your machine. Installing Java in your machines should resolve the issue. Otherwise, running the Firebase CLI as an administrator is something worth trying.

If none of these steps worked, you may file a ticket in the [Firebase Tools GitHub repository](https://github.com/firebase/firebase-tools/issues) as the cause of the issue lies within the Command Line Interface. You may also provide the output of running `java --version` as well as other relevant information in your ticket.
