### ISSUE TITLE
[Bug] Could not find com.google.firebase:firebase-*service*-unity:11.6.0.

### ISSUE THREAD

**Issue by LightGameStudio42** [firebase/firebase-unity-sdk#941]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.16
  * Firebase Unity SDK version: 11.6.0
  * Source you installed the SDK: UPM, tarball (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: analytics (Auth, Database, etc.)
  * Other Firebase Components in use: auth, rt database (Auth, Database, etc.)
  * Additional SDKs you are using: yandex ads (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: tarball from website

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
1. Remove appodeal plugin from project
2. Resolve and force resolve
3. Build and get this error

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

`Execution failed for task ':launcher:mergeReleaseResources'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-analytics-unity:11.6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-analytics-unity/11.6.0/firebase-analytics-unity-11.6.0.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-analytics-unity/11.6.0/firebase-analytics-unity-11.6.0.pom
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-analytics-unity-11.6.0.jar
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-analytics-unity.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.google.firebase:firebase-app-unity:11.6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-app-unity/11.6.0/firebase-app-unity-11.6.0.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-app-unity/11.6.0/firebase-app-unity-11.6.0.pom
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-app-unity-11.6.0.jar
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-app-unity.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.google.firebase:firebase-auth-unity:11.6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-auth-unity/11.6.0/firebase-auth-unity-11.6.0.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-auth-unity/11.6.0/firebase-auth-unity-11.6.0.pom
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-auth-unity-11.6.0.jar
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-auth-unity.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.google.firebase:firebase-crashlytics-unity:11.6.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-crashlytics-unity/11.6.0/firebase-crashlytics-unity-11.6.0.pom
       - https://repo.maven.apache.org/maven2/com/google/firebase/firebase-crashlytics-unity/11.6.0/firebase-crashlytics-unity-11.6.0.pom
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-crashlytics-unity-11.6.0.jar
       - file:/H:/Unity/Somnium/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/firebase-crashlytics-unity.jar
     Required by:
         project :launcher > project :unityLibrary`

[Editor.log](https://github.com/firebase/firebase-unity-sdk/files/14239705/Editor.log)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @LightGameStudio42,

This behavior seems rather unusual considering that you haven't touched the Firebase SDK according to your steps. Could you try if [removing the Firebase SDK](https://firebase.google.com/docs/unity/setup-alternative#alternative_migrate_to_upm) and reimporting it makes any difference? 

If that didn't work, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that we can identify what's causing this to happen.

**Comment by LightGameStudio42** [comment]
Fixed by deleting and creating again files in "publishing settings"
