### ISSUE TITLE
Firebase Unity iOS works fine on editor but crashing on build

### ISSUE THREAD

**Issue by JustGerome** [firebase/firebase-unity-sdk#944]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.46f1
  * Firebase Unity SDK version: firebase_unity_sdk_11.6.0
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Storage
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Website

### [REQUIRED] Please describe the question here:
I am relatively new to building my application on iOS and unity application instantly crashed on build and returned with this error

I tried building the project on Xcode versions 12, 13, 14, 15

Error loading /Users/jlcgprod02/Library/Developer/CoreSimulator/Devices/7E87BB0F-8400-4248-AADE-0730ACF2BE34/data/Containers/Bundle/Application/81994DF6-3E47-4B4C-A630-6CFC98B3B214/MalabonCityApp.app/Frameworks/UnityFramework.framework/UnityFramework (236): dlopen(/Users/jlcgprod02/Library/Developer/CoreSimulator/Devices/7E87BB0F-8400-4248-AADE-0730ACF2BE34/data/Containers/Bundle/Application/81994DF6-3E47-4B4C-A630-6CFC98B3B214/MalabonCityApp.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): symbol not found in flat namespace '__ZTVN8firebase9firestore4util13ByteStreamCppE'

What I've tried:

-Reinstalled Firebase SDK and Libraries
-Reinstalled Coacoapods
-Checked Unityframework dependencies and libraries

**Comment by paulinon** [comment]
Hi @JustGerome,

Are you opening the `.xcworkspace` file? This is the one you need to use to build your app. If you are, could you share your  detailed steps to reproduce the issue along with your `Podfile` so that we can identify what's causing this to happen?
