### ISSUE TITLE
[Bug] FirebaseAnalytics.SetConsent

### ISSUE THREAD

**Issue by yangjiechao** [firebase/firebase-unity-sdk#954]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2020.3.38f
  * Firebase Unity SDK version: _____11.7
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ AdMax(11.11.4),Admob(8.5.2),FirebaseAnalytics(11.7),FirebaseCrashlytics(11.7),FirebaseRemoteConfig(11.7)
  * Platform you are using the Unity editor on: _____ Mac
  * Platform you are targeting: _____ iOS
  * Scripting Runtime: _____  IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the issue here:

1. I add Arguments according to the document to add debug console view events - FIRAnalyticsVerboseLoggingEnabled, but can't see any Log, must add extra - FIRAnalyticsDebugEnabled, Log:ad_storage is granted. analytics_storage is granted. ad_user_data is granted. ad_personalization is granted. 
2. Then I call Firebase. Analytics. FirebaseAnalytics. SetConsent (dicConsent); After that, the AD_storage-related log, instead, Analytics data has been reset and Resetting App Measurement data
3. Even if I call the native method [FIRAnalytics setConsent:consent]; remain get the log:Analytics data has been reset and Resetting App Measurement data

**Comment by yangjiechao** [comment]
I find the problem,if i call the unity-firebase remote config, the the log will disapper

**Comment by paulinon** [comment]
Hi @yangjiechao,

Apologies for the late revert. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps you've taken to replicate the issue? Could you also clarify what you mean when you said that your Analytics data has been reset?

**Comment by yangjiechao** [comment]
> Hi @yangjiechao,
> 
> Apologies for the late revert. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps you've taken to replicate the issue? Could you also clarify what you mean when you said that your Analytics data has been reset?

Although you cannot see the log messages about ad_storage is granted. after calling firebase remote.FetchData or analytics.SetConsent of unity firebase sdk, it still works normally and I will close the issue.
