### ISSUE TITLE
[Question] Dynamic Links - black screen on iOS 17.

### ISSUE THREAD

**Issue by XubeiX** [firebase/firebase-unity-sdk#957]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.20f1
  * Firebase Unity SDK version: 10.7.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: DynamicLinks (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, Crashlytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac M1 (Mac, Windows, or Linux)
  * Platform you are targeting: iOS and Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: https://developers.google.com/unity/archive

### [REQUIRED] Please describe the question here:

My project uses EMD version 1.2.175 and Firebase Analytics, Crashlytics and DynamicLinks version 10.7.0 - the project was crated in Unity 2021.3.20f1. There are no problems in this version of Unity. After building the project on iOS, I am able to lunch the application using the icon without any problems, as well as lunch it using Dynamic Links(the first lunch where Dynamic Links launches the application and passes the link to it).

I decided to update Unity to 2022.3.20f1 after the Unity update, I am still able to build iOS app without any problem. The app launched with the icon works without problems. However, when I want to run app fot the first time using Dynamic Links the app starts, static splash screen is shown, then a black screen is displayed and nothing more happens. It looks like Unity is not running? I tried updating both EDM and all Firebase libs to the latest versions, but the problem still occurs. Do you have any idea what could be causing the black screen? Because this is the only scenario in which it appears. If I launched the app with the icon before, moved it to the background, run Dynamic Links from Safari then the app will come to the foreground and Dynamic Links will be passed and work.

**Comment by paulinon** [comment]
Hi @XubeiX,

Please note that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More information can be found at at https://firebase.google.com/support/dynamic-links-faq.
