### ISSUE TITLE
[Question] the issue of changes to iOS privacy policies

### ISSUE THREAD

**Issue by NiceGomdol** [firebase/firebase-unity-sdk#965]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

### [REQUIRED] Please describe the question here:

Hello. We are developing an iOS app using Unity, and our app includes the Firebase Unity SDK. Due to the recent changes in iOS privacy policies, the use of a third-party SDK now requires the SDK's manifest file and signature.

Upon reviewing the release notes, I noticed that starting from version 10.22.0, Firebase for iOS has begun to address this issue. I was wondering if there is a plan to support the Firebase Unity SDK in a similar way, or if there is an alternate solution we should consider.

**Comment by superbderrick** [comment]
Any updates?:

**Comment by paulinon** [comment]
Hi folks, 

We are currently collaborating with the iOS team to determine Apple's requirements going forward. Although we can't provide a timeline at the moment, you may refer to this thread for updates. That said, I'll be marking this as a feature request.

**Comment by paulinon** [comment]
Hi folks,

Version [11.8.0](https://firebase.google.com/support/release-notes/unity#version_1180_-_march_13_2024) of the Unity SDK has been released. This points to version [10.22.0](https://firebase.google.com/support/release-notes/ios#version_10220_-_march_4_2024) of the iOS SDK which contains the added privacy manifest. That said, I'll be closing this issue for now.

**Comment by NiceGomdol** [comment]
@paulinon  thank you for your response. It seems that signatures are also required on iOS, and based on [what I found](https://github.com/firebase/firebase-ios-sdk/issues/12238#issuecomment-1999790713), Firebase 10.23.0 supports it. Can you tell me when the Unity Firebase SDK, including version 10.23.0, is expected to be released?
