### ISSUE TITLE
[Bug] Storage PutFileAsync/PutBytesAsync stops transfering bytes after exactly 5 minutes, throws "Firebase.Storage.StorageException: The operation retry limit has been exceeded" after exactly 5 more minutes

### ISSUE THREAD

**Issue by TobiasWehrum** [firebase/firebase-unity-sdk#968]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.17f1
  * Firebase Unity SDK version: 11.6.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: Auth, Firestore, Functions
  * Additional SDKs you are using: Sentry, Cesium
  * Platform you are using the Unity editor on: Windows 10
  * Platform you are targeting: Desktop
  * Scripting Runtime: Mono
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

I'm trying to upload a 423 MB video file with PutFileAsync while using a progress handler to show the upload progress.

After exactly 5 minutes the upload always seems to stop: The progress handler continues to be called, but BytesTransferred will keep the value it had at the 5 minute mark (instead of steadily progressing like before).

After exactly 5 more minutes PutFileAsync throws `Firebase.Storage.StorageException: The operation retry limit has been exceeded`.

If I try to upload anything else after that exception in the Unity Editor the whole Editor will freeze and has to be closed via Task manager.

If I try to upload anything else after that exception in a build, the app will either directly crash or will throw a `System.ApplicationException: ret == ((((DWORD )0x00000000L) ) + 0 ) ---> System.ApplicationException: ret == ((((DWORD )0x00000000L) ) + 0 )` immediately.

This happens in the Unity Editor and in a desktop build on Windows 10 every single time I tested it. I also tested PutBytesAsync in the Unity Editor, and it has the exact same behaviour.

We also tested tested this in a build on another Windows 10 machine, and there too we got `Firebase.Storage.StorageException: The operation retry limit has been exceeded` after pretty much exactly 10 minutes (and then the System.ApplicationException if we tried to upload again).

If I set MaxDownloadRetryTime, MaxUploadRetryTime and MaxOperationRetryTime to 1 second, `Firebase.Storage.StorageException: The operation retry limit has been exceeded` will be thrown right after BytesTransferred stops increasing, further suggesting that something goes wrong there and that it starts retrying at that point.

**Comment by paulinon** [comment]
Hi @TobiasWehrum,

Does setting `MaxUploadRetryTime` to a higher value make a difference? You may use this code to have a maximum upload retry time of one hour:

`storage.MaxUploadRetryTime = new TimeSpan(TimeSpan.TicksPerHour);`

If that doesn't work, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that we can identify what's causing this to happen?

**Comment by TobiasWehrum** [comment]
@paulinon When I tested that yesterday (with `new TimeSpan(1, 0, 0)`) the only difference it made was how long it took to throw `Firebase.Storage.StorageException: The operation retry limit has been exceeded` after it stopped uploading at the 5 minute mark.

I'll make an example later.

**Comment by paulinon** [comment]
Hi @TobiasWehrum,

Thanks for the additional information. I was able to reproduce the issue, and it persists even after setting the upload retry time. That said, I'll be relaying my observations to our team. You may refer to this thread for updates.

**Comment by TobiasWehrum** [comment]
Thank you, @paulinon - looking forward to this getting resolved.

On a related note, I think the same bug might apply not just to uploading, but also to downloading. I didn't have time to investigate yet, but yesterday I observed a particularly big download on a slow internet connection that seemed to stop after about 5 minutes, and then threw a `StorageException: The operation retry limit has been exceeded.` not long after.

**Comment by TobiasWehrum** [comment]
@paulinon I just tested it to confirm it: Literally the same (stops transfering after 5 minutes, operation retry limit StorageException at 10 minutes) happens when downloading via `GetFileAsync`.

**Comment by a-maurice** [comment]
This should be fixed with the latest release, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.9.0
The 5 minute timeout was the default set by Curl, so we just adjusted that.

**Comment by TobiasWehrum** [comment]
@a-maurice Thanks for the fix and the info what it was!

It doesn't sound like the curl timeout should lead to the observed crashes/freezes though. There might be a secondary bug here that could occur under other conditions too, like e.g. when "The operation retry limit has been exceeded" is thrown for other reasons.

**Comment by a-maurice** [comment]
Yeah, it is certainly possible, and we will keep an eye out for possible fixes for that.
