### ISSUE TITLE
[Bug] After adding the firbease SDK 11.8.0. Cocoapods cannot find relevant

### ISSUE THREAD

**Issue by rehmanilyas** [firebase/firebase-unity-sdk#971]
* Unity editor version: 2020.3.15f2
  * Firebase Unity SDK version: 11.8.0
  * Source you installed the SDK: FirebaseMessaging, FirebaseAnalytics, FirebaseCrashlytics (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: FirebaseMessaging
  * Other Firebase Components in use: _FirebaseAnalytics, FirebaseCrashlytics
  * Additional SDKs you are using: Facebook, Applovin
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: IOS
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: _____

After adding the firbease SDK 11.8.0. Cocoapods cannot find relevant frameworks.
Getting these errors when run `pod install --repo-update` command

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
  In Podfile:
    Firebase/Messaging (= 10.22.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Messaging (= 10.22.0)`.
```

PodFile:
```
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'UnityFramework' do
  pod 'Amplitude', '~> 8.16.3'
  pod 'AppLovinMediationByteDanceAdapter', '5.7.0.7.0'
  pod 'AppLovinMediationChartboostAdapter', '9.6.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.14.0.1'
  pod 'AppLovinMediationIronSourceAdapter', '7.8.0.0.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.9.2.1'
  pod 'AppLovinMediationVungleAdapter', '7.2.2.0'
  pod 'AppLovinSDK', '12.3.0'
  pod 'AppsFlyerFramework', '6.12.2'
  pod 'FBSDKCoreKit', '~> 16.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 16.0.1'
  pod 'FBSDKGamingServicesKit', '~> 16.0.1'
  pod 'FBSDKLoginKit', '~> 16.0.1'
  pod 'FBSDKShareKit', '~> 16.0.1'
  pod 'Firebase/Analytics', '10.22.0'
  pod 'Firebase/Core', '10.22.0'
  pod 'Firebase/Crashlytics', '10.22.0'
  pod 'Firebase/DynamicLinks', '10.11.0'
  pod 'Firebase/Messaging', '10.22.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

```

**Comment by rehmanilyas** [comment]
Removing slashes from firebase pods worked.
Changed:
```
  pod 'Firebase/Analytics', '10.22.0'
  pod 'Firebase/Core', '10.22.0'
  pod 'Firebase/Crashlytics', '10.22.0'
  pod 'Firebase/DynamicLinks', '10.11.0'
  pod 'Firebase/Messaging', '10.22.0'
```
to:
```
  pod 'FirebaseAnalytics', '10.22.0'
  pod 'FirebaseCore', '10.22.0'
  pod 'FirebaseCrashlytics', '10.22.0'
  pod 'FirebaseDynamicLinks', '10.11.0'
  pod 'FirebaseMessaging', '10.22.0'
```

**Comment by paulinon** [comment]
Glad to hear that you resolved the issue, @rehmanilyas.

I noticed that you're making use of Firebase Dynamic Links in your implementation. Please note that this service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK. More information can be found at https://firebase.google.com/support/dynamic-links-faq.

That said, I'll be closing this issue for now.
