### ISSUE TITLE
My Report Platform recent has much Error: Unable to cache file app_resources_lib.jar, embedded Java class loading will fail. It is likely the device is out 

### ISSUE THREAD

**Issue by yangjiechao** [firebase/firebase-unity-sdk#973]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2020.3.38f1
  * Firebase Unity SDK version: _____8.10.1
  * Source you installed the SDK: _____ .unitypackage
  * Problematic Firebase Component: _____ (Analytics, RemoteConfig, etc.)
  * Other Firebase Components in use: _____ Crashlytics,Performance
  * Additional SDKs you are using: _____ GA, MaxSdk
  * Platform you are using the Unity editor on: _____ Mac
  * Platform you are targeting: _____ Android
  * Scripting Runtime: _____ IL2CPP

### 
Recently, my game has a lot of error reports, there are at least 15,000 users, stacked to write that there is not enough data space, but should not be so many users will have this problem,who can tall me why?

Error Stacke:
1.
Unable to cache file app_resources_lib.jar, embedded Java class loading will fail. It is likely the device is out of space for application data storage, free some space and try again. Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0() Firebase.FirebaseApp:CreateInternal() Firebase.CreateDelegate:Invoke() Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp) Firebase.RemoteConfig.FirebaseRemoteConfig:get_DefaultInstance() AGSdk.FirebaseRemoteConfig:FetchDataAsync(TimeSpan) AGSdk.AGSdkManager:<SetupFirbase>b__19_0(Task`1) System.Action`1:Invoke(T) Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1() System.Func`1:Invoke() Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0() System.Action:Invoke() Firebase.ExceptionAggregator:Wrap(Action) Firebase.Dispatcher:PollJobs() Firebase.Platform.FirebaseHandler:Update()

2.
Unable to cache file app_resources_lib.jar, embedded Java class loading will fail. It is likely the device is out of space for application data storage, free some space and try again. Firebase.AppUtilPINVOKE:PollCallbacks() Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()

3.
Unable to cache file google_api_resources_lib.jar, embedded Java class loading will fail.  It is likely the device is out of space for application data storage, free some space and try again. Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0() Firebase.FirebaseApp:CreateInternal() Firebase.CreateDelegate:Invoke() Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp) Firebase.RemoteConfig.FirebaseRemoteConfig:get_DefaultInstance() AGSdk.FirebaseRemoteConfig:FetchDataAsync(TimeSpan) AGSdk.AGSdkManager:<SetupFirbase>b__19_0(Task`1) System.Action`1:Invoke(T) Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1() System.Func`1:Invoke() Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0() System.Action:Invoke() Firebase.ExceptionAggregator:Wrap(Action) Firebase.Dispatcher:PollJobs() Firebase.Platform.FirebaseHandler:Update() 

4.
Unable to cache file google_api_resources_lib.jar, embedded Java class loading will fail. It is likely the device is out of space for application data storage, free some space and try again. Firebase.AppUtilPINVOKE:PollCallbacks() Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()

**Comment by paulinon** [comment]
Hi @yangjiechao,

Does freeing some storage space for the devices make any difference? If not, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can identify what's causing this to happen? Additionally, updating the Firebase SDK to its latest version could be worth trying since it contains the latest fixes and updates.

**Comment by soqman** [comment]
I had the same problem on one of my devices. how did you resolve the problem?

**Comment by a-maurice** [comment]
The problem seems to be that the devices don't have enough memory to load the jar file that it needs to function.  Do you have any metrics on the types of devices that are seeing this error?

Have you tried building with minification enabled, or other techniques to reduce the APK size?
