### ISSUE TITLE
[Question] Apple APM Requirement Firebase Signed xcframework

### ISSUE THREAD

**Issue by hendri-voodoo** [firebase/firebase-unity-sdk#980]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.22f1
  * Firebase Unity SDK version: 11.8.1++
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: all
  * Other Firebase Components in use: all
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Apple will start enforcing its APM requirements by the end of April 2024, and one of them is that all xcframeworks must be codesigned. When I checked the Firebase iOS SDK, it is mentioned that an update will be released by 8 April 2024 https://github.com/firebase/firebase-ios-sdk/issues/12238#issuecomment-2026217595 

Do you have an ETA for when the iOS update will be added to the Firebase Unity SDK Package?

**Comment by a-maurice** [comment]
The Firebase iOS SDK update is a bit confusing, only the Swift Package Manager version of the libraries have the code signing.  The Cocoapods don't but are planned for the next release, and when that is available, we will update ASAP.

**Comment by hendri-voodoo** [comment]
Hi @a-maurice thanks for the clarification, but it also means that most of the Unity developer wont get the update ontime then? since unity only support Cocoapods and if cocoapods release is delayed to next cycle from 8th April it means that the unity version wont get it until May?

If we are using only Crashlytics and Analytics do we need the signed library? Or we can move forward with current version of Firebase Unity Sdk?

**Comment by ncooke3** [comment]
Hi @hendri-voodoo, Firebase iOS SDK's Crashlytics pod is source, so no code signature is required for it. Firebase iOS SDK's Analytics pod contains a binary, but Analytics is not on Apple's list so I don't believe a signed binary will be _required_ on May 1. That being said, as you pointed out, the Firebase iOS SDK will be releasing next week to ensure that all binary SDKs (regardless of whether they are on Apple's list or not) are signed.

**Comment by a-maurice** [comment]
We aim to have a new release out next week with the updated Cocoapods.  In the meantime, you can also use the previous 11.8.1 release, and manually update the pod versions, and that should work as well.

**Comment by hendri-voodoo** [comment]
hi @a-maurice , so if I use the firebase-unity-sdk 11.8.1 and manually change the ios dependency in the xml file to 10.24.0 it wont cause another issue right?

**Comment by a-maurice** [comment]
The latest Unity SDK release is now available, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.9.0

It uses the Firebase iOS SDK at 10.24.0, and so should have everything signed as needed.
