### ISSUE TITLE
Firebase SDK Validation Failed in Unity (Break Symlinks)

### ISSUE THREAD

**Issue by bforrose** [firebase/firebase-unity-sdk#988]
### Description

After adding the Firebase SDK to Unity and exporting it to Xcode, the build fails. The build failure is due to the Firebase SDK's Validation Failed. (Validation Error: A sealed resource is missing or invalid).

The reason for the Validation Failed error is as follows: There is a build issue due to the symlink while applying the Firebase.zip file.

Symlinks have been identified in the folders and files under the following XCFrameworks:

- \*.xcframework/ios-arm64_x86_64-maccatalyst/\*.framework
- \*.xcframework/macos-arm64_x86_64/\*.framework

Adding these XCFrameworks to the UnityEngine will break the symlinks. (The file copying provided by the UnityEngine does not preserve symlinks.) In this state, performing a Unity Build will result in a Validation Failed error for the Firebase SDK in Xcode. (Validation Error: A sealed resource is missing or invalid).
<img width="256" alt="스크린샷 2024-04-11 15 06 10" src="https://github.com/firebase/firebase-ios-sdk/assets/12608166/14f6ec5b-7ad5-4f7b-904f-2867a369c84d">

**original XCFramework**
<img width="672" alt="스크린샷 2024-04-11 15 12 47" src="https://github.com/firebase/firebase-ios-sdk/assets/12608166/05b161d9-43e6-4a58-bdaa-6d03f93cfd4e">

**XCFramework added to UnityEngine (Break Symlinks)**
<img width="664" alt="스크린샷 2024-04-11 15 18 25" src="https://github.com/firebase/firebase-ios-sdk/assets/12608166/e667b5ba-8476-4765-a2cb-f8332f9d2285">

### Firebase SDK Version

10.24.0

### Xcode Version

15.1

### Installation Method

Zip

### Firebase Product(s)

Analytics, Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulinon** [comment]
Hi @bforrose,

Could you provide more detailed steps to reproduce the issue so that we could identify what's causing this to happen?

**Comment by bforrose** [comment]
Hi @paulinon 

The issue can be reproduced using the following steps:

1. Open Unity Editor. (Platform: iOS)
2. Drag and drop the FirebaseAnalytics.xcframework into the Unity Editor's Assets/Plugins/iOS folder.
3. The FirebaseAnalytics.xcframework file is copied to the Assets/Plugins/iOS subdirectory.
4. Check the symbolic links of the files under Assets/Plugins/iOS/FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework using Finder.

Following these steps results in the symbolic links inside the FirebaseAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/FirebaseAnalytics.framework file being broken. The breaking of the symbolic links causes the XCFramework's validity check to fail.

Additionally, our SDK is provided with the Firebase SDK included in a .unitypackage.

1. Create a .unitypackage that includes the Firebase SDK.
2. Select Assets > Import Package > Custom Package, and add the created .unitypackage.
3. Files are copied to the Unity Editor, and the symbolic links of the following XCFrameworks in the Firebase SDK are broken:
\*.xcframework/ios-arm64_x86_64-maccatalyst/\*.framework
\*.xcframework/macos-arm64_x86_64/\*.framework

The breaking of these symbolic links causes the validity check in Xcode to fail.

**Comment by bforrose** [comment]
Hi @a-maurice

Adding an XCFramework to an XCode project does not cause any issues. However, our automation script is designed to add the XCFramework registered in the Unity Editor to the XCode project. I inquired to see if there might be any other possible solutions. We will try to resolve this issue by modifying our automation script.
Thank you for your response.

**Comment by ncooke3** [comment]
> We will try to resolve this issue by modifying our automation script.

@bforrose, I would recommend using commands like `cp -rP src/ dest/` or `rsync -a src/ dest/` when copying XCFrameworks. Either one of these commands has preserved symlinks in my testing.

**Comment by a-maurice** [comment]
Sounds good, I'll close this issue for now, as there isn't really much we can do on our end, but hopefully you are able to get it to work out.
