### ISSUE TITLE
[Question] When is the release of the version incorporating firebase-ios-sdk v10.24.0 expected?

### ISSUE THREAD

**Issue by k0uhe1D** [firebase/firebase-unity-sdk#990]
### What is your question?

The new firebase-ios-sdk v10.24.0, which includes code signing in accordance with Apple's PrivacyManifest, has been released.
https://github.com/firebase/firebase-ios-sdk/releases/tag/10.24.0
When will the version of firebase-unity-sdk that incorporates this be released?
I would like to inquire about the current release plan.

### Firebase Unity SDK Version

11.8.1

### Unity editor version

2021.3.36f1

### Installation Method

.unitypackage

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by vladyslav-androshchuk** [comment]
Hello Firebase team,

We are also curious about it. We have dozens of projects awaiting the release of Firebase Unit SDK with all compliance with new Apple rules. It should be fine to just up the pod version, but we want to be sure that integrity is in order.

**Comment by a-maurice** [comment]
The latest Unity SDK release is now available, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.9.0

It uses the Firebase iOS SDK at 10.24.0, and so should have everything signed as needed.
