### ISSUE TITLE
[Question] macOS version does't store player credentials after game quit.

### ISSUE THREAD

**Issue by Fatorin** [firebase/firebase-unity-sdk#992]
### What is your question?

My project is using Firebase Authentication as our identity authentication system.

The login mechanism for our desktop version originally involved embedding a web browser within the game and storing login credentials internally.

Later, to improve the player login experience, we switched to a login process similar to the mobile version. 

When testing on **_Windows version_**, **_Unity Editor on Windows_**, and **_Unity Editor on MacOS_**, player credentials(FirebaseUser) are stored after successful login, so there's no need relogin until signout.

However, when I build the **_macOS version_**, player credentials aren't stored upon closing the game, requiring login every time when application start.

I understand that the desktop version SDK is still in the beta phase, but if credentials can be stored on **_Unity Editor on MacOS_**, why can't they be stored in the macOS version?

Note: I'm testing using a Mac M1.

### Firebase Unity SDK Version

11.8.1

### Unity editor version

2021.3.25f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

Authentication

### Targeted Platform(s)

Desktop

### Unity editor platform

Mac

### Scripting Runtime

Mono

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

**Comment by argzdev** [comment]
Hey @Fatorin, thanks for reaching out. The player session should remain after a successful login, there should be no need for a relogin. That said, I've tested this out with our [quickstart-unity](https://github.com/firebase/quickstart-unity) and it seems to work correctly. There might be a configuration issue on your side, you could test out our quickstart to get a code reference on how this is setup. Make sure your code is monitoring the `StateChanged` right after initializing Firebase:

e.g.:
```
    protected void InitializeFirebase() {
      DebugLog("Setting up Firebase Auth");
      auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
      auth.StateChanged += AuthStateChanged;
    }
```

Also could you check if you allowed the permission to store the credentials in the Apple Keychain? There should be sort of a pop up dialog asking for this permission when you log in the first time.
 
Let me know if this helps!

**Comment by argzdev** [comment]
From my understanding, this type of issue "Invalid Info.plist" can only occur whenever the app is code signed. Does the issue happen after building the macOS version prior to code signing? Or after you've performed code sign on your app?

**Comment by Fatorin** [comment]
I built the macOS development version on M1, but I didn't use code signing for my application because I wanted to test if login functionality works first. Should I do it?

**Comment by argzdev** [comment]
That's interesting, is the issue present when simply testing in the Unity Editor? or when you've built and run the app? I'm testing on an intel machine so that could be why I'm unable to reproduce the same behavior.

**Comment by Fatorin** [comment]
When I run my game and login on Unity Editor, Firebase does not output any error messages.

Even after I restart the game, it also can auto-relogin, just as I expected.

However, if I build the application for the Apple Silicon version, I will get an error message when I successfully login.

But I can't auto-relogin when I restart the game.

Unfortunately, I don't have an Intel machine to try the Intel 64-bit version.

**Comment by Fatorin** [comment]
I found the same problem in an old issue. I should sign my application and update the Xcode project settings.
[Issue](https://github.com/firebase/firebase-ios-sdk/issues/9392#issuecomment-1238751984)

**Comment by argzdev** [comment]
That is an interesting issue. Thank you for sharing how you were able to resolve this, @Fatorin. I'm glad you were able to work around it.
