### ISSUE TITLE
[Bug] iOS Build crashing on second launch when made with Xcode 15.3

### ISSUE THREAD

**Issue by jayantjha23** [firebase/firebase-unity-sdk#995]
### Description

iOS app build with Xcode 15.3 crashes on second launch after debugging I found that it is stucking in firebase  code
var task = FirebaseMessaging.GetTokenAsync(); 
Build is working fine  when made with Xcode 14.

### Reproducing the issue

Make iOS Build with Xcode 15.3 .
Unity Version-2021.3.28f1
firebase version -9.6.0
step to reproduce
1.try to get token from firebase using var task = FirebaseMessaging.GetTokenAsync(); 
2. get instance id from firebase using var task=FirebaseAnalytics.GetAnalyticsInstanceIdAsync();

### Firebase Unity SDK Version

9.6.0

### Unity editor version

2021.3.28f1

### Installation Method

.unitypackage

### Problematic Firebase Component(s)

All

### Targeted Platform(s)

Apple Platforms

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulinon** [comment]
Hi @jayantjha23,

Does updating the Firebase SDK to its [latest version](https://firebase.google.com/support/release-notes/unity#version_1181_-_march_29_2024) make any difference? If it doesn't, could you provide the full stack trace being returned so we can identify what's causing this to happen?
